### ISSUE TITLE
gdb did not know about "osv syms" command. 

### ISSUE THREAD

**Issue by wuqixuan** [cloudius-systems/osv#1003]
I try using gdb to debug the OSv as per "https://github.com/cloudius-systems/osv/wiki/Debugging-OSv#debugging-osv-with-gdb". But cannot use "osv syms" command to shared library. Can anybody help ? 

$gdb build/release/loader.elf
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-80.1.alios7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/qixuan.wqx/unikernel/aliuk_up/aliuk/build/release.x64/loader.elf...done.
Traceback (most recent call last):
  File "/home/qixuan.wqx/unikernel/aliuk_up/aliuk/scripts/loader.py", line 891, in <module>
    timer_state_expired = enum_value('sched::timer_base::state', 'expired')
  File "/home/qixuan.wqx/unikernel/aliuk_up/aliuk/scripts/loader.py", line 889, in enum_value
    raise Exception('value %s not found in enum %s' % (val_name, type_name))
Exception: value expired not found in enum sched::timer_base::state
(gdb) connect
warning: Unable to find dynamic linker breakpoint function.
GDB will be unable to debug shared library initializers
and track explicitly loaded dynamic code.
sched::cpu::do_idle (this=this@entry=0xffff800000ea5040) at core/sched.cc:405
405	        handle_incoming_wakeups();
(gdb) bt
#0  sched::cpu::do_idle (this=this@entry=0xffff800000ea5040) at core/sched.cc:405
#1  0x00000000003f9dd8 in sched::cpu::idle (this=0xffff800000ea5040) at core/sched.cc:423
#2  0x00000000003f9dff in operator() (__closure=<optimized out>) at core/sched.cc:165
#3  std::_Function_handler<void(), sched::cpu::init_idle_thread()::__lambda7>::_M_invoke(const std::_Any_data &) (__functor=...)
    at /usr/include/c++/4.8.2/functional:2071
#4  0x00000000003fb588 in main (this=0xffff800001481040) at core/sched.cc:1208
#5  sched::thread_main_c (t=0xffff800001481040) at arch/x64/arch-switch.hh:268
#6  0x0000000000399c83 in thread_main () at arch/x64/entry.S:113
(gdb) osv syms
Undefined command: "osv".  Try "help".
(gdb) osv syms
Undefined command: "osv".  Try "help".

**Comment by wkozaczuk** [comment]
Did you follow this part:
" So before running gdb, add the following line to your ~/.gdbinit file:

add-auto-load-safe-path scripts/loader.py"

**Comment by wkozaczuk** [comment]
@wuqixuan Are you still experiencing this issue? I wonder if we can close it.

**Comment by wkozaczuk** [comment]
Cannot re-produce it and have not heard from the original reporter - closing it.
