### ISSUE TITLE
OSv guest's wall clock does not follow host's wall clock

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#1015]
@rickpayne reported on the OSv mailing list (check out the entire thread at https://groups.google.com/d/msg/osv-dev/8lK0Q1T8ccA/dB9VQfS5BwAJ) that an OSv guest's fails to correctly track the current time (i.e., wall clock) when the host's clock is controlled by, e.g., ntp. For example:
```
$ curl http://192.168.x.x/os/date && TZ=UTC date
"Thu Sep 13 19:17:25 UTC 2018" Thu Sep 13 19:17:28 UTC 2018 
```
It turns out that, as @rickpayne found after debugging this, that OSv only uses the MSR_KVM_WALL_CLOCK_NEW MSR once, on boot, but this is wrong, as the KVM documentation explains:

```
     MSR_KVM_WALL_CLOCK_NEW:
     ....
     The hypervisor is only guaranteed to update this data at the moment of MSR write.
     Users that want to reliably query this information more than once have
     to write more than once to this MSR.
````

@rickpayne provided (see in the aforementioned thread) a patch which solves this problem by writing the MSR_KVM_WALL_CLOCK_NEW on every wallclock read. I was worried this will have too big a performance cost (remember that an MSR write involves an exit to the hypervisor) and @glommer agrees with my worry. A better patch will probably involve updating the wall clock offset once in a while - not on every wallclock read.

**Comment by wkozaczuk** [comment]
Fixed with https://github.com/cloudius-systems/osv/commit/e694d066d20d87897d4a9b6dc721c0926d0fdc74
