### ISSUE TITLE
Hang in tlb_flush()

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#102]
In our build machine, we started to see hangs during boot, in tlb_flush().

Reviewing the code, I'm guessing the problem is as follows:

tlb_flush() sets a counter to the number of known cpus (sched::cpus.size()) minus 1, sends all CPUs an IPI, and waits for the counter to become zero as each CPU receives the IPI and decreases the counter.

We have a problem is sched::cpus already contains a CPU which doesn't yet have our IDT (interrupt handlers) installed, because we'll send it an IPI, but it won't handle it as we expect, won't decrease the counter, and the tlb_flush() will hang.

Looking at the code, indeed parse_madt() loops over the CPUs, creates a sched::cpu object for each, and pushes it onto the sched::cpus vector. The cpu is initialized in parallel (smp_main() runs on it), which includes setting the IDT - but interrupts may start arriving before that and might not have the right IDT (I don't which IDT they have...).

We can do one of two things:
1. parse_madt() will not add the CPU to the list of CPUs, and the CPU itself will later add itself. This will require some sort of locking and we'll lose the deterministic CPU numbering (might not be a bad thing).
2. parse_madt() will continue to set up the sched::cpus vector like it does now, but will not put the new cpu object into the vector before the CPU has initialized enough (especially the idt).

**Comment by wkozaczuk** [comment]
I wonder if given 8 years have passed, this is still an issue. The latest comment by #nyh seems to indicate that it may no longer be.
