### ISSUE TITLE
Ignore missing symbols when loading objects with BIND_NOW in relocate_rela()

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#1023]
Trying to run
```
scripts/build image=rust-httpserver
scripts/run.py
```
Now fails on 
```
/libhttpserver.so: failed looking up symbol posix_spawnattr_setsigdefault
```
There's actually a bunch of functions we'll need, and we can implement all of them as "unimplemented" stubs:
```
$ nm -D apps/rust-httpserver/target/release/libhttpserver.so 
...
                 U posix_memalign
                 U posix_spawn_file_actions_adddup2
                 U posix_spawn_file_actions_destroy
                 U posix_spawn_file_actions_init
                 U posix_spawnattr_destroy
                 U posix_spawnattr_init
                 U posix_spawnattr_setflags
                 U posix_spawnattr_setsigdefault
                 U posix_spawnattr_setsigmask
                 U posix_spawnp
```

But there's another thing we can do. The backtrace of the failed symbol resolution shows that this symbol was requested while **loading** the object, not when actually running:
```
[backtrace]
0x0000000000354cf9 <elf::object::symbol(unsigned int, bool)+1305>
0x000000000039d386 <elf::object::arch_relocate_rela(unsigned int, unsigned int, void*, long)+294>
0x0000000000351934 <elf::object::relocate_rela()+196>
0x0000000000352b77 <elf::object::relocate()+199>
0x0000000000355f5a <elf::program::load_object(std::__cxx11::basic_string<char, s...
```

That suggests that commit f5cc12d56dd986d2c7982c5738b1f859702b07fb did not fully solve issue #993 to allow bind_now objects to be loaded despite some missing symbol (we wanted to fail only when (and if) eventually using one of these symbols).

Indeed, this shared object does have bind_now requested:
```
$ readelf -a  apps/rust-httpserver/target/release/libhttpserver.so
...
 0x0000000000000018 (BIND_NOW)           
 0x000000006ffffffb (FLAGS_1)            Flags: NOW
```

Commit f5cc12d56dd986d2c7982c5738b1f859702b07fb focused on `relocate_pltgot()`, but what failed now was `relocate_rela()`. Indeed we see:
```
$ readelf -r apps/rust-httpserver/target/release/libhttpserver.so
...
000000528468  002000000006 R_X86_64_GLOB_DAT 0000000000000000 posix_spawnattr_setsig@GLIBC_2.2.5 + 0
```
I don't remember what this means and why the plt was not used here, and whether we can also ignore this error somehow (requiring some code changes), hoping this function will never be used and only crash when finally used. 

Finally, if we have a way to build this shared object without bind_now, this problem will also go away :-)

**Comment by wkozaczuk** [comment]
I have actually fixed both rust examples by changing the crate-type to cdylib. Please see https://github.com/cloudius-systems/osv-apps/commit/6329570cc685a6ba543c2ddecfb8b7173c3b3832 for details. 
Apparently something has changed between version 1.24.1 and 1.32.0 (latest) where before the examples worked fine with dylib but now cdylib has to used. I think it still might be interesting to understand why the shared rust libraries (produced with dylib) do not work.

**Comment by nyh** [comment]
Thanks. It's good that now the Rust example works, but now we no longer have a reproducer for this issue ;-)

**Comment by wkozaczuk** [comment]
@nyh You can replicate it by building and running rust-httpserver with OSv API server:
```
./scripts/build fs=rofs image=rust-httpserver,httpserver-html5-cli
./scripts/run.py
OSv v0.52.0-54-ga191c10e
eth0: 192.168.122.15
/rust-httpserver.so: failed looking up symbol _Unwind_GetRegionStart

[backtrace]
0x000000000035cc8d <elf::object::symbol(unsigned int, bool)+1325>
0x00000000003a7eb6 <elf::object::arch_relocate_rela(unsigned int, unsigned int, void*, long)+310>
0x00000000003597d4 <elf::object::relocate_rela()+196>
0x000000000035aa57 <elf::object::relocate()+199>
0x000000000035df94 <elf::program::load_object(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::al>
0x000000000035e8d2 <elf::program::get_library(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::al>
0x000000000042e2bc <osv::application::application(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<cha>
0x000000000022b916 <do_main_thread(void*)+1958>
0x000000000045b195 <???+4567445>
0x00000000003feb76 <thread_main_c+38>
0x00000000003a4112 <???+3817746>
```

Just for the sake of clarity I renamed locally libhttpserver.so to rust-httpserver.so.
I also verified that even the app build as cdylib still is BIND_NOW.

What I do not understand is why rust-httpserver works but itself but not with httpserver-api.so. How do these two (or more as httpserver-api.so depends on and comes with other shared objects) affect each other? Is it because they are possibly loaded from 2 different threads?

Finally I think (as you noted) this issue hopefully can be solved by doing something similar to arch_relocate_rela() as we did to arch_relocate_jump_slot().

**Comment by kaushalyap** [comment]
@wkozaczuk Side question here: can we use OSv with Rust for production? is there anything missing?

**Comment by nyh** [comment]
@kaushalyap please move side questions to the mailing list - osv-dev@googlegroups.com. Thanks.
