### ISSUE TITLE
Implement named semaphores

### ISSUE THREAD

**Issue by pshem** [cloudius-systems/osv#1025]
When testing various python3 modules, I triggered an unimplemented symbol in `scikit-learn`(aka. `sklearn`):
![selectionshot_2019-02-12_03 22 28](https://user-images.githubusercontent.com/26800787/52859032-94b4bd00-3123-11e9-87a4-7dd737726a6f.png)

This symbol was stubbed as unimplemented in Issue #77. If anyone has time to investigate, `scikit-learn` depends on `numpy` and `scipy` being present on the unikernel. I'll be publishing a PR for osv-apps adding a nice way to add selected python modules to the `python3x` osv-app shortly.

**Comment by pshem** [comment]
PR added: https://github.com/cloudius-systems/osv-apps/pull/61

**Comment by nyh** [comment]
While we could easily create stubs for `sem_open()` and related functions (`sem_close()`, `sem_unlink()`, using UNIMPL (so they crash when called) or returning an error when called, you'll need to check whether this is actually enough. It is possible that the code actually needs sem_open() to work correctly, and it's not enough for it to be a stub. There's really no way to tell without trying.

Instead, it will be better and probably easy to implement **named semaphores** (which `sem_open()` creates) properly, given that we already implemented unnamed semaphores (sem_init()) and semaphore operations on them in `libc/sem.cc`. Seems to me all we need to do is to add a global map `unordered_map<string, indirect_semaphore> to map names to semaphores. If you create such a patch I'll happily review it.

**Comment by wkozaczuk** [comment]
Also are we sure this is not an example of what #993 was trying to solve - resolution of a symbol failing on load - and some kind of gap we have in that implementation? We also have this new issue #1023 that may be another indicator. 

Is this happening with Python image being created on Fedora or Ubuntu? Shared libraries on Fedora tend to have BIND_NOW set to 1.

**Comment by nyh** [comment]
@wkozaczuk I think that because the backtrace has "elf_resolv_pltgot", it means this function was actually called during the actual run, and it was not just an issue of on-load linking of all the functions. I don't know what will happen if the function existed but returned an error, for example. But as I said above, I think it's easy to just go ahead and implement it.

**Comment by StonewallJohnson** [comment]
Hello, I am a student from the University of Texas at Austin. My group and I were wondering if we could try this issue as part of our assignment to contribute to open source virtualization projects? With approval from someone who is part of the project and our teacher, we can get started on this.

**Comment by wkozaczuk** [comment]
While the implementation should not be difficult, I think we should first assess how desirable this functionality is in the context of OSv. I would think the **named semaphores** are more likely used for interprocess communication while OSv is intended to run single applications which more likely would use **unnamed semaphores** that OSv implements already.
@nyh what do you think?

**Comment by nyh** [comment]
@wkozaczuk I agree, although if the implementation is relatively small, it can't hurt to have it even if it's not super useful.

I would start by finding some sort of application which actually uses named semaphores - one example was mentioned above, but as I noted I'm not even sure it needed a real implementation of named semaphores, maybe it just needed the functions to exist.

Alternatively, you can write a simple test program (you can make it into a real test in the `tests/` subdirectory) which tests the implementation, a program which you can run on both Linux and OSv to verify that the implementation works correctly (i.e., same as Linux).

Please check out my idea in https://github.com/cloudius-systems/osv/issues/1025#issuecomment-464434219 how perhaps the named semaphores can be implemented using the already-existing unnamed semaphores, and save a bit of implementation effort.

**Comment by wkozaczuk** [comment]
I think I agree with @nyh so let us go ahead and implement it. As a matter of fact, I do have an old branch with WIP of - https://github.com/cloudius-systems/osv/compare/master...wkozaczuk:osv:named_semaphores.

**Comment by EylamTagor** [comment]
Hi! I am in the group with @StonewallJohnson, confirming we are currently working on this issue.

**Comment by wkozaczuk** [comment]
Closed with https://github.com/cloudius-systems/osv/pull/1232/commits/253973197e86e9a43b3652fbbb911a4ca865f0a1
