### ISSUE TITLE
scripts/firecracker.py doesn't pass input to OSv

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#1028]
When running OSv under firecracker with scripts/firecracker.py, it seems the user's input isn't passed to OSv. For example,

If I try for example:
```
$ scripts/build fs=ramfs image=rogue
$ scripts/firecracker.py
```
The game rogue starts well (and almost instantaneously!), but when I try to move with "l", "h", etc., these characters just get printed on the screen and I don't see any evidence that it is being passed to OSv.

We need the user's input to be passed to OSv. Moreover, the terminal should be set to "raw mode" so that every character typed is passed immediately to OSv. Doesn't the firecracker executable take care of that?

CC @wkozaczuk

**Comment by wkozaczuk** [comment]
I have done more tests and indeed if one bypasses firecracker.py and starts firecracker process directly and then independently starts for example our python2x/3x app one can type and see output printed properly. 
This confirms that firecracker.py has to be adjusted to properly pass the input and output to/from firecracker process.
