### ISSUE TITLE
create image with 'ls' executable issue

### ISSUE THREAD

**Issue by taseikyo** [cloudius-systems/osv#1052]
Hi everyone,
I follow the guide [Building OSv kernel and creating images](https://github.com/cloudius-systems/osv#building-osv-kernel-and-creating-images) and run the following cmds to create image with 'ls' executable
```
./scripts/manifest_from_host.sh -w ls && ./scripts/build --append-manifest
./scripts/run.py
```
But I get an unexpected output...
```
...
Booted up in 0.00 ms
This image has an empty command line. Nothing to run.
```
Is there anything wrong?😂

Thanks in advance.

**Comment by nyh** [comment]
Please ask questions on the mailing list (osv-dev@googlegroups.com), not on the bug tracker.
If the image does not include a preset command line (I don't know where build --append-manifest gets it from), you can choose one with the "-e" option of run.py. For example "scripts/run.py -e /ls" runs the executable /ls (change the path to wherever you installed this ls).

**Comment by wkozaczuk** [comment]
./scripts/run.py -e '/ls'
./scripts/run.py -e '/ls -la'

The ./scripts/manifest_from_host.sh does not set a default command line
which it could.

Again from more details please ask us on the mailing list.

**Comment by taseikyo** [comment]
thanks for your reply : )
