### ISSUE TITLE
Boot on Firecracker does not achieve 15 ms boot time

### ISSUE THREAD

**Issue by hckuo** [cloudius-systems/osv#1054]
According this [post](https://github.com/cloudius-systems/osv/wiki/Running-OSv-on-Firecracker), OSV can boot within 15 ms on firecracker. I failed to reproduce it.
```
sudo FIRECRACKER_PATH=../firecracker ./scripts/firecracker.py -c 1 -m 2G
OSv v0.54.0
Booted up in 51.69 ms
Cmdline: /hello
Hello from C code
```
```
OS
Ubuntu Ubuntu 18.04.1-64
Security Device
SuperMicro AOM-TPM-9655V-C
Remote Mgmt Card
Aspeed AST2400 - Onboard
RAM
2x 8GB Micron 8GB DDR4 1Rx8
Modify
Processor
3.8GHz Intel Xeon-KabyLake (E3-1270-V6-Quadcore)
Modify
Power Supply
2x SuperMicro PWS-504P-1R
Motherboard
Supermicro X11SSW-4TF_R1.02
View details
Drive Controller
Mainboard Onboard
Modify
Backplane
SuperMicro BPN-SAS3-815TQ-N4
Hard Drive    Seagate Enterprise Capacity 3.5 V5    2000 GB
```

Is it normal or I missed something?

Thanks

**Comment by wkozaczuk** [comment]
I am guessing you built an image with ZFS which is default read-write filesystem which takes around 50-60ms to initialize. Try to build an image with ROFS (read-only FS) - `./scripts/build image=native-example fs=rofs`.

**Comment by hckuo** [comment]
thank you!
