### ISSUE TITLE
Upgrade utility scripts to Python 3

### ISSUE THREAD

**Issue by wkozaczuk** [cloudius-systems/osv#1056]
Given the Python end-of-life scheduled for Jan 1st, 2020, we should upgrade at least the key scripts (setup.py, module.py, test.py, etc) under script to be Python 3 compatible. 

Please see https://docs.python.org/3/howto/pyporting.html

**Comment by lgoldstein** [comment]
I second this - I recently installed Ubuntu 18 and it comes with Python 3 and not 2 (I can install Python 2 as well, but IMO it would not be advisable).

**Comment by BassMatt** [comment]
Hi!

I submitted a patch with a few changes to all the files listed in `scripts/README` to update them to python3. 

I was wondering if the files in `scripts/osv/`, and `scripts/trace.py` were in scope? I spent a little bit of time updating them but they seemed to do some more complicated things with `prof.py`, so I'm looking for a bit of guidance first..

**Comment by wkozaczuk** [comment]
@BassMatt thanks for the patch. Please address the minor issues others pointed on the mailing list and we will apply it. 
Regarding what is in scope I think that both `scripts/trace.py` and `scripts/osv/*` are. Though I would leave the `prof.py` for now as I am not sure how much used it used. In general, the most important ones are `scripts/run.py` and others used by it directly or indirectly as well as all the python files used by `script/build` (`module.py`, etc).

**Comment by wkozaczuk** [comment]
Following python files have been identified as 'in use' or deemed as possibly useful in the near future:
```
./modules/httpserver-html5-gui/tests/static/teststatic.py
./modules/httpserver-html5-gui/tests/testhttpserver.py
./scripts/export_manifest.py
./scripts/firecracker.py
./scripts/freq.py
./scripts/gen-rofs-img.py
./scripts/imgedit.py
./scripts/libosv.py
./scripts/loader.py
./scripts/manifest_common.py
./scripts/memory_analyzer.py
./scripts/metadata.py
./scripts/mkbootfs.py
./scripts/nbd_client.py
./scripts/osv/client.py
./scripts/osv/debug.py
./scripts/osv/modules/api.py
./scripts/osv/modules/filemap.py
./scripts/osv/modules/resolve.py
./scripts/osv/prof.py
./scripts/osv/trace.py
./scripts/osv/tree.py
./scripts/prof.py
./scripts/run.py
./scripts/setup.py
./scripts/tester.py
./scripts/test.py
./scripts/tests/test_app.py
./scripts/tests/test_app_with_test_script.py
./scripts/tests/test_http_app_with_curl_and_ab.py
./scripts/tests/testing.py
./scripts/tests/test_net.py
./scripts/tests/test_tracing.py
./scripts/top.py
./scripts/trace.py
./scripts/upload_manifest.py
./tests/tst-tcp-hash-cli.py
```
