### ISSUE TITLE
OSv inside MikroTik METARouter VM?

### ISSUE THREAD

**Issue by cypa** [cloudius-systems/osv#1075]
any chance to use OSv inside MikroTik METARouter VM?
honestly it's a weird feature of MikroTik but anyway please take a look at https://wiki.mikrotik.com/wiki/Manual:Metarouter

**Comment by nyh** [comment]
This is OSv's bug tracker, listing specific bugs and issues - not a place to ask questions. For that, we have the mailing list - osv-dev@googlegroups.com.
Anyway, the answer to your question is probably no, or at least not easily - what processor does this metarouter have? OSv only support x86-64 and, partially, 64-bit ARM at the moment. OSv would probably also need drivers to work in this METARouter VM - I don't know what its network, for example, looks like. If you want to continue discussing this, let's use the mailing list.
