### ISSUE TITLE
malloc_usable_size of malloc_large returns incorrect value.

### ISSUE THREAD

**Issue by Pusnow** [cloudius-systems/osv#1077]
OSv uses `malloc_large` for huge memory request, and it stores alloced size (page alloced) in header (`page_range`).

https://github.com/cloudius-systems/osv/blob/69ea10059c579ccdfbcd154c13a466e18fd81a38/core/mempool.cc#L844-L850

However, in `large_object_size` it only returns `size` in header.

https://github.com/cloudius-systems/osv/blob/69ea10059c579ccdfbcd154c13a466e18fd81a38/core/mempool.cc#L1070-L1075
 

I think `malloc_usable_size` should subtract `offset` or header size.

Example code:

```
#include <stdio.h>
#include <stdlib.h>

int main()
{
	
	void* ptr = malloc(0x4010);
	int size = malloc_usable_size(ptr);

	printf("ptr: %p size: %lx\n", ptr, size); 

	return 0;
}
```

Output:
```
Cmdline: /hello
ptr: 0xffff800001b64040 size: 5000 
```

I think the `size` should be `0x4FC0`.

**Comment by wkozaczuk** [comment]
You might be right. What I am more worried that std_realloc that depends on it might be wrong:
```c++
static inline void* std_realloc(void* object, size_t size)
{
    if (!object)
        return malloc(size);
    if (!size) {
        free(object);
        return nullptr;
    }

    size_t old_size = object_size(object);
    size_t copy_size = size > old_size ? old_size : size;
    void* ptr = malloc(size);
    if (ptr) {
        memcpy(ptr, object, copy_size);
        free(object);
    }

    return ptr;
}
```

**Comment by wkozaczuk** [comment]
We clearly have bigger issue - here is the related issue #784.
