### ISSUE TITLE
Build process can't find Lua libraries

### ISSUE THREAD

**Issue by milisarge** [cloudius-systems/osv#1082]
```
# ldconfig -p | grep -Po "liblua*.5\.3.so.0" | head -1

# ls /usr/lib/liblua.
liblua.a         liblua.so        liblua.so.5.3    liblua.so.5.3.5 
```
modules/Lua/Makefile line 17
`LUA_LIBRARY := $(shell ldconfig -p | grep -Po "liblua*.5\.3.so.0" | head -1)`
 i doubt it works properly?

**Comment by wkozaczuk** [comment]
Hi,

I think it works on both Ubuntu and Fedora. But I could imagine it failing on some distributions. `scripts/setup.py` should be installing Lua 5.3.*.

Which version of OSv are you referring to? The line 17 of this Makefile looks different from what you are reporting.

Here is what I see:
```
10 LUA_LIBRARY := $(shell ldconfig -p | grep -Po "liblua*.5\.3.so.0" | head -1)
11 ifndef LUA_LIBRARY
12         LUA_LIBRARY := $(shell ldconfig -p | grep -Po "liblua*.5\.3.so" | head -1)
13 endif
```

Can you show us output from `ldconfig -p`?

**Comment by milisarge** [comment]
line number can be different(i added comments etc.) but makefiles are same as at you.
```
# ldconfig -p | grep lua
	liblua5.2.so.5.2 (libc6,x86-64) => /lib/liblua5.2.so.5.2
	liblua5.2.so (libc6,x86-64) => /lib/liblua5.2.so
	libluajit-5.1.so.2 (libc6,x86-64) => /lib/libluajit-5.1.so.2
	libluajit-5.1.so (libc6,x86-64) => /lib/libluajit-5.1.so
	liblua.so.5.3 (libc6,x86-64) => /lib/liblua.so.5.3
	liblua.so (libc6,x86-64) => /lib/liblua.so
```
my distro is LFS based. but Lua works properly

**Comment by wkozaczuk** [comment]
The commit 05c06bafd55e96419171147a44fb52f635e65ec9 revamped a process to build the module lua and the particular line mentioned in the description of this issue is gone. So this issue is no longer relevant and I am closing it.
