### ISSUE TITLE
Accessing raw packets (straightforward connection with the interfaces)

### ISSUE THREAD

**Issue by ViniGarcia** [cloudius-systems/osv#1089]
There any support to PF_PACKET protocol (even it being based in FreeBSD) or a bpf or netpcap porting to OSv?

Thanks so much! :)

**Comment by ViniGarcia** [comment]
PS: PF_PACKET + binding the socket to a device.

**Comment by wkozaczuk** [comment]
Could you please ask your question on the mailing list?
