### ISSUE TITLE
aarch64: bugs in arm-clock

### ISSUE THREAD

**Issue by wkozaczuk** [cloudius-systems/osv#1091]
It appears there are bugs in the [arm-clock implementation](https://github.com/cloudius-systems/osv/blob/master/arch/aarch64/arm-clock.cc) that cause time/clock related "misbehaviors".

Looking at the code, both the `boot_time()` and `time()` delegate to `uptime()`, which seems to be wrong. The `boot_time()` should return a constant value captured early and represent the point-it-time the boot process started (see at hpet.cc which returns `_wall` value). Similarly `time()` should be equal to sum of `uptime()` and `boottime()` which does not seem to be the case for arm_clock.

**Comment by anirudh-goyal** [comment]
Hello, I'm a CS student at UT Austin. I was wondering if me and my classmates could work on this issue as part of our virtualization class? Thank you!

**Comment by nyh** [comment]
> Hello, I'm a CS student at UT Austin. I was wondering if me and my classmates could work on this issue as part of our virtualization class? Thank you!

Sure you can, and we'll be happy to help if we can. If you have general questions on OSv, how to run it, how it works, etc., please subscribe to the OSv mailing list (osv-dev@googlegroups.com) and ask questions there. On this bug tracker here we should focus on the specific issue. Good luck.

**Comment by wkozaczuk** [comment]
Hi @anirudh-goyal! Please note that my comment mentioning printing `inf` most likely is not related to this issue but to the lack of proper floating-point support in aarch64 port that is addressed by the pending musl upgrade patch.

Also to develop/test this issue you will need to be able to build and run aarch64 images. The best Linux distribution for that is Fedora if you want to cross-compile and run the image in the emulated mode on x64 hardware. If you do not like this, you can also run OSv on the latest Raspberry PI 4.

For more details about the state of our AArch64 port read this wiki page - https://github.com/cloudius-systems/osv/wiki/AArch64

**Comment by michaelsatanovsky** [comment]
Hi. I'm working with @anirudh-goyal on this issue. Is there some documentation or something for me to read to understand the expected behavior for `u64 processor_to_nano(u64 ticks)`?

**Comment by wkozaczuk** [comment]
Unfortunately, there is no specific documentation of how this method should operate except for the comments in https://github.com/cloudius-systems/osv/blob/master/drivers/clock.hh. 

You can also compare the existing implementation of it used by kvm and xen paravirtual clocks - see include/osv/pvclock-abi.hh. This [commit](https://github.com/cloudius-systems/osv/commit/2df3c0293aa2b237402e97cc90408baccf0e4440) comments might also help.

**Comment by wkozaczuk** [comment]
@michaelsatanovsky @anirudh-goyal are you still working on this issue?

**Comment by wkozaczuk** [comment]
I think to properly implement `time()` we need to add support of PrimeCell RTC (PL031) - https://developer.arm.com/documentation/ddi0224/c/Functional-overview/RTC-operation/RTC-operation.
