### ISSUE TITLE
x86_64 build error

### ISSUE THREAD

**Issue by punitagrawal** [cloudius-systems/osv#1099]
I am building top of tree ( currently bd3c1e8b ("aarch64: implement feenableexcept/fedisableexcept/fegetexcept")) on an Ubuntu 18.04 system and get the following error when running `./scripts/build -j1 image=native-example`.

Any idea what I am doing wrong?

```
  ...
  AS libc/arch/x64/ucontext/setcontext.s
  AS libc/arch/x64/ucontext/start_context.s
  CXX libc/arch/x64/ucontext/ucontext.cc
  CC libc/stdio/__fdopen.c
In file included from <command-line>:0:0:
libc/stdio/__fdopen.c: In function ‘__fdopen’:
./libc/syscall_to_function.h:13:66: error: expected ‘)’ before ‘__VA_OPT__’
 #define __OSV_TO_FUNCTION_SYS_fcntl(fd, cmd, ...) (fcntl(fd, cmd __VA_OPT__(,) __VA_ARGS__))
                                                                  ^
./libc/syscall_to_function.h:34:37: note: in expansion of macro ‘__OSV_TO_FUNCTION_SYS_fcntl’
 #define __syscall(sys_number, ...) (__OSV_TO_FUNCTION_##sys_number(__VA_ARGS__) < 0 ? -errno : 0)
                                     ^~~~~~~~~~~~~~~~~~
libc/stdio/__fdopen.c:30:25: note: in expansion of macro ‘__syscall’
  if (strchr(mode, 'e')) __syscall(SYS_fcntl, fd, F_SETFD, FD_CLOEXEC);
                         ^~~~~~~~~
./libc/syscall_to_function.h:13:66: error: expected ‘)’ before ‘__VA_OPT__’
 #define __OSV_TO_FUNCTION_SYS_fcntl(fd, cmd, ...) (fcntl(fd, cmd __VA_OPT__(,) __VA_ARGS__))
                                                                  ^
./libc/syscall_to_function.h:34:37: note: in expansion of macro ‘__OSV_TO_FUNCTION_SYS_fcntl’
 #define __syscall(sys_number, ...) (__OSV_TO_FUNCTION_##sys_number(__VA_ARGS__) < 0 ? -errno : 0)
                                     ^~~~~~~~~~~~~~~~~~
libc/stdio/__fdopen.c:34:15: note: in expansion of macro ‘__syscall’
   int flags = __syscall(SYS_fcntl, fd, F_GETFL);
               ^~~~~~~~~
./libc/syscall_to_function.h:13:66: error: expected ‘)’ before ‘__VA_OPT__’
 #define __OSV_TO_FUNCTION_SYS_fcntl(fd, cmd, ...) (fcntl(fd, cmd __VA_OPT__(,) __VA_ARGS__))
                                                                  ^
./libc/syscall_to_function.h:34:37: note: in expansion of macro ‘__OSV_TO_FUNCTION_SYS_fcntl’
 #define __syscall(sys_number, ...) (__OSV_TO_FUNCTION_##sys_number(__VA_ARGS__) < 0 ? -errno : 0)
                                     ^~~~~~~~~~~~~~~~~~
libc/stdio/__fdopen.c:36:4: note: in expansion of macro ‘__syscall’
    __syscall(SYS_fcntl, fd, F_SETFL, flags | O_APPEND);
    ^~~~~~~~~
make: *** [build/release.x64/libc/stdio/__fdopen.o] Error 1
Makefile:337: recipe for target 'build/release.x64/libc/stdio/__fdopen.o' failed
make failed. Exiting from build script
```

**Comment by nyh** [comment]
According to https://gcc.gnu.org/onlinedocs/cpp/Variadic-Macros.html, "__VA_OPT__" is a new C++20 feature, so it probably doesn't work on your older compiler. I'll try to come up with an alternative implementation that doesn't rely on very new features. Or @wkozaczuk maybe you have an idea?

**Comment by nyh** [comment]
I'm preparing a patch and will send it to the mailing list in a few minutes. @punitagrawal please try it, and @wkozaczuk please review it. Thanks.

**Comment by punitagrawal** [comment]
> According to https://gcc.gnu.org/onlinedocs/cpp/Variadic-Macros.html, "`__VA_OPT__`" is a new C++20 feature, so it probably doesn't work on your older compiler. I'll try to come up with an alternative implementation that doesn't rely on very new features. Or @wkozaczuk maybe you have an idea?

Thanks for the reply.

The compiler is indeed not quite state of the art. It's the default shipping with Bionic (pasting version information for reference).

`
% gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
`

Installing and using gcc-8 fixes the build issue for me.

**Comment by punitagrawal** [comment]
> I'm preparing a patch and will send it to the mailing list in a few minutes. @punitagrawal please try it, and @wkozaczuk please review it. Thanks.

After applying the patch manually (I don't see an option to download and I am not subscribed), I was able to compile the native-example with gcc-7 shipped with bionic.

Thanks for the quick fix.
