### ISSUE TITLE
Identify and reject executables not matching kernel machine (x64, aarch64)

### ISSUE THREAD

**Issue by wkozaczuk** [cloudius-systems/osv#1104]
As @punitagrawal notices in issue #1103, OSv kernel happily tries to execute 64-bit executables that do not match the machine of the kernel - for example `aarch64` kernel loading and executing `x64` executable which leads to a confusing message.

It should not be difficult to parse the machine identifier from OSv kernel ELF header, compare it with the executable machine and reject to load/process it if different.

**Comment by SamLab17** [comment]
Hi, can I take a shot at this issue? I recently mentioned in the Google group I was looking for some issues to get started contributing.

**Comment by wkozaczuk** [comment]
Go for it
