### ISSUE TITLE
Make getpid() return non-zero number

### ISSUE THREAD

**Issue by wkozaczuk** [cloudius-systems/osv#1109]
Currently, `getpid()` and other related code in OSv uses `0` as the kernel/app process ID. This works for most apps but for example .NET core apps reject 0 and crash (see the relevant [discussion](https://groups.google.com/g/osv-dev/c/k69cHw7qvTg/m/z6s86f61CQAJ) on the mailing list).

It would be nice to make PID a constant that can be changed to any number. 1 could be a good candidate.

**Comment by nyh** [comment]
Note that pid 1 also has a special significance in Linux, so maybe we should set this constant by default to 2. Or to 42 :-)

**Comment by SamLab17** [comment]
I'd be happy to take a look at this! Although, still being new to the project, I'm not sure where the best place to define this constant would be so that it's accessible everywhere and also easily configurable. Are there any examples of some other configurable constants I could look at?

**Comment by wkozaczuk** [comment]
@SamLab17 the pid does not need to be configurable - it is enough for it to be `const` or `#define`. I am not sure of a good header - maybe new `include/osv/pid.h`? The key is that it needs to be include-able by both C and C++ files - `./libc/unistd/getppid.c` and `runtime.cc`.

Please note this issue is not as easy as changing `getpid()` and `getppid()` to use new constant but also find any places that assume process ID is 0. One interesting place is `kill()` implementation in `libc/signal.cc`.

**Comment by wkozaczuk** [comment]
Fixed by the commit c5a08457c6d0ce82eee4f9899c2e84591d80e7f6
