### ISSUE TITLE
tst-stdio-rofs fails in x86_64 too

### ISSUE THREAD

**Issue by kimjungwow** [cloudius-systems/osv#1114]
Hi!

I try to run tests with building top of tree ( currently 04a3d7e557c3813a2ffc9ca7b66880c821e92b4f ("build: enforce Partial RELRO for internal apps")) on an Ubuntu 20.04 system. I checked my `host_arch` is x86_64 by `uname -m`.

When I run `./scripts/build check fs=rofs`, it seems **tst-stdio-rofs fails in x86_64 too.**
![Imgur](https://imgur.com/5hSN9v4.png)

**Comment by wkozaczuk** [comment]
I bet this particular assertion fails on QEMU with TCG (Tiny Code
Generator) meaning no KVM acceleration. It fails because without
acceleration this particular part of the test takes too long to complete.
Possibly the best thing to do is to disable this part of the test.

Can you execute run.py with --dry-run option to see what QEMU command line
shows?

**Comment by kimjungwow** [comment]
Hi!
When I execute `./scripts/run.py --dry-run`, I got following outputs.

```
/home/XXXX/Desktop/OSV/scripts/../scripts/imgedit.py setargs /home/XXXX/Desktop/OSV/build/last/usr.img "--rootfs=rofs "
qemu-system-x86_64 \
-m 2G \
-smp 4 \
-vnc :1 \
-gdb tcp::1234,server,nowait \
-device virtio-blk-pci,id=blk0,drive=hd0,scsi=off,bootindex=0 \
-drive file=/home/XXXX/Desktop/OSV/build/last/usr.img,if=none,id=hd0,cache=none,aio=native \
-netdev user,id=un0,net=192.168.122.0/24,host=192.168.122.1 \
-device virtio-net-pci,netdev=un0 \
-device virtio-rng-pci \
-chardev stdio,mux=on,id=stdio,signal=off \
-mon chardev=stdio,mode=readline \
-device isa-serial,chardev=stdio
```

**Comment by wkozaczuk** [comment]
Yep. It looks like you are running without KVM on (possibly nested virtualization?). 
In any case this specific part of tst-stdio.cc:

```
TEST(STDIO_TEST, fread_unbuffered_pathological_performance) {
  FILE* fp = fopen("/dev/random", "r");
  ASSERT_TRUE(fp != nullptr);

  // Make this stream unbuffered.
  setvbuf(fp, nullptr, _IONBF, 0);

  char buf[65*1024];
  memset(buf, 0xff, sizeof(buf));

  time_t t0 = time(nullptr);
  for (size_t i = 0; i < 1024; ++i) {
    ASSERT_EQ(1U, fread(buf, 64*1024, 1, fp));
  }
  time_t t1 = time(nullptr);

  fclose(fp);

  // 1024 64KiB reads should have been very quick.
  ASSERT_LE(t1 - t0, 1);

  for (size_t i = 64*1024; i < 65*1024; ++i) {
    ASSERT_EQ('\xff', buf[i]);
  }
}
```

has an assert verifying that the reads do not take longer than 1s which seems to be failing in your case. I guess we should disable this part of the test.
