### ISSUE TITLE
aarch64: virtio::register_mmio_devices() sometimes page faults on real hardware like RockPro64 or Odroid

### ISSUE THREAD

**Issue by wkozaczuk** [cloudius-systems/osv#1117]
This was initially reported here - https://github.com/cloudius-systems/osv/issues/1106#issuecomment-735759882.
When it crashes the output looks like this:
```
./scripts/run.py 
OSv v0.55.0-164-gd58635f3
getauxval() stubbed
page fault outside application, addr: 0xffff80000a000000
[registers]
PC: 0x00000000402ea2c0 <mmio_getl(void volatile*)+0>
X00: 0xffff80000a000000 X01: 0x008000000a000713 X02: 0xffff80000a001000
X03: 0x008000000a000713 X04: 0xffff80000a000000 X05: 0xffff80000a000fff
X06: 0xffff80000a000000 X07: 0x0000000000000000 X08: 0x0000000000000001
X09: 0xffff800040ed7008 X10: 0x0000000000000713 X11: 0xfffffffffffff8a3
X12: 0x0080000000000003 X13: 0x0000200000100a40 X14: 0x0000000000000703
X15: 0x0000000000000000 X16: 0x0000000000000000 X17: 0x0000000000000000
X18: 0x0000000000000000 X19: 0xffffa00040ed9140 X20: 0xffffa000407e71a0
X21: 0x0000000000000030 X22: 0x0000000000000200 X23: 0x0000000040554390
X24: 0xffffa000407e7260 X25: 0xffffa00040c68cc0 X26: 0x00000000401fd670
X27: 0x000000000a000000 X28: 0x0000000040735010 X29: 0x0000200000100aa0
X30: 0x00000000401fd394 SP:  0x0000200000100aa0 ESR: 0x0000000096000007
PSTATE: 0x0000000080000345
Aborted

[backtrace]
0x00000000401d9564 <mmu::vm_fault(unsigned long, exception_frame*)+724>
0x000000004020aa54 <page_fault+192>
0x000000004020a824 <???+1075882020>
0x00000000401fd504 <virtio::register_mmio_devices(hw::device_manager*)+180>
0x00000000402083a0 <arch_init_drivers()+256>
0x00000000400daf48 <do_main_thread(void*)+104>
0x0000000040347240 <???+1077178944>
0x00000000402e7ad0 <thread_main_c+32>
0x00000000402e5468 <sched::cpu::reschedule_from_interrupt(bool, std::chrono::duration<long, std::ratio<1l, 1000000000l> >)+788>
```

**Comment by wkozaczuk** [comment]
This patch seems to make the problem go away based on hundreds of executions on the same hardware it used to crash:

```
diff --git a/drivers/virtio-mmio.cc b/drivers/virtio-mmio.cc
index 43db8130..55cea144 100644
--- a/drivers/virtio-mmio.cc
+++ b/drivers/virtio-mmio.cc
@@ -113,6 +113,7 @@ void mmio_device::register_interrupt(interrupt_factory irq_factory)
 bool mmio_device::parse_config()
 {
     _addr_mmio = mmio_map(_dev_info._address, _dev_info._size);
+    mmu::flush_tlb_all();
 
     u32 magic = mmio_getl(_addr_mmio + VIRTIO_MMIO_MAGIC_VALUE);
     if (magic != ('v' | 'i' << 8 | 'r' << 16 | 't' << 24)) {
```

It is not clear why flushing TLB helps or why it is necessary. It might be that the side effects of executing `mmu::flush_tlb_all()` make this problem go away. This could be a problem of overlapping mapping possibly. It could be that mapping device memory on aarch64 always requires flushing TLB afterwards.

Finally, looking at the value of ESR (Syndrom Register) - `0x0000000096000007` - the EC class is `0b100101` ([ISS encoding for an exception from a Data Abort](https://developer.arm.com/docs/ddi0595/g/aarch64-system-registers/esr_el1#ISS_anexceptionfromaDataAbort)) and Data Fault Status Code is `0b000111` which indicates Translation fault, level 3.

**Comment by nyh** [comment]
Interesting. Flushing the TLB is important if the target address might have previously been used, but is this the case here?
You can test your other guesses by replcing flush_tlb_all() by a sleep(1) or something, and seeing (maybe) if just the time passing or context switches or something solves the problem, or a flush_tlb_all() is really needed. I have one wild guess: Maybe physical memory was previously mapped using huge pages, and now that you break this mapping up into smaller maps (if that's the case...) you need to delete the old TLB entries? But this is just a wild, and likely incorrect, guess.

Also I have to admit, I don't understand or remember, what, if anything, mmio_map() actually does. Don't we already have a mapping of the *entire* physical memory (and malloc(), for example, uses it)?

**Comment by wkozaczuk** [comment]
One more observation - this does not happen with a single vCPU. So it is another SMP related issue.

**Comment by punitagrawal** [comment]
Thanks for raising an issue from the earlier report.

> ```
> diff --git a/drivers/virtio-mmio.cc b/drivers/virtio-mmio.cc
> index 43db8130..55cea144 100644
> --- a/drivers/virtio-mmio.cc
> +++ b/drivers/virtio-mmio.cc
> @@ -113,6 +113,7 @@ void mmio_device::register_interrupt(interrupt_factory irq_factory)
>  bool mmio_device::parse_config()
>  {
>      _addr_mmio = mmio_map(_dev_info._address, _dev_info._size);
> +    mmu::flush_tlb_all();
>  
>      u32 magic = mmio_getl(_addr_mmio + VIRTIO_MMIO_MAGIC_VALUE);
>      if (magic != ('v' | 'i' << 8 | 'r' << 16 | 't' << 24)) {
> ```
> 
> It is not clear why flushing TLB helps or why it is necessary. It might be that the side effects of executing `mmu::flush_tlb_all()` make this problem go away. This could be a problem of overlapping mapping possibly. It could be that mapping device memory on aarch64 always requires flushing TLB afterwards.

This made me go look at the definition of flush_tlb_all() for arm64.

```
void flush_tlb_all() {
    asm volatile("dsb sy; tlbi vmalle1is; dsb sy; isb;");
}
```

I think I have an explanation - The issue isn't helped so much by the "TLB clean + Invalidate" as much as the synchronization barriers in there. On arm64, any page table updates need to be followed by appropriate barrier operations - in this case a `dsb` and an `isb`. The corresponding commit log in the Linux kernel page table operations for arm64[0] has a good explanation for what's going on. The translation fault encountered here also matches the expected behaviour when the `isb` is missing.

To test this, I replaced the `flush_tlb_all()` with just `asm volatile("dsb sy; isb;");` and wasn't able to reproduce the problem (though I did see an  infrequent crash due to another issue) while running `hello-world` in a loop (~100 times). Can you confirm if the dsb + isb makes the problem go away for you too?

Things became a lot less clear when looking for the right place to fix this in the architecture specific code. AFAICT, the OSv page table operations don't expose the appropriate hooks for the architecture to perform any necessary maintenance operations.

If I've followed the OSv page table operations correctly, something like below (better factored for architectural abstraction) is needed - 

```
diff --git a/include/osv/mmu-defs.hh b/include/osv/mmu-defs.hh
index 18edf4413c90..22b6f69f15a7 100644
--- a/include/osv/mmu-defs.hh
+++ b/include/osv/mmu-defs.hh
@@ -202,6 +202,7 @@ public:
     pt_element<N> ll_read() const { return *p; }
     void write(pt_element<N> pte) {
         *const_cast<volatile u64*>(&p->x) = pte.x;
+       asm volatile("dsb sy; isb;");
     }
 protected:
     hw_ptep_impl(pt_element<N>* ptep) : hw_ptep_impl_base<N>(ptep) {}
```

[0] https://github.com/torvalds/linux/commit/d0b7a302d58abe24ed0f32a0672dd4c356bb73db

**Comment by wkozaczuk** [comment]
@punitagrawal Indeed your suggestion seems to help in my case as well. It is so great you nailed it down!

Probably the best way would be to move the implementation of `hw_ptep_impl::write()` to `arch/*64/arch-mmu.hh` files.

Also, I wonder if we need to use synchronization barriers for `hw_ptep_rcu_impl::write()`.
