### ISSUE TITLE
aarch64: does not build on Fedora 31

### ISSUE THREAD

**Issue by hlef** [cloudius-systems/osv#1126]
Following [the wiki](https://github.com/cloudius-systems/osv/wiki/AArch64), `./scripts/build` fails with the following output:
```
# ./scripts/build image=empty fs=ramfs -j4 arch=aarch64
[...]
  OBJCOPY build/release.aarch64/preboot.bin
  LINK kernel.elf
  LINK zfs.so
  LINK mkfs.so
  STRIP kernel.elf -> kernel-stripped.elf 
DUP FUNXC
DUP FUNXC
DUP FUNXC
  LINK cpiod.so
  MKBOOTFS build/release.aarch64/bootfs.bin
  AS bootfs.S
  LINK loader.elf
  LIBOSV.SO
  STRIP loader.elf -> loader-stripped.elf 
DUP FUNXC
DUP FUNXC
DUP FUNXC
  DD build/release.aarch64/loader.img preboot.bin
  DD build/release.aarch64/loader.img loader-stripped.elf
  IMGEDIT build/release.aarch64/loader.img
Unable to resolve libgcc_s.so.1 using "aarch64-linux-gnu-gcc".
Looking in ../downloaded_packages/aarch64/gcc/install/lib64
```

This happens on Fedora 31 (I did not try other versions of Fedora).

Am I doing something wrong?

**Comment by wkozaczuk** [comment]
Do you have the latest master? I pushed some changes a couple of days ago,
that may have fixed a related issue.

BTW "Looking in ../downloaded_packages/aarch64/gcc/install/lib64" is
normal. I do not see any error.

**Comment by hlef** [comment]
Thanks again for the quick answer! Indeed, taking another look, it seems that the build succeeded. I was just confused by that error message. Sorry for the noise, and thanks for the great work!

**Comment by wkozaczuk** [comment]
@hlef Do you mind closing this issue if you are satisfied with the response?
