### ISSUE TITLE
aarch64: unmask interrupts on non-primary cores

### ISSUE THREAD

**Issue by wkozaczuk** [cloudius-systems/osv#1132]
As part of the research of issue #1123, I have discovered that the generic timer interrupts (PPI - Private Peripheral Interrupt) are never delivered on non-primary cores even though the timer condition is properly set. This causes many unit tests to hang. 

After trial-and-error (I could not quite figure it out of the GIC documentation), I have discovered that the timer interrupts need to be also unmasked on secondary CPU to make those CPUs receive timer interrupts. This very hacky patch below illustrates what needs to be done:
```
diff --git a/arch/aarch64/gic.cc b/arch/aarch64/gic.cc
index 9aba2c9f..a01ecd1d 100644
--- a/arch/aarch64/gic.cc
+++ b/arch/aarch64/gic.cc
@@ -58,6 +58,9 @@ void gic_driver::init_cpu(int smp_idx)
     gicc_ctlr |= 1;
     this->gicc.write_reg(gicc_reg::GICC_CTLR, gicc_ctlr);
 
+    if (smp_idx)
+        this->gicd.write_reg_grp(gicd_reg_irq1::GICD_ISENABLER, 27, 1);
+
 #if CONF_logger_debug
     debug_early("CPU interface enabled.\n");
 #endif
```

In essence, it unmasks the timer interrupt (Id=27) on every non-primary cpu during this cpu GIC initialization.

There is only one instance of PPI interrupt used in OSv - in arm clock events - but I am afraid we might be missing similar unmasking logic for other kinds of interrupts SGI (Software Generated Interrupts) - used for interprocessor communication and SPI (Shared Peripheral Interrupt) - used for all other devices but arm clock.

**Comment by nyh** [comment]
Hmm, I'm not an expert in this code but I have a question: If I remember correctly, the code setting a timer unmasks the timer interrupt (for the current core) - which we mask while handling this interrupt - so why wasn't that unmasking enough?

**Comment by wkozaczuk** [comment]
I am not an expert either and still learning :-). But in short for the timer interrupts to "work", many dots need to be connected. As I understand, when the timer condition is met (`CVAL` <= global system counter) on a specific core, the interrupt signal is asserted to the interrupt controller (GIC - Generic Interrupt Controller) only when that CPU timer is enabled (ENABLE bit) and interrupt unmasked (IMASK bit) in the core timer control register (`CTL` registers). So in essence unmasking at this level only takes care of delivering a signal to GIC. And this is what we were discussing in that other alarm clock event-related patch. 

Now once the signal is asserted on the GIC side, it is up to other settings in GIC if the corresponding timer interrupt (PPI - Private Peripheral Interrupt) will be delivered to that core back where the timer condition is met. One of these settings is another masking of interrupts driven by the `GICD_ISENABLER` register which in essence dictates if the interrupts are forwarded to specific cores (https://developer.arm.com/documentation/ihi0048/b/Programmers--Model/Distributor-register-descriptions/Interrupt-Set-Enable-Registers--GICD-ISENABLERn?lang=en):

"Interrupt Set-Enable Registers, GICD_ISENABLERn
The GICD_ISENABLER characteristics are:

Purpose
The GICD_ISENABLERs provide a Set-enable bit for each interrupt supported by the GIC. Writing 1 to a Set-enable bit enables forwarding of the corresponding interrupt from the Distributor to the CPU interfaces. Reading a bit identifies whether the interrupt is enabled.

Usage constraints
A register bit corresponding to an unimplemented interrupt is RAZ/WI.

If the GIC implements the Security Extensions:

a register bit that corresponds to a Group 0 interrupt is RAZ/WI to Non-secure accesses
if the GIC implements configuration lockdown, the system can lock down the Set-enable bits for the lockable SPIs that are configured as Group 0, see Configuration lockdown.
Whether implemented SGIs are permanently enabled, or can be enabled and disabled by writes to GICD_ISENABLER0 and GICD_ICENABLER0, is implementation-defined.

Configurations
These registers are available in all configurations of the GIC. If the GIC implements the Security Extensions these registers are Common.

The number of implemented GICD_ISENABLERs is (GICD_TYPER.ITLinesNumber+1). The implemented GICD_ISENABLERs number upwards from GICD_ISENABLER0.

**In a multiprocessor implementation, GICD_ISENABLER0 is banked for each connected processor. This register holds the Set-enable bits for interrupts 0-31**."
