### ISSUE TITLE
Implement subset of arch_prctl syscall to support local-exec TLS of statically linked executables

### ISSUE THREAD

**Issue by wkozaczuk** [cloudius-systems/osv#1137]
The Golang apps like our `golang-pie-example` built with newer Golang compiler/linker (at least as of 1.15) no longer run correctly on OSv and crash like so:
```
OSv v0.55.0-247-g1433c08b
eth0: 192.168.122.15
Booted up in 162.61 ms
Cmdline: /hello.so
syscall(): unimplemented system call 158
Aborted

[backtrace]
0x00000000402178f7 <???+1075935479>
0x000000004046369e <osv::handle_mmap_fault(unsigned long, int, exception_frame*)+30>
0x0000000040342a1a <mmu::vm_fault(unsigned long, exception_frame*)+298>
0x0000000040390d5f <page_fault+143>
0x000000004038fc16 <???+1077476374>
0x0000100000066c9f <???+421023>
0x000000004045f2a5 <???+1078325925>
0x00000000403fbd89 <thread_main_c+41>
0x0000000040390b92 <???+1077480338>
```

The unimplemented syscall 158 is `__NR_arch_prctl` which can be used to set FS_BASE for local-exec TLS. It looks like something had changed in the Golang build-chain between 1.12 and 1.15. The Golang apps built with  ` -buildmode=pie` used to work just fine on OSv. It seems that in the past the Golang produced pies used to use two ways of communicating with kernel - 1) via SYSCALL instruction and 2) via libc calls for pthreads (OSv still does not support the **clone** syscall). The newer build chain seems to produce an executable that only communicates via SYSCALL.

Here is some info about the executable:
```
file apps/golang-pie-example/hello.so 
apps/golang-pie-example/hello.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=KLddGH5JkygDOUUjd9N8/Bw6msSNbQDLVNmZHbfg9/N-nQvH6Ne9pl5aExWhga/Ncb0ercFgAfBxICpTZba, not stripped

ldd apps/golang-pie-example/hello.so
	statically linked

readelf -l apps/golang-pie-example/hello.so 

Elf file type is DYN (Shared object file)
Entry point 0x465080
There are 12 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  PHDR           0x0000000000000040 0x0000000000400040 0x0000000000400040
                 0x00000000000002a0 0x00000000000002a0  R      0x1000
  INTERP         0x0000000000000fe4 0x0000000000400fe4 0x0000000000400fe4
                 0x000000000000001c 0x000000000000001c  R      0x1
      [Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]
  NOTE           0x0000000000000f80 0x0000000000400f80 0x0000000000400f80
                 0x0000000000000064 0x0000000000000064  R      0x4
  LOAD           0x0000000000000000 0x0000000000400000 0x0000000000400000
                 0x0000000000099ed0 0x0000000000099ed0  R E    0x1000
  LOAD           0x000000000009a000 0x000000000049a000 0x000000000049a000
                 0x0000000000072ce5 0x0000000000072ce5  R      0x1000
  LOAD           0x000000000010d000 0x000000000050d000 0x000000000050d000
                 0x0000000000086467 0x0000000000086467  RW     0x1000
  GNU_RELRO      0x000000000010d000 0x000000000050d000 0x000000000050d000
                 0x0000000000086467 0x0000000000086467         0x1000
  LOAD           0x0000000000194000 0x0000000000594000 0x0000000000594000
                 0x0000000000015a00 0x00000000000481a8  RW     0x1000
  DYNAMIC        0x0000000000194040 0x0000000000594040 0x0000000000594040
                 0x00000000000000b0 0x00000000000000b0  RW     0x8
  TLS            0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000008  R      0x8
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x8
  LOOS+0x5041580 0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000         0x8

readelf -s apps/golang-pie-example/hello-stripped.so 

Symbol table '.dynsym' contains 1 entry:
   Num:    Value          Size Type    Bind   Vis      Ndx Name
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND 
```

The info seems to be a bit confusing as it suggests that the executable is position-dependent (the entry point) and is statically linked.

I have also experimented with basic C hello world app linked statically and here is some info:
```
 readelf -l apps/native-static-example/hello

Elf file type is EXEC (Executable file)
Entry point 0x401ce0
There are 8 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000400000 0x0000000000400000
                 0x0000000000000488 0x0000000000000488  R      0x1000
  LOAD           0x0000000000001000 0x0000000000401000 0x0000000000401000
                 0x0000000000081d5d 0x0000000000081d5d  R E    0x1000
  LOAD           0x0000000000083000 0x0000000000483000 0x0000000000483000
                 0x0000000000027038 0x0000000000027038  R      0x1000
  LOAD           0x00000000000ab000 0x00000000004ac000 0x00000000004ac000
                 0x0000000000005310 0x0000000000006b40  RW     0x1000
  NOTE           0x0000000000000200 0x0000000000400200 0x0000000000400200
                 0x0000000000000044 0x0000000000000044  R      0x4
  TLS            0x00000000000ab000 0x00000000004ac000 0x00000000004ac000
                 0x0000000000000020 0x0000000000000060  R      0x8
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x10
  GNU_RELRO      0x00000000000ab000 0x00000000004ac000 0x00000000004ac000
                 0x0000000000003000 0x0000000000003000  R      0x1

strace apps/native-static-example/hello
execve("apps/native-static-example/hello", ["apps/native-static-example/hello"], 0x7ffc5ad38b90 /* 44 vars */) = 0
arch_prctl(0x3001 /* ARCH_??? */, 0x7ffedba29df0) = -1 EINVAL (Invalid argument)
brk(NULL)                               = 0x1dfc000
brk(0x1dfcd80)                          = 0x1dfcd80
arch_prctl(ARCH_SET_FS, 0x1dfc380)      = 0
uname({sysname="Linux", nodename="fedora-mbpro", ...}) = 0
readlink("/proc/self/exe", "/home/wkozaczuk/projects/osv-mas"..., 4096) = 68
brk(0x1e1dd80)                          = 0x1e1dd80
brk(0x1e1e000)                          = 0x1e1e000
mprotect(0x4ac000, 12288, PROT_READ)    = 0
fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0x1), ...}) = 0
write(1, "Hello from static C code\n", 25Hello from static C code
) = 25
exit_group(0)                           = ?
+++ exited with 0 +++
``` 

So in each case, apps make the `arch_prctl` syscall which OSv would need to support.

It is not the first time the issue of `arch_prctl` is raised - please see this conversation - https://groups.google.com/g/osv-dev/c/qLfRBRRUIHM and this one related to one of the patches attempting to add the `arch_prctl` support - https://groups.google.com/g/osv-dev/c/FPkZzUb5uB4/m/npEg9GqDAgAJ. 

Here is what @nyh wrote in the latter one:

> In an earlier review in https://groups.google.com/forum/#!msg/osv-dev/PW3bkaVCuMg/340vWUeimdMJ
and also today in another thread, I pointed out the problems with this arch_prctl thing which makes this patch either incomplete or even counter-productive:

> 1. After a thread does ARCH_SET_FS, if it get switched out and then back in, thread::switch_to() will overwrite this setting with a fixed pointer "thread->_tcb". So to support ARCH_SET_FS we need to save and restore this value on context switch (or more efficiently, save it only on ARCH_SET_FS, not on every switch out, and restore on switch in).

> 2. After a thread does ARCH_SET_FS, it cannot call any OSv code (or any library function in general). We need to modify the system-call code to restore the standard fs_base (the _tcb) when entering the system call, and restore it back to the thread's chosen address when exiting the system call.

> 3. It's even worse if after a thread does ARCH_SET_FS is calls a function directly, not through a system call. e.g., malloc(). It is possible (???) that Go is aware of this problem and restores the FS_BASE before calling C functions, but if it doesn't, we're in big problems.

My sense is that adding support of `arch_prctl` will be a bit tricky but not impossible _if we stick to certain assumptions_:
* we would only support the syscall but not `arch_prctl` glibc wrapper on purpose
* we would only support `arch_prctl` with statically linked executables both position-dependent and independent ones only; the key thing is that the SYSCALL instruction would provide us with necessary trigger points to switch the `FS` register to point to correct TLS block for a given thread 

So here is a concrete list of things to be done:
* implement the `arch_prctl`  syscall to handle `ARCH_SET_FS` and `ARCH_GET_FS` and store the  `ARCH_SET_FS` parameter in a new field for the current thread 
* modify the syscall assembly to save FS register on entry and restore FS register on exit if there is one set by `ARCH_SET_FS` for current thread
* modify the page fault handler and possibly interrupt handler (assembly?) to save FS register on entry and restore FS register on exit if there is one set by `ARCH_SET_FS` for the current thread (only if app?)
* possibly change context switch code to save and restore FS register; this may not be necessary as this would be done by the above 2

**Comment by nyh** [comment]
Your idea of supporting arch_prctl only for static executables (which can't call any OSv functions) makes sense.
However, because the issue you created is specific to golang, before we do this I would ask to consider why golang went back to static executables, and whether they really did that switch. If I remember the history corrected, golang _started_ with static executables, but then switched to dynamic executables which use glibc only for minimal things. Why did they switch back - do you know the motivation? **Did** they switch back? The page https://www.arp242.net/static-go.html suggests that maybe both compilation modes are still supported - but the dynamic version is used only if "cgo" is used. Since OSv is, for all intents and purposes, a C library, maybe it would be fine to force Go programs which are built for OSv to declare that they do, in fact, use a C library - and force the go compiler to generate a dynamic executable?

**Comment by wkozaczuk** [comment]
Thanks for the link to that article. Indeed it is still possible to generate dynamically linked Go executables and very often it is the default if the app uses networking (which non-trivial app does not use networking?). There are some changes between some executables generated by older (~1.12) and newer (~1.15) Go toolchain which affects its support on OSv which I will open a separate issue to address. The bottom line though is that golang apps built as static are not supported on OSv and one of the reasons is the missing `arch_prctl` syscall.

**Comment by wkozaczuk** [comment]
Over the weekend I have been trying to make some progress on the static ELF support. To that end, I resurrected some of the old commits from the static-elf branch originally written by Pekka and refined some of those to add more functional `brk` support and some other missing syscalls. In essence, I have been trying to get `native-example` built as a static executable to run on OSv. And I have been able to get OSv to start the app and handle a good chunk of syscalls up to the point when it calls the `arch_prtcl` with `ARCH_SET_FS`.

Obviously, as it was raised in the original Pekka's patches reviews (8 years ago) and somewhat described in one of my comments above, the `arch_prtcl` cannot set the `fs` register to the address passed to the `arch_prtcl` but instead it should just save it somewhere as part of the current app thread info (some new field). However, on exit from this syscall the `fs` should be set to that user value. And from this point on any time this app thread makes any other syscall call or any interrupt is taken or a page fault is triggered, we **somehow** need to re-set `fs` to the `_tcb` (the OSv thread descriptor) on entry and switch back `fs` to the user value (we saved in  `arch_prtcl`) on exit.

Now the problem is how do we exactly accomplish it?

**Comment by nyh** [comment]
By the way, regarding GS, https://www.kernel.org/doc/html/latest/x86/x86_64/fsgs.html says that "The GS segment has no common use and can be used freely by applications.". I guess this means we can decide not to support the applications (if there are any) that use it - and it's not used by glibc or the ABI or anything like that.
