### ISSUE TITLE
vfs: missing statx

### ISSUE THREAD

**Issue by wkozaczuk** [cloudius-systems/osv#1148]
The boost 1.75 started using `statx()` instead of `stat()`. This makes following unit tests to break:
- tst-rename.so
- tst-stat.so
- tst-vfs.so

So we need to implement it.

**Comment by nyh** [comment]
A nice short introduction to statx and why it was added in Linux 4.11 (April 2017):
https://tech.feedyourhead.at/content/using-the-new-statx-system-call
