### ISSUE TITLE
Can OSv be setup to run an embedded NAS?

### ISSUE THREAD

**Issue by lonnietc** [cloudius-systems/osv#1149]
Greetings All,

A bit new to Unikernels and am very interested in trying to see if OSv can be setup to run a small footprint NAS as a VM inside of a Hypervisor like Xen or some other?

Any ideas would be greatly appreciated.
Cheers

**Comment by wkozaczuk** [comment]
Would you mind closing the issue and asking the question on the mailing
list - https://groups.google.com/g/osv-dev.

Thanks,
Waldek
