### ISSUE TITLE
ZFS transaction replay is not supported

### ISSUE THREAD

**Issue by penberg** [cloudius-systems/osv#117]
We fixed #108 but the root cause is still there. OSv does not support replaying ZFS transactions which results in data loss for unclean images.

**Comment by wkozaczuk** [comment]
I have improved the ZFS support in some aspects recently and now it is possible to mount a ZFS image on Linux host (see https://github.com/cloudius-systems/osv/wiki/Filesystems#creating-and-manipulating-zfs-disks-on-host) and possibly fix the image using the replay like that. 

Also given we do not plan to spend more effort in improving ZFS and implementing this feature in OSv itself I propose this fix this issue.
