### ISSUE TITLE
Implement Linux version of SO_REUSEPORT

### ISSUE THREAD

**Issue by wkozaczuk** [cloudius-systems/osv#1170]
It turns out that the multi-threaded version of the Rust `tokyo` framework relies on the `SO_REUSEPORT` socket option (see https://man7.org/linux/man-pages/man7/socket.7.html). There seems to be code in the FreeBSD tree (`bsd/`) in OSv that handles `SO_REUSEPORT` but is inactive at this point (I think Linux used to NOT implement `SO_REUSEPORT`). Patching OSv like so:
```diff --git a/bsd/sys/compat/linux/linux.h b/bsd/sys/compat/linux/linux.h
index 7bc8c509..1e6116aa 100644
--- a/bsd/sys/compat/linux/linux.h
+++ b/bsd/sys/compat/linux/linux.h
@@ -89,6 +89,7 @@ typedef struct {
 #define        LINUX_SO_NO_CHECK       11
 #define        LINUX_SO_PRIORITY       12
 #define        LINUX_SO_LINGER         13
+#define        LINUX_SO_REUSEPORT      15
 #define        LINUX_SO_PEERCRED       17
 #define        LINUX_SO_RCVLOWAT       18
 #define        LINUX_SO_SNDLOWAT       19
diff --git a/bsd/sys/compat/linux/linux_socket.cc b/bsd/sys/compat/linux/linux_socket.cc
index 540b5477..cee3993b 100644
--- a/bsd/sys/compat/linux/linux_socket.cc
+++ b/bsd/sys/compat/linux/linux_socket.cc
@@ -340,6 +340,8 @@ linux_to_bsd_so_sockopt(int opt)
                return (SO_OOBINLINE);
        case LINUX_SO_LINGER:
                return (SO_LINGER);
+       case LINUX_SO_REUSEPORT:
+               return (SO_REUSEPORT);
        case LINUX_SO_RCVLOWAT:
                return (SO_RCVLOWAT);
        case LINUX_SO_SNDLOWAT:
```
is enough to make the app start but the load tests reveal that it very poorly scales with the number of the CPUs or even slow downs:

```
wrk --latency -t8 -d5s -c 200 http://<guest_ip>:<port>

Reqs/second:

Linux guest 1 cpu -  28,061.11
Linux guest 2 cpu -  68,742.13
Linux guest 4 cpu - 132,515.62

OSv guest 1 cpu -    57,886.77 //very good
OSv guest 2 cpu -    47,312.48 //BAD
OSv guest 4 cpu -    47,073.25 //Even WORSE
```

After reading this article - https://newbedev.com/how-do-so-reuseaddr-and-so-reuseport-differ - it looks like the Linux version of `SO_REUSEPORT`, based on BSD socket `SO_REUSEPORT`, differs (enhances it) in two significant ways:

1. "To prevent "port hijacking", there is one special limitation: All sockets that want to share the same address and port combination must belong to processes that share the same effective user ID! So one user cannot "steal" ports of another user. This is some special magic to somewhat compensate for the missing SO_EXCLBIND/SO_EXCLUSIVEADDRUSE flags." I do not think it applies to OSv.
2. "**Additionally the kernel performs some "special magic" for SO_REUSEPORT sockets that isn't found in other operating systems: For UDP sockets, it tries to distribute datagrams evenly, for TCP listening sockets, it tries to distribute incoming connect requests (those accepted by calling accept()) evenly across all the sockets that share the same address and port combination. Thus an application can easily open the same port in multiple child processes and then use SO_REUSEPORT to get a very inexpensive load balancing.**". This applies very much and I think these could be threads instead of processes (the Rust example does not seem to try to fork).

Now, I have found a patch to FreeBSD that adds a new option `SO_REUSEPORT_LB` (see https://www.freebsd.org/cgi/man.cgi?query=setsockopt&sektion=2&format=html) - https://reviews.freebsd.org/D11003, which adds load balancing logic to the original `SO_REUSEPORT` option in FreeBSD code.

Now, some of the comments like this one in patch:
```
/*
	 * XXX: Maybe we could let SO_REUSEPORT_LB set SO_REUSEPORT bit here
	 * so that we don't have to add to the (already messy) code below.
	 */
	int reuseport_lb = (so->so_options & SO_REUSEPORT_LB);

	/*
```

makes me think that rather than adding code to handle`SO_REUSEPORT_LB` by somehow merging this patch, we should instead change the existing implementation of `SO_REUSEPORT` in OSv (which is inactive at this point) to make it behave like `SO_REUSEPORT_LB` obviously based on this patch. That way our code will be simpler and as a result, we will implement the Linux version of `SO_REUSEPORT`.

I hope that none of this logic in the patch affects the Jacobsen channels-related changes and applying it should be pretty straightforward. @nyh, @dorlaor any ideas?

- Current OSv non-multithreaded example - https://github.com/cloudius-systems/osv-apps/blob/master/rust-pie-httpserver/src/main.rs
- Multi-threaded/worker version of the same code - https://gist.github.com/alexcrichton/7b97beda66d5e9b10321207cd69afbbc/revisions

**Comment by nyh** [comment]
Unfortunately I remember very little about the van-Jacobson channel changes, so I don't have sage advice to dispense. The only thing I can say is that the channels themselves are for the bulk of bytes flowing over an individual connection, while the `SO_REUSEPORT` (at least for TCP, I assume we're focusing on TCP) is only about _accepting_ new connections. So if you look at the patch from FreeBSD I **hope** that perhaps most of it can be directly translated to OSv, perhaps with some changes to the locking similar to what we did to the regular `accept()`.

**Comment by wkozaczuk** [comment]
I have looked more into the FreeBSD patch - [final commit](https://reviews.freebsd.org/rS334719), and it turns out that it depends on the so-called [PCB groups logic](https://www.unix.com/man-page/freebsd/9/pcbgroup/) which unfortunately was removed in [this commit](https://github.com/cloudius-systems/osv/commit/fc996a4de5bcabcfea533fbe1022589096a289f1) from OSv. More specifically the new function `in_pcblookup_lbgroup()` is called by `in_pcblookup_group()` which does not exits in `bsd/sys/netinet/in_pcb.cc` anymore.

This means we cannot merge this patch mostly as-is without bringing PCB groups back, which I doubt is a good idea (is it?). It seems like we would need to implement it from scratch and I think the main difficulty is the load balancing part. It seems we would need to track associations between sockets and threads which called `socket()` or `bind()` and properly use these associations in `accept()` to decide which socket/thread to pass it on, if this makes any sense.

Does anybody have more specific ideas?

BTW here is another good [LWN article](https://lwn.net/Articles/542629/) describing SO_REUSEPORT in Linux, its motivation, and some bugs it initially introduced. 

This one is also pretty interesting - https://blog.cloudflare.com/the-sad-state-of-linux-socket-balancing/ - it compares Nginx way with SO_REUSEPORT.

**Comment by wkozaczuk** [comment]
Actually, take it back. After more carefully analyzing the FreeBSD patch, it looks like like `in_pcblookup_lbgroup()` is called by `in_pcblookup_hash_locked()` not `in_pcblookup_group()` as I saw before. So this functionality does not seem to depend on PCB groups which means we might be able to somehow manually bring over this change to OSv tree.
