### ISSUE TITLE
Please host the source code of your website on github

### ISSUE THREAD

**Issue by hexagonrecursion** [cloudius-systems/osv#1182]
Hello. I wanted to submit a PR against your website http://osv.io/ to improve the wording on your front page, but I could not find the source code in your github organization.

**Comment by nyh** [comment]
@wkozaczuk do you remember where is the source of the OSv website?
I'm closing this issue as it's not an issue, more of a question.

**Comment by nyh** [comment]
I think I found it: https://github.com/osv-io/osv-io.github.io
