### ISSUE TITLE
Please mention that OSv is open-source on your front page

### ISSUE THREAD

**Issue by hexagonrecursion** [cloudius-systems/osv#1183]
Your [front page](http://osv.io/) currently introduces OSv as:

> OSv is the versatile modular unikernel ...

The fact that OSv is open-source is currently almost a footnote at the bottom of your 
[FAQ](http://osv.io/frequently-asked-questions).

Please change this to read:

> OSv is an `<a href="(link to the FAQ)">open-source</a>`  versatile modular unikernel ...

**Comment by nyh** [comment]
I agree. When this site was designed, the "hip" way to say that something was open-source was to have a "fork me on github" ribbon on the right. I don't think anyone does this nonsense any more. Let's have text, with words like "open source" and even BSD license - with links to github, the license, and so on.

@wkozaczuk do you know how to edit the web site? I lost track of how where is its source...

**Comment by hexagonrecursion** [comment]
> I agree. When this site was designed, the "hip" way to say that something was open-source was to have a "fork me on github" ribbon on the right. I don't think anyone does this nonsense any more.

* IMHO a prominently displayed link to your repository and issue tracker is a **good thing**.
* To me "fork me on github" is not automatically synonymous with free software - not every project on github is free software.
* Why not both?

**Comment by wkozaczuk** [comment]
Hi,

Feel free to create a pull request on
https://github.com/osv-io/osv-io.github.io. I think we can also start
tracking the issues with the website by creating issues on
https://github.com/osv-io/osv-io.github.io.

Thanks,
Waldek
PS. If you have other suggestions on improving the website (and refreshing
its look and feel), we would really appreciate it. We desperately looking
for help.
