### ISSUE TITLE
OSv Dashboard with Linux executables

### ISSUE THREAD

**Issue by sammekh** [cloudius-systems/osv#1187]
Is it possible to have OSv Dashboard with Linux executable?
I've tried building using `manifest_from_host.sh` and then building an image with, `./scripts/build make=httpserver --append-manifest`, it does build the image using the manifest files but not with the dashboard, or is it not possible to build Dashboard with Linux executable?

**Comment by nyh** [comment]
What do you mean "OSv Dashboard" - you mean the HTTP server?
@wkozaczuk can you please help him understand how to combine both an old-style module (httpserver) with manifest_from_host.sh? I'm not an expert on that, unfortunately.

**Comment by wkozaczuk** [comment]
@sammekh I think you just need to replace `make` with `image` like so:
```
./scripts/build image=httpserver --append-manifest
```
Please note you may need to explicitly pass the command line argument to the `run.py` using `-e` option.

**Comment by sammekh** [comment]
@wkozaczuk I was able to create an image this way but trying to access the httpserver only shows 
`{"message": "Not found", "code": 404}`
are there any intermediate steps I need to configure it? I've tested it on qemu with tap device and VMware ESXi, application on the image runs without any issue

**Comment by wkozaczuk** [comment]
I am not sure what is left here to fix nor is this issue reproducible so I am closing it.
