### ISSUE TITLE
place xen vcpus in arbitrary locations

### ISSUE THREAD

**Issue by glommer** [cloudius-systems/osv#120]
Xen's shared info structure only contains space for 32 vcpus. That means if we want to boot with more cpus than 32, we need to have extra space for vcpus.

The VCPUOP_register_vcpu_info hypercall can be used to that. It is not available in all hypervisors, and is very likely not available on Amazon (I haven't tested, but it is not available in the version amazon uses. They may have backported it, though...)

We should test for availability of that hypercall somehow, and use it to place extra CPUs in different locations.

**Comment by wkozaczuk** [comment]
Given we have a very small team of volunteers, is the ability to run OSv with more than 32 cpus on XEN still relevant? Shall we close it?

**Comment by nyh** [comment]
I don't see a reason to close it - it indicates a specific missing feature, and if one day somebody wants to implement it, they can get hints here. If there is any reason to suspect that Xen doesn't have this 32 cpus issue any more, we can close it.
We can also add a "Xen" label to xen-specific issues and just ignore all of them :-)

**Comment by wkozaczuk** [comment]
It has been almost 3 years since we touched on this issue. And given I have almost no Xen know-how and we have very few volunteers and zero interest from anyone in improving our Xen support I suggest we close this issue.
