### ISSUE TITLE
Can't build Java module on Fedora 36 and 37

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#1211]
Building OSv kernel itself works well in Fedora 36 and Fedora 37 (i.e., "make"). But  "make check" doesn't work because Java fails to build on these systems which now have JVM version 17.

The failure is in `modules/openjdk9_1x-from-host/Makefile`, the line:

```
    $(call very-quiet, $(SRC)/scripts/manifest_from_host.sh $(libsunec_path) > usr.manifest)
```

It seems Java 17 doesn't have a "libsunec.so".
I searched the DNF repository, and saw that JDK up to version 11 had this "libsunec.so" file but versions above it, like 17, don't.

@wkozaczuk do you remember what this library was supposed to be, why we need it, and how we can fix the openjdk-from-host package to work with JVM version 17?

CC @wkozaczuk @benipeled

**Comment by wkozaczuk** [comment]
I have tested it with `"17.0.5" 2022-10-18`:

```
PATH=/home/wkozaczuk/tools/jdk-17.0.5+8/bin:$PATH ./scripts/build image=openjdk9_1x-from-host,java-example fs=rofs

./scripts/run.py -e '/usr/bin/java -version !'
OSv v0.57.0-5-g13cc25ca
eth0: 192.168.122.15
Booted up in 177.33 ms
Cmdline: /usr/bin/java -version !
openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)
OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)

./scripts/run.py -e '/usr/bin/java -cp /java-example Hello !'
OSv v0.57.0-5-g13cc25ca
eth0: 192.168.122.15
Booted up in 170.81 ms
Cmdline: /usr/bin/java -cp /java-example Hello !
Hello, World!
```
