### ISSUE TITLE
sched_{set,get}scheduler?

### ISSUE THREAD

**Issue by lucabe72** [cloudius-systems/osv#1222]
Hi all,

I see that you have rt_tests in your osv-apps repository (pulled in the "apps" directory  by git submodule), so I decided to try running cyclictest on OSv...

After some tests, I managed to start the cyclictest application, but it fails with "/cyclictest: failed looking up symbol sched_getscheduler". Investigating a little bit, I found that your libc actually provides a broken implementation of sched_getsched() (it just does "return __syscall_ret(-ENOSYS);")... But this is not even compiled (maybe because it is broken?)

So, my question is: does OSv support sched_getscheduler / sched_setscheduler? Does it support real-time applications?

Thanks,
Luca

**Comment by wkozaczuk** [comment]
Hi,

Indeed there is no RT app support in OSv (what you found is a file from musl that is actually not compiled as part of OSv).

There is already an existing issue to add support of Posix-RT APIs to OSv  - please see #386. As a matter of fact, there is also some implementation of it in form of patches on the mailing list that have never been merged. For details please see this issue comment - https://github.com/cloudius-systems/osv/issues/386#issuecomment-557723065. I think that @nyh used to maintain some rt branch that has this code in it.

If you are very interested in it and willing to test it we could try to rebase those patches/branch.

**Comment by lucabe72** [comment]
Thanks for the clarification and for the links you provided (#386 really looks what I am looking for :), this helped a lot!

Do you have a link to the RT branch mentioned on the mailing list? (I see that all the patches linked in Issue 386 or on the mailing list are quite old)

Thanks,
Luca

**Comment by hw-claudio** [comment]
Hi Luca, indeed those patches are likely very old, 2014. If more conventient, see these branches (the last few commits):

https://github.com/hw-claudio/osv_aarch64/commits/rt_wip
https://github.com/hw-claudio/osv_aarch64/commits/rt

My use case was exactly the same (getting cyclictest to work), so with some work they should give you a starting point to get to the target.

Also consider playing with the cyclictest options, by changing the clocks used etc you might make it easier to avoid specific missing APIs, and possibly still get useful results..

Ciao,

Claudio

**Comment by nyh** [comment]
I'll try to clean up my own patches (which add the basic real-time-scheduling feature to the OSv scheduler) and create a PR from them ASAP, today.
Later we can discuss whether to finally commit those changes to the main-line OSv. I believe they were good but they did introduce changes to the most delicate part of the kernel - the scheduler - so we should be careful what we do there.

**Comment by hw-claudio** [comment]
Pleasure to "see" you always Nadav, happy to hear about the ScyllaDB many successes :-)

Ciao

**Comment by lucabe72** [comment]
Hi Claudio,

thanks for the references, I am going to look at those commits.

As a first step, I plan to use cyclictest with setitimer(), after that I'll
try clock_nanosleep().

Thanks,
Luca

**Comment by lucabe72** [comment]
Thanks, this will be very useful for testing cyclictest :)

Luca
