### ISSUE TITLE
Debian Wheezy build error: qemu-system-x86_64: -device virtio-rng-pci: Parameter 'driver' expects device type

### ISSUE THREAD

**Issue by ghost** [cloudius-systems/osv#127]
Building OSv under Debian Wheezy x64 and there is the following error:

Creating bare.img as qcow2                                                                                               

/usr/local/src/OSv/osv/scripts/mkzfs.py -o bare.img -d bare.img.d -m /usr/local/src/OSv/osv/build/release/bootfs.manifest  
qemu-system-x86_64: -device virtio-rng-pci: Parameter 'driver' expects device type  
Traceback (most recent call last):  
  File "/usr/local/src/OSv/osv/scripts/mkzfs.py", line 40, in <module>  
    upload_manifest.upload(osv, manifest, depends)  
  File "/usr/local/src/OSv/osv/scripts/upload_manifest.py", line 58, in upload  
    s.connect(("127.0.0.1", 10000));  
  File "/usr/lib/python2.7/socket.py", line 224, in meth  
    return getattr(self._sock,name)(_args)  
socket.error: [Errno 111] Connection refused  
make[1]: *_\* [bare.img] Error 1  
make[1]: **\* Deleting file `bare.img'

**Comment by wkozaczuk** [comment]
Should this one be closed?

**Comment by nyh** [comment]
Yes. virtio-rng was added to qemu at the end of 2012. Nobody should be using older qemu today.
