### ISSUE TITLE
Running on EC2

### ISSUE THREAD

**Issue by m-mueller678** [cloudius-systems/osv#1275]
What is the current state of EC2 support. The list of OSv EC2 images in the wiki is empty, and I haven't had any success so far with getting the scripts for building and importing a custom image to work. I haven't experimented much with capstan, yet, after I had some initial troubles. Is EC2 support better there? What's the currently recommended way of running OSv on EC2?

**Comment by wkozaczuk** [comment]
Hi,

There is a document from 2015 (now very outdated) describing the state of the art - https://github.com/cloudius-systems/osv/wiki/Running-OSv-on-EC2. In general, one should be (or at least was) able to run OSv on XEN-based HVM (C4, M4 older type vs new KVM-based Nitro) EC2 instances. I myself was able to run it last time successfully 4 years ago.

In general, the idea is to create OSv AMI from a local OSv QCOW2 image (which can be built using capstan) and then create EC2 instance using the AMI.

The original script `scripts/ec2-make-ami.py` (see d230e99996cdbb542d950c06f961aff22a5b69ad for some extra info) uses the AWS boto3 python library and can be used to create an AMI from locally built OSv image under `$OSV_ROOT/build/release`. I was the last one to modify it and use it probably 5-6 years ago.

 More recently (in 2019) I developed some ad-hoc scripts and cloud formation scripts to create AMIs and run OSv on EC2 instances. I have just uploaded those into this new public repo - https://github.com/wkozaczuk/osv-on-aws. 

Of course, It is also possible to run OSv on "bare-metal" EC2 instances.

I suggest that going forward we use the emailing list to discuss/seek more help - https://groups.google.com/g/osv-dev

Finally, I would love to support OSv on KVM-based Nitro instances but that requires implementing new drivers NVMe and ENA (see #924 and #1203 and #1204). But this requires some non-trivial work and help from volunteers.

**Comment by wkozaczuk** [comment]
I have created a new script to deploy OSv to an EC2 instance - see https://github.com/cloudius-systems/osv/commit/873cb55a00f15d7f42540a34a7b4b80ba53aed6b. There is also a pull request - https://github.com/cloudius-systems/osv/pull/1283 - that allows running OSv on Nitro instances.
