### ISSUE TITLE
how to solve it

### ISSUE THREAD

**Issue by cjwcj** [cloudius-systems/osv#1279]
Makefile:1996: *** Error: libstdc++.a needs to be installed.。

**Comment by nyh** [comment]
In the future, please ask questions on the mailing list (osv-dev on googlegroups.com), not the bug tracker.
Anyway, the error message is fairly self-explanatory - you need to install libstdc++.a in whatever way your Linux distribution does this. In Fedora, for example, you need to install the **libc++-static** package.

We have a script `scripts/setup.py` which you can run to install all of OSv's dependencies if your Linux distribution is supported by this script. There may be a few more things you'll need in addition to `libc++-static`.

The longer story is that usually, to run C++ software, you need to install the **shared-library** version of the standard C++ library, so you always have that installed. You only need the **static** version of this library if you intend to compile C++ software and if you intend to compile it as a static executable - which most people don't so most likely you never installed this package.
