### ISSUE TITLE
I have two problems.

### ISSUE THREAD

**Issue by tanyh18** [cloudius-systems/osv#1280]
the first image I used to compile OSv with make (I don't know if it is correct) and then ran into the error when executing it, and the second image was supposed to build an OSv image, but there was also an error
![image](https://github.com/cloudius-systems/osv/assets/75199268/b9eb788c-bd97-4142-8004-e86e26f85041)
![image](https://github.com/cloudius-systems/osv/assets/75199268/7cd81b7d-8748-43e6-b6b7-d669f0b0953d)

**Comment by wkozaczuk** [comment]
Sorry for replying so late. In the future please post a question on https://groups.google.com/g/osv-dev. 

The reason your build command fails is because there is no `hello` image. You probably meant `native-example`. So it should be:
```
scripts/build image=native-example
```
