### ISSUE TITLE
OSv doesn't build on Fedora 40

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#1320]
As usual, after upgrading to Fedora 40 (with, among other upgrades, gcc 14.1.1), OSv no longer builds.
The goal of this issue is to make it build.

**Comment by nyh** [comment]
I pushed patches fixing most of the gcc 14.1.1 build problems. One problem remains - a warning about bsd/porting/route.cc where gcc claims the code is trying to copy 56 bytes from a 54-byte object and I still need to debug this.

**Comment by wkozaczuk** [comment]
Is presence of 1323 and 1324 a reason we have not updated setup.py to support this distribution?

**Comment by nyh** [comment]
I think I just forgot
