### ISSUE TITLE
The build failed with an error stating that -std is unrecognized.

### ISSUE THREAD

**Issue by Luca-Cliver** [cloudius-systems/osv#1334]
The compiler is already g++11, but I'm not sure if it's an issue with the build command input or something else. I'm a complete beginner, so I apologize for taking up your time and resources.
![3bdb032c380c2ddfbf405cfedfd12a4](https://github.com/user-attachments/assets/8cf078ff-ac96-4127-8b3a-afab6069ac29)

**Comment by wkozaczuk** [comment]
Please pull newest master and see if the problem goes away.

**Comment by Luca-Cliver** [comment]
> Please pull the newest master and see if the problem goes away.

Thanks very much! But I met another questions when I tried to run fio. DUMMY_HANDLER for invalid_opcode aborting. May I ask how can I solve this problem?
![image](https://github.com/user-attachments/assets/4a008839-42d0-4a07-85c7-85154052ecb3)

**Comment by wkozaczuk** [comment]
What is the Linux distribution, gcc version? Can you also provide the exact build command and run with `-V` to enable verbose output?

Could you please open another issue for this one?
