### ISSUE TITLE
Do not use std::locale in kernel

### ISSUE THREAD

**Issue by wkozaczuk** [cloudius-systems/osv#1335]
After some research and experimentation, it turns out that using `std::locale` from the C++ standard library can cost upwards of half a megabyte kernel size, and in the case of OSv, it is closer to 640K.

The `std::locale` is referenced indirectly most of the time, as this straightforward example illustrates, by streams:

```c++
#include <iostream>

int main() {
   std::cout << "Hello, world!\n";
}
```

```bash
c++ -static-libstdc++ test1.cc -o /tmp/test

du -h /tmp/test 
928K	/tmp/test
``` 

A similar example that does not use streams is way smaller:
```c++
#include <vector>

int main() {
   std::vector<int> a;
   a.push_back(1);
}
```

```bash
c++ -static-libstdc++ test2.cc -o /tmp/test_no_streams

du -h /tmp/test_no_streams 
172K	/tmp/test_no_streams
```

So any time we use streams directly or indirectly in the kernel (even for printing to standard out using `cout` or `cerr`) costs us over 500K.

Most of the savings come from removing symbols and related code as illustrated by this partial output from `readelf`:
```
10092: 000000004041b410     8 FUNC    LOCAL  DEFAULT    4 std::locale::locale(std::locale::_Impl*)
 10152: 000000004046f6c0   126 FUNC    LOCAL  DEFAULT    4 std::messages<wchar_t>::do_open(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, st
d::locale const&) const
 10163: 000000004046d380   179 FUNC    LOCAL  DEFAULT    4 void std::__convert_to_v<long double>(char const*, long double&, std::_Ios_Iostate&, __locale_struct* const&)
 10243: 0000000040426330  2935 FUNC    LOCAL  DEFAULT    4 std::locale::facet::_M_cow_shim(std::locale::id const*) const
 10277: 000000004045ccb0    10 FUNC    LOCAL  DEFAULT    4 bool std::has_facet<std::num_put<wchar_t, std::ostreambuf_iterator<wchar_t, std::char_traits<wchar_t> > > >(std::
locale const&)
 10294: 0000000040428f90   558 FUNC    LOCAL  DEFAULT    4 std::istreambuf_iterator<wchar_t, std::char_traits<wchar_t> > std::__facet_shims::__money_get<wchar_t>(std::integ
ral_constant<bool, false>, std::locale::facet const*, std::istreambuf_iterator<wchar_t, std::char_traits<wchar_t> >, std::istreambuf_iterator<wchar_t, std::char_traits<wcha
r_t> >, bool, std::ios_base&, std::_Ios_Iostate&, long double*, std::__facet_shims::__any_string*)
 10318: 0000000040437610   480 FUNC    LOCAL  DEFAULT    4 void std::__facet_shims::__numpunct_fill_cache<char>(std::integral_constant<bool, true>, std::locale::facet const
*, std::__numpunct_cache<char>*)
...
  8542: 0000000040640a30    24 OBJECT  LOCAL  DEFAULT  247 (anonymous namespace)::moneypunct_wf
  8543: 0000000040640a50    24 OBJECT  LOCAL  DEFAULT  247 (anonymous namespace)::moneypunct_wt
  8544: 0000000040640420   160 OBJECT  LOCAL  DEFAULT  247 (anonymous namespace)::moneypunct_cache_wt
  8545: 0000000040640a20    16 OBJECT  LOCAL  DEFAULT  247 (anonymous namespace)::money_get_w
  8546: 0000000040640a10    16 OBJECT  LOCAL  DEFAULT  247 (anonymous namespace)::money_put_w
  8563: 000000004041d0f4   165 FUNC    LOCAL  DEFAULT    4 std::__cxx11::moneypunct<char, true>::_M_initialize_moneypunct(__locale_struct*, char const*) [clone .cold]
  8564: 000000004041d6aa   165 FUNC    LOCAL  DEFAULT    4 std::__cxx11::moneypunct<char, false>::_M_initialize_moneypunct(__locale_struct*, char const*) [clone .cold]
  8565: 000000004041dc32    16 FUNC    LOCAL  DEFAULT    4 std::__cxx11::moneypunct<char, true>::~moneypunct() [clone .cold]
  8566: 000000004041dd1a    16 FUNC    LOCAL  DEFAULT    4 std::__cxx11::moneypunct<char, true>::~moneypunct() [clone .cold]
  8567: 000000004041dd5c    16 FUNC    LOCAL  DEFAULT    4 std::__cxx11::moneypunct<char, false>::~moneypunct() [clone .cold]
  8568: 000000004041de3a    16 FUNC    LOCAL  DEFAULT    4 std::__cxx11::moneypunct<char, false>::~moneypunct() [clone .cold]
```

Another place where the streams and locale are used is the boost::format, boost::split, boost::replace, and std::regex.

The solution involves replacing the usages of `std::cout/cerr`, `std::.*stream` and `std::regex`, `boost::format`,  `boost::split`, `boost::replace` with the equivalent code that does not use locale like C `printf`, etc.

The code changes are somewhat tedious but not terrible as my branch [remove_std_locale](https://github.com/wkozaczuk/osv/tree/remove_std_locale) demonstrates.

Please note that the largest savings - estimated 640K - come when the kernel is built with most symbols hidden but the libc ones.

**Comment by nyh** [comment]
> Please note that the largest savings - estimated 640K - come when the kernel is built with most symbols hidden but the libc ones.

Hi, There is something I don't understand... The 640K of code which you are saving, is it all C++ std::local code? Because it seems some of the stuff you removed in your patches includes other stuff like
1. C++ `operator<<` type IO. 
2. Boost stuff
3. C stuff like the local support itself (various tables for isdigit(), tolower(), etc., etc).

I'm most curious about point 3 - I have a vague recollection that the C locale support, not even C++, already added a bunch of overhead in the form of various in-memory tables for tolower(), isdigit(), etc. Since OSv needs to support this, I don't think we can keep this out of the kernel, at least for the "C" locale. Did you test that after your patches and with the kernel-that-only-exports-C-symbols you can continue to run a C and/or C++ programs that use various isdigit(), tolower(), etc?
We have a test tests/tst-cxxlocale.cc for testing the C++ version of the locale, but I don't think our tests are ever run with your stripped-down C-interface-only kernel.

**Comment by wkozaczuk** [comment]
In short, we are not removing the glibc locale support needed by some apps. The locale support is still provided by musl. All the locale-related unit tests still pass with a kernel built with all but glibc symbols hidden. To support the C++ tests we add the `libstdc++.so.6` to the image as it is hidden. 

I have just pushed another commit that enhances the test makefile to support building and running test images with a kernel built with all but glibc symbols hidden.

I do not have a detailed list of all the symbols that get removed, but most of those were either `std::locale::*`,  `std::numpunct<>` , `std::moneypunct<>` and similar ones. I think many `boost::format`-related templates from `<printf.hh>` also got removed. Interestingly, even the default kernel with all symbols exposed is also ~250K smaller.

For more insight please look at this - https://github.com/ThePhD/sol2/issues/657#issuecomment-395090844
