### ISSUE TITLE
osv-cloudinit 

### ISSUE THREAD

**Issue by tzach** [cloudius-systems/osv#139]
cloudinit is a mechanism to inject information to OSv init process, similar to other OS CloudInit [3]
In particular, this is useful when running an instance on EC2[1] or open-stack [2] can be use to inject this information.

user-data can be use to:
* set public ssh keys
* set private hostname
* set CRaSH user/pass
* set env variables (#140)
* run OSv API commands 
etc

user data can be injected in run.py CLI  
* one property at a -d, --user-data,
-d s3-bucket:my-logs

* via a file of parameters 
-f, --user-data-file user.txt

User data file will ignore remark (start with #) like, and will be in pair format.
For example
```sh
# ssh login:
ssh-username: admin
ssh-password: nimda

#run OSv API command *
api: file/rm/etc/lol
api: env-var/set/logger-dest?server=http://centralize-logger.com
```

* this API does not exists yet

[1] http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AESDG-chapter-instancedata.html
[2] https://github.com/cloudbase/cloudbase-init/
[3] http://pellaeon.github.io/bsd-cloudinit/

**Comment by nyh** [comment]
We already added cloud-init module two years ago.
