### ISSUE TITLE
Build failures occurring in debian in VB in OSX

### ISSUE THREAD

**Issue by rkiddy** [cloudius-systems/osv#157]
I got a build failure. The failure suggests one can try the "--stacktrace" or "--info" or "--debug" option on the make command. The only one that actually executes is "--debug".

You know, I am new with Debian. I am not doing much more than any monkey trained to type in terminal would do. Should I wait to try this? Are you guys under the impression that this stuff should just build? Or are the tricks that are not yet fully documented?

I know helping me build is not and should not be a priority. I can wait. Just let me know when this is buildable by a less expert community. Thanx.

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':web:webjar'.
  
  > A problem occurred starting process 'command '/usr/lib/jvm/java-6-openjdk-amd64/bin/java''
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 28.897 secs
make: **\* [all] Error 1
ray@debian02:~/osv$ 
ray@debian02:~/osv$ make --stacktrace external all
make: unrecognized option '--stacktrace'
Usage: make [options] [target] ...
Options:
  -b, -m                      Ignored for compatibility.
  -B, --always-make           Unconditionally make all targets.
  -C DIRECTORY, --directory=DIRECTORY
                              Change to DIRECTORY before doing anything.
  -d                          Print lots of debugging information.
  --debug[=FLAGS]             Print various types of debugging information.
  -e, --environment-overrides
                              Environment variables override makefiles.
  -f FILE, --file=FILE, --makefile=FILE
                              Read FILE as a makefile.
  -h, --help                  Print this message and exit.
  -i, --ignore-errors         Ignore errors from commands.
  -I DIRECTORY, --include-dir=DIRECTORY
                              Search DIRECTORY for included makefiles.
  -j [N], --jobs[=N]          Allow N jobs at once; infinite jobs with no arg.
  -k, --keep-going            Keep going when some targets can't be made.
  -l [N], --load-average[=N], --max-load[=N]
                              Don't start multiple jobs unless load is below N.
  -L, --check-symlink-times   Use the latest mtime between symlinks and target.
  -n, --just-print, --dry-run, --recon
                              Don't actually run any commands; just print them.
  -o FILE, --old-file=FILE, --assume-old=FILE
                              Consider FILE to be very old and don't remake it.
  -p, --print-data-base       Print make's internal database.
  -q, --question              Run no commands; exit status says if up to date.
  -r, --no-builtin-rules      Disable the built-in implicit rules.
  -R, --no-builtin-variables  Disable the built-in variable settings.
  -s, --silent, --quiet       Don't echo commands.
  -S, --no-keep-going, --stop
                              Turns off -k.
  -t, --touch                 Touch targets instead of remaking them.
  -v, --version               Print the version number of make and exit.
  -w, --print-directory       Print the current directory.
  --no-print-directory        Turn off -w, even if it was turned on implicitly.
  -W FILE, --what-if=FILE, --new-file=FILE, --assume-new=FILE
                              Consider FILE to be infinitely new.
  --warn-undefined-variables  Warn when an undefined variable is referenced.

This program built for x86_64-pc-linux-gnu
Report bugs to bug-make@gnu.org

**Comment by wkozaczuk** [comment]
Should this be closed? This problem seems to be related to gradle build tool not even OSv build process.
