### ISSUE TITLE
Our clock, even osv::clock::uptime, is not really monotonic

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#164]
Vlad reports that even our uptime clock isn't exactly monotonic, and he saw in his tests backward jumps of 15-68 usec in tests on his laptop
After further testing, he noticed that if a thread has preemption disabled, he doesn't see the clock jumping back. So it seems the problem happens when the thread is migrated.

Is it possible that when multiple vcpus keep track of their kvmclock separately, each with its own TSC, they drift apart? Is a 68 usec drift reasonable?
(By the way, does KVM handle correctly the case of PCPU migration?)

Can we fix this problem? Perhaps keep a per-thread monotonic clock offset or epoch something so that when a thread moves between vcpus, it doesn't experience jumps (not positive and not negative) in its clock?

If this is an inherent problem, we need to document better what it means for the "monotonic" clock to be monotonic.

**Comment by nyh** [comment]
I think this issue was fixed by commit ae29aca1. 

However, issue #719 suggests the problem with two CPUs seeing slightly different time might still exist even after that commit (in that issue, a difference of 2.6 microseconds). Perhaps some systems can have such a difference and still advertise the "kvm clocksource stable" cpu feature, or we have some other bug.

**Comment by wkozaczuk** [comment]
@nyh Can this issue be closed?

**Comment by nyh** [comment]
I'll close this issue. It is full of guesses with no real evidence that a bug existed 7 years ago, let alone today.
