### ISSUE TITLE
Block IO tracing and visualization

### ISSUE THREAD

**Issue by dorlaor** [cloudius-systems/osv#189]
Ohad Rodeh have developed solution for logging every IO access (sector, times for req-response) and visualizes it. It allows customers insight into what happens
in their data center and one can identify the desired cache sizes, SSD
drive recommendations, change of workloads, etc.

I like to have such an ability in our product. The basics is to trace all
the data and should be simple. A possible next stage is to visualize it in
a similar way. Such visualization code should be portable so it will be run both
by a single node within our gui or even cli and on client side as well.

http://domino.watson.ibm.com/library/cyberdig.nsf/1e4115aea78b6e7c85256b360066f0d4/9e29fdded06e5de785257c1d005e7e9e!OpenDocument

**Comment by wkozaczuk** [comment]
I do not think we have enough manpower nor interest to work on this visualization enhancement. So I am closing it.
