### ISSUE TITLE
Allow running a statically-compiled Linux executable

### ISSUE THREAD

**Issue by ERnsTL** [cloudius-systems/osv#212]
OSv currently can only run position-independent shared objects.

This means we usually can't run a random Linux application without recompiling it (with `-fPIC -shared`), unless we're lucky and the application is already mostly a .so (like is the case in the JVM).

It is, as detailed below, desireable to allow running a single statically compiled executable, as created for example by the [Go programming language](http://golang.org/) (Golang).

The Go programming language was created with the [needs of server farms at Google](http://golang.org/doc/faq#Is_Google_using_go_internally), cloud computing, multicore processors and concurrency in mind and excels for use to write network servers and [is positioned as such](http://nathany.com/why-go/). Consequentially, its popularity has grown along with the trend in virtualization and cloud computing.

Running virtualized network servers in the cloud efficiently is also a primary use-case of OSv.

Because of this use-case overlap and bright future for the Go language in cloud computing, I created this ticket in the hope that the feature of running its statically compiled executables will be given an amount of priority and be available in one of the next releases.

This issue is possibly related to:
- [Issue #190](https://github.com/cloudius-systems/osv/issues/190)

**Comment by pyros2097** [comment]
There is also a plan for golang 1.5 to enable packaging the go library as a shared lib. I think they may also allow you to compile a go app to .so, So that it doesn't need to be an executable won't this allow golang to work out the box in osv?

**Comment by nyh** [comment]
Modern golang already supports compiling the executable as a shared library or PIE, so Go is no longer a reason to support statically-linked executables.

**Comment by wkozaczuk** [comment]
@nyh, should it be closed because of the reasons stated in last comment?

**Comment by nyh** [comment]
Well, the original request - wanting to run statically-linked executables on OSv - still stands. It's just that now that it's not needed for Go, it is even lower priority than it was. And 90% of the arguments above, about why Go uses static executables, become irrelevant. Maybe we should open a new, clean, issue and close this one.

**Comment by wkozaczuk** [comment]
Closing this one in lieu of more focused new issues:
- #1137
- #1138
- #1139
- #1140
