### ISSUE TITLE
Support Open Stack Cloud-init

### ISSUE THREAD

**Issue by tzach** [cloudius-systems/osv#246]
#139 describe a generic cloud-init support.

User data source (metadata) is provider specific.
This requirement is for supporting user data in Open Stack
http://docs.openstack.org/api/openstack-compute/2/content/List_Metadata-d1e5089.html

**Comment by wkozaczuk** [comment]
Don't we support cloud init for a while now? Doesn't this https://github.com/cloudius-systems/osv/commit/269b789a2cb2d86f872f407818d1b0b1b7ee461c address it? Shall this be closed?

**Comment by nyh** [comment]
Yes, I think we did this.
