### ISSUE TITLE
Support for a compression and decompression utility in OSv

### ISSUE THREAD

**Issue by indykish** [cloudius-systems/osv#251]
Would be nice to have ability to tar and untar something in OSv. The scenarios I can think off are when I mutate a running OSv  instance with updated tarballed code.

**Comment by wkozaczuk** [comment]
This seems to be pretty vague. I do not quite understand when this utility would run. What is the motivation? I personally think that OSv instances should be immutable except for data.

Shall we close it?

**Comment by indykish** [comment]
yes. Thanks

**Comment by nyh** [comment]
By the way, note that:
1. We already have a "cpio" (not tar) inside OSv for exactly the purpose of unpacking files into an existing OSv images.
2. It should be easy - but I am not aware of anyone reporting trying it - to run "tar" on OSv if you want an actual "tar" format packing or unpacking.
