### ISSUE TITLE
Automatically generate system call tables

### ISSUE THREAD

**Issue by glommer** [cloudius-systems/osv#260]
There are some programs that insist on calling syscall() directly, and when it happens, we need to go and implement always the same boilerplate:

A case in a switch that interprets the arguments, and passes them to a symbol. Because we always have the functionality implemented as a standard symbol, it can't get too distant from this.

This code is massive and repetitive, and will always force us to wait for a missing syscall to appear, so we can go and do monkey work for a new one. There has to be a better way, in which we just mark a particular symbol.

For example:

int write(....) {
   [...]
}
SYSCALL(__NR_write, write);

Or even:

int SYSCALL(__NR_write, write)(...) {
   [...]
}

A computer should be generating that code, not us.

**Comment by wkozaczuk** [comment]
Is this already how it is done in linux.cc using the SYSCALLx macros?

**Comment by wkozaczuk** [comment]
Is this issue obsolete?

**Comment by glommer** [comment]
I don't really look at this code for many years. It is possible that it is already there. I'll just close it for now.
