### ISSUE TITLE
Osv v.0.6 on VBox

### ISSUE THREAD

**Issue by witbnet** [cloudius-systems/osv#269]
Dear Team,

I'm Running on OSX (10.9.2) and the last release of VBox. Vboxnet0 is setting ok but when I start the VM : Gurun Meditation !

See the following line, logfile sending on demand.

0:00:03.551653 Guest Log: BIOS: Boot : bseqnr=3, bootseq=0002
00:00:03.552227 Guest Log: BIOS: Booting from Hard Disk...
00:00:03.704849 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
00:00:03.704851 !!
00:00:03.704852 !!                 Guru Meditation 1155 (VINF_EM_TRIPLE_FAULT)
00:00:03.704872 !!
00:00:03.704922 !! Skipping ring-0 registers and stack, rcErr=VINF_EM_TRIPLE_FAULT
00:00:03.704932 !!
00:00:03.704933 !! {mappings, <NULL>}
00:00:03.704934 !!
00:00:03.704946 
00:00:03.704946 The mappings are DISABLED.
00:00:03.704951 00000000ff400000 - 00000000ffbfffff  Hypervisor Memory Area
00:00:03.704962 !!
00:00:03.704963 !! {hma, <NULL>}
00:00:03.704963 !!
00:00:03.704971 Hypervisor Memory Area (HMA) Layout: Base 00000000ff400000, 0x00800000 bytes

**Comment by wkozaczuk** [comment]
I wonder https://github.com/cloudius-systems/osv/commit/13b8acbf712fd18f5b5e39da3b4faa8d40a2e951 fixes it. How can we reproduce it? If not maybe we should close it.

**Comment by witbnet** [comment]
I think this could be closes. I gave my old iMac and couldn't test it. But
I'll try again OSV on my new iMac soon.

Thanks for your follow-up

Fred

Le vendredi 17 mai 2019, WALDEMAR KOZACZUK <notifications@github.com> a
écrit :
> I wonder 13b8acb fixes it. How can we reproduce it? If not maybe we
should close it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/BHL0eHpYUsTlF3B6IsuspPbLkMWuwuU9Omua2_2wzPeLBD22ZJUShhkhh9T5Xhgx9jxPyBDgmKWws0Kx3WZ71_LfACLvDIxShQ2YooRJN3CB29XVQclcCsmtYf9ehPH1nwllhtqRjkRi6M-FWCVlskMhxiNasqA1Ef1ksJABSD613k0_vWNQt_4xbGzy6Qzr8fT6hrZg9vnckb4FK2rLaoyB2ZqViJH1KNlDSIB09w=s0-d-e1-ft#https://github.com/notifications/beacon/ABXP5AHXTJSAJMKD5LL5MT3PV27ZJA5CNFSM4AOHZEX2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVU6GJQ.gif>

**Comment by wkozaczuk** [comment]
@witbnet Definitely give it a try. On Mac it should work with VirtualBox or QEMU. There is even an accelerator for Mac now - Intel HAXM. There is also experimental support for [HyperKit](https://github.com/moby/hyperkit). 
Let me know if you need help!
