### ISSUE TITLE
LZMA support was disabled at compile time

### ISSUE THREAD

**Issue by objectkuan** [cloudius-systems/osv#272]
when i ran the "osv syms" command, i got many warnings like

warning: Cannot parse .gnu_debugdata section; LZMA support was disabled at compile time

anyone can help me fix it? thanks a lot

**Comment by Rev1408** [comment]
Hi,
How was your problem solved, i have the same error.

go gators!!

**Comment by nyh** [comment]
It seems the message is self-explanatory: The shared object you're trying to debug, or one of the shared objects it uses, has an LZMA-compressed "gnu_debugdata" section (for an explanation what this is, please see https://sourceware.org/gdb/onlinedocs/gdb/MiniDebugInfo.html) - but your gdb binary was not compiled with LZMA.
The question is, why is your gdb compiled without LZMA support? Are you using a gdb that came with your Linux distribution? Which? Or have you compiled gdb yourself?

**Comment by Rev1408** [comment]
I am compiling it myself, because the linux(alpine) i am using does not come with GDB with support to LZMA.
Do you know what flags i have to pass, to compile GDB with LZMA. I could not find any documentation on that.
I am doing this 
cd gdb-7.11
./configure 
make
make -C gdb install

**Comment by nyh** [comment]
You need to look at the gdb's README or "configure" script to see how to enable LZMA. I am guessing this is either automatic (if you have liblzma installed) or you need to give configure "--with-lzma".

You should report the lack of lzma support to your Linux distribution. I hope it's not deliberately compiled out (you can point them to https://sourceware.org/gdb/onlinedocs/gdb/MiniDebugInfo.html on why it is important). Gdb is a pretty big application, and adding liblzma  will not kill your Linux distribution's minimalism. As they say, "Everything should be made as simple as possible, but not simpler.".

Anyway, I'm closing this issue. I don't think it's an OSv issue or anything we can do in OSv to help fix it... Please reopen if you disagree.
