### ISSUE TITLE
Upload compressed version of OSv images

### ISSUE THREAD

**Issue by tzach** [cloudius-systems/osv#291]
Each OSv release, we upload many standalone OSv image to S3[1]:
1. for each virtual appliance 
2. for each HV
all the combinations
Upload and download time of images can be reduce by compression

[1] http://osv.io/downloads/

**Comment by wkozaczuk** [comment]
I think something similar can be achieved using compose-remote command of MikelAngelo capstan - https://github.com/mikelangelo-project/capstan/blob/master/Documentation/generated/CLI.md#contextualizing-unikernel-remotely. Shall we close it?

**Comment by nyh** [comment]
I think the original issue was about Amazon AMIs, which supposedly need to be complete images and cannot be compressed and also include the empty space. We have many other options now, and nobody is producing these AMIs so this is no longer an issue.
