### ISSUE TITLE
FIX / FAST Optimised Version

### ISSUE THREAD

**Issue by sirinath** [cloudius-systems/osv#294]
Is it possible to add extremely fine tuned ultra low latency FIX support for OSv for consumption in native as well as Java and .net (when you have better .net support) applications bundled with a open source FIX adopter. In this case the FIX adapter can be deeply integrated into the OS / kernel for better performance, but a separate fork available to be used outside OSv. This should support multiple versions and extensions to FIX with seamless connections to all major international brokers / venues.

Since FIX might not be used by everyone, the FIX part and optimisations could be an extra module / patch or what ever this can be called. This will bring the notion of modules / patchers and combining such modules / patchers to create a new OS image. (This should be easy and without rebuilding the OS from source or any other painful time consuming process.) This can be used for other custom images also.

**Comment by wkozaczuk** [comment]
Again given limited resources we have, shall this be closes? Is this still relevant?
