### ISSUE TITLE
No way to pass proxy parameters to OSv 

### ISSUE THREAD

**Issue by jaspal-dhillon** [cloudius-systems/osv#303]
Currently, there is no way to pass the proxy parameters ( proxy,port,username,password) via the command line. Due to this, TCPDownloadFile test simply gives a java.net.ConnectionException.

**Comment by wkozaczuk** [comment]
Again given limited resources we have, shall this be closes? Is this still relevant? Which application is supposed to receive those proxy parameters?

**Comment by nyh** [comment]
In commit 6462f294985064bdc1f8d492795c0ffbe967cd56, we added the "--env" command line option to add anything to the command line. So I think this closes this issue.
