### ISSUE TITLE
Fail to run iperf3 on osv

### ISSUE THREAD

**Issue by asias** [cloudius-systems/osv#305]
We are missing some symbols.

[asias@hjpc osv]$ scripts/check-libcfunc-avail.sh release apps/iperf3/libiperf.so.0.0.0
__h_errno_location not found
getpeername not found
system not found
sched_setaffinity not found
sendfile not found
hstrerror not found
[asias@hjpc osv]$ scripts/check-libcfunc-avail.sh release apps/iperf3/iperf3.so
daemon not found

The iperf3 module for osv is here: https://github.com/asias/osv-apps/tree/iperf3

**Comment by wkozaczuk** [comment]
We can definitely run iperf3 now on OSv at least as of https://github.com/cloudius-systems/osv-apps/commit/1807b4dbf14df922269d08f20153d7fc4ca4dd75. Closing it.
