### ISSUE TITLE
Clarify requirement for compiling OSv on Ubuntu

### ISSUE THREAD

**Issue by elazarl** [cloudius-systems/osv#311]
It's hard for me to understand under what conditions (if at all) it is possible to build OSV on Ubuntu. It sounds as if Ubuntu is supported:

> **Ubuntu users**: you may use Oracle JDK if you don't want to pull too many dependencies for `openjdk-7-jdk`

but for instance, the previous Ubuntu LTS[0], the `qemu-system-x86` package doesn't exist.

It'll be nice to have Ubuntu requirement spelled out, like they are for Debian.

[0]  which is still widespread, as 14.04 was released a few month ago

**Comment by wkozaczuk** [comment]
Is it still a valid issue after 4 years. The latest Ubuntu is 18.04

**Comment by nyh** [comment]
Yes, this issue is outdated. We do support Ubuntu in scripts/setup.py - but not the latest version (it just requires Ubuntu-using volunteers to update this script). The README.md mention both Ubuntu and Fedora, but doesn't mention which releases are supported.
