### ISSUE TITLE
New performance regression in ctxsw micro-benchmark

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#312]
After the commit dd33a91daa6f35a590f2df70b94c2a2bc975b815 last week, the "colocated" context-switch measurement by ctxsw.so was down to 303ns (on my test machine, "Loki").

Unfortunately, when I measure ctxsw.so now on the current master, this measurement has grown to 440ns.

I'm now trying to bisect this regression, with confusing results - it seems that while performance is consistently bad on the master, and consistently good (with barely a nanosecond of variation) a week ago, in the middle I get some mix between the two. I'll continue to investigate.

**Comment by wkozaczuk** [comment]
@nyh your latest comment (from 7 years ago) suggested there was no regression after all? Shall we close it or maybe open a new one about the excessive number of exits to hypervisor?
BTW I wonder which APIC accesses would cause the exists? According to this - https://software.intel.com/content/www/us/en/develop/blogs/apic-virtualization-performance-testing-and-iozone.html - virtual APIC provides exit-less functionality.

**Comment by nyh** [comment]
Let's close it. If one day we find an example of excessive exists, we can debug it then.
