### ISSUE TITLE
Cassandra mem-config

### ISSUE THREAD

**Issue by elcallio** [cloudius-systems/osv#338]
Need to investigate & decide upon strategy/optimal settings for application. If delivered as "appliance", hard-coded memory settings is a no-no. Normal cassandra startup will guestimate ms/mx based on system info, but since OSv does not run scripts that is not really an option. (This obviously translates to other apps with the same problem). 
If no mem flags + balloon gives good enough performance that seems the simplest way to deal with it.

**Comment by wkozaczuk** [comment]
I do not think many people care about better supporting Cassandra on OSv. Shall we close it?

**Comment by tzach** [comment]
@wkozaczuk you can close
This is pre Scylla issue

**Comment by nyh** [comment]
@tzach - the entire OSv was pre-Scylla ;-)
But this is a vague request to think how to run Cassandra on OSv. I think it applies to many applications, not just Cassandra, and the idea is that when someone thinks of a way to run an application conveniently and efficiently on OSv, he can put it in apps.git. It's not an OSv kernel issue. So it was a good decision to close.
