### ISSUE TITLE
run_elf: wait for native program threads completion after main() execution

### ISSUE THREAD

**Issue by daynix** [cloudius-systems/osv#343]
Some threads of native program may live longer then main(). We have to wait for completion of those threads before leaving run_elf() and unloading the program module.

**Comment by wkozaczuk** [comment]
I think that this is a default behavior and that is why we need this code in java.cc - https://github.com/cloudius-systems/osv/blob/b3aef656ddd79df7299c385d7ad9e28e813727ea/modules/java-base/java.cc#L278-L280. Shall we close it?

**Comment by nyh** [comment]
Yes. For a long time now, this is the default behavior. Closing.
