### ISSUE TITLE
Expose OSv API to Java application

### ISSUE THREAD

**Issue by tzach** [cloudius-systems/osv#346]
Java application might want to use existing API like shutdown, getenv, etc.
Although there is REST API for that, it will be more friendly and more efficient to expose the API as Java functions.
Something on the line of

```
API.os.shutdown();
```

**Comment by wkozaczuk** [comment]
Given limited resources we have I suggest we close it. Plus in my opinion it seems way to specific to Java.

**Comment by nyh** [comment]
I agree. This was a direction we were enthusiastic about in the beginning - when 1. we were focusing on Java, and 2. we were less focused than today on running unmodified applications. It is highly unlikely at this stage that people will write special Java applications to run on OSv only. If there's ever such demand, we can do it then.
