### ISSUE TITLE
"environ" global variable not exported to libosv.so as such but rather as "__environ"

### ISSUE THREAD

**Issue by lgoldstein** [cloudius-systems/osv#365]
$ nm -CD loader.elf  | grep environ
0000000000ce6aa0 V environ
0000000000ce6aa0 V _environ
0000000000ce6aa0 D __environ
0000000000ce6aa0 V ___environ

$ nm -CD libosv.so | grep environ
0000000000ce6aa0 A __environ

I believe that environ(7) states that the variable name should be "environ" (this is also how it should be accessed via JNA...).

Note: this is not a major issue for now since I can use "__environ", but it would help to have the standard name - especially as it its mapped to the same address as "environ"

**Comment by wkozaczuk** [comment]
This issue got closed and then reopened. Is it still relevant? Can we reproduce it? Otherwise I suggest we close it.
