### ISSUE TITLE
No entropy source on GCE in zones: us-central1-a, us-central1-b and europe-west1-*

### ISSUE THREAD

**Issue by tgrabiec** [cloudius-systems/osv#376]
Looks like GCE doesn't provide `virtio-rng`, so the only entropy source right now is `rdrand`, which is available on `Ivy bridge` CPUs. This CPU is available in zones:
- asia-east1-a
- asia-east1-b
- us-central1-f

Source: https://developers.google.com/compute/docs/zones

**Comment by zenczykowski** [comment]
You can now get virtio-rng on GCE:
https://bugzilla.redhat.com/show_bug.cgi?id=1572944#c79
