### ISSUE TITLE
JSON friendly value for processor features in the RESTful API

### ISSUE THREAD

**Issue by glommer** [cloudius-systems/osv#385]
Current result of /hardware/processor is a string of present features. It is more json-friendly to have a key: value list where value is on / off.

**Comment by wkozaczuk** [comment]
In my opinion, this one falls into the category of "very nice to have". Also, it would not be very difficult on the client-side to implement parsing of this string as-is. So I am closing it unless @glommer insists we keep this issue alive ;-)
