### ISSUE TITLE
Git submodules mis-aligned on 'master' branch

### ISSUE THREAD

**Issue by lgoldstein** [cloudius-systems/osv#392]
The *master* GIT branch is not following the *master*(s) of its sub-modules - specifically *apps* and *httpserver/swagger-ui*. As can be seen from the *git submodule status* command below (issued while being on the osv *master*), these sub-modules are "frozen" on some commit instead of following their respective *master*(s).

'''shell
$ git submodule status
 8487f408c800ea43bb353561e54e44b39269ee8d apps (**8487f40**) 
 ec73300374d85693a2c2ce79269fbba1c447629f external/aarch64/gcc.bin (heads/master)
 fb96c84bbe4e30136debb7ffea74ba6a3bb568d7 external/aarch64/misc.bin (heads/master)
 443f2cca797910915274a0a3a42ea8a67752c063 external/aarch64/openjdk.bin (heads/master)
 3e45e0f2383cabdc00275c00a12ea8797f285c30 external/x64/acpica (heads/master)
 588fda357d3234e237ef1f81aa6594c10d168783 external/x64/gcc.bin (heads/master)
 c1278866ed57e51576a78b71c6326115004a9676 external/x64/glibc-testsuite (heads/master)
 ef094e3a925c6097f122399d40914d6b9bcff09f external/x64/glibc.bin (heads/master)
 b84811d4b7e9986b238e8241828b1333d92aa9a6 external/x64/misc.bin (heads/master)
 019ea95e844cc9e51c149a519391e2a99915ad39 external/x64/openjdk.bin (heads/master)
 a9a859242e190b8bd4884c44a63259584ca1096f mgmt (a9a8592)
 5f3d36dbd2a98b59750d13ecc12b7e843dc809aa modules/httpserver/swagger-ui (**v2.0.3-15-g5f3d36d**)
'''

Furthermore, if one tries to run *git submodule update*, the *apps* submodule becomes **detached** (very bad...). The solution is simple:

'''shell
cd apps (or httpserver/swagger-ui)
git checkout master
git pull -v --progress origin master:master
cd ..            (back to osv root)
git pull -v --progress origin master:master
git status    (you should see the updated submodule as modified)
git add apps (or httpserver/swagger-ui)
git commit -m "Fixed sub-modules tracking"
git push -v --progress origin master:master
'''

**Note:** whenever dealing with git sub-modules, one has to *add*, *commit* and *push* them at top-level *master* branch as well or they fall behind...

**Comment by nyh** [comment]
This is not an issue, but rather a discussion on the pros and cons of git submodules. We can reopen if someone has a specific idea on what needs to be fixed.
