### ISSUE TITLE
API: Use the swagger validator - to verify our swagger file is compatible with the spec

### ISSUE THREAD

**Issue by slivne** [cloudius-systems/osv#404]
Swagger code-gen project (https://github.com/wordnik/swagger-codegen) includes a tool called validator that checks the swagger file against the spec - making sure that our swagger file will be "eatable" by swagger compatible clients / it will be possible to generate clients

.
.

Validating your swagger spec
You can use the validation tool to see that your server is creating a proper spec file. If you want to learn more about the spec file and format, please see swagger-core. This tool will read the server and generate a report of any violations of the spec. If there are violations, the client codegen and ui may not work correctly.

To validate an api and write output to ./swagger-errors.html:

./bin/validate.sh http://petstore.swagger.wordnik.com/api/api-docs "specia-key" ./swagger-errors.html

.
.

**Comment by wkozaczuk** [comment]
I am not sure what this issue exactly entails. Is it about automating the build process of `httpserver-api` module to include a step to use the validator tool? 

Also, we have Swagger `*json` in both `httpserver-api` and `httpserver-monitoring-api` and use `json2code.py` to generate C++ model code. So the json files must be valid.  

Either way, I do not think it is relevant enough nor desired by anyone to keep it open. So I am closing it.
