### ISSUE TITLE
HTTP server port should be configurable, not 8000 by default  

### ISSUE THREAD

**Issue by tzach** [cloudius-systems/osv#406]
Ports in the 8000 - 9000 range are commonly used by application, and may override the OSv HTTP server port.
A better choice will be port 5498, which is almost never used.

In the case user do want to change port, the port can be update in cloud-init.

**Comment by wkozaczuk** [comment]
I believe this can be closed as the httpserver does allow specifying host and port it can bind to. Please see https://github.com/cloudius-systems/osv/blob/master/modules/httpserver-api/global_server.cc#L82-L87. I have also tested by setting port setting in httpserver.conf and indeed it made it listen on different port.

**Comment by nyh** [comment]
I think Tzach suggested changing the default, but I agree, there is no compelling reason to change this default now.
Tzach is right that 5498 is officially unassigned by IANA. 8000 is assigned to some protocol nobody heard about (irdmi), by the way, so its not like any other application is expected to need it.
