### ISSUE TITLE
NET: KASSERT(tp->get_state() > TCPS_LISTEN) in tcp_do_segment()

### ISSUE THREAD

**Issue by vladzcloudius** [cloudius-systems/osv#420]
master hash: dbdd63a94df244b7d62f9c40db9c876df609f6bb
After running a netperf test when it was going to finish I've got the assert above.
gdb showed that 
- tp->state() was 0 (CLOSED) at that time.
- thflags was 16 (ACK).

Looks like it's RCU related issue.

**Comment by wkozaczuk** [comment]
Duplicate of #454 so closing it.
