### ISSUE TITLE
httpserver: server is dead when loaded on KVM

### ISSUE THREAD

**Issue by vladzcloudius** [cloudius-systems/osv#456]
master HEAD: 36f78327bbde3815965420ac3b79feaec43b3310

Build command: make

Loading on local KVM goes as follows:

[xxx@yyy-zzz osv]$ sudo scripts/run.py -nv -c1 -m4G -V
OSv v0.11-246-g36f7832
1 CPUs detected
bsd: initializing - done
VFS: mounting ramfs at /
VFS: mounting devfs at /dev
RAM disk at 0x0xffff8000024cd040 (4096K bytes)
net: initializing - done
vga: Add VGA device instance
eth0: ethernet address: 52:54:00:12:34:56
virtio-blk: Add blk device instances 0 as vblk0, devsize=10842275840
random: virtio-rng registered as a source.
random: intel drng, rdrand registered as a source.
random: <Software, Yarrow> initialized
VFS: unmounting /dev
VFS: mounting zfs at /zfs
zfs: mounting osv/zfs from device /dev/vblk0.1
VFS: mounting devfs at /dev
VFS: mounting procfs at /proc
random: device unblocked.
program zpool.so returned 1
BSD shrinker: event handler list found: 0xffffa00001692180
        BSD shrinker found: 1
BSD shrinker: unlocked, running
[I/28 dhcp]: Waiting for IP...
[I/198 dhcp]: Server acknowledged IP for interface eth0
eth0: 192.168.122.89
[I/198 dhcp]: Configuring eth0: ip 192.168.122.89 subnet mask 255.255.255.0 gateway 192.168.122.1 MTU 1500
Running from /init/00-cmdline: /usr/mgmt/cloud-init.so;

could not load libgssapi_krb5.so.2
could not load libkrb5.so.3
could not load libk5crypto.so.3
Probing EC2 ...
Uncaught signal 2 ("Interrupt"). Powering off.
/etc/qemu-ifdown: could not launch network script
[vladz@vladz-laptop osv]$ less README.md
[vladz@vladz-laptop osv]$ sudo scripts/run.py -nv -c1 -m4G -V
OSv v0.11-246-g36f7832
1 CPUs detected
bsd: initializing - done
VFS: mounting ramfs at /
VFS: mounting devfs at /dev
RAM disk at 0x0xffff8000024cd040 (4096K bytes)
net: initializing - done
vga: Add VGA device instance
eth0: ethernet address: 52:54:00:12:34:56
virtio-blk: Add blk device instances 0 as vblk0, devsize=10842275840
random: virtio-rng registered as a source.
random: intel drng, rdrand registered as a source.
random: <Software, Yarrow> initialized
VFS: unmounting /dev
VFS: mounting zfs at /zfs
zfs: mounting osv/zfs from device /dev/vblk0.1
VFS: mounting devfs at /dev
VFS: mounting procfs at /proc
random: device unblocked.
program zpool.so returned 1
BSD shrinker: event handler list found: 0xffffa00001692180
[I/28 dhcp]: Waiting for IP...
[I/198 dhcp]: Server acknowledged IP for interface eth0
eth0: 192.168.122.89
[I/198 dhcp]: Configuring eth0: ip 192.168.122.89 subnet mask 255.255.255.0 gateway 192.168.122.1 MTU 1500
Running from /init/00-cmdline: /usr/mgmt/cloud-init.so;

could not load libgssapi_krb5.so.2
could not load libkrb5.so.3
could not load libk5crypto.so.3
Probing EC2 ...
EC2: read_until: Connection reset by peer
Probing GCE ...
GCE: read_until: Connection reset by peer
cloud-init failed: Failed getting cloud-init information No data source matched
program /usr/mgmt/cloud-init.so returned 1

[/]%

The messages blow 
could not load libgssapi_krb5.so.2
could not load libkrb5.so.3
could not load libk5crypto.so.3

Come from libhttpserver.so and as a result the httpserver doesn't respond as expected (on port 8000).

The issue is not present in master 8a0c751c44857216ceff82569041972a3d858c9d.

**Comment by nyh** [comment]
I believe this issue was handled long, long ago. modules/cloud-init/cloud-init.cc now checks for hypervisor and firmware vendor to try to avoid pausing when not on EC2 or AWS.
