### ISSUE TITLE
Integration with AWS CloudWatch Custom Metrics

### ISSUE THREAD

**Issue by tzach** [cloudius-systems/osv#459]
OSv REST API provides useful information such as CPU, disk, fs and trace points.
It will be useful to make this information available to 3rd party tools like AWS CloudWatch[1]
CloudWatch works in push mode, where an agent initiate a REST API request toward a server.
Each request can hold one data point, a series of data point or statistical information.

I propose to a new OSv module, agent, which will periodically and efficiently probe a sub set of API and push them to CloudWatch.
Subset should be configurable, and later accessible with REST API.

Example for pushing information to CloudWatch via the aws CLI

```
aws cloudwatch put-metric-data --namespace "Usage Metrics" --metric-data file://metric.json
```

where metric.json is

```
[
  {
    "MetricName": "memory/free",
    "Timestamp": "Wednesday, Aug 17, 2014 9:28:20 PM",
    "Value": 2199,
    "Unit": "Bytes"
  },
  {
    "MetricName": "trace-point-malloc",
    "Timestamp": "Wednesday, Aug 17, 2014 9:28:21 PM",
    "Value": 2199,
    "Unit": "Count/Second"
  }
]
```

In the future, similar agents will push similar information in different format through other channels, like AMQP[2], allowing integration with tools like Riemann.

[1] http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/WhatIsCloudWatch.html
[2] #141

**Comment by wkozaczuk** [comment]
Given how few resources we have I suggest we close this issue.
