### ISSUE TITLE
Integration with GCE monitoring

### ISSUE THREAD

**Issue by tzach** [cloudius-systems/osv#487]
Similar to #459 for EC2, GCE have a similar monitoring system[1]. 
GCE motoring allow writing and reading different metrics, some available out of the box, some custom.
compute.googleapis.com/instance/cpu/usage_time is an example to the first.

For the second, stackdriver (acquired by Google), provide an REST API
To use the API, an app need a API key  [2] 
For OSv, the key will need to be provided via cloud-init, and/or REST API

Pushing custom metric is done over REST API[3], much like EC2 CloudWatch

```
data_point = {
   ‘name’: ‘my_custom_metric’,
   ‘value’: 32,
﻿   ﻿﻿﻿#Note: Stackdriver rejects when the collected_at value is older than 2 hours.
   ‘collected_at’: 1325394000
   #Note: Include an instance value if your metric is tied to an instance.
   #'instance': 'i-123a567b',
}
```

Like CloudWatch, the API support sending aggregated statistics, not just raw data.

[1] https://developers.google.com/cloud-monitoring/what-is-cloud-monitoring
[2] http://www.stackdriver.com/custom-metrics-made-easy/
[3] http://support.stackdriver.com/customer/portal/articles/1491766-sending-custom-application-metrics-to-the-stackdriver-system

**Comment by wkozaczuk** [comment]
Given how few resources we have I suggest we close this issue.

**Comment by nyh** [comment]
I'm closing because if we ever want to do something like this, we'll likely choose what is common today, not what was common 5 years ago.
