### ISSUE TITLE
malloc methodologies (jemalloc)

### ISSUE THREAD

**Issue by Gadreel** [cloudius-systems/osv#496]
I'm sure that you have already put a lot of thought into memory allocation techniques so take this worth a grain of salt.  It looks like jemalloc is extremely good at providing even results at scale, without the occasional hiccup:

Scalable memory allocation using jemalloc - https://www.facebook.com/notes/facebook-engineering/scalable-memory-allocation-using-jemalloc/480222803919

A Scalable Concurrent malloc(3) Implementation for FreeBSD - http://people.freebsd.org/~jasone/jemalloc/bsdcan2006/jemalloc.pdf

Now the reason I'm interested at all is that [Netty](https://github.com/netty/netty), the high end Java networking library, has an Memory Pool that is an independent component from the networking library.  Their memory pool is based on the jemalloc design.  What is nice about their design is that the memory pool implementation can be switched out - so an OSv specific pool could replace the default one and that pool implementation could coordinate directly with the underlying memory system for optimal memory page layout.

Even if you aren't using jemalloc, the fact that Netty is widely used and very successful suggests the possibility for an OSv enhanced memory pool implementation in Netty.

**Comment by wkozaczuk** [comment]
Again more of a discussion rather than issue/bug. Can we close it?
