### ISSUE TITLE
Connecting to virtualbox osv instance via ssh

### ISSUE THREAD

**Issue by rampage644** [cloudius-systems/osv#503]
Hi,

I've been playing with `OSv` for a while and faced with a strange behavior when trying to connect to virtualbox-powered osv image.

When i try connecting via _ssh_ to osv connection stalls. But! Sometimes it goes smooth. I managed to get connected 3 times (out of hundreds of attempts). Ping is ok. 

I can't reproduce it with `VMWare Player` or `qemu-kvm` based images. So, it should be definitely relative to `VirtualBox`.

What data should i provide for ease of debugging? `ssh -vvv` output or anything else. I'm using v0.12-stable images (downloaded).

**Comment by wkozaczuk** [comment]
Is this related to the crash app that alllowed connecting to OSv using ssh? As I understand this app is deprecated in lieu of the REST api. Should this issue be closed?

**Comment by nyh** [comment]
I'm closing this issue. We've fixed many network-related, virtualbox-related, and other bugs over the years, and it's impossible to tell if one of them was responsible for the hang the original poster reported. The ssh server is gone anyway, so we can no longer test with it.
