### ISSUE TITLE
major() and friends macros are not Linux compatible

### ISSUE THREAD

**Issue by pkit** [cloudius-systems/osv#506]
When compiling a code that uses major(), minor() and makedev() in Linux, these functions will resolve to gnu_dev_major(), gnu_dev_minor() and gnu_dev_makedev() respectively. These symbols are not present in musl and hence the code will fail to run on OSv. Musl uses macros to define major() and friends, so code probably must be moved to normal functions. 
On the other hand, looks like current musl macros are quite old, see the new ones here: https://github.com/esmil/musl/blob/master/include/sys/sysmacros.h

**Comment by wkozaczuk** [comment]
@nyh can this issue be resolved by adding aliases (`libc/aliases.ld`) for `major(), minor() and makedev()` to point to the `gnu_*` equivalent ones.

Readelf seems to list the following symbols:
```
readelf -sW build/release/kernel-stripped.elf | grep -P 'minor|major|makedev'
  1668: 0000000040205233     9 FUNC    GLOBAL DEFAULT    4 zvol_create_minors
  1939: 000000004046c000    64 FUNC    GLOBAL DEFAULT    4 gnu_dev_makedev
  9730: 0000000040341410     1 FUNC    GLOBAL DEFAULT    4 zvol_rename_minors
 11417: 0000000040341330     1 FUNC    GLOBAL DEFAULT    4 zvol_remove_minors
 12759: 000000004046bfe0    18 FUNC    GLOBAL DEFAULT    4 gnu_dev_minor
 14225: 0000000040329ad0   116 FUNC    GLOBAL DEFAULT    4 zfsdev_minor_alloc
 16258: 000000004046bfc0    25 FUNC    GLOBAL DEFAULT    4 gnu_dev_major
``` 

All these `gnu_*` functions were adding with this commit f1bad6f04edd346f81fe7c7c76f13babd26241cd and are in `libc/linux/makedev.c`.

**Comment by nyh** [comment]
Closing - this issue was indeed fixed a week after this issue by the commit you identified. The problem was not missing major() et al. - those aren't needed because major() is just a macro:
```
/usr/include/sys/sysmacros.h:#define major(dev) gnu_dev_major (dev)
```
We needed to export the gnu_dev_major at al. functions - and we do.
