### ISSUE TITLE
Loops during boot running either on qemu or kvm

### ISSUE THREAD

**Issue by jkozak** [cloudius-systems/osv#52]
Built per the instructions and started using scripts/run.py with no arguments.  OS is debian wheezy, amd64. zfs-fuse is running

Get this repeated on the terminal:

 acpi 0 apic 0
 acpi 1 apic 1
 acpi 2 apic 2
 acpi 3 apic 3 
 APIC base fee00000

connecting to the VNC console shows a "booting from hard disk" loop.

**Comment by nyh** [comment]
I'm closing this issue. The reported behaviour is the generic "triple fault" reboot, which happens in any case where the code faults before properly setting up the IDT. There is no way to know what caused this specific problem without more information. The best way to debug such a problem is to use "run.py -H" - the -H option, among other things, disables the reboot in this case and allows attaching gdb to figure out what caused it.
