### ISSUE TITLE
Golang support

### ISSUE THREAD

**Issue by 6D65** [cloudius-systems/osv#522]
Hi, 

You probably have been asked this a billion times already, but I can't seem to find the info whether you support Go. I watched some not too new presentations, and there's mentioned that JVM based languages are fully supported, and C to some extent(except exec, fork).

I like the idea of a low overhead cloud OS but carying over 100MB of runtime for the JVM languages is a thing that i would avoid, especially when the OS itself is around 20MB.

Btw, i'm aware that Go is not slim either, but at least it's getting better.

Thanks

**Comment by wkozaczuk** [comment]
WIth the latest commit https://github.com/cloudius-systems/osv/commit/d76e530402a18f60383206a158089a7858b88c12 we seem to have pretty solid support of Golang apps on OSv. Two applications - golang-example and golang-httpserver function well (especially the latter one even under heavy load) when compiled with almost latest Golang 1.10.1. I think we can now close this issue.

**Comment by nyh** [comment]
I think you are right! Thank you for all your hard work on this. Nice to finally close this issue after almost 4 years.
And thanks also to @benoit-canet @HawxChen @penberg and whomever else I forgot for your code that went into Go support and for the moral support :-)
