### ISSUE TITLE
Fault when exiting the internal cli

### ISSUE THREAD

**Issue by dorlaor** [cloudius-systems/osv#524]
Version (HEAD): v0.13-76-g1033d7e
The image is image=Cassandra,cli

To trigger the issue (consistent) run 'exit' using the internal cli:

/# exit
Goodbye
exception nested too deeply
[backtrace]
page fault outside a

**Comment by wkozaczuk** [comment]
Wow. We can still build the cassandra image. 

Anyway, I did manage to build `cassandra,cli`, waited until cassandra finishes starting, and typed `exit`. OSv would terminate gracefully, no page fault. I tried 3 times. 

Given I cannot reproduce this issue following the steps above I am closing it.
