### ISSUE TITLE
Compile Failure When Set "conf-tracing=1"

### ISSUE THREAD

**Issue by morgan-139117** [cloudius-systems/osv#530]
Compile Failed when I set conf-tracing=1 in "base.mk" using Fedora 20 64bit with
command: make mode=debug (after make clean mode=debug).

Error log:

  CC musl/src/crypt/crypt_r.o
  CC musl/src/crypt/crypt_sha256.o
  CC musl/src/crypt/crypt_sha512.o
  CXX dummy-shlib.o
  LD dummy-shlib.so
  LD loader.elf
arch/x64/string.o: In function `_mm_loadu_si128':
/root/osv2/arch/x64/sse.hh:37: undefined reference to`_mm_loadu_si128(long long __vector const_)'
arch/x64/string.o: In function `_mm_loadu_si128':
/usr/lib/gcc/x86_64-redhat-linux/4.8.3/include/emmintrin.h:684: undefined reference to`_mm_loadu_si128(long long __vector const_)'
arch/x64/string.o: In function `_mm_storeu_si128':
/root/osv2/arch/x64/sse.hh:41: undefined reference to`_mm_storeu_si128(long long __vector_, long long __vector)'
...........................// Similar errors repeated 10K times here, says undefined reference to 'xxxx'.
...........................// 
/usr/lib/gcc/x86_64-redhat-linux/4.8.3/include/emmintrin.h:696: undefined reference to `_mm_store_si128(long long __vector_, long long __vector)'
make[1]: **\* [loader.elf] Error 1
make[1]: Leaving directory `/root/osv2/build/debug.x64'
make: **\* [all] Error 2

I am not sure if I missed something. Please help!

Thanks.

**Comment by wkozaczuk** [comment]
Is this something related to very old distribution of Fedora/GCC? If so can we close it?

**Comment by nyh** [comment]
This issue should have been closed long ago - the compilation problems were solved, and the kernel size issue now gives a clearer message on how to fix it in the Makefile.
