### ISSUE TITLE
aarch64 build fails

### ISSUE THREAD

**Issue by ikitayama** [cloudius-systems/osv#538]
I'm on aarch64-next and trying to build it on Ubuntu 14.10.

Downloaded: http://repo.maven.apache.org/maven2/ch/qos/logback/logback-classic/1.0.13/logback-classic-1.0.13.jar (259 KB at 207.9 KB/sec)
Downloaded: http://repo.maven.apache.org/maven2/ch/qos/logback/logback-core/1.0.13/logback-core-1.0.13.jar (410 KB at 298.8 KB/sec)
Downloaded: http://repo.maven.apache.org/maven2/org/bouncycastle/bcprov-jdk16/1.46/bcprov-jdk16-1.46.jar (1833 KB at 734.2 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.553s
[INFO] Finished at: Thu Oct 30 16:10:49 JST 2014
[INFO] Final Memory: 7M/240M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project crash: Could not resolve dependencies for project com.cloudius.cli:crash:jar:1.0.0: The following artifacts could not be resolved: org.crashub:crash.cli:jar:1.3.0-beta16-osv1, org.crashub:crash.shell:jar:1.3.0-beta16-osv1, org.crashub:crash.connectors.ssh:jar:1.3.0-beta16-osv1: Could not find artifact org.crashub:crash.cli:jar:1.3.0-beta16-osv1 in cloudius (http://cloudius.artifactoryonline.com/cloudius/repo) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
Makefile:6: recipe for target 'crash' failed
make[2]: *** [crash] Error 1
make[2]: Leaving directory '/home/itaru/projects/osv_aarch64/mgmt'
Traceback (most recent call last):
  File "/home/itaru/projects/osv_aarch64/scripts/module.py", line 239, in <module>
    args.func(args)
  File "/home/itaru/projects/osv_aarch64/scripts/module.py", line 196, in build
    make_modules(modules, args)
  File "/home/itaru/projects/osv_aarch64/scripts/module.py", line 100, in make_modules
    raise Exception('make failed for ' + module.name)
Exception: make failed for mgmt
/home/itaru/projects/osv_aarch64/build.mk:1055: recipe for target 'process-modules' failed
make[1]: *** [process-modules] Error 1
make[1]: Leaving directory '/home/itaru/projects/osv_aarch64/build/release.x64'
Makefile:25: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by nyh** [comment]
This issue is no longer relevant - OSv's makefile is very different now, and doesn't build httpserver (which is part of the modules, that probably indeed don't work on aarch64).
