### ISSUE TITLE
thread dashboard may freeze when trying to interrupt it

### ISSUE THREAD

**Issue by tgrabiec** [cloudius-systems/osv#54]
There is a bug in crash 1.2.7 which causes that interrupting a command like 'thread top' may fail with ~9% probability and all subsequent attempts to interrupt it will be silently ignored.

As it turns out this is fixed in crash upstream master. It is a one-liner which can be easily applied to our fork once it's ready.

See crashub/crash@5cfc4606fe0dbc4d9a65448acf65b1f6fe76fce4

**Comment by wkozaczuk** [comment]
I do not think is it is relevant anymore so I am proposing we close it.

**Comment by nyh** [comment]
We haven't used the "crash" shell in years. Closing.
