### ISSUE TITLE
Need to implement "pthread_setcancell_state"

### ISSUE THREAD

**Issue by lgoldstein** [cloudius-systems/osv#544]
I am running Java code on an image that has _not_ been created with DEBUG messages enabled (I don't even know how this is done or if it is at all possbile), and from time to time, during my code's execution I get the "pthread_setcanceled_state stubbed" message appearing on the console. To the best of my knowledge, this message is _not_ issued by my code. I believe the aforementioned method should be:
- Implemented - if deemed necessary
  or
- Make the message a WARNING or ERROR if indeed the method is necessary and if not implemented then affects the executing code (and then implement it ASAP...)
  or
- Make sure the message does not appear if image not created with DEBUG messages enabled - if not implementing the method is deemed harmless.

**Comment by wkozaczuk** [comment]
@nyh given that this issue settled as adding implementation of `pthread_setcancell_state` and this commit https://github.com/cloudius-systems/osv/commit/ca6bcd4128e13175879933c328281cf21bc21d57 added `pthread_setcancelstate`, shall we close this issue?

**Comment by nyh** [comment]
I agree. Closing. `pthread_cancel()` is still stubbed (and prints a warning if used), but the functions `pthread_setcancel_*()` already do what they are supposed to do (just save the state) and there's no reason to have an issue about them.
