### ISSUE TITLE
EC2 detection from DMI tables

### ISSUE THREAD

**Issue by penberg** [cloudius-systems/osv#547]
Cloud init, for example, wants to run on EC2 and GCE only. However, it currently always runs on Xen because we don't have a way for detecting when we're running on EC2. We can use DMI BIOS vendor information for detecting when we're running on EC2 by looking at both the vendor and the version:

```
Handle 0x0000, DMI type 0, 24 bytes
BIOS Information
    Vendor: Xen
    Version: 4.2.amazon
    Release Date: 05/23/2014
    Address: 0xE8000
    Runtime Size: 96 kB
    ROM Size: 64 kB
    Characteristics:
        PCI is supported
        EDD is supported
        Targeted content distribution is supported
    BIOS Revision: 4.2
```

**Comment by copumpkin** [comment]
We can also detect EC2/GCE by looking for a reachable 169.254.169.254

**Comment by wkozaczuk** [comment]
@penberg Is it relevant enough to keep it open?

**Comment by nyh** [comment]
I'm closing this issue. In the last few years, people (e.g., in the Mikelangelo project) have used cloud-init outside EC2 or GCE, e.g., by taking an additional disk with the configuration information. So the specific suggestions suggested here would not be enough.
