### ISSUE TITLE
Improve xen tracing infrastructure

### ISSUE THREAD

**Issue by glommer** [cloudius-systems/osv#55]
We have no tracepoints in the xen code that came from BSD. Some of it is very important, like irq entries and buffer allocation. Semantically speaking, a subset of those traces are common to virtio. Where possible, we should aim at having tracepoints with the same name, that users can call regardless of the underlying hypervisor.

**Comment by wkozaczuk** [comment]
Given I have almost no xen know-how and given this issue does not list any specific tracepoints, I propose we close this issue.
