### ISSUE TITLE
How can I run osv in Xen?

### ISSUE THREAD

**Issue by yxliang01** [cloudius-systems/osv#550]
In the official website of osv, I can see that xen is officially supported, but I can't find the image for xen...

**Comment by wkozaczuk** [comment]
@yxliang01 It looks like this issue can be closed as you reported (almost 4 years ago) that you were able to run OSv on XEN. 

Can this issue be closed?

**Comment by yxliang01** [comment]
Right! Sorry that I forgot to close this. Thanks @wkozaczuk for reminding.
