### ISSUE TITLE
Missing support for Linux ioctl SIOCOUTQ 

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#557]
It seems we do not implement the Linux ioctl SIOCOUTQ (a.k.a. TIOCOUTQ) on TCP sockets. This ioctl, described in tcp(7), returns the amount of unacknowledged data in the socket's buffer. It is useful for figuring out if your response reached the remote end. It's useful to know this, for example, if you intend to poweroff right after the response; See also http://blog.netherlabs.nl/articles/2009/01/18/the-ultimate-so_linger-page-or-why-is-my-tcp-not-reliable for another use case.

**Comment by int0dh** [comment]
Would it be better to add TCP_UNACKED socket option instead ? I have sent patch to review

**Comment by nyh** [comment]
Well, SIOCOUTQ is an existing Linux API that existing applications might use, so eventually we will have to implement it, even if you add different ways to get the same information.
