### ISSUE TITLE
Handle xen migration

### ISSUE THREAD

**Issue by glommer** [cloudius-systems/osv#56]
The xen drivers have stubs that are not implemented (some are just not tested) for suspend / resume. However, suspend / resume in xen driver's context also refer to the migration of a xen guest to another machine. The paravirtual drivers aid that process and will gracefully shutdown and later resume their functioning. Usually the process is very close to connect / disconnect, but some important differences are expected.

We need to implement and test those routines to make sure xen guests are migrateable.

**Comment by wkozaczuk** [comment]
I do not think the OSv guests are migratable on any hypervisor. And given I have very little Xen know-how and given our Xen support has stagnated a long time ago I propose we close this issue.
