### ISSUE TITLE
exit on osv shell doesnt work

### ISSUE THREAD

**Issue by pradeepkumars** [cloudius-systems/osv#562]
Looks like regerssion.  Earlier never seen this issue. exit doesnt work
All junk characters are printing. 

/# help
COMMAND  DESCRIPTION                                                   
api      execute arbitrary OSv API operations as defined by the schema 
cat      concatenate files and print on the standard output            
cd       change the shell working directory                            
date     print the system date and time                                
df       report file system disk space usage                           
dmesg    print operating system boot log                               
echo     display a line of text                                        
exit     close shell and exit                                          
free     display amount of free and used memory in system              
hello    a command example                                             
help     list console available commands and show help                 
ls       list directory contents                                       
mkdir    make directories                                              
poweroff poweroff an OSv instance                                      
reboot   reboot an OSv instance                                        
rm       remove files or directories                                   
top      display OSv threads                                           
uptime   tell how long the system has been running                     
/# exiUH��AWI��AVAUATI��SH�
exi: command not found
/# exiUH��AWI��AVAUATI��SH�
exi: command not found
/# exiUH��AWI��AVAUATI��SH�
exi: command not found
/# 
/# wecAUATI��SH��AUATI��SH��AUATI��SH��AUATI��SH���UH��AWI��AVAUATI��SH���UH��AWI��AVAUATI��SH���UH��AWI��AVAUATI��SH���UH��AWI��AVAUATI��SH���UH��AWI��AVAUATI��SH���UH��AWI��AVAUATI��SH���UH��AWI��AVAUATI��SH���UH��AWI��AVAUATI��SH���UH��AWI��AVAUATI��SH���UH��AWI��AVAUATI��SH���UH��AWI��AVAUATI��SH���UH��AWI��AVAUATI��SH���UH��AWI��AVAUATI��SH���UH��AWI��AVAUATI��SH���UH��AWI��AVAUATI��SH�
/# echo

/# exiUH��AWI��AVAUATI��SH�
exi: command not found
/# exiUH��AWI��AVAUATI��SH�
exi: command not found
/# 
/# 
/# 
/# exiUH��AWI��AVAUATI��SH�
exi: command not found
/# 
/# 
/#

**Comment by nyh** [comment]
We were never able to reproduce this issue. Can someone please close it?
