### ISSUE TITLE
negative cpu percentage

### ISSUE THREAD

**Issue by pradeepkumars** [cloudius-systems/osv#563]
![screenshot from 2014-12-05 10 10 20](https://cloud.githubusercontent.com/assets/1373731/5449474/1bc623f0-851c-11e4-93e8-73de82b80579.png)

**Comment by nyh** [comment]
I believe this issue was discussed in the osv-gui bug tracker (https://github.com/cloudius-systems/osv-gui/issues/116) and solved in that project (https://github.com/cloudius-systems/osv-gui/commit/f3435903a36f104fc1fe93460bd966f84db1ffd8).
Can we close this issue too?
