### ISSUE TITLE
Implement fchmod (currently stubbed)

### ISSUE THREAD

**Issue by lgoldstein** [cloudius-systems/osv#565]
The current "implementation" of _fchmod_ is currently a __stub__ that simply does nothing and displays a `fchmod() stubbed` message. While in a single-user environment access rights are not really important, we need to make sure we provide a complete implementation - just in case some code somehow relies on the correct behavior of _fchmod_ - e.g., what if it attempts to set some (r)ead/(w)rite/e(x)ecute permission on a file which is then checked by some other code. If the permission is not sent correctly, then the code might fail. This should be easy enough since _chmod_ is already implemented - see _fs/vfs/main.cc_ file.

**Comment by lgoldstein** [comment]
@avikivity ```The implementation should be trivial since chmod is implemented``` - any chance it can be done some time soon ? Turns out it causes an "benign" exception in the Java Apache SSH daemon. This exception causes connections to be aborted once file-transfer is successfully completed - on re-connect everything seems OK.

**Comment by nyh** [comment]
On Thu, Jan 1, 2015 at 1:57 PM, Lyor Goldstein <notifications@github.com>
wrote:

> @avikivity <https://github.com/avikivity> The implementation should be
> trivial since chmod is implemented - any chance it can be done some time
> soon ?
>

Yes, I will do it today - either based on your patch or from first
principles (I'll look into it).

-- 
Nadav Har'El
nyh@cloudius-systems.com

**Comment by lgoldstein** [comment]
Thanks – no hurry, it’s just a bit annoying every time I used SFTP… BTW, if you are implementing it, look into implementing *fchown* – you can re-use the *file_path_from_fd* method as well...

**Comment by nyh** [comment]
On Sun, Dec 21, 2014 at 1:19 PM, Lyor Goldstein <notifications@github.com>
wrote:

> Here is a quick patch I wrote based on what I was able to find in the code
> (I am sure you can do better...). I did not test it,
>
I just sent to the mailing list a patch implementing fchmod() in a more
straightforward way - calling the same low-level vn_mode() which chmod()
calls, with natural locking of the file structure and dentry. I also wrote
a test, which this new fchmod() passes (we have bug #570, but I doubt this
will bother your use case).
