### ISSUE TITLE
ESXi image building

### ISSUE THREAD

**Issue by rowlandwatkins** [cloudius-systems/osv#569]
Hi folks,

This might be a stupid question, but is it possible to build ESXi images via capstan? Otherwise, I guess I'd need to create the vmdk via make:

[[[
make image=openjdk8,httpserver osv.vmdk
]]]

If I can't use capstan to insert the app into the image, I guess I'll have to use a Makefile...

Happy New Year and thanks for all the help!

Cheers,

Rowland

**Comment by rowlandwatkins** [comment]
Hi Dor,

Happy New Year and many thanks for the info! Ah, OK so I'm putting together a build pipeline in Jenkins on a fresh Ubuntu VM, running on ESX (virtual VT-X etc activated, so KVM is available). Maybe I can just build the images from scratch using source rather than using capstan - then I can use the usual ESX instructions, and use the OVFtool to deploy into my internal environment.

On a separate note - I've hit a problem where Capstan CPIO copy doesn't complete on capstan build - I'll open a ticket in the capstan project.

Cheers,

Rowland

**Comment by dorlaor** [comment]
On Tue, Jan 6, 2015 at 10:49 AM, Rowland Watkins <notifications@github.com>
wrote:

> Hi Dor,
>
> Happy New Year and many thanks for the info! Ah, OK so I'm putting
> together a build pipeline in Jenkins on a fresh Ubuntu VM, running on ESX
> (virtual VT-X etc activated, so KVM is available). Maybe I can just build
> the images from scratch using source rather than using capstan - then I can
> use the usual ESX instructions, and use the OVFtool to deploy into my
> internal environment.
>
That's indeed an option, I think that the standard build format creates raw
images that should be converted using ovftool.
However, we should just fix the capstan issue

> On a separate note - I've hit a problem where Capstan CPIO copy doesn't
> complete on capstan build - I'll open a ticket in the capstan project.
>

It should work although I never tried running OSv as a nested guest. Let's
see the build -v output

**Comment by rowlandwatkins** [comment]
Cool, I think I figured it all out at this end - I'm using a combo of capstan (upload app into cloudius/osv-openjsk8-fedora), qemu-img to create a vmdk, scripts/gen-vmx.sh and ovftool to get the instance into ESX - works a treat! The image is > 100MB, which is pretty awesome - makes a mockery of standard VMs to do the same thing, even if in Docker ;-) Really appreciate the advice and debugging hints, thanks!

Cheers,

Rowland

**Comment by dorlaor** [comment]
On Thu, Jan 8, 2015 at 5:54 AM, Rowland Watkins <notifications@github.com>
wrote:

> Cool, I think I figured it all out at this end - I'm using a combo of
> capstan (upload app into cloudius/osv-openjsk8-fedora), qemu-img to create
> a vmdk, scripts/gen-vmx.sh and ovftool to get the instance into ESX - works
> a treat! The image is > 100MB, which is pretty awesome - makes a mockery of
> standard VMs to do the same thing, even if in Docker ;-) Really appreciate
> the advice and debugging hints, thanks!
>

That's great!
Would you mind to create an example app that can be shared as a git repo
like capstan-example-java or similar?
Later on we can publish a blog about it

**Comment by rowlandwatkins** [comment]
Sure, I'll put together a ping-pong Akka example that runs forever. What's the preferred license - 3 clause BSD?

**Comment by dorlaor** [comment]
On Thu, Jan 8, 2015 at 10:41 AM, Rowland Watkins <notifications@github.com>
wrote:

> Sure, I'll put together a ping-pong Akka example that runs forever. What's
> the preferred license - 3 clause BSD?
>
Terrific! and yes w.r.t the license.
