### ISSUE TITLE
Dashboard: JVM tab missing

### ISSUE THREAD

**Issue by tzach** [cloudius-systems/osv#579]
When running Tomcat on from EC2 AMI, the JVM tab is missing.
Maybe this related to the new HTTP plugin?

**Comment by rowlandwatkins** [comment]
@tzach I don't think this is limited to Tomcat - the JVM tab does appear to have taken a holiday, even for my scala apps...

**Comment by dorlaor** [comment]
I noticed it too with Cassandra. The Cassandra tab exists but not the jvm
one

**Comment by tzach** [comment]
Yes, its not limited to EC2 - I see it locally as well.
I will look into it, maybe with @amnonh help.

**Comment by tzach** [comment]
I'm guessing this is somehow related to making Java a plugin
https://github.com/cloudius-systems/osv/commit/23037196affb5c1b7b9db26fe096f3c63267094c
@syuu1228 can you please take a look?

**Comment by rowlandwatkins** [comment]
I noticed in the modules directory that there's an "httpserver-jvm-plugin" - does this need to be specified or it gets pulled automatically by "httpserver" module?

**Comment by rowlandwatkins** [comment]
Hi all,

Creating a new image and explicitly adding image=httpserver,httpserver-jvm-plugin adds the JVM tab back in, however, I'm not seeing any data being pulled in.

Here's my full build configuration:

[[[
scripts/build image=jdk8,httpserver,cloud-init,mgmt,httpserver-jvm-plugin fs_size_mb=1024
]]]

Is there anything else I might be missing?

Cheers,

Rowland

**Comment by tzach** [comment]
I tested with
```
scripts/build image=tomcat,httpserver
```
and I see the Java tab just fine, including the data, so the original problem was fix.

**Comment by nyh** [comment]
On Wed, Apr 1, 2015 at 5:57 AM, Rowland Watkins <notifications@github.com>
wrote:

> Hi all,
>
> Creating a new image and explicitly adding
> image=httpserver,httpserver-jvm-plugin adds the JVM tab back in, however,
> I'm not seeing any data being pulled in.
>
> Here's my full build configuration:
>
> [[[
> scripts/build image=jdk8,httpserver,cloud-init,mgmt,httpserver-jvm-plugin
> fs_size_mb=1024
> ]]]
>
Is there anything else I might be missing?
>

I don't know what is "jdk8", we don't have such a module...  Maybe
openjdk8-fedora?

I see that openjdk8-fedora/module.py is missing the plugins of
modules/java/module.py - and I'll add them. But above you added
httpserver-jvm-plugin manually so should have been enough...



-- 
Nadav Har'El
nyh@cloudius-systems.com

**Comment by rowlandwatkins** [comment]
@nyh Apologies, "jdk8" is an alias to openjdk8-fedora in my local config.json

This could be a transient issue - let me try a complete clean build and get back to you after the weekend, I expect that should clear things up.
