### ISSUE TITLE
distribute xen interrupts

### ISSUE THREAD

**Issue by glommer** [cloudius-systems/osv#58]
All xen interrupts are arriving at CPU0. We should try to spread them more in an intelligent fashion. AFAIU, xen does not yet support multiqueue (See http://wiki.xenproject.org/wiki/Xen_Development_Projects#Multiqueue_support_for_Xen_netback.2Fnetfront_in_Linux_kernel), and Amazon certainly does not. So we won't take the interrupts at the same time. Still, we should be prepared to take them anywhere.

**Comment by wkozaczuk** [comment]
Given I have very little Xen know-how and given our Xen support has stagnated a long time ago I propose we close this issue.
