### ISSUE TITLE
exit() sometimes causes crash during shutdown

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#580]
OSv's implementation of the exit() function unmounts the filesystem before powering off (the intention is to have a clean shutdown, with disk modifications flushed). The problem is that in parallel with this thread calling exit(), the application might have additional threads, and these threads run code from an executable on the unmounted filesystem. If one of these threads happens to run after the filesystem is unmounted but before the VM finally poweroffs, it can crash for various reasons.

Bas Wegh reported an relatively easy way to reproduce this bug, with the Erlang shell image ("make image=erlang"), giving it the command "q()." to exit. In about half of the runs, it crashes as in the following verbose output ("scripts/run.py -V"):

```
Eshell V6.2  (abort with ^G)
1> q().
ok
2> program exited with status 0
VFS: unmounting /dev
VFS: unmounting /proc
VFS: unmounting /
exception nested too deeply
```

The message "program exited with status 0" tells us that Erlang called exit(). We then see that the filesystem is being unmounted, and when that's done - a crash with the message "exception nested too deeply". Debugging this in gdb (with backtrace removed from abort() to reduce amount of nested crashes), we see the crash happens during a page fault in one of the Erlang threads:

```
#32 0x000000000039265a in page_fault (ef=0xffff80007fd55078)
    at /home/nyh/osv.tmp1/arch/x64/mmu.cc:38
#33 <signal handler called>
#34 0x0000100000cc8dee in erts_thr_yield ()
#35 0x0000100000cce234 in sched_spin_wait ()
#36 0x0000100000cce728 in scheduler_wait ()
#37 0x0000100000cd8cbe in schedule ()
#38 0x0000100000d972dd in process_main ()
#39 0x0000100000cd6bc9 in sched_thread_func ()
#40 0x0000100000e5ee2f in thr_wrapper ()
```

(This is the important part of the stack trace. The actual stack trace is longer, and ends up causing a "exception nested too deeply" message, because the page fault tries to read something from disk, which causes an exception to be thrown, and the exception unwinding code causes another page fault).

**Comment by lgoldstein** [comment]
@nyh Another exit / reboot related issue is #495
