### ISSUE TITLE
Strange exception - 'vfork failed' with error code 0 when starting a new thread via Java's ExecutorService class

### ISSUE THREAD

**Issue by lgoldstein** [cloudius-systems/osv#582]
Attached is the stack trace dump - as can be plainly seen, it is pure Java core code (1.8.0_31 in this case). The exception does not seem to affect my code, and what makes it strange is the following:
- The reported error code is "0" - i.e., success, so why the exception ?
- **when** it occurs: only on the **first** SSH connection attempt after the **first** boot of a fresh image has been created. In other words, if I do the same thing after the VM has been re-started with the same image, or disconnect and re-connect again there is no such behavior.
- Despite the exception the SSH connection succeeds

Again, it does not seem to affect the code (but then again, I am not testing everything), but worth a look.
![vfork-failure](https://cloud.githubusercontent.com/assets/1436205/6058420/f5747ee0-ad2f-11e4-8b2e-33afc43bf4e1.JPG)

**Comment by nyh** [comment]
On Thu, Feb 5, 2015 at 12:12 PM, Lyor Goldstein <notifications@github.com>
wrote:

> Attached is the stack trace dump - as can be plainly seen, it is pure Java
> core code (1.8.0_31 in this case). The exception does not seem to affect my
> code, and what makes it strange is the following:
>
>    - The reported error code is "0" - i.e., success, so why the exception
>    ?
>
> vfork() failed (returned -1), but did not set errno so errno remained 0.
Java tried to print errno to better explain the error, and ended up
printing "error 0".

Our silly implementation of vfork() is:

int vfork()
{
    debug("vfork stubbed\n");
    return -1;
}

We can easily set errno to something else, but I'm not sure what would be a
reasonable errno to return (perhaps EAGAIN?), and even if we did return a
more reasonable errno, I don't think it will really improve anything other
than slightly change the error dump you're seeing.


>
>    - *when* it occurs: only on the *first* SSH connection attempt after
>    the *first* boot of a fresh image has been created. In other words, if
>    I do the same thing after the VM has been re-started with the same image,
>    or disconnect and re-connect again there is no such behavior.
>    - Despite the exception the SSH connection succeeds
>
>
We need more lines from the Java call trace to understand what ssh is
trying to do, but my unfounded guess is that it tries to fork to run some
shell command which does some one-time initialization, and if that fails,
it falls back to doing this initialization in another way instead - so next
time, this initialization work is not attempted again. But I really have no
idea *what* it is trying to do.

**Comment by lgoldstein** [comment]
```We need more lines from the Java call trace to understand what ssh is trying to do``` - actually, as strange as it may seem it isn't trying to do anything. I am using Apache SSHD and providing my own commands factory - and I assure you, I do not support the 'vfork' command nor do I issue such a command.

```my unfounded guess is that it tries to fork to run some shell command``` - again, extremely unlikely - the code you can see in the stack trace that is not JDK core is mine and I assure you I do **not** try to spawn a process (nor does the Apache SSHD code - I *grep*-ed it most thoroughly). Also, if you look closely at the stack trace you can see that only the JDK core code is invoked - there is no process being spawned by my code. The only "suspect" is the ```UnixProcess.forkAndExec``` which is **core** code and not mine...

The only explanation I can think of is that the core Java code does something like this (unlikely, but if it does, it is out of my hands...). I have been attempting to re-create this again and it seems to be some kind of **timing** issue as well - it doesn't always occur - it seems to be intermittent...

**Comment by wkozaczuk** [comment]
Is it really a bug on OSv side? Shall we close it?

**Comment by wkozaczuk** [comment]
I do not think we have enough info to reproduce it. Plus as @nyh points out given OSv does not support fork() and probably never will, there is probably not much value trying to fix anything on OSv size.

**Comment by nyh** [comment]
I don't think reproducing this issue is a problem - just call vfork ;-)
We have a simple solution to this issue - use the NO_SYS(vfork) macro instead of that "WARN_STUBBED; return -1" body. NO_SYS  sets errno as expected.
