### ISSUE TITLE
Investigate EC2 network disconnects

### ISSUE THREAD

**Issue by glommer** [cloudius-systems/osv#59]
Dor reported that connection at amazon is suddenly dropped. If one tries to reconnect later it works again. I see the same behavior with an Ubuntu guest, but the time-to-disconnect there is much larger, which indicates a timeout related problem, which does not seem to be consistent with what Dor is seeing (disconnects are very quick to appear). Need to investigate that.

**Comment by wkozaczuk** [comment]
This 8-years old does not have any steps to reproduce it nor it is specific enough to troubleshoot it. So I am closing it.
