### ISSUE TITLE
scripts/ec2-simulator and capstan

### ISSUE THREAD

**Issue by rowlandwatkins** [cloudius-systems/osv#592]
Hi folks,

Is it possible to use the scripts/ec2-simulator.py with capstan images?

I'm having trouble getting my image to get the cloud-init configuration before the app starts (command line scala with configuration passed as argument /conf/application.conf).

Bridge networking and cloud-init enabled (built image with image=osvinit)

I'm not sure what else I might be missing here...

Many thanks in advance!

Cheers,

Rowland

**Comment by tgrabiec** [comment]
Starting from commit 7d9c432053bfd84f852094f11d09ab0c48d729f1 cloud init module does not probe for data source when not run on either Xen or GCE.

 To check if it attempts probing or not, check out the dmesg log, either using REST API (`curl http://osv:8000/os/dmesg`) or by starting OSv with the `--verbose` kernel option.

To force the probing, you need to pass `--force-probe` parameter to cloud init module's command line. 

If you want to use `capstan`, one thing you could try is to use the `files:` section of the Capstanfile to override contents of `/init/00-cmdline` file in the image to this:

```
/usr/mgmt/cloud-init.so --force-probe;
```

**Comment by tzach** [comment]
@rowlandwatkins  maybe this example will be useful:
https://github.com/cloudius-systems/capstan-env-var-java-example

It demo, among other, setting env vars at init, using the method @tgrabiec mentioned above.

**Comment by rowlandwatkins** [comment]
Thanks @tgrabiec and @tzach capstan-env-var-java-example works a treat.

I've tested and it looks like the local-init.yaml isn't strictly required, so I'll just opt for using the remote-init.yaml and not pass the local-init.yaml to cloud-init. It's nice to be able to remove static configuration now!

Cheers,

Rowland
