### ISSUE TITLE
Running OSv images using capstan 

### ISSUE THREAD

**Issue by Jeongseob** [cloudius-systems/osv#596]
Hi all,

I am interested in the OSv project. So, currently, I would like to use the OS-v images by using capstan. Basically, it works well, but when I configured the network bridge, it does not work. 
Currently, I have used Ubuntu 14.04 (64bit). Could you help me?

--------------------------------------------------------------------------------------------------------------
jeongseob@ilsan:~$ sudo ./bin/capstan run -n bridge cloudius/osv
Created instance: cloudius-osv
failed to launch bridge helper
qemu-system-x86_64: -netdev bridge,id=hn0,br=virbr0,helper=/usr/libexec/qemu-bridge-helper: Device 'bridge' could not be initialized

exit status 1
--------------------------------------------------------------------------------------------------------------

I attach my ifconfig.

jeongseob@ilsan:~$ ifconfig
eth0      Link encap:Ethernet  HWaddr fc:aa:14:3f:e4:c4
          inet addr:141.212.106.96  Bcast:141.212.106.255  Mask:255.255.255.0
          inet6 addr: fe80::feaa:14ff:fe3f:e4c4/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:11338 errors:0 dropped:0 overruns:0 frame:0
          TX packets:563 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1747879 (1.7 MB)  TX bytes:93892 (93.8 KB)
          Interrupt:20 Memory:f7c00000-f7c20000

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:348 errors:0 dropped:0 overruns:0 frame:0
          TX packets:348 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:40906 (40.9 KB)  TX bytes:40906 (40.9 KB)

virbr0    Link encap:Ethernet  HWaddr 00:00:00:00:00:00
          inet addr:192.168.122.1  Bcast:192.168.122.255  Mask:255.255.255.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:5 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:710 (710.0 B)  TX bytes:824 (824.0 B)

jeongseob@ilsan:~$

**Comment by dorlaor** [comment]
On Tue, Mar 3, 2015 at 11:00 PM, Jeongseob Ahn <notifications@github.com>
wrote:

> Hi all,
>
> I am interested in the OSv project. So, currently, I would like to use the
> OS-v images by using capstan. Basically, it works well, but when I
> configured the network bridge, it does not work.
> Currently, I have used Ubuntu 14.04 (64bit). Could you help me?
> ------------------------------
>
> jeongseob@ilsan:~$ sudo ./bin/capstan run -n bridge cloudius/osv
>
You're either missing the bridge helper or don't have virbr0 bridge
configured.
The later can be easily created by installing libvirt and running the
libvirtd service

**Comment by Jeongseob** [comment]
Thanks, but when I run OSv image from source like below, the ping on host works.
In addition, I installed libvirt. 
-------------------------------------------------------------------------------------------
jeongseob@ilsan:~/OSv$ sudo ./scripts/run.py -nv
OSv v0.18-15-gf09fa1a
eth0: 192.168.122.89
-------------------------------------------------------------------------------------------

jeongseob@ilsan:~$ ping 192.168.122.89
PING 192.168.122.89 (192.168.122.89) 56(84) bytes of data.
64 bytes from 192.168.122.89: icmp_seq=1 ttl=64 time=0.494 ms

**Comment by dorlaor** [comment]
On Tue, Mar 3, 2015 at 11:18 PM, Jeongseob Ahn <notifications@github.com>
wrote:

> Thanks, but when I run OSv image from source like below, the ping on host
> works.
>

The qemu command line is different between Capstan bridge mode and the
run.py script.
The main difference is that the first uses the bridge helper and the later
uses tap mode and this must have a root user - -netdev
tap,id=hn0,script=scripts/qemu-ifup.sh,vhost=on

You can try running the qemu cmdline that Capstan creates manually and see
what happens and what's missing. You don't need sudo for it.

**Comment by Jeongseob** [comment]
It seems like the path of qemu-bridge-helper is different between Capstan and my system. Capstan seeks the path "qemu-system-x86_64: -netdev bridge,id=hn0,br=virbr0,helper=/usr/libexec/qemu-bridge-helper: Device 'bridge' could not be initialized", but there is no qemu-bridge-helper in the path. I found the qemu-bridge-helper in "/usr/lib". I just copied the file, but it produces error like below. 

failed to parse default acl file `/etc/qemu/bridge.conf'

Do I have to install some other packages related to QEMU?

**Comment by dorlaor** [comment]
On Tue, Mar 3, 2015 at 11:39 PM, Jeongseob Ahn <notifications@github.com>
wrote:

> It seems like the path of qemu-bridge-helper is different between Capstan
> and my system. Capstan seeks the path "qemu-system-x86_64: -netdev
> bridge,id=hn0,br=virbr0,helper=/usr/libexec/qemu-bridge-helper: Device
> 'bridge' could not be initialized", but there is no qemu-bridge-helper in
> the path. I found the qemu-bridge-helper in "/usr/lib". I just copied the
> file, but it produces error like below.
>
Probably some other files are missing or misplaced. It's probably a Fedora
vs Ubuntu difference.
Try to run the same cmdline that Capstan is trying to (you can wrap the
qemu binary with a shell
file that echo the cmd) and change the full path to the bridge helper
instead of moving it.

My qemu related rpms are:
qemu-kvm-tools-2.1.3-2.fc21.x86_64
qemu-img-2.1.3-2.fc21.x86_64
qemu-kvm-2.1.3-2.fc21.x86_64
libvirt-daemon-driver-qemu-1.2.9.2-1.fc21.x86_64
qemu-common-2.1.3-2.fc21.x86_64
ipxe-roms-qemu-20140303-3.gitff1e7fc7.fc21.noarch
qemu-guest-agent-2.1.3-2.fc21.x86_64
qemu-system-x86-2.1.3-2.fc21.x86_64

But it's probably the path issue

**Comment by Jeongseob** [comment]
Um... i do not know why there is no /etc/qemu/bridge.conf". I am not familiar with the KVM and QEMU stuff. Do yo use Fedora?

**Comment by dorlaor** [comment]
On Wed, Mar 4, 2015 at 12:27 AM, Jeongseob Ahn <notifications@github.com>
wrote:

> Um... i do not know why there is no /etc/qemu/bridge.conf". I am not
> familiar with the KVM and QEMU stuff. Do yo use Fedora?
>
Yap.

> cat /etc/qemu/bridge.conf
allow virbr0

**Comment by Jeongseob** [comment]
I am sorry to disturb you. I already tried to create the bridge.conf as you mentioned, but there is still problem. 

jeongseob@ilsan:~$ capstan run -n bridge cloudius/osv
Created instance: cloudius-osv
failed to create tun device: Operation not permitted
failed to launch bridge helper
qemu-system-x86_64: -netdev bridge,id=hn0,br=virbr0,helper=/usr/libexec/qemu-bridge-helper: Device 'bridge' could not be initialized

**Comment by dorlaor** [comment]
On Wed, Mar 4, 2015 at 12:49 AM, Jeongseob Ahn <notifications@github.com>
wrote:

> I am sorry to disturb you. I already tried to create the bridge.conf as
> you mentioned, but there is still problem.
>
> jeongseob@ilsan:~$ capstan run -n bridge cloudius/osv
> Created instance: cloudius-osv
> failed to create tun device: Operation not permitted
>

Did you add the suid permission to the location of your bridge-helper:

ls -la /usr/libexec/qemu-bridge-helper
-rwsr-xr-x. 1 root root 15384 Feb  8 04:38 /usr/libexec/qemu-bridge-helper

Otherwise, try with sudo

**Comment by Jeongseob** [comment]
Sure, I tried both of them. These does not work, but when running the capston as a root (not sudo), it works. 

root@ilsan:~# ./bin/capstan run -n bridge cloudius/osv-iperf
Created instance: cloudius-osv-iperf
OSv v0.18
eth0: 192.168.122.148
pthread_setcancelstate() stubbed
------------------------------------------------------------
Server listening on TCP port 5001
TCP window size: 64.0 KByte (default)
------------------------------------------------------------
