### ISSUE TITLE
cloud-init.so ignore --file on AWS

### ISSUE THREAD

**Issue by rowlandwatkins** [cloudius-systems/osv#597]
Hi folks,

So I use --file on ESXI to pass a static configuration within our internal integration environment. When I deploy onto AWS though, --force-probe doesn't override file, and thus AWS reads whatever is passed via --file.

Is there anyway we can have --force-probe override --file on AWS and GCE?

Cheers,

Rowland

**Comment by rowlandwatkins** [comment]
OK, so I've bypassed this issue for the time being by getting Jenkins to populate the cmdline script.

**Comment by wkozaczuk** [comment]
This seems more like a question for a distribution list. Shall we close it?
