### ISSUE TITLE
missing mkostemp() function

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#604]
We are missing an implementation of mkostemp(). It is needed for example by phantomjs.
Hopefully adding it should be as trivial as adding

```
musl += temp/mkostemp.o
```

to the Makefile. We already use musl's mktemp, mkostemps, and friends.

**Comment by rowlandwatkins** [comment]
@nyh Yep, works as you suggested - now basic font handling in AWT generates correct output, many thanks! I'll try and get a patch to the mailing list this week.
