### ISSUE TITLE
OVA image no longer working on ESX

### ISSUE THREAD

**Issue by lgoldstein** [cloudius-systems/osv#607]
After using _git bisect_ the culprit seems to be commit 4214f3345f6cbb1174dfba3cc64abb780eb0fa95

**Comment by dorlaor** [comment]
On Mon, Mar 30, 2015 at 11:47 AM, Lyor Goldstein <notifications@github.com>
wrote:

> After using *git bisect* the culprit seems to be commit 4214f33
> <https://github.com/cloudius-systems/osv/commit/4214f3345f6cbb1174dfba3cc64abb780eb0fa95>
>

Thanks! Takuya, that's your xsave:

Author: Takuya ASADA <syuu@cloudius-systems.com>
Date:   Sat Feb 7 06:35:48 2015 +0900

    x64: enable xsave when it available

    Signed-off-by: Takuya ASADA <syuu@cloudius-systems.com>
    Reviewed-by: Nadav Har'El <nyh@cloudius-systems.com>
    Reviewed-by: Avi Kivity <avi@cloudius-systems.com>
    Signed-off-by: Pekka Enberg <penberg@cloudius-systems.com>

**Comment by syuu1228** [comment]
I've tested with 
- Core i7 870 (no ASX), ESXi 5.5
- Core i7 4950HQ (AVX 2.0) ESXi 6.0
vs
- Latest build of cloudius/osv image(using build-vm-images)
- Latest build of cloudius/osv-cassandra image(using build-vm-images)
I cannot reproduce the problem, it just able to boot.

Lyor, could you tell me your CPU / ESXi ver / revision of your local tree / app name passed to image= ?

**Comment by lgoldstein** [comment]
My ESX:
- Model: Precision WorkStation T5400, Dell Inc.
- 8 CPUs x 2.327 GHz – 2 processor sockets, 4 cores per socket, 8 logical processors
- 16 GB RAM memory
- 690 GB disk
- vSphere 5.5
I am testing the latest image with Oracle Java 1.8.0_30 as the _jdkbase_ with a special 'image' value of my own - I will send you a separate e-mail regarding how to download my image, build and run the OVA...

**Comment by lgoldstein** [comment]
P.S. Please note that the **VMDK** image boots for me as well when I run it in _Vmware Workstation_ - when I create an OVA and deploy it to my ESX it does not boot.

**Comment by syuu1228** [comment]
Could you check model name of the CPU on your machine as well?
I guess it's Xeon E54xx, is this right? (checked Precision T5400 cpu list)

**Comment by nyh** [comment]
On Thu, Apr 2, 2015 at 10:47 PM, Takuya ASADA <notifications@github.com>
wrote:

> Could you check model name of the CPU on your machine as well?
> I guess it's Xeon E54xx, is this right? (checked Precision T5400 cpu list)


The Xeon E5400 series is pretty old (see
http://ark.intel.com/products/series/33905/Intel-Xeon-Processor-5400-Series#@All),
predating AVX.

Could it be that we have a simple bug that mis-handles the case where we
*don't* have AVX, and we must fall back to the old ways of doing this?

Takuya, should be pretty easy to simulate this even on qemu (change the
"-cpu" paramter that run.py passes to qemu to set an older cpu, or take
away features from the host cpu).

**Comment by syuu1228** [comment]
On Fri, Apr 3, 2015 at 5:45 AM, nyh <notifications@github.com> wrote:

> On Thu, Apr 2, 2015 at 10:47 PM, Takuya ASADA <notifications@github.com>
> wrote:
>
> > Could you check model name of the CPU on your machine as well?
> > I guess it's Xeon E54xx, is this right? (checked Precision T5400 cpu
> list)
>
>
> The Xeon E5400 series is pretty old (see
>
> http://ark.intel.com/products/series/33905/Intel-Xeon-Processor-5400-Series#@All
> ),
> predating AVX.
>
> Could it be that we have a simple bug that mis-handles the case where we
> *don't* have AVX, and we must fall back to the old ways of doing this?
>
> Takuya, should be pretty easy to simulate this even on qemu (change the
> "-cpu" paramter that run.py passes to qemu to set an older cpu, or take
> away features from the host cpu).


I'll try it.

**Comment by syuu1228** [comment]
On Fri, Apr 3, 2015 at 5:45 AM, nyh <notifications@github.com> wrote:

> On Thu, Apr 2, 2015 at 10:47 PM, Takuya ASADA <notifications@github.com>
> wrote:
>
> > Could you check model name of the CPU on your machine as well?
> > I guess it's Xeon E54xx, is this right? (checked Precision T5400 cpu
> list)
>
>
> The Xeon E5400 series is pretty old (see
>
> http://ark.intel.com/products/series/33905/Intel-Xeon-Processor-5400-Series#@All
> ),
> predating AVX.
>
> Could it be that we have a simple bug that mis-handles the case where we
> *don't* have AVX, and we must fall back to the old ways of doing this?
>

My ESXi machine is Core i7 870, which is not supported AVX either, but it
able to run the VM image without problem.

**Comment by syuu1228** [comment]
Tested with Nehalem, core2duo, Westmere. It worked.

**Comment by nyh** [comment]
On Fri, Apr 3, 2015 at 1:12 AM, Takuya ASADA <notifications@github.com>
wrote:

> Tested with Nehalem, core2duo, Westmere. It worked.


Too bad, it was a good guess ;-)

**Comment by lgoldstein** [comment]
Hi guys,
Thanks for the quick response. To answer your question – my CPU is Xeon E5410 2.33 Ghz (indeed a rather old model). A few remarks:

- Your build and deploy process are different than the way I do it. You are running:
```
make clean
make jdkbase=/usr/java/jdk1.8.0_40
cd apps/
unzip -x ~/java-shell.zip
cd java-shell
java -cp bootstrap-1.8.1.0.jar -Djava.awt.headless=true -Djava.shell.main.failure.stack.trace.delay=5000 org.apache.commons.cli.shell.bootstrap.Bootstrap -jsalogfinest # to download dependent jars, looks like it's better to run java-shell once
scripts/build image=java-shell jdkbase=/usr/java/jdk1.8.0_40
	…etc…
```
Whereas I only run
```
scripts/build image=java-shell jdkbase=/usr/java/jdk1.8.0_40
…etc…
```
I don’t know if this can account for the problem – I’ll try your way and see how it goes

- You seem to be using 
```
ovftool -ds=datastore1 build/release.x64/osv-esx.ova vi://root:xxxxx@192.168.1.57
```
In order to deploy the OVA, whereas I do it manually via the vSphere client UI – again, I’ll try doing it your way and see if it changes anything

I have followed your procedure instead of mine and still the same problem – cannot run the code – don’t even see the DHCP assignment message that shows the IP address assigned to the VM, let alone the Java code. I have also tried this image on another ESX – Dell PowerEdge R620, CPU=Xeon E5-26200, 2.00 Ghz, and it works just fine, so it seems indeed to be some kind of CPU/ESXi version issue.

Just to double-check, I checked out the last commit I know that yielded a working OVA (ca35d5c9aabacc57262a437551d03bcb776af153), built and deployed the image – it worked just fine on my (old model) ESX. Then I checked out the commit right after that one (4214f3345f6cbb1174dfba3cc64abb780eb0fa95) and tried it - it did not work. Therefore, it seems we have a very focused and narrow issue to resolve - why would the specific commit affect the specific CPU model I have.

P.S. in view of the fact that it seems to be an ESX/CPU model issue related to rather old models, it does not seem to be high priority. However, it would be great if you could try the OVA I generated – you can download it from [here](http://1drv.ms/19Xfei2). Maybe you can analyze the OVA somehow and figure out the problem – no rush though since we determined that the problem is the model (though IMO it would be nice to at least diagnose the exact problem with the older model).

**Comment by nyh** [comment]
On Mon, Apr 6, 2015 at 10:07 AM, Lyor Goldstein <notifications@github.com>
wrote:

I have followed your procedure instead of mine and still the same problem –
> cannot run the code – don’t even see the DHCP assignment message that shows
> the IP address assigned to the VM, let alone the Java code. I have also
> tried this image on another ESX – Dell PowerEdge R620, CPU=Xeon E5-26200,
> 2.00 Ghz, and it works just fine, so it seems indeed to be some kind of
> CPU/ESXi version issue.


Unfortunately I cannot test this myself (I don't have VMware, nor access to
the old CPU you mention). Surely, OSv is crashing on something very early
and would be useful if you could attach a debugger to it or add printouts
which say where it crashes - maybe the guys who developed the OSv support
for VMware can share debugging tips (I never did this myself).

I tried to review the code again, and cannot find any obvious flaws - it
makes sure to verify the XSAVE cpu feature is available before trying to
use this instruction (and the xcr0 register, to enable avx instructions). I
also tested with qemu that OSv seems to run under emulated older CPus. The
only wild guess I can make without more information on where the crash
happens is that maybe VMware has a bug where it reports AVX to the guest,
while AVX isn't actually supported? I tried searching the web for a
discussion of the possibility of such a bug, but the only thing I could
find is that if you use "EVC" (enhanced vmotion compatibility) it is
possible to make ESX pretend it has  xsave/avx. Is it possible you have EVC
enabled? As I said, this is just a wild guess...

> Just to double-check, I checked out the last commit I know that yielded a
> working OVA (ca35d5c
> <https://github.com/cloudius-systems/osv/commit/ca35d5c9aabacc57262a437551d03bcb776af153>),
> built and deployed the image – it worked just fine on my (old model) ESX.
> Then I checked out the commit right after that one (4214f33
> <https://github.com/cloudius-systems/osv/commit/4214f3345f6cbb1174dfba3cc64abb780eb0fa95>)
> and tried it - it did not work. Therefore, it seems we have a very focused
> and narrow issue to resolve - why would the specific commit affect the
> specific CPU model I have.
>

This specific commit is what started to use the XSAVE feature, if
available. Things should still be working even if XSAVE is not available
(on older CPUs, like yours), but apparently something is broken, but I
can't figure out why.


-- 
Nadav Har'El
nyh@cloudius-systems.com

**Comment by lgoldstein** [comment]
```would be useful if you could attach a debugger to it or add printouts which say where it crashes``` - how do I do that ? Please note that if there is such a crash, there is *nothing* printed on the console. I have tried configuring serial output in the past - with no success. Is there some compilation switch I could turn on to make the boot process more verbose ? 

```maybe the guys who developed the OSv support for VMware can share debugging tips``` - such tips would be welcome indeed, please don't hesitate to send them to me.

```the only thing I could find is that if you use "EVC"``` - i'll see if anyone knows about this and/or AVX issues in _Vmware_.

Like I said previously, it does seem to be specific to my model - but I think we should make sure that indeed it is am (old) CPU issue and we will not encounter it on newer models...

**Comment by lgoldstein** [comment]
@nyh I have tried some of the EVC related CPUID mask settings recommended in some of the KB articles - to no avail. I feel though that I lack the proper knowledge of how to mask the XSAVE feature on the ESX - would be nice if someone could suggest how.

On a related issue, if I dump _/proc/cpuinfo_ on one of the VMs that is running on the same ESX as the OSV image should, it reports the _xsave_ flag (see below) - don't know if it helps
```
root@esx-playground:~# more /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 23
model name      : Intel(R) Xeon(R) CPU           E5410  @ 2.33GHz
stepping        : 10
microcode       : 0xa0b
cpu MHz         : 2327.500
cache size      : 6144 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc
aperfmperf pni ssse3 cx16 sse4_1 xsave hypervisor lahf_lm dtherm
bogomips        : 4655.00
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:
```

**Comment by nyh** [comment]
On Mon, Apr 13, 2015 at 1:29 PM, Lyor Goldstein <notifications@github.com>
wrote:

>
> flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc
> aperfmperf pni ssse3 cx16 sse4_1 xsave hypervisor lahf_lm dtherm
>
> Interesting,  this is a good lead. this reports you have "xsave" but *not*
AVX.

Takuya, did we handle this case correctly? I'm not sure we did... :-( In
arch-cpu.hh I see we check if features().xsave and then enable saving of
avx, without checking if avx is also available. I'm guessing this is wrong?

I'll try to think how to test this hypothesis....

**Comment by lgoldstein** [comment]
As I have stated before - since you do not have access to an equivalent ESX model, I would be more than happy to test patches for you - simply commit them to a different GIT branch, let me know what and how you want me to test and I will do it...

**Comment by lgoldstein** [comment]
While we are on this issue - how hard would it be to generate the virtual _/proc/cpuinfo_ file in OSV, so we can have this information available.

**Comment by dorlaor** [comment]
On Mon, Apr 13, 2015 at 3:37 PM, Lyor Goldstein <notifications@github.com>
wrote:

> While we are on this issue - how hard would it be to generate the virtual
> */proc/cpuinfo* file in OSV, so we can have this information available.
>

The information is available through the restapi/cli:

/# api hardware processor flags
sse3 ssse3 cmpxchg16b sse4.1 sse4.2 x2apic tsc_deadline xsave avx rdrand
clflush fgsbase repmovsb kvmclock kvmclock2 kvm_pv_eoi kvmclock_stable

**Comment by lgoldstein** [comment]
Maybe so, but (reminder) I am creating my own image that does not have this API in it (nor can I add it...). Also, other users may decide _not_ to include this API - thus I think it would be nice to have it available via the file system as well (OSV attempts to be as Linux-like as possible...). Since the API already obviously exists, I wonder how difficult it would be to expose it via _/proc/cpuinfo_ - same as other "virtual" files already exported there...

**Comment by dorlaor** [comment]
On Mon, Apr 13, 2015 at 3:55 PM, Lyor Goldstein <notifications@github.com>
wrote:

> Maybe so, but (reminder) I am creating my own image that does not have
> this API in it (nor can I add it...). Also, other users may decide *not*
> to include this API - thus I think it would be nice to have it available
> via the file system as well (OSV attempts to be as Linux-like as
> possible...). Since the API already obviously exists, I wonder how
> difficult it would be to expose it via */proc/cpuinfo* - same as other
> "virtual" files already exported there...
>

It shouldn't be difficult at all since we have the information already and
we do have few entries under /proc today

**Comment by nyh** [comment]
On Mon, Apr 13, 2015 at 1:47 PM, Nadav Har'El <nyh@cloudius-systems.com>
wrote:

> On Mon, Apr 13, 2015 at 1:29 PM, Lyor Goldstein <notifications@github.com>
> wrote:
>
>>
>> flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable nonstop_tsc
>> aperfmperf pni ssse3 cx16 sse4_1 xsave hypervisor lahf_lm dtherm
>>
>> Interesting,  this is a good lead. this reports you have "xsave" but
> *not* AVX.
>
> Takuya, did we handle this case correctly? I'm not sure we did... :-( In
> arch-cpu.hh I see we check if features().xsave and then enable saving of
> avx, without checking if avx is also available. I'm guessing this is wrong?
>
> I'll try to think how to test this hypothesis....
>
>
Lyor, I just posted a tiny patch to the mailing list to avoid enabling AVX
saving when it is not available - even when XSAVE is available. Can you
please test if this patch helps your crashing case?

Thanks!



-- 
Nadav Har'El
nyh@cloudius-systems.com

**Comment by lgoldstein** [comment]
@nyh The patch did the trick - I am now able to run the OVA on my (old) model. I have also tested it on a newer model and it seems to work just fine. As far as I am concerned you can commit this patch.

Thanks for the effort.
