### ISSUE TITLE
Hook the JVM dtrace to OSv shell

### ISSUE THREAD

**Issue by dorlaor** [cloudius-systems/osv#61]
For GC events, we could try to hook our tracepoints to the dtrace
probes in Hotspot JVM:

http://docs.oracle.com/javase/7/docs/technotes/guides/vm/dtrace.html

**Comment by wkozaczuk** [comment]
This may have been a desired feature eight years ago, but given these days Java is no longer our main focus nor we have time to investigate it and Java itself has progressed (version 17 as of now), I consider this issue as irrelevant and closing it.
