### ISSUE TITLE
missing memalign()

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#621]
We implemented posix_memalign() and aligned_alloc(), but not the very similar function memalign().

memalign() is considered obsolete (see the manual page posix_memalign(3)), but still can be used by some applications (e.g., it was used by an older version of Seastar).

**Comment by justinc1** [comment]
I would be glad if memalign is implemented - its used in hello world OpenMPI program.
I currently just tried to add next to my main()
```
void *memalign(size_t align, size_t len) {
  void *ptr = NULL;
  int ret;
  ret = posix_memalign(&ptr, align, len);
  return ptr;
}
```
so that runtime linker will not complain (more precisely, that it will complain about other staff).

**Comment by nyh** [comment]
If you can send a patch to implement memalign in core/mempool.cc (where posix_memalign is defined) it would be very much appreciated :-)

Please read the memalign manual page carefully, what are the exact behavioural differences between memalign and posix_memalign, and whether memalign() can be correctly written by calling posix_memalign(), or you need to reimplement memalign() using the same low level allocations which posix_memalign() uses. It would be nice if we could explain why the former is the case.
