### ISSUE TITLE
Multiple Java directories found in root fs

### ISSUE THREAD

**Issue by rowlandwatkins** [cloudius-systems/osv#627]
Hi folks,

I've created my own image including OpenJDK8, and added the unlimited security policies (local_policy.jar and US_export_policy.jar) to the installed JRE. However, I've found three JRE installs:

1) /usr/lib/jvm/jre
2) /usr/lib/java/jre
3) /usr/lib/java-1.8.0-openjdk-1.8.0.45-32.b13.fc23.x86_64/jre

I'm not sure if this is a side effect to me adding OpenJDK8 when compiling the image, but was wondering which one is correct - at present I simply add the unlimited security policy jars to all three.

Cheers,

Rowland

**Comment by lgoldstein** [comment]
I believe some of them are symbolic links - only one of them is the "real" JDK

**Comment by lgoldstein** [comment]
@rowlandwatkins Yes, this is it (in my case I am using _Oracle_'s JDK that's why the link is called _java-8-oracle_ instead of _java-...openjdk..._:
```
ssh-shell-192.168.174.1:50420 osv[/usr/lib/jvm]: ls -la
     drwxr-xr-x 29-Apr-2015 08:28:06            4 java/
     drwxrwxrwx 29-Apr-2015 08:28:06            4 java-8-oracle/ -> /usr/lib/jvm/java-8-oracle/java
     drwxrwxrwx 29-Apr-2015 08:30:19           11 jre/ -> /usr/lib/jvm/jre/java/jre
```

**Comment by rowlandwatkins** [comment]
Ahhh, bit silly of me there - I checked through the CLI, but "ls -la" didn't show anything!

Many thanks for helping clear that up :)

Incidentally, is it difficult to use Oracle's JDK on OSv?

**Comment by lgoldstein** [comment]
* The "ls -la" that you see is a *special* Java-based CLI that I wrote
* Using Oracle's JDK instead of OpenJDK is trivial:

1. Install the Oracle JDK on your build machine
2. Run the build script with _jdkbase=/path/to/to/oracle/jdk_ argument and voila...

**Comment by rowlandwatkins** [comment]
@lgoldstein Many thanks for the tips - all works as expected :)
