### ISSUE TITLE
Wiki Debian: Debian and related distributions can't use su

### ISSUE THREAD

**Issue by cosmo0920** [cloudius-systems/osv#640]
https://github.com/cloudius-systems/osv/wiki/Building-OSv-on-Debian-stable

Ordinary Debian and Ubuntu users does not set root password.
They get administer privileges with `sudo`.

e.g.)

wrong: `su -c "apt-get update"`
correct: `sudo apt-get update`

**Comment by nyh** [comment]
It is a wiki, writeable by anyone (unless I'm missing something?) so you
can make this change yourself.

**Comment by cosmo0920** [comment]
Thanks for your suggestion.

> It is a wiki, writeable by anyone (unless I'm missing something?) so you
> can make this change yourself.

I didn't noticed that github wiki is writable by anybody.
I've changed them correct format.

This issue is fixed!
