### ISSUE TITLE
Capstan and EC2

### ISSUE THREAD

**Issue by yieldone** [cloudius-systems/osv#642]
Hi folks,

Am I correct in that Capstan won't run on EC2? It looks like KVM can't really fly at all without /dev/kvm being available using nested virtualisation, which EC2 doesn't support.

I suppose another approach would be to simply generate my app images using Makefiles against a base image, which might well be faster.

Cheers,

Rowland

**Comment by dorlaor** [comment]
On Mon, Jul 13, 2015 at 6:08 PM, yieldone <notifications@github.com> wrote:

> Hi folks,
>
> Am I correct in that Capstan won't run on EC2? It looks like KVM can't
> really fly at all without /dev/kvm being available using nested
> virtualisation, which EC2 doesn't support.
>

You're correct in general. You could run Capstan with qemu full emulation
but it will be slow.
In order to create an image we actually boot a VM and stream the content of
the files to it in order to init it's ZFS FS. In the past we used to
generate ZFS using the host and fuse but since it required root and wasn't
trivial we decided to fall back to a simple DIY mode using our
very own OSv

**Comment by yieldone** [comment]
@dorlaor Many thanks for the confirmation, at least I won't go chasing down that rabbit hole.

Fortunately, it looks like scripts/run.py can safely run qemu full emulation, which surely means capstan can too. So I hacked around Capstan a little bit and found that in hypervisor/qemu/qemu.go that we can remove the need for KVM by removing the following:

[[[
if runtime.GOOS == "linux" {
	args = append(args, "-enable-kvm", "-cpu", "host,+x2apic")
}
]]]

I'm assuming this won't break other things, but all I really want is to build images, not run them (yet). This seems a reasonable tradeoff compared to building the image locally then having to upload a 300MB+ image, which takes several minutes and eats into the Jenkins build time.

I'll take a look to see how it might be possible to pass capstan an argument not to use KVM in such circumstances - would this useful?

Cheers,

Rowland

**Comment by dorlaor** [comment]
On Tue, Jul 14, 2015 at 1:08 PM, yieldone <notifications@github.com> wrote:

> @dorlaor <https://github.com/dorlaor> Many thanks for the confirmation,
> at least I won't go chasing down that rabbit hole.
>
> Fortunately, it looks like scripts/run.py can safely run qemu full
> emulation, which surely means capstan can too. So I hacked around Capstan a
> little bit and found that in hypervisor/qemu/qemu.go that we can remove the
> need for KVM by removing the following:
>
> [[[
> if runtime.GOOS == "linux" {
> args = append(args, "-enable-kvm", "-cpu", "host,+x2apic")
> }
> ]]]
>

I agree it worth adding, worth to test how much take will it take qemu to
build the image.
@penberg will be able to merge it.

**Comment by penberg** [comment]
@yieldone Yup, it would certainly be useful.

**Comment by ilackarms** [comment]
do the disk images produced by `capstan` have the capability of running on EC2? i.e. do they contain required  drivers for running on Xen hypervisor? I tried building a qemu image with capstan, converted it to raw format, `dd`ed it to an EC2 EBS volume, and then created a bootable AMI from that. It appears the instance was able to boot, but did not run my application, although maybe i am misinterpreting the logs: 

```
Xen Minimal OS!
  start_info: 0xae2000(VA)
    nr_pages: 0x26700
  shared_inf: 0x7c9d3000(MA)
     pt_base: 0xae5000(VA)
nr_pt_frames: 0x9
    mfn_list: 0x9ae000(VA)
   mod_start: 0x0(VA)
     mod_len: 0
       flags: 0x0
    cmd_line: root=/dev/sda1 ro 4
  stack:      0x96d840-0x98d840
MM: Init
      _text: 0x0(VA)
     _etext: 0x7dc7d(VA)
   _erodata: 0x9a000(VA)
     _edata: 0x9fce0(VA)
stack start: 0x96d840(VA)
       _end: 0x9ade40(VA)
  start_pfn: af1
    max_pfn: 26700
Mapping memory range 0xc00000 - 0x26700000
setting 0x0-0x9a000 readonly
skipped 0x1000
MM: Initialise page allocator for c1f000(c1f000)-26700000(26700000)
MM: done
Demand map pfns at 26701000-2026701000.
Heap resides at 2026702000-4026702000.
Initialising timer interface
Initialising console ... done.
gnttab_table mapped at 0x26701000.
Initialising scheduler
Thread "Idle": pointer: 0x2026702050, stack: 0x26660000
Thread "xenstore": pointer: 0x2026702800, stack: 0x26670000
xenbus initialised on irq 1 mfn 0xcdb8d6
Thread "shutdown": pointer: 0x2026702fb0, stack: 0x26680000
Dummy main: start_info=0x98d940
Thread "main": pointer: 0x2026703760, stack: 0x26690000
"main" "root=/dev/sda1" "ro" "4" 
vbd 2049 is hd0
******************* BLKFRONT for device/vbd/2049 **********


backend at /local/domain/0/backend/vbd/11248/2049
Failed to read /local/domain/0/backend/vbd/11248/2049/feature-barrier.
Failed to read /local/domain/0/backend/vbd/11248/2049/feature-flush-cache.
25165824 sectors of 512 bytes
**************************
[H[J

    GNU GRUB  version 0.97  (629760K lower / 0K upper memory)



       [ Minimal BASH-like line editing is supported.   For

         the   first   word,  TAB  lists  possible  command

         completions.  Anywhere else TAB lists the possible

         completions of a device/filename. ]




grubdom>        
```

**Comment by wkozaczuk** [comment]
Is it describing any specific bug/issue? Should this discussion be moved to google groups? Shall we close it?

**Comment by nyh** [comment]
I think the issue started pretty specific: While our run.py script can run either with or without KVM (with KVM not available on virtual machines which don't support nested virtualization - shame on them!), Capstan fails when it can't run KVM. And the request was to fix it so it falls back to running Qemu **without KVM**. I don't know if it's still an existing issue.
It looks like at the end the question mutated into something else - whether OSv images can run on EC2. I think they can, and that is not an issue. If there are bugs in that area, they should be opened as separate issues.

**Comment by nyh** [comment]
But, this means this issue is Capstan-specific and belongs on the Capstan bug tracker. So I'm closing it here, and leaving it to the Capstan developers (@wkozaczuk and previously @penberg @justinc1 @gberginc ) to decide if it should be reopened in the Capstan bug tracker.
