### ISSUE TITLE
S3 Bucket generated name is not allowed 

### ISSUE THREAD

**Issue by PerGon** [cloudius-systems/osv#647]
Hi,

When running the command:

```
./scripts/release-ec2.sh --modules-list tomcat --region eu-west-1 --zone eu-west-1a
```

my S3 bucket name is generated and looks like this:

```
osv-v0.22-9-g0c87699-ubuntu-at-ip-172-31-33-241-2015-08-01T13-52-18Z
```

The script terminates with an error

```

Adding /usr/lib/jvm/java/jre/lib/zi/Antarctica/Palmer...
>>> Creating bucket osv-v0.22-9-g0c87699-ubuntu-at-ip-172-31-33-241-2015-08-01T13-52-18Z

A client error (IllegalLocationConstraintException) occurred when calling the CreateBucket operation: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.
>>> [2015-08-01T14-06-09Z] ERROR: Failed to create S3 bucket.
```

According to the S3 bucket documentation (http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html) there are some restrictions for bucket names. One of them being:

> no more than 63 characters long

1st Issue:
My bucket name is too long.

2nd Issue:
The period also seemed to mess with the bucket creating:

```
ubuntu@ip-172-31-33-241:~/test$ aws s3api create-bucket --bucket osv-v0.22

A client error (IllegalLocationConstraintException) occurred when calling the CreateBucket operation: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to.
```

```
ubuntu@ip-172-31-33-241:~/test$ aws s3api create-bucket --bucket osv-v0-22
{
    "Location": "/osv-v0-22"
}
```

My workaround was to change this line to something else. https://github.com/cloudius-systems/osv/blob/master/scripts/release-ec2.sh#L142

**Comment by wkozaczuk** [comment]
I do not think we ever going to be using this script. Shall we close it?

**Comment by wkozaczuk** [comment]
Closing the issue due to lack of interest in maintaining this script. I do not think we will release anything to S3 anytime soon.
