### ISSUE TITLE
Support building with AWS instance credentials

### ISSUE THREAD

**Issue by copumpkin** [cloudius-systems/osv#652]
It looks like many of the EC2-related scripts expect AWS credentials to be provided via environment variables. This hinders running the build itself on an AWS instance that has dynamically temporary instance credentials (or on developer machines that emulate them).

Luckily, all standard AWS tools know how to go look at http://169.254.169.254 to get the dynamic instance credentials, but only if you don't explicitly pass them other credentials. My hypothesis is that if the OSv scripts stopped passing credentials around explicitly (e.g., https://github.com/cloudius-systems/osv/blob/master/scripts/release-ec2.sh#L144), everything would just work. The AWS tools would look at environment variables if present, like what happens right now, but they would also work with instance credentials, or with credentials specified in ~/.aws/credentials.

**Comment by nyh** [comment]
If you could test your hypothesis, and send a patch for this issue, it would be very welcome.

**Comment by wkozaczuk** [comment]
I do not think we maintain these EC2 scripts. And due to limited resources I suggest we close this issue.
