### ISSUE TITLE
Error resolving "stdout" in PIE - in Fedora 22

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#654]
This bug was discovered by bhuztez@gmail.com

When OSv is compiled under Fedora 22 (gcc 5.1.1), if the executable is a PIE and refers to "stdout", this resolves to a null pointer instead of the right address. If the executable is compiled as a shared-library, we do not have this problem, and stdout is a valid (non-zero) pointer!

This can be demonstrated by adding a
```c++
printf("%p\n", stdout);
```
to apps/native-example/hello.c. This program is usually compiled as PIE and will exhibit this bug (print 0). If we modify apps/native-example/Makefile to compile it instead as shared object (-fpic, -shared), the code correctly prints a non-zero pointer.

It's worth noting that a "printf()" does work - it's not that stdout is trashed, it's more that symbol resolution is trashed somehow.

**Comment by nyh** [comment]
In this case, it turns out that gcc 5.1.1 (on Fedora 22) compiles the program (hello) differently from 4.9.2 (Fedora 21):

If we run
```sh
nm -D hello | grep stdout
```

We expect to see that "stdout" is undefined, and will be resolved from OSv:
```
                 U stdout
```

This is indeed what we get when compiling hello.c on gcc 4.9.2 (Fedora 21), as either shared-object or PIE.

But on gcc 5.1.1. (Fedora 22), we only get this as expected when compiling as shared object. When compiling as PIE with -pie -fpie - we see instead
```
00000000000201048 B stdout
```

I.e., stdout is in the object's BSS, which explains why it thinks it has the value of 0!

Even more strangely, if we use "-pie -fpic" - i.e., compile each object with "-fpic" instead of "-fpie" but like with "-pie" - we get a valid PIE but without this bug, which seems to work well.

This observation gives us an easy workaround for this bug: change the app's Makefile to compile with "-fpic" instead of "-fpie" (and continue linking with "-pie"), - or switch from PIE to shared object (-fpic, -shared). But I'm still very curious why this change occured. Is this a gcc bug, or a feature? What reason could such a "feature" have?

But it's important noting that the seemingly-broken PIE, with the "B stdout", is perhaps not really broken because does work correctly on Linux - It prints a non-zero value for stdout! So apparently Linux's dynamic linker has a different resolution order than we do here - it finds the shared library's (glibc) copy of "stdout" before the PIE's own copy in its BSS, while we find the PIE's own copy first. Perhaps this resolution order is something which we need to fix to get this sort of executables working as they do on Linux?

**Comment by nyh** [comment]
I summarized the gcc changed in https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67469, but it is very likely gcc won't be "fixed" to go back its old behavior here, and we'll need to accept these new gcc executables.

But how do we fix it? By changing symbol resolution order so "stdout" is found in the library (the OSv kernel) before it is found in the executable itself? Is this even the right thing to do? See commit 82513d413502457c8280c6582876653527b9dd1d about problems we've had in the past when the kernel's symbols overrided the executable's symbols...

**Comment by nyh** [comment]
The gcc change was deliberate - it places all globals in the executable and uses "copy relocation" to allow them to be overriden by the library (in our case, OSv) to slightly improve performance of the common case where a PIE accesses globals from itself, not from the library. It is explained in this gcc commit:
https://gnu.googlesource.com/gcc/+/130f233477ed03a7bdffb832e7eb9f0a366e0d6b

**Comment by copumpkin** [comment]
According to the follow-up in there, this change was introduced intentionally by [this commit](https://gnu.googlesource.com/gcc/+/130f233477ed03a7bdffb832e7eb9f0a366e0d6b)

**Comment by nyh** [comment]
@bhuztez added a printout to our copy-relocation handling code in arch-elf.cc:
```
case R_X86_64_COPY: {
        symbol_module sm = symbol(sym);
        memcpy(addr, sm.relocated_addr(), sm.size());
```

And noticed the memcpy copies the same address to itself. I think what is happening is that our dynamic linking of the object is looking everywhere - including the object itself - for the symbol, and it probably should exclude the current object in the search (I think the whole point of the copy relocation is to copy from a different object).

**Comment by nyh** [comment]
By the way, while "nm -D" doesn't show anything special about "stdout", the copy relocation can be seen in "objdump -R" (showing dynamic relocations):
```
0000000000201048 R_X86_64_COPY     stdout
```

**Comment by nyh** [comment]
@bhuztez, I just sent a patch for this issue to the mailing list. Can you please test? Thanks.

**Comment by bhuztez** [comment]
@nyh yes, it's OK now.
