### ISSUE TITLE
OSv build fails on Arch Linux

### ISSUE THREAD

**Issue by diegoamc** [cloudius-systems/osv#655]
Hello,

I tried to build OSv on Arch Linux following the steps on the README file. Specifically, I ran the commands on the `Arch Linux` section, updated the git submodules and executed the build script.
This is what I get:

```
Building into build/release.x64
  GEN gen/include/osv/version.h
Using image config: /home/diego/Documents/osv/images/default.py
Importing /home/diego/Documents/osv/modules/cli/module.py
Importing /home/diego/Documents/osv/modules/lua/module.py
Importing /home/diego/Documents/osv/modules/ncurses/module.py
Importing /home/diego/Documents/osv/modules/libedit/module.py
Importing /home/diego/Documents/osv/modules/httpserver/module.py
Importing /home/diego/Documents/osv/modules/openssl/module.py
No module.py in /home/diego/Documents/osv/modules/libz
No module.py in /home/diego/Documents/osv/modules/libtools
No module.py in /home/diego/Documents/osv/modules/libyaml
Modules:
  lua
  ncurses
  libedit
  libz
  openssl
  libtools
  libyaml
  httpserver.*
  cli
make: Nothing to be done for 'module'.
make: Nothing to be done for 'module'.
make: Nothing to be done for 'module'.
 
make[1]: Entering directory '/home/diego/Documents/osv/modules/httpserver/osv-gui'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/diego/Documents/osv/modules/httpserver/osv-gui'
make: Nothing to be done for 'module'.
Preparing usr.manifest
Appending /home/diego/Documents/osv/modules/libz/usr.manifest to usr.manifest
Appending /home/diego/Documents/osv/modules/openssl/usr.manifest to usr.manifest
Appending /home/diego/Documents/osv/modules/libtools/usr.manifest to usr.manifest
Appending /home/diego/Documents/osv/modules/libyaml/usr.manifest to usr.manifest
Preparing bootfs.manifest
Saving command line to /home/diego/Documents/osv/build/release.x64/cmdline
WARNING: Image format was not specified for 'bare.raw' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
Traceback (most recent call last):
  File "/home/diego/Documents/osv/scripts/mkzfs.py", line 30, in <module>
    manifest = upload_manifest.read_manifest(options.manifest)
  File "/home/diego/Documents/osv/scripts/upload_manifest.py", line 65, in read_manifest
    components = string.split(line, ": ", 2)
AttributeError: 'module' object has no attribute 'split'
./scripts/build failed: $SRC/scripts/mkzfs.py -o usr.img -d usr.img.d -m bootfs.manifest
```

What could be the problem?

**Comment by nyh** [comment]
Looks like a bug in scripts/upload_manifest.py. I'm guessing that in your system, "python" defaults to python3 and not python2 like most other systems - can you please verify (what does "python --version" return)?

Perhaps you can help me figure out what is the alternative to string.split(line, ": ", 2) - perhaps calling line.split(...)? Is there a way to do this which will work on both Python 2 and 3?

**Comment by diegoamc** [comment]
Yes, in my system python defaults to python3.

I'm no expert in python, but I think that `line.split(": ", 2)` should produce the desired outcome both in Python 2 and 3.

**Comment by diegoamc** [comment]
@nyh, just with that modification I could build and run OSv. I've created a patch but I'm having trouble configuring gmail to let me log in using git. Couldn't I use the browser to send it?

Also, when I tried to run OSv with external networking I get another error. Should I create a new issue for that?

**Comment by nyh** [comment]
I have just sent a patch for this to the osv-dev mailing list. Please test it (although I tested it myself on both python 2 and 3, and it seems to work well).

**Comment by nyh** [comment]
Nadav Har'El
nyh@scylladb.com <nyh@cloudius-systems.com>

On Tue, Sep 29, 2015 at 6:45 PM, Diego de Araújo Martinez Camarinha <
notifications@github.com> wrote:

> Also, when I tried to run OSv with external networking I get another
> error. Should I create a new issue for that?


Yes, if it's not related to this issue, please don't discuss it in the same
issue.

You can open a new issue, or if you're not sure if it's a real bug, you can
discuss it on the mailing list first.

**Comment by diegoamc** [comment]
Ok, thanks!
