### ISSUE TITLE
missing __asprintf_chk

### ISSUE THREAD

**Issue by justinc1** [cloudius-systems/osv#657]
I'm trying to load minimal OpenMPI program, and loader complains about __asprintf_chk.
```
/usr/lib/libopen-pal.so.13: failed looking up symbol __asprintf_chk
```
For now, I just hardcoded next to main():
```
#include <stdarg.h>
int __asprintf_chk(char **strp, int flags, const char *fmt, ...) {
  int ret;
  va_list myargs;
  va_start(myargs, fmt);
  ret = __vasprintf_chk(strp, flags, fmt, myargs);
  va_end(myargs);
  return ret;
}
```
PS:
It might be possible that some compiler switch during OpenMPI build would replace __asprintf_chk with variant already in OSv (the _chk part makes it sound like there is some extra checking inside, like sort of debug variant). But I have no idea if such switch exists.

**Comment by nyh** [comment]
These *_chk variants are used when code is compiled with -DFORTIFY_SOURCE=2 (or maybe even 1). On some Linux distros, this flag is turned on by default, but you can disable it on code you're compiling if you wish. But often, when you're using a pre-compiled shared library (e.g., which you copied from your Linux distribution) you get one already compiled with fortify source, and can't disable it without recompiling the library (which you probably don't want to do).

So the best solution is just to implement all those _chk functions - even a silly implementation which doesn't check anything is better than a crash. And we've been doing this, as I guess you've seen. We just didn't get around to all those functions.

Can you please sent a patch to implement this missing __asprintf_check in, for example, libc/stdio/__vfprintf_chk.c, where many of its friends already live?

Thanks!
