### ISSUE TITLE
CFLAGS -mno-red-zone need added 

### ISSUE THREAD

**Issue by saneee** [cloudius-systems/osv#668]
according http://forum.osdev.org/viewtopic.php?t=21720

**Comment by nyh** [comment]
Can you please explain what you are proposing?

Keep in mind that OSv wants to run unmodified, already-compiled, Linux code. True some code will need recompilation for different reasons (e.g., to re-compile a regular executable as a PIE), but a lot of other code - especially shared libraries - do not need any recompilation. This is how we run Java, for example - we can take a pre-compiled libjvm.so.

So we cannot force people to recompile shared libraries with "-mno-red-zone". It wouldn't be very helpful if OSv itself did not use the red zone but the application code did use it - so we just need to support the red zone correctly in OSv - and we do, as far as I know (you can search for "red zone" in our git log to find the relevant patches that fixed it).

In fact, before we correctly handled the red zone, we did require "-mno-red-zone", and after the bugs were fixed the compilation flag was removed, in commit 5879aeb3d1e83a3ac91beb7d060ffd683c5229d5. This was more than two years ago.

So I'm closing this issue now, but please reopen (with more explanations) if I misunderstood your intention.

**Comment by saneee** [comment]
When interrupts occur in ring 0, stack segment will not be changed. So the cpu use the same stack to push eip,eflag etc. So the red zone problem is not about  osv, but cpu. Can we change cpu?
Not only osv need -mno-red-zone, but also all apps run in ring0.

**Comment by avikivity** [comment]
OSv uses Interrupt Stack Tables (IST) so interrupts do not overwrite the red zone.

**Comment by saneee** [comment]
Thanks
