### ISSUE TITLE
Capstan not cleaning up or not forcing vbox cleanup?

### ISSUE THREAD

**Issue by gaffo** [cloudius-systems/osv#673]
Trying to use virtualbox builds on mac but I'm getting stuff about it already existing?

➜  ws-uk  capstan run -v -p vbox
Created instance: ws-uk

VBoxManage: error: Machine settings file '/Users/gaffo/.capstan/instances/vbox/ws-uk/ws-uk.vbox' already exists
VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component MachineWrap, interface IMachine, callee nsISupports
VBoxManage: error: Context: "CreateMachine(bstrSettingsFile.raw(), bstrName.raw(), ComSafeArrayAsInParam(groups), bstrOsTypeId.raw(), createFlags.raw(), machine.asOutParam())" at line 272 of file VBoxManageMisc.cpp

➜  ws-uk  capstan build -v -p vbox
Building ws-uk...
OSv v0.23
eth0: 192.168.122.15
Waiting for connection from host...

(process:22267): GLib-WARNING **: gmem.c:482: custom memory allocation vtable not supported
Uploading files...
hello.so  --> /tools/hello.so
Adding /tools/hello.so...
➜  ws-uk  capstan run -v -p vbox
Created instance: ws-uk

VBoxManage: error: Machine settings file '/Users/gaffo/.capstan/instances/vbox/ws-uk/ws-uk.vbox' already exists
VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component MachineWrap, interface IMachine, callee nsISupports
VBoxManage: error: Context: "CreateMachine(bstrSettingsFile.raw(), bstrName.raw(), ComSafeArrayAsInParam(groups), bstrOsTypeId.raw(), createFlags.raw(), machine.asOutParam())" at line 272 of file VBoxManageMisc.cpp

**Comment by gaffo** [comment]
Seems to happen when doing the same box name on both qemu && vbox on a mac?

**Comment by gaffo** [comment]
deleting the ~/.capstan directory and re-doing with just vbox works?

**Comment by nyh** [comment]
This issue belongs in the separate Capstan bug tracker, not in the OSv one. If you move it there, please close this one. Thanks.

**Comment by wkozaczuk** [comment]
Can we close it?
