### ISSUE TITLE
"python" interpreter in scripts

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#675]
According to https://www.python.org/dev/peps/pep-0394/, the "python" command should always point to python version 2, and "python3" should be used to run python version 3. This PEP, if adopted by distributions,  implies that new installations which don't have python version 2 installed, and only installed Python 3, will not have a "python" command at all. This will break some of our scripts, e.g., scripts/run.py, which try to run "python".

Fedora 23's release notes already say that: https://docs.fedoraproject.org/en-US/Fedora/23/html/Release_Notes/sect-Release_Notes-Changes_for_Developers.html
"The python executable will not be installed by default on many Fedora 23 systems. The Python project, in PEP 0394, recommends that /usr/bin/python remain associated with Python 2, which may not be installed. Users with scripts or similar that require /usr/bin/python can install it, or use the new /usr/bin/python3 interpreter."

Of course one easy solution is to force users to install also python 2 anyway (it's one "yum" command away), but this is silly, considering that our scripts also work well in python 3....

Perhaps we should assume that all modern distributions already have the command "python3" installed, and switch our scripts to call that instead of "python"?

**Comment by wkozaczuk** [comment]
@nyh,

Given we have converted most of our python scripts to work with Python 3 (and python 2 becomes by default (unless you install it) unavailable) and/or made some of the scripts work with both 2 and 3, is this issue still something we need to address?

(Yeah the issue was written 5 years ago :-))

**Comment by nyh** [comment]
I'm closing this issue. Five years ago, it was starting to appear like the "python" command was about to disappear and users will need to run "python3", but this has not actually happened to the best of my knowledge... I think from now on, this is actually **less likely** to be a problem than it was - today, new distributions will likely have just Python3 by default and are very likely to link "python" to "python3".

We still have a bunch of scripts, including loader.py, silentant.py,  zfs_mount.py, ec2-*.py, test-ruby.py, tester.py - which use "python" instead of "python3". The goal of this issue was to convert all of them to call "python3" instead of "python". I don't think we need to bother with this change, so I'm closing the issue. Feel free to reopen if you think this is still a problem.
