### ISSUE TITLE
unimplemented getrlimit resource

### ISSUE THREAD

**Issue by justinc1** [cloudius-systems/osv#676]
When trynig to run OpenFOAM with OpenMPI, I get:
```
OSv v0.24
eth0: 192.168.122.219
/# 
Aborted

[backtrace]
0x0000000000442c3a <getrlimit+170>
0x000010000a51645d <opal_util_init_sys_limits+157>
0x00000000fffffffe <???+-2>
```

The kprintf from libc/libc.cc seems missing, but comparing that file with https://github.com/open-mpi/ompi-release/blob/v1.10/opal/util/sys_limits.c, I see only RLIMIT_FSIZE missing. I guess it would be enough to only return 0?

**Comment by nyh** [comment]
Hi Justin, to see the invisible kprintf, run OSv with "verbose" mode - i.e., "run.py -V" or equivalently pass the "--verbose" option to the kernel.

**Comment by justinc1** [comment]
Prints 'getrlimit: resource 1 not supported' then, and that is RLIMIT_FSIZE, musl/include/sys/resource.h.
I just added it to getrlimit(), trivial patch send to osv-dev list.
