### ISSUE TITLE
Inconsistent mix of build_env = host / external

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#687]
In usr.manifest.skel we have:

/usr/lib/libgcc_s.so.1: %(gccbase)s/lib64/libgcc_s.so.1
/usr/lib/&/libboost_filesystem.so.1.55.0: %(miscbase)s/usr/lib64/&
/usr/lib/&/libboost_regex.so.1.55.0: %(miscbase)s/usr/lib64/&

However,
1. Taking libgcc_s.so.1 from %(gccbase), i.e, external/, is only the right thing to do for build_env=external. For build_env=host (the default), we should take the system's libgcc_s.so.1. See the code that sets the "libgcc.a" variable, and we should find libgcc_s.so.1 similarly.
2. If boost_env=host, we take boost libraries and header files from the build system, so we shouldn't take these two boost libraries from external...By the way, I don't know why we're adding them at all - perhaps they are use in one of our tools like cpiod.so and friends?

**Comment by wkozaczuk** [comment]
@nyh, 

Given that "external" does not exist anymore in `Makefile`, `module.py` files as I submitted many patches to eliminate it from everywhere (I think) and given that #743 is closed, shall we close this one as well?

**Comment by wkozaczuk** [comment]
@nyh Closing for the reasons explained above. I hope you agree this can be closed.

**Comment by nyh** [comment]
Indeed, the offending lines don't exist in usr.manifest.skel any more, so it's good you closed this issue.
