### ISSUE TITLE
can not find **start-cassandra**, how to run the newly build osv image?

### ISSUE THREAD

**Issue by pushpendrachaturvedi** [cloudius-systems/osv#692]
i am building an osv-cassandra image on ubuntu host according to 

https://github.com/cloudius-systems/osv and
https://github.com/cloudius-systems/osv/wiki/Cassandra-quickstart-on-OSv-with-KVM

commands i ran

$git clone https://github.com/cloudius-systems/osv.git
$cd osv
$scripts/setup.py
$git submodule update --init --recursive
$make image=cassandra

as per 2nd l8ink for quick start on kvm

i am unable to find apps/cassandra/start-cassandra directory/file

i can see *cassandra.yaml* file inside **/apps/cassandra/** directory but not **start-cassandra** file

**How should i start cassandra?**

**how should i start/run the image?**

@tzach please help

**Comment by nyh** [comment]
Please use the bug tracker for specific bugs, not general questions and discussions - and use the osv-dev mailing list for the latter.

I'll nevertheless try to answer your question:

After ```make image=cassandra```, when the created image (build/last/usr.img) boots, it already runs Cassandra appropriately, and it doesn't use a script called "start-cassandra" for that.
Rather, the python code in apps/cassandra/module.py builds an elaborate Java command line which you can see in /build/last/cmdline - and that gets run when the image boots.

You can run this image locally with the script "scripts/run.py".
