### ISSUE TITLE
fpathconf() function is missing

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#703]
We already have a stub for pathconf() (apparently this was enough for some program which needed this...), but fpathconf() is missing, as reported in issue #701. 

There is one implementation in musl which might be relevant. Another option is to stub it (like in pathconf()) but I don't know if this is good enough for the use case of #701.

In any case, once we have fpathconf(), pathconf() should call it instead of trying to do its own thing. We can simple include in our Makefile Musl's trivial pathconf.c, which is the trivial:
```c++
#include <unistd.h>
long pathconf(const char *path, int name)
{
        return fpathconf(-1, name);
}
```

**Comment by joelthompson** [comment]
I verified that my use case works fine with a stubbed fpathconf, so I've submitted a patch to the mailing list to stub out fpathconf and altered pathconf to use that.
