### ISSUE TITLE
nfs client crash

### ISSUE THREAD

**Issue by justinc1** [cloudius-systems/osv#705]
I'm trying to connect to NFS server on my desktop (kernel server, ubuntu 15.10).
On server
```
cat /etc/exports
/fff       172.16.0.0/16(rw,sync,no_subtree_check,insecure)
```

On test host:
```
./scripts/run.py -d -V -n -v --novnc -b br0 -e '/tools/mount-nfs.so nfs://172.16.93.112//fff?uid=0 /fff; /cli/cli.so'

VFS: mounting nfs at /fff
/# ls /fff
page fault outside application, addr: 0x0000000000000000
[registers]
RIP: 0x00000000006e6030 <nfs_readdir+0>
RFL: 0x0000000000010246  CS:  0x0000000000000008  SS: 0x0000000000000010
RAX: 0xffffa00005556f80  RBX: 0x00002000002fee90  RCX: 0xffff80000552cee0  RDX: 0x0000000000000000
RSI: 0x0000000000000000  RDI: 0xffffa00005556f80  RBP: 0x00002000002fead0  R8:  0xffffa0000553e820
R9:  0xffffa0000552cef8  R10: 0x0000000000000042  R11: 0x0000000080000070  R12: 0x00002000002fecd0
R13: 0xffffa0000552cef8  R14: 0x0000000000000042  R15: 0x0000000080000070  RSP: 0x00002000002fea88
Aborted

[backtrace]
0x000000000022bc6d <abort(char const*, ...)+249>
0x00000000003c6605 <???+3958277>
0x00000000003c67a2 <mmu::vm_fault(unsigned long, exception_frame*)+350>
0x000000000048ba65 <page_fault+310>
0x000000000048a8f6 <???+4761846>
0x000000000065fd32 <sys_readdir+138>
0x00000000006302ae <readdir64_r+106>
0x0000100000c9b495 <httpserver::api::file::get_file_handler::list_directory(std::string const&, http::server::request const&, http::server::reply&)+1317>
0x00000000000e0000 <???+917504>
```

**Comment by benoit-canet** [comment]
I reproduced the bug on my machine now I will proceed to debug it.

**Comment by benoit-canet** [comment]
I didn't opened an nfs directory handle for / so readdir segfault on a nullptr handle.

**Comment by benoit-canet** [comment]
patch sent

**Comment by justinc1** [comment]
I can list directory now, but cat-ing file fails:
```
/# ls /fff
asdf.txt
/# cat /fff/asdf.txt
page fault outside application, addr: 0x0000000000000000
[registers]
RIP: 0x00000000006dd6d4 <???+7198420>
RFL: 0x0000000000010206  CS:  0x0000000000000008  SS:  0x0000000000000010
RAX: 0xffffa0000561dc00  RBX: 0x0000000000000000  RCX: 0x00002000002fd830  RDX: 0x00000000006e7110
RSI: 0x0000000000000000  RDI: 0x0000000000000000  RBP: 0x00002000002fd830  R8:  0xffffa000056140e0
R9:  0xffffa00004f4c298  R10: 0x0000000000000042  R11: 0x0000000080000078  R12: 0x00000000006e7110
R13: 0xffffa00004f4c298  R14: 0x0000000000000042  R15: 0x0000000080000078  RSP: 0x00002000002fd800
Aborted

[backtrace]
0x000000000022bc6d <abort(char const*, ...)+249>
0x00000000003c6605 <???+3958277>
0x00000000003c67a2 <mmu::vm_fault(unsigned long, exception_frame*)+350>
0x000000000048ba65 <page_fault+310>
0x000000000048a8f6 <???+4761846>
0xffffa00005617bbf <???+90274751>

```

**Comment by benoit-canet** [comment]
Please try cat on a non nfs file.
I tried mkdir and it does not workk on non nfs path either.

**Comment by nyh** [comment]
On Thu, Jan 14, 2016 at 2:52 PM, Benoît Canet <notifications@github.com>
wrote:

> Please try cat on a non nfs file.
> I tried mkdir and it does not workk on non nfs path either.
>

mkdir through the CLI apparently has a known bug:
https://github.com/cloudius-systems/osv/issues/691

I am not aware of a "cat" bug, but it can be... You can get a more
informational stack trace from gdb, maybe we can figure out where the
problem comes from.

**Comment by benoit-canet** [comment]
look like cat is working on regular file.

I am digging

**Comment by benoit-canet** [comment]
Hi Justin,

This error is a permission denied error returned by the NFS server that
got badly handled by OSv.

I will try to find the right server flags.

Best regards

Benoît

**Comment by benoit-canet** [comment]
I will tcpdump to get a clue of what is happening.

**Comment by benoit-canet** [comment]
Hi Justin,

Try adding no_root_squash to your server configuration.

From man export:

     root_squash
             Map requests from uid/gid 0 to the anonymous uid/gid. Note
that this does not apply to any other uids or gids that might be equally
sensitive, such as user bin  or  group
             staff.

      no_root_squash
             Turn off root squashing. This option is mainly useful for
diskless clients.

      all_squash
             Map  all  uids and gids to the anonymous user. Useful for
NFS-exported public FTP directories, news spool directories, etc. The
opposite option is no_all_squash, which is
             the default setting.

Best regards

Benoît

**Comment by benoit-canet** [comment]
This definitively fix the issue on my setup.

There is still a gross error code mishlanding in the OSv VFS layer because
it get EACCESS
and end up crashing in a weird way.

I will dig this.

**Comment by benoit-canet** [comment]
The httpserver code responsible for this is weird.


void file_interaction_handler::read(const string& file,
                                   const http::server::request& req,
http::server::reply& rep)
{
   ifstream is(file, ios::in | ios::binary);
   if (!is) {
       throw not_found_exception("Page not found");
   }

I am not sure EACCESS should be casted into not_found_exception.

**Comment by justinc1** [comment]
Just an additional corner case (I guess).
With /etc/exports:
```
/export                                       192.168.122.0/24(fsid=0,rw,sync,no_subtree_check,no_root_squash,insecure,crossmnt,sec=sys)
/export/home/justin_cinkelj/devel/mikelangelo 192.168.122.0/24(rw,sync,no_subtree_check,no_root_squash,insecure,sec=sys)
```

Cmd
```
sudo ./scripts/run.py -d -V -n -v --novnc -b virbr0 -e '/tools/mount-nfs.so nfs://192.168.122.1/export/home/justin_cinkelj/devel/mikelangelo?uid=0 /fff; /cli/cli.so'
VFS: mounting nfs at /fff

/# ls /fff
page fault outside application, addr: 0x0000000000000000
[registers]
RIP: 0x000000000067ef0d <strlen+81>
RFL: 0x0000000000010246  CS:  0x0000000000000008  SS:  0x0000000000000010
RAX: 0x0000000000000010  RBX: 0x00002000002fecd0  RCX: 0x0000000000000200  RDX: 0x00002000002fe900
RSI: 0x00002000002fe8b0  RDI: 0x0000000000000010  RBP: 0x00002000002fe890  R8:  0x00002000002fe8a0
R9:  0x0000000000000000  R10: 0x0000000000000042  R11: 0x0000000080000070  R12: 0x00002000002febd0
R13: 0x0000000000000000  R14: 0x0000000000000042  R15: 0x0000000080000070  RSP: 0x00002000002fe890
Aborted

[backtrace]
0x000000000022bc6d <abort(char const*, ...)+249>
0x00000000003c6605 <???+3958277>
0x00000000003c67a2 <mmu::vm_fault(unsigned long, exception_frame*)+350>
0x000000000048ba65 <page_fault+310>
0x000000000048a8f6 <???+4761846>
0x0000100000c911e7 <httpserver::api::file::get_file_handler::get_file_status(std::string const&, std::string const&, stat const&)+519>
0x00000000000249b0 <???+149936>
```

Here server exports have NFSv4 syntax, so that might be part of problem. With sec=none, I got permission denied (at least ii doesn't crash).

**Comment by benoit-canet** [comment]
I think libnfs is nfs V3 only. So OSv is nfsv3 only.

Best regards

Benoît

**Comment by justinc1** [comment]
That was my understanding too - NFSv3 only (and TCP only?).

But I would expect to not even be able to mount if server is v4. It's a bit confusing if mount succeeds, and then access fails.

**Comment by benoit-canet** [comment]
It thing libnfs is tcp only. Anyway as libnfs author said on github issue
the performance
advantage of NFS UDP over NFS TCP is moot given current cpu are monsters.

The mount operation is delayed to the first io syscall done by a given
thread.

That is mount will do approximatively nothing and the first
read/write/whatever
of a given thread will do a thread_local mount.

**Comment by nyh** [comment]
On Sat, Jan 16, 2016 at 9:04 PM, Benoît Canet <notifications@github.com>
wrote:

>
> The mount operation is delayed to the first io syscall done by a given
> thread.
>
> That is mount will do approximatively nothing and the first
> read/write/whatever
> of a given thread will do a thread_local mount.
>

This is very confusing, as users normally expect a mount to fail if there
is a problem with the whole mountpoint (such as permission denied, protocol
version not supported, etc.), and not wait until the first operation. If
memory serves me right, this is also what happens on "normal" (e.g., Linux
clients).

So I think that if our mount() doesn't actually check anything, we should
change to check something. It could be something as silly as doing stat()
on the filesystem's root and ignoring the result, or something equally
silly, but will allow mount() to return an error.

I suggest we split this into two issues:
1. This issue, about the client crashing (should show an error instead)
2. A new issue, about mount() should fail instead of waiting until the
first operation.

**Comment by benoit-canet** [comment]
On Sat, Jan 16, 2016 at 10:00 PM, nyh <notifications@github.com> wrote:

> On Sat, Jan 16, 2016 at 9:04 PM, Benoît Canet <notifications@github.com>
> wrote:
>
> >
> > The mount operation is delayed to the first io syscall done by a given
> > thread.
> >
> > That is mount will do approximatively nothing and the first
> > read/write/whatever
> > of a given thread will do a thread_local mount.
> >
>
> This is very confusing, as users normally expect a mount to fail if there
> is a problem with the whole mountpoint (such as permission denied, protocol
> version not supported, etc.), and not wait until the first operation. If
> memory serves me right, this is also what happens on "normal" (e.g., Linux
> clients).
>
> So I think that if our mount() doesn't actually check anything, we should
> change to check something. It could be something as silly as doing stat()
> on the filesystem's root and ignoring the result, or something equally
> silly, but will allow mount() to return an error.
>
> I suggest we split this into two issues:
> 1. This issue, about the client crashing (should show an error instead)
>

I tried to install all debuginfo related to OSv on my machine to track down
where this exception is thrown with no luck.


> 2. A new issue, about mount() should fail instead of waiting until the
> first operation.


I will write something doing like that asap.

**Comment by benoit-canet** [comment]
From fs/nfs/nfs_vfsops.cc

/*
* Mount a file system.
*/
static int nfs_op_mount(struct mount *mp, const char *dev, int flags,
                       const void *data)
{
   assert(mp);

   // build a temporary mount context to check the NFS server is alive
   int err_no;
   std::unique_ptr<mount_context> ctx(new mount_context(mp->m_special));

   if (!ctx->is_valid(err_no)) {
       return err_no;
   }

   return 0;
}

The mount command really do mount so I don't understand why it does not
catch the NFSv4 discrepancy.

**Comment by benoit-canet** [comment]
It works fine for me
with: rw,sync,no_subtree_check,no_root_squash,insecure,sec=sys.

Are you sure your guest has an ip in the 192.168.122.0/24 range ?

**Comment by justinc1** [comment]
Closing it as @benoit-canet suggested in #706
