### ISSUE TITLE
Can't use relative paths when running 'java' from CRaSH shell

### ISSUE THREAD

**Issue by tgrabiec** [cloudius-systems/osv#71]
For example:

cd /tests
java -jar bench/bench.jar
RunJava: File not found: bench/bench.jar

java -jar /tests/bench/bench.jar
      28 NanoTime
    1296 context switch
       1 NullPointerException

Perhaps CRaSH 'java' command could pass the shell's cwd to RunJava so that it would be used to resolve non-absolute paths.

**Comment by nyh** [comment]
crash has been removed from the project, so we can close bugs related to it.
