### ISSUE TITLE
debug_ll() should not allocate memory

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#712]
While debugging another bug (see #711) I noticed that while an abort() was trying to print a backtrace, and using debug_ll(), an malloc()/free() was attempted, which crashed.

But debug_ll() is supposed to be *lockless*, and malloc()/free() are not guaranteed to be lockless, so this is asking for trouble.

The problem is that console_multiplexer::write_ll() calls
```c++
        _ldisc->write(str, len,
            [&] (const char *str, size_t len) { drivers_write(str, len); });
        drivers_flush();
```

The lambda parameter to _ldisc->write() is an std::function. Passing an std::function by value allocates and frees memory. BAD IDEA.

So LineDiscipline::write should either take a bare old-style function pointer and a context parameter - instead of an std::function - or we should think of another way to avoid allocation in this code path.

**Comment by justinc1** [comment]
Nadav, maybe patch I just send to osv-dev is what you had in mind when saying to use "old-style function pointer"? Hope it helps.
