### ISSUE TITLE
monitoring-agent failed: connect failed Operation canceled

### ISSUE THREAD

**Issue by bamboojsr** [cloudius-systems/osv#714]
Hi, all
I had get error runing OSv image use KVM/QEMU

env: 
host os:15-Ubuntu
libvirt version:1.2.12

qemu-system-x86_64 -vnc :1 -gdb tcp::1234,server,nowait -m 2G -smp 2   -chardev stdio,mux=on,id=stdio -mon chardev=stdio,mode=readline,default   -device isa-serial,chardev=stdio -drive file=osv-v0.24.qemu.qcow2,if=virtio,cache=unsafe   -netdev tap,id=hn0,script=qemu-ifup.sh,vhost=on -device virtio-net-pci,netdev=hn0,id=nic1   -device virtio-rng-pci -enable-kvm -cpu host,+x2apic
OSv v0.24
eth0: 192.168.122.89
pthread_setcancelstate() stubbed
/# monitoring-agent failed: connect failed Operation canceled

**Comment by nyh** [comment]
@tzach, @dorlaor, do you have any idea what this "monitoring agent" is and why it complains about failing?
Is this "monitoring agent" included on our pre-compiled images? Should we remove it?

**Comment by dorlaor** [comment]
On Sun, Jan 31, 2016 at 7:02 PM, nyh <notifications@github.com> wrote:

> @tzach <https://github.com/tzach>, @dorlaor <https://github.com/dorlaor>,
> do you have any idea what this "monitoring agent" is and why it complains
> about failing?
> Is this "monitoring agent" included on our pre-compiled images? Should we
> remove it?
>
You can remove it, it was supposed to count #boots and similar:

commit 2a8348aecf1de63471c0e5134c5855149fee1dc8
Author: Amnon Heiman <amnon@cloudius-systems.com>
Date:   Wed Nov 5 15:45:06 2014 +0200

    Adding the monitor-agent module

    The monitor agent responsible for gotharing and sending usage
information to a
    remote server.  It is currently upload the information to s3 bucket.

    On boot, the gothered information is saved in a uuid file on a
predefine s3
    bucket.

    The collected data function is fill_data and additional information can
be
    added as needed.

    A copy of the saved data is stored locally. The bucket name and local
file name
    can be overriden from the command line.

**Comment by bamboojsr** [comment]
Thanks,
http://osv.io/osv-stat/  say "Disabling monitoring" method is "monitor-agent:
	enable: false", But i don't know how to configure it undering running OSv in KVM/QEMU use download img. 

So chose make img by README.md, when running usr.img is normal.

During a long times, I want to find the lightweight img in virtualization. I think OSv have future.

**Comment by nyh** [comment]
On Mon, Feb 1, 2016 at 9:12 AM, bamboojsr <notifications@github.com> wrote:

> Thanks,
> http://osv.io/osv-stat/ say "Disabling monitoring" method is
> "monitor-agent:
> enable: false", But i don't know how to configure it undering running OSv
> in KVM/QEMU use download img.
>

These instructions are only usable if you have a "cloud-init" setup, which
you proably don't. So I don't know another convenient way to disable it.

Starting from the next OSv release, this "monitoring" feature will be gone
- so we should probably remove this web page.
