### ISSUE TITLE
A simple regexp creation will crash OSv

### ISSUE THREAD

**Issue by benoit-canet** [cloudius-systems/osv#715]
#include <regexp>
    std::regex re(".*uid=([0-9]+).*");

will crash OSv with:

    [registers]
    RIP: 0x00000000007c3b1c <std::ctype<char>::do_tolower(char*, char const*) const+28>
    RFL: 0x0000000000010286  CS:  0x0000000000000008  SS:  0x0000000000000010
    RAX: 0xffffa000028b15e1  RBX: 0xffffa000028b15e1  RCX: 0x0000000000000000  RDX: 0xffffa000028b15e1
    RSI: 0xffffa000028b15e1  RDI: 0x000000000187be00  RBP: 0x00002000003feb60  R8:  0x0000000000000000
    R9:  0x00000000013f7198  R10: 0x0000000000000036  R11: 0x0000000000000001  R12: 0x00002000003ffa58
    R13: 0x00000000013f7198  R14: 0x0000000000000036  R15: 0x0000000000000001  RSP: 0x00002000003feb38
    Aborted

    [backtrace]
    0x000000000022d8f0 <abort(char const*, ...)+249>
    0x00000000003c7fdf <???+3964895>
    0x00000000003c817e <mmu::vm_fault(unsigned long, exception_frame*)+350>
    0x000000000048d37d <page_fault+315>
    0x000000000048c206 <???+4768262>
    0x00000000005fe5b3 <std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > std::__cxx11::regex_traits<char>::transform_primary<char*>(char*, char*) const+151>
    0x00000000005fa0e5 <std::__detail::_BracketMatcher<std::__cxx11::regex_traits<char>, false, false>::_M_apply(char, std::integral_constant<bool, false>) const+439>
    0x00000000005f5e04 <std::__detail::_BracketMatcher<std::__cxx11::regex_traits<char>, false, false>::_M_make_cache(std::integral_constant<bool, true>)+76>
    0x00000000005f22d1 <std::__detail::_BracketMatcher<std::__cxx11::regex_traits<char>, false, false>::_M_ready()+189>
    0x00000000005f2e6e <void std::__detail::_Compiler<std::__cxx11::regex_traits<char> >::_M_insert_bracket_matcher<false, false>(bool)+278>
    0x00000000005ef822 <std::__detail::_Compiler<std::__cxx11::regex_traits<char> >::_M_bracket_expression()+164>
    0x00000000005eb49d <std::__detail::_Compiler<std::__cxx11::regex_traits<char> >::_M_atom()+1511>
    0x00000000005e7f5a <std::__detail::_Compiler<std::__cxx11::regex_traits<char> >::_M_term()+46>
    0x00000000005e5922 <std::__detail::_Compiler<std::__cxx11::regex_traits<char> >::_M_alternative()+24>
    0x00000000005e38b6 <std::__detail::_Compiler<std::__cxx11::regex_traits<char> >::_M_disjunction()+26>
    0x00000000005eb3e9 <std::__detail::_Compiler<std::__cxx11::regex_traits<char> >::_M_atom()+1331>
    0x00000000005e7f5a <std::__detail::_Compiler<std::__cxx11::regex_traits<char> >::_M_term()+46>
    0x00000000005e5922 <std::__detail::_Compiler<std::__cxx11::regex_traits<char> >::_M_alternative()+24>
    0x00000000005e5945 <std::__detail::_Compiler<std::__cxx11::regex_traits<char> >::_M_alternative()+59>
    0x00000000005e5945 <std::__detail::_Compiler<std::__cxx11::regex_traits<char> >::_M_alternative()+59>
    0x00000000005e5945 <std::__detail::_Compiler<std::__cxx11::regex_traits<char> >::_M_alternative()+59>
    0x00000000005e5945 <std::__detail::_Compiler<std::__cxx11::regex_traits<char> >::_M_alternative()+59>
    0x00000000005e5945 <std::__detail::_Compiler<std::__cxx11::regex_traits<char> >::_M_alternative()+59>
    0x00000000005e38b6 <std::__detail::_Compiler<std::__cxx11::regex_traits<char> >::_M_disjunction()+26>
    0x00000000005e1741 <std::__detail::_Compiler<std::__cxx11::regex_traits<char> >::_Compiler(char const*, char const*, std::locale const&, std::regex_constants::syntax_option_type)+583>
    0x00000000005df3b8 <std::enable_if<std::__detail::__is_contiguous_normal_iter<char const*>::value, std::shared_ptr<std::__detail::_NFA<std::__cxx11::regex_traits<char> > const> >::type std::__detail::__compile_nfa<char const*, std::__cxx11::regex_traits<char> >(char const*, char const*, std::__cxx11::regex_traits<char>::locale_type const&, std::regex_constants::syntax_option_type)+155>
    0x00000000005dd33f <std::__cxx11::basic_regex<char, std::__cxx11::regex_traits<char> >::basic_regex<char const*>(char const*, char const*, std::locale, std::regex_constants::syntax_option_type)+145>
    0x00000000005daf61 <std::__cxx11::basic_regex<char, std::__cxx11::regex_traits<char> >::basic_regex<char const*>(char const*, char const*, std::regex_constants::syntax_option_type)+93>
    0x00000000006f1e49 <std::__cxx11::basic_regex<char, std::__cxx11::regex_traits<char> >::basic_regex(char const*, std::regex_constants::syntax_option_type)+65>
    0x00000000006f0db0 <mount_context::mount_context(char const*)+738>
    0x00000000006f46f4 <???+7292660>
    0x0000000000675537 <sys_mount+911>
    0x00000000006aa00b <mount+62>
    0x0000100005400ee6 <???+88084198>
    0x000000000063e81b <osv::application::run_main(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, char**)+713>
    0x000000000063ea6f <osv::application::run_main()+329>
    0x000000000063e51e <osv::application::main()+108>
    0x000000000063e121 <???+6545697>
    0x000000000063e146 <???+6545734>
    0x000000000069a22e <???+6922798>
    0x000000000069c7a9 <???+6932393>
    0x000000000044fbef <std::function<void ()>::operator()() const+49>
    0x00000000005c1f47 <sched::thread::main()+27>
    0x00000000005be765 <thread_main_c+38>
    0x000000000048d185 <???+4772229>

**Comment by nyh** [comment]
I can easily reproduce this by adding to tst-regex.cc:
```c++
#include <regex>
...
// Try that C++11's std::regex works. Issue #715 reported a bug in this.
std::regex re(".*uid=([0-9]+).*");
```

The gdb stack trace is:
```
#7  0x0000000000389829 in page_fault (ef=0xffff800003ba8088)
    at arch/x64/mmu.cc:38
#8  <signal handler called>
#9  0x0000000000532dbc in std::ctype<char>::do_tolower(char*, char const*) const ()
#10 0x0000100000c12811 in tolower (__hi=0xffffa00003a8c081 "\300\250\003", 
    __lo=<optimized out>, this=<optimized out>)
    at /usr/include/c++/5.3.1/bits/locale_facets.h:853
#11 std::regex_traits<char>::transform_primary<char const*> (
    this=0xffffa000035ae960, __first=__first@entry=0x2000002ff2fc "", 
    __last=__last@entry=0x2000002ff2fd "")
    at /usr/include/c++/5.3.1/bits/regex.h:265
#12 0x0000100000c14d5e in std::__detail::_BracketMatcher<std::regex_traits<char>, false, false>::_M_apply (this=this@entry=0x2000002ff3b0, 
    __ch=__ch@entry=0 '\000')
    at /usr/include/c++/5.3.1/bits/regex_compiler.tcc:581
#13 0x0000100000c17a69 in _M_make_cache (this=0x2000002ff3b0)
    at /usr/include/c++/5.3.1/bits/regex_compiler.h:492
#14 _M_ready (this=0x2000002ff3b0)
    at /usr/include/c++/5.3.1/bits/regex_compiler.h:459
#15 std::__detail::_Compiler<std::regex_traits<char> >::_M_insert_bracket_matcher<false, false> (this=this@entry=0x2000002ffc30, __neg=<optimized out>)
    at /usr/include/c++/5.3.1/bits/regex_compiler.tcc:428
#16 0x0000100000c187e6 in std::__detail::_Compiler<std::regex_traits<char> >::_M_bracket_expression (this=this@entry=0x2000002ffc30)
    at /usr/include/c++/5.3.1/bits/regex_compiler.tcc:355
#17 0x0000100000c19c66 in std::__detail::_Compiler<std::regex_traits<char> >::_M_atom (this=this@entry=0x2000002ffc30)
    at /usr/include/c++/5.3.1/bits/regex_compiler.tcc:341
#18 0x0000100000c1a138 in _M_term (this=0x2000002ffc30)
    at /usr/include/c++/5.3.1/bits/regex_compiler.tcc:139
#19 std::__detail::_Compiler<std::regex_traits<char> >::_M_alternative (
    this=0x2000002ffc30) at /usr/include/c++/5.3.1/bits/regex_compiler.tcc:121
#20 0x0000100000c1a3c9 in std::__detail::_Compiler<std::regex_traits<char> >::_M_disjunction (this=0x2000002ffc30)
    at /usr/include/c++/5.3.1/bits/regex_compiler.tcc:97
#21 0x0000100000c19e46 in std::__detail::_Compiler<std::regex_traits<char> >::_M_atom (this=this@entry=0x2000002ffc30)
    at /usr/include/c++/5.3.1/bits/regex_compiler.tcc:334
#22 0x0000100000c1a138 in _M_term (this=0x2000002ffc30)
    at /usr/include/c++/5.3.1/bits/regex_compiler.tcc:139
#23 std::__detail::_Compiler<std::regex_traits<char> >::_M_alternative (
    this=0x2000002ffc30) at /usr/include/c++/5.3.1/bits/regex_compiler.tcc:121
#24 0x0000100000c1a0a9 in std::__detail::_Compiler<std::regex_traits<char> >::_M_alternative (this=0x2000002ffc30)
    at /usr/include/c++/5.3.1/bits/regex_compiler.tcc:124
#25 0x0000100000c1a0a9 in std::__detail::_Compiler<std::regex_traits<char> >::_M_alternative (this=0x2000002ffc30)
    at /usr/include/c++/5.3.1/bits/regex_compiler.tcc:124
#26 0x0000100000c1a0a9 in std::__detail::_Compiler<std::regex_traits<char> >::_M_alternative (this=0x2000002ffc30)
    at /usr/include/c++/5.3.1/bits/regex_compiler.tcc:124
#27 0x0000100000c1a0a9 in std::__detail::_Compiler<std::regex_traits<char> >::_M_alternative (this=0x2000002ffc30)
    at /usr/include/c++/5.3.1/bits/regex_compiler.tcc:124
#28 0x0000100000c1a0a9 in std::__detail::_Compiler<std::regex_traits<char> >::_M_alternative (this=0x2000002ffc30)
    at /usr/include/c++/5.3.1/bits/regex_compiler.tcc:124
#29 0x0000100000c1a3c9 in std::__detail::_Compiler<std::regex_traits<char> >::_M_disjunction (this=this@entry=0x2000002ffc30)
    at /usr/include/c++/5.3.1/bits/regex_compiler.tcc:97
#30 0x0000100000c1ad65 in std::__detail::_Compiler<std::regex_traits<char> >::_Compiler (this=0x2000002ffc30, __b=<optimized out>, __e=<optimized out>, 
    __loc=..., __flags=<optimized out>)
    at /usr/include/c++/5.3.1/bits/regex_compiler.tcc:82
#31 0x0000100000c0b71a in __compile_nfa<char const*, std::regex_traits<char> >
    (__flags=<optimized out>, __loc=..., __last=0x100000c1b5cc "", 
    __first=0x100000c1b5bc ".*uid=([0-9]+).*")
    at /usr/include/c++/5.3.1/bits/regex_compiler.h:194
#32 basic_regex<char const*> (__f=(unknown: 16), __loc=..., 
    __last=0x100000c1b5cc "", __first=0x100000c1b5bc ".*uid=([0-9]+).*", 
    this=0x2000002ffbd0) at /usr/include/c++/5.3.1/bits/regex.h:767
#33 basic_regex<char const*> (__f=(unknown: 16), __last=0x100000c1b5cc "", 
    __first=0x100000c1b5bc ".*uid=([0-9]+).*", this=0x2000002ffbd0)
    at /usr/include/c++/5.3.1/bits/regex.h:512
#34 basic_regex (__f=(unknown: 16), __p=0x100000c1b5bc ".*uid=([0-9]+).*", 
    this=0x2000002ffbd0) at /usr/include/c++/5.3.1/bits/regex.h:445
#35 main (argc=<optimized out>, argv=<optimized out>)
    at /home/nyh/osv/tests/tst-regex.cc:43
```

**Comment by nyh** [comment]
This was a problem with the default ("C") locale, that didn't have the appropriate tolower/toupper lookup tables. I sent a patch to the mailing list.
What a mess this locale business is :-( It's a wonder any of it actually works...
