### ISSUE TITLE
can't ping OSv guest IP

### ISSUE THREAD

**Issue by bamboojsr** [cloudius-systems/osv#718]
HI,
I follow README building img, and start up OSv, But can't ping guest IP in host

ENV:ubuntu 15

OSv v0.24-51-g0ccc4ec
4 CPUs detected
Firmware vendor: SeaBIOS
bsd: initializing - done
VFS: mounting ramfs at /
VFS: mounting devfs at /dev
RAM disk at 0x0xffff800002840040 (4096K bytes)
net: initializing - done
vga: Add VGA device instance
eth0: ethernet address: 52:54:00:12:34:56
virtio-blk: Add blk device instances 0 as vblk0, devsize=10737418240
random: virtio-rng registered as a source.
random: <Software, Yarrow> initialized
VFS: unmounting /dev
VFS: mounting zfs at /zfs
zfs: mounting osv/zfs from device /dev/vblk0.1
random: device unblocked.
VFS: mounting devfs at /dev
VFS: mounting procfs at /proc
program zpool.so returned 1
BSD shrinker: event handler list found: 0xffffa00001d81a00
        BSD shrinker found: 1
BSD shrinker: unlocked, running
[I/43 dhcp]: Waiting for IP...
[I/246 dhcp]: Server acknowledged IP for interface eth0
eth0: 192.168.122.15
[I/246 dhcp]: Configuring eth0: ip 192.168.122.15 subnet mask 255.255.255.0 gateway 192.168.122.1 MTU 1500
Running from /init/30-auto-00: /libhttpserver.so &!
could not load libicuuc.so.52
could not load libicui18n.so.52
could not load libicudata.so.52
could not load libssl.so.1.0.0
could not load libcrypto.so.1.0.0

brctl show:
bridge name     bridge id               STP enabled     interfaces
virbr0          8000.525400eb020d       no              virbr0-nic

above all, also OSv print guest ip, but i cant' find tap.

**Comment by nyh** [comment]
This is a question, not a bug report or feature request, so let's move it to the mailing list if you want to continue to discuss it.

How did you run the OSv image - with scripts/run.py? Or somewhere else?
If you used scripts/run.py, you need to pass the "-n" option to it if you want it to use the bridge (otherwise, it uses qemu's user-mode networking, and you CAN'T ping the guest from outside).

**Comment by bamboojsr** [comment]
Thanks, I used scripts/run.py to start OSv, 

Today , In my ENV, I start up OSv ./scripts/run.py -n is report "/etc/qemu/bridge.conf", because i don't have is file.
So   I start up cmd is  ./scripts/run.py -v -n ,  -v options is can use script/qemu-ifup.sh , finally I can get ping this guest.
