### ISSUE TITLE
rare DHCP abort

### ISSUE THREAD

**Issue by justinc1** [cloudius-systems/osv#725]
While running simple and short openfoam test, once test is already finished, an VM about to terminate:
```
Finalising parallel run
Assertion failed: sched::preemptable() (arch/x64/mmu.cc: page_fault: 33)

[backtrace]
0x000000000022bc6d <abort(char const*, ...)+249>
0x000000000022bcce <__assert_fail+58>
0x000000000048ba70 <page_fault+193>
0x000000000048a976 <???+4761974>
0x00000000005bc68e <sched::thread::wake()+68>
0x00000000006078d8 <dhcp::dhcp_worker::queue_packet(mbuf*)+110>
0x000000000060502c <dhcp_hook_rx(mbuf*)+88>
0x0000000000293a36 <ip_preprocess_packet+930>
0x0000000000294030 <ip_input+34>
0x0000000000275f9f <netisr_dispatch_src+312>
0x00000000002761d8 <netisr_dispatch+33>
0x000000000026b66b <ether_demux+153>
0x000000000026b4ee <???+2536686>
0x000000000026b513 <???+2536723>
0x0000000000275f9f <netisr_dispatch_src+312>
0x00000000002761d8 <netisr_dispatch+33>
0x000000000026b5cf <???+2536911>
0x000000000043ec4c <virtio::net::receiver()+1044>
0x000000000043db08 <???+4446984>
0x0000000000440a24 <???+4459044>
0x000000000044c687 <std::function<void ()>::operator()() const+49>
0x00000000005bc8a9 <sched::thread::main()+27>
0x00000000005b9044 <thread_main_c+38>
0x000000000048b8f5 <???+4765941>
```

Bug is rare, occurred only once in 1000 runs. But I did see such backtrace already a few times, so I guess It will be back, and than I add more details. No gdb backtrace, as VM was already destroyed.

Cmd I used:
```
./foam-run-test.sh $ii

rm -fr /scratch/justin/openfoam/mik3d_15min-2cpu-r5/processor*/[1-9]*
LD_LIBRARY_PATH=~/ompi-test/bin/ mpirun -n 2 -H node0102 -wd /scratch/justin/openfoam/mik3d_15min-2cpu-r5 --launch-agent "/home/justin/devel/mikelangelo/osv_proxy/lin_proxy.sh --nfs 'nfs://172.18.2.3/storage/mikelangelo/ssd_scratch?uid=1008 /scratch' -m2024 -c4 --bridge=br0 --net-mac 52:54:00:00:01:43 --net-ip 172.18.3.201/23 --net-gw 172.18.2.1 --net-dns 172.18.2.1" -x TERM=xterm -x MPI_BUFFER_SIZE=2100100 -x WM_PROJECT_DIR=/scratch/justin/openfoam /usr/bin/simpleFoam -case /scratch/justin/openfoam/mik3d_15min-2cpu-r5/ -parallel 1>~/log/log-$ii 2>&1
```

One possibly significant detail. After each mpirun, old VM should be virsh destory-ed and undefined. But I notices some VMs were still running (which most likely mean qemu process was present, but OSv inside it should be finished or crashed; should cause problems). The VMs I'm starting up use same MAC and than get also same IP from DHCP.

In that case at least, VM did start up, orted.so was started, and mpirun was able to start simpleFOAM too. Maybe that VM got reply packet intended for some other VM (one MAC for all hack) ? Then, a simple network traffic reply should trigger bug.

**Comment by justinc1** [comment]
On second look, it is not so rare. I prevented simpleFOAM to finish work in 1 of 1000 runs. But there were 12 VMs which crashed due to it - but only after simpleFOAM finished, so I didn't notice them immediately.

**Comment by nyh** [comment]
According to the backtrace you provided, the crash seems to be in
```
_dhcp_thread->wake();
```
Would be useful to see this crash in gdb and see what is the address in this _dhcp_thread.

_dhcp_thread is a thread we construct and never destruct, so how could `_dhcp_thread->wake()` fail? We can add a printout in `dhcp_worker::~dhcp_worker()` to verify it never gets called, so _dhcp_thread would never be destructed...

 Could it be that some other shutdown-time bug is corrupting memory, and causing _dhcp_thread to be overwritten, so its wake() fails?
One thing it would be helpful t try is to add a gdb watchpoint on the net_dhcp_worker._dhcp_thread: it should be set once in dhcp_start(), and then never written to again. If it does get written to again, we found a bug.

**Comment by justinc1** [comment]
Part of problem are VMs with statically assigned MAC and  IP. I likely started two VMs with the same MAC, and first one was using DHCP, the second one static IP. When second one get packet intended for first one, it does  _dhcp_thread->wake with _dhcp_thread being NULL. Easily reproduced with tcpreplay. Patch sent.
