### ISSUE TITLE
Compiling application for OSv and running it

### ISSUE THREAD

**Issue by miztiik** [cloudius-systems/osv#730]
How do i compile an application for it to run on OSv and then load it to OSv?

For some reason, i am not able to access the gui/dashboard(of OSV) from the VirtualBox host

Any help would be appreciated.

**Comment by benoit-canet** [comment]
On Mon, Feb 22, 2016 at 7:46 PM, Miztiik <notifications@github.com> wrote:

> How do i compile an application for it to run on OSv and then load it to
> OSv?
>
There is a tool named Capstan.

> For some reason, i am not able to access the gui/dashboard(of OSV) from
> the VirtualBox host
>
Are you sure to have nested virtualization activated ?

I also heard of a nested virtulization issue with VirtualBox lately.

**Comment by miztiik** [comment]
The example [here](https://github.com/cloudius-systems/capstan-example) says i need to create a `capstan file`

Can i reuse the same `Makefile` or i have to change it to my needs? If so what aspects of it needs to be changed?

**Comment by nyh** [comment]
Please take a look at https://github.com/cloudius-systems/osv/wiki/Porting-native-applications-to-OSv

If you want to continue this thread, let's do this on the OSv mailing list, not in the bug tracker.
