### ISSUE TITLE
On Fedora 23, cloud-init module does does not run

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#738]
The cloud-init module (which we insert by default to images build with "scripts/build modules=..." as opposed to "scripts/build image=...") does not run on Fedora 23 with gcc 5.3.1:

```
$ scripts/build image=rogue,cloud-init
$ scripts/run.py
OSv v0.24-79-gf64563a
eth0: 192.168.122.15
/usr/mgmt/cloud-init.so: failed looking up symbol _ZN4YAML6detail9node_data12empty_scalarB5cxx11E (YAML::detail::node_data::empty_scalar[abi:cxx11])
```

My guess is that we're mixing the a yaml library from external/ with the host's libstdc++ library (which we use by default), and that doesn't work. We can fix this by using the build machine's yaml library or, as we did in commit 6a3bff38a281e65ee715bab4fadef63e0918f7d3 - compile cloud-init.so with the old C++ ABI (but that approach will be messy if cloud-init also uses OSv APIs).

**Comment by rowlandwatkins** [comment]
Hi @nyh,

Just to confirm got the same problem, confusingly hangs capstan forever ;) Any pointers on where I need to modify - is this a Makefile issue?

Cheers,

Rowland
