### ISSUE TITLE
/usr/bin/ld: cannot find -ltools

### ISSUE THREAD

**Issue by hpccdiaz** [cloudius-systems/osv#751]
Hi, I am getting this error when trying to execute the NFS test... any idea about how to solve it? Regards.

carlos@node0101:~/osv$ sudo scripts/run.py -e "modules/nfs-tests/tst-nfs.so" --verbose
OSv v0.24-108-gca6bcd4
4 CPUs detected
Firmware vendor: Bochs
bsd: initializing - done
VFS: mounting ramfs at /
VFS: mounting devfs at /dev
net: initializing - done
vga: Add VGA device instance
eth0: ethernet address: 52:54:00:12:34:56
virtio-blk: Add blk device instances 0 as vblk0, devsize=10737418240
random: virtio-rng registered as a source.
random: <Software, Yarrow> initialized
VFS: unmounting /dev
VFS: mounting zfs at /zfs
zfs: mounting osv/zfs from device /dev/vblk0.1
random: device unblocked.
VFS: mounting devfs at /dev
VFS: mounting procfs at /proc
program zpool.so returned 1
BSD shrinker: event handler list found: 0xffffa00001cda300
	BSD shrinker found: 1
BSD shrinker: unlocked, running
[I/42 dhcp]: Waiting for IP...
[I/245 dhcp]: Server acknowledged IP for interface eth0
eth0: 192.168.122.15
[I/245 dhcp]: Configuring eth0: ip 192.168.122.15 subnet mask 255.255.255.0 gateway 192.168.122.1 MTU 1500
Running from /init/30-auto-00: /libhttpserver.so &!
could not load libicuuc.so.52
could not load libicui18n.so.52
Failed to load object: modules/nfs-tests/tst-nfs.so. Powering off.

**Comment by hpccdiaz** [comment]
They seems to be warnings, as they appear also when running the image without a program to execute... 

carlos@node0101:~/osv$ sudo scripts/run.py -V
OSv v0.24-108-gca6bcd4
4 CPUs detected
Firmware vendor: Bochs
bsd: initializing - done
VFS: mounting ramfs at /
VFS: mounting devfs at /dev
net: initializing - done
vga: Add VGA device instance
eth0: ethernet address: 52:54:00:12:34:56
virtio-blk: Add blk device instances 0 as vblk0, devsize=10737418240
random: virtio-rng registered as a source.
random: <Software, Yarrow> initialized
VFS: unmounting /dev
VFS: mounting zfs at /zfs
zfs: mounting osv/zfs from device /dev/vblk0.1
random: device unblocked.
VFS: mounting devfs at /dev
VFS: mounting procfs at /proc
program zpool.so returned 1
BSD shrinker: event handler list found: 0xffffa00001dc4400
	BSD shrinker found: 1
BSD shrinker: unlocked, running
[I/42 dhcp]: Waiting for IP...
[I/245 dhcp]: Server acknowledged IP for interface eth0
eth0: 192.168.122.15
[I/245 dhcp]: Configuring eth0: ip 192.168.122.15 subnet mask 255.255.255.0 gateway 192.168.122.1 MTU 1500
Running from /init/30-auto-00: /libhttpserver.so &!
could not load libicuuc.so.52
could not load libicui18n.so.52
could not load libssl.so.1.0.0
could not load libcrypto.so.1.0.0

**Comment by nyh** [comment]
The missing ICU libraries is not a bug, it is a harmless annoyance already reported in issue #600.

The missing libssl/libcrypto is a bug I haven't seen before - what application are you using there? I can't reproduce this with the default "scripts/build" (of image=cli).

**Comment by hpccdiaz** [comment]
Hi Nadav,

In the previous post no application was used, just entering into the vm comand line.

Now, I am trying to build with the tests image but I have the following error about the "tools" library:

carlos@node0101:~/osv$ git pull
Already up-to-date.
carlos@node0101:~/osv$ sudo scripts/build image=tests nfs=true
Building into build/release.x64
  GEN gen/include/osv/version.h
No such image configuration: tests. Assuming list of modules.
Importing /home/carlos/osv/modules/tests/module.py
Importing /home/carlos/osv/modules/java-tests/module.py
Importing /home/carlos/osv/modules/java/module.py
Importing /home/carlos/osv/apps/fonts/module.py
No module.py in /home/carlos/osv/modules/ca-certificates
No module.py in /home/carlos/osv/modules/libz
No module.py in /home/carlos/osv/modules/josvsym
Importing /home/carlos/osv/modules/httpserver-jolokia-plugin/module.py
Importing /home/carlos/osv/modules/httpserver-jvm-plugin/module.py
Modules:
  fonts
  ca-certificates
  libz
  josvsym
  httpserver-jolokia-plugin
  httpserver-jvm-plugin
  java
  java-tests
  tests.*
mkdir -p build/etc/pki/ca-trust/extracted/openssl
mkdir -p build/etc/pki/ca-trust/extracted/pem
mkdir -p build/etc/pki/ca-trust/extracted/java
p11-kit extract --format=openssl-bundle --filter=certificates --overwrite build/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
p11-kit extract --format=pem-bundle --filter=ca-anchors --overwrite --purpose server-auth build/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
p11-kit extract --format=pem-bundle --filter=ca-anchors --overwrite --purpose email build/etc/pki/ca-trust/extracted/pem/email-ca-bundle.pem
p11-kit extract --format=pem-bundle --filter=ca-anchors --overwrite --purpose code-signing build/etc/pki/ca-trust/extracted/pem/objsign-ca-bundle.pem
p11-kit extract --format=java-cacerts --filter=ca-anchors --overwrite --purpose server-auth build/etc/pki/ca-trust/extracted/java/cacerts
make: Nothing to be done for `module'.
  MKDIRS
  LINK jolokia.so
/usr/bin/ld: cannot find -ltools
collect2: error: ld returned 1 exit status
make: *** [jolokia.so] Error 1
Traceback (most recent call last):
  File "scripts/module.py", line 250, in <module>
    args.func(args)
  File "scripts/module.py", line 205, in build
    make_modules(modules, args)
  File "scripts/module.py", line 109, in make_modules
    raise Exception('make failed for ' + module.name)
Exception: make failed for httpserver-jolokia-plugin
scripts/build failed: jdkbase=$jdkbase ARCH=$arch mode=$mode OSV_BASE=$SRC OSV_BUILD_PATH=$OSV_BUILD_PATH scripts/module.py $j_arg build -c $modules $usrskel_arg
carlos@node0101:~/osv$

**Comment by hpccdiaz** [comment]
In the Makefile of the "httpserver-jolokia-plugin"

modules/httpserver-jolokia-plugin/Makefile 
Showing the top match. Last indexed on Mar 18.

42	DYN_LIBS = -lpthread -ldl -L$(OSV_BUILD_PATH)/tools -ltools -L$(libs-dir) -lyaml-cpp $(boost-libs)

I don't know well if it tries to find the library "libtools" under the directory OSV_BUILD_PATH

carlos@node0101:~$ env | grep OSV
OSV_BUILD_PATH=/home/carlos/osv/build/last/
OSV_BASE=/home/carlos/osv/

In such case, there is no library "libtools" there:

carlos@node0101:~/osv/build/last/tools$ ls
cpiod  mkfs  mount  uush

**Comment by hpccdiaz** [comment]
The library is here:

carlos@node0101:~/osv$ find . -name libtools.so
./modules/libtools/libtools.so

**Comment by hpccdiaz** [comment]
As workaround I have created this symbolic link and it is able now to find the library "libtools"

carlos@node0101:~/osv/build/last$ sudo ln -s ../../modules/libtools/ tools

**Comment by hpccdiaz** [comment]
In addition to the image=tests, it is needed also to add the module nfs-tests in this way:

carlos@node0101:~/osv$ sudo scripts/build image=tests nfs=true modules=nfs-tests

Therefor the nfs-tests.so file is added to the image and can be executed.

Adding /tst-nfs.so...
Adding /init/30-auto-00...
carlos@node0101:~/osv$ sudo scripts/run.py -e /tst-nfs.so
OSv v0.24-109-g2781c85
eth0: 192.168.122.15
Allowed options:
  --help                produce help message
  --server arg          set server ip
  --share arg           set remote share

**Comment by nyh** [comment]
On Tue, May 24, 2016 at 6:22 PM, hpccdiaz <notifications@github.com> wrote:

> In addition to the image=tests, it is needed also to add the module
> nfs-tests in this way:
>
> carlos@node0101:~/osv$ sudo scripts/build image=tests nfs=true
> modules=nfs-tests
>

You can also do

     scripts/build image=tests,nfs-tests nfs=true

to get both "tests" and "nfs-tests" modules.

The NFS tests are deliberately separate, because they don't make sense
without NFS compiled in (nfs=true).

**Comment by nyh** [comment]
Thanks. I can reproduce the httpserver-jolokia-plugin build failure. I'll send a patch.
