### ISSUE TITLE
cloud-init: support mount points

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#754]
This issue was reported by Gregor Berginc from the Mikelangelo project.

OSv's cloud-init implementation is missing support for the "mounts" option, whose purpose and syntax is explained [here](http://cloudinit.readthedocs.io/en/latest/topics/examples.html#adjust-mount-points-mounted). This option asks to mount additional disks, and he specifically would like this to be able to mount NFS disks (see tools/mount/mount-nfs.cc).

**Comment by justinc1** [comment]
implemented now by 6eb48ee9c457f1aacf813e57090a8c1cc53aaab4
