### ISSUE TITLE
Error on startup of OSv when trying to run elasticsearch on openjdk8 compact profile

### ISSUE THREAD

**Issue by wkozaczuk** [cloudius-systems/osv#756]
I get this every time I try to start OSv image created to run elasticsearch. I wonder if it is because I built openjdk8 compact profiles against wrong libnio library? Or maybe realpath_chk is not implemented in OSv?

Created instance: elasticsearch
OSv v0.24
eth0: 10.0.2.15
/usr/lib/jvm/j2re-compact3-image-with-java-beans/jre/lib/amd64/libnio.so: failed looking up symbol __realpath_chk

[backtrace]
0x00000000003444fd <elf::object::symbol(unsigned int)+205>
0x000000000034487e <elf::object::resolve_pltgot(unsigned int)+126>
0x0000000000344a66 <elf_resolve_pltgot+54>
0x0000000000390b8e <???+3738510>
0x00002000140dea4f <???+336456271>
0x00002000006189da <???+6392282>
0x0000200000607d7f <???+6323583>
0x0000200000607d7f <???+6323583>
0x0000200000607e53 <???+6323795>
0x00002000006077cf <???+6322127>
0x0000200000607ffc <???+6324220>
0x000020000060050a <???+6292746>
0x0000100001a28a19 <???+27429401>
0x00001000019ec0d8 <???+27181272>
0x00001000019ec530 <???+27182384>
0x00001000019ec969 <???+27183465>
0x0000100001a1efd8 <???+27389912>
0x000020000062634d <???+6447949>
0x0000200000607d7f <???+6323583>
0x0000200000607ffc <???+6324220>
0x0000200000607ffc <???+6324220>
0x0000200000607ffc <???+6324220>
0x0000200000607ffc <???+6324220>
0x000020000060050a <???+6292746>
0x0000100001a28a19 <???+27429401>
0x0000100001cc70f1 <???+30175473>
0x0000100001cc7ac3 <???+30177987>
0x0000100001a7232f <JVM_InvokeMethod+383>
0x00002000006189da <???+6392282>
0x0000200000607d7f <???+6323583>
0x0000200000607d7f <???+6323583>
0x0000200000607e53 <???+6323795>
0x0000200000607d7f <???+6323583>
0x0000200000607ffc <???+6324220>
0x0000200000607ffc <???+6324220>
0x000020000060050a <???+6292746>
0x0000100001a28a19 <???+27429401>
0x0000100001a260f3 <???+27418867>
0x0000100001a266e9 <???+27420393>
0x0000100001a671bd <???+27685309>
0x0000100001d8fee7 <???+30998247>
0x0000100001c49301 <???+29659905>
0x000000000043f4f5 <???+4453621>
0x00000000003efaa7 <thread_main_c+39>
0x0000000000391ed5 <???+3743445>
0x00001000022c1aff <???+36444927>
0x00000000003f082f <???+4130863>
0xfb89485354415540 <???+1413567808>

**Comment by wkozaczuk** [comment]
Clearly there is something wrong with the compact profile JDK that I built because when I switch to using official cloudius/osv-openjdk8 full JDK I get different error:

OSv v0.24
eth0: 10.0.2.15
[2016-06-04 11:56:59,667][WARN ][bootstrap                ] running as ROOT user. this is a bad idea!
syscall(): unimplemented system call 999. Aborting.

[backtrace]
0x00000000003e4e38 <syscall+408>
0x0000100008f1279f <ffi_call_unix64+75>
0x00002000142cbc5f <???+338476127>

It seems that elasticsearch uses JNA on startup to make some native calls and maybe one of them is not available in OSv? 

Adding some links to elasticsearch code:
https://github.com/elastic/elasticsearch/blob/93de1ed6068e8e9f35897f623efe00aa3cfafeea/core/src/main/java/org/elasticsearch/bootstrap/Bootstrap.java
https://github.com/elastic/elasticsearch/blob/93de1ed6068e8e9f35897f623efe00aa3cfafeea/core/src/main/java/org/elasticsearch/bootstrap/JNANatives.java

**Comment by wkozaczuk** [comment]
I made some progress by disabling elasticsearch config option that makes it use seccomp. Now it continues past that to blow up in Java:

io.osv.ContextFailedException: org.elasticsearch.bootstrap.StartupError: java.lang.ExceptionInInitializerError
	at io.osv.Context.join(Context.java:63)
	at io.osv.ContextIsolator.runSync(ContextIsolator.java:146)
	at io.osv.RunJava.main(RunJava.java:35)
Caused by: org.elasticsearch.bootstrap.StartupError: java.lang.ExceptionInInitializerError
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at io.osv.ContextIsolator.runMain(ContextIsolator.java:233)
	at io.osv.ContextIsolator.access$400(ContextIsolator.java:32)
	at io.osv.ContextIsolator$3.run(ContextIsolator.java:118)
Caused by: java.lang.ExceptionInInitializerError
	at org.elasticsearch.common.inject.InjectorBuilder.<init>(InjectorBuilder.java:50)
	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:93)
	at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70)
	at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:46)
	at org.elasticsearch.node.Node.<init>(Node.java:213)
	at org.elasticsearch.node.Node.<init>(Node.java:140)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
	... 7 more
Caused by: io.osv.util.InitializationException: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "shutdownHooks")
	at io.osv.util.LazilyInitialized.get(LazilyInitialized.java:66)
	at io.osv.jul.LogManagerWrapper.getManager(LogManagerWrapper.java:44)
	at io.osv.jul.IsolatingLogManager.getDelegate(IsolatingLogManager.java:23)
	at io.osv.jul.IsolatingLogManager.getLogger(IsolatingLogManager.java:43)
	at java.util.logging.LogManager.demandLogger(LogManager.java:551)
	at java.util.logging.Logger.demandLogger(Logger.java:455)
	at java.util.logging.Logger.getLogger(Logger.java:502)
	at org.elasticsearch.common.inject.internal.Stopwatch.<clinit>(Stopwatch.java:29)
	... 17 more
Caused by: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "shutdownHooks")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at java.util.logging.LogManager.checkSubclassPermissions(LogManager.java:272)
	at java.util.logging.LogManager.<init>(LogManager.java:251)
	at io.osv.jul.DefaultLogManager.<init>(DefaultLogManager.java:11)
	at io.osv.jul.LogManagerWrapper$1.call(LogManagerWrapper.java:34)
	at io.osv.jul.LogManagerWrapper$1.call(LogManagerWrapper.java:29)
	at io.osv.util.LazilyInitialized.get(LazilyInitialized.java:59)
	... 24 more

I believe it is caused by code in elasticsearch bootstrap that sets up shutdown hooks Runtime.getRuntime().addShutdownHook() which maybe is disallowed by OSv RunJava code.

**Comment by nyh** [comment]
On Sat, Jun 4, 2016 at 7:42 AM, wkozaczuk <notifications@github.com> wrote:

> I get this every time I try to start OSv image created to run
> elasticsearch. I wonder if it is because I built openjdk8 compact profiles
> against wrong libnio library? Or maybe realpath_chk is not implemented in
> OSv?
>
> Created instance: elasticsearch
> OSv v0.24
> eth0: 10.0.2.15
> /usr/lib/jvm/j2re-compact3-image-with-java-beans/jre/lib/amd64/libnio.so:
> failed looking up symbol __realpath_chk
>

We do have __realpath_chk in OSv, in libc/misc/realpath.c, but it was
implemented in December while the v0.24 release you are using was built
almost a year ago, and misses this feature.

Can you please build the latest OSv from source and try that?
@penberg, should we make a new OSv release, or alternatively, stop
providing "releases" completely and ask users to compile on their own?

**Comment by nyh** [comment]
On Sat, Jun 4, 2016 at 3:08 PM, wkozaczuk <notifications@github.com> wrote:

> Clearly there is something wrong with the compact profile JDK that I built
> because when I switch to using official cloudius/osv-openjdk8 full JDK I
> get different error:
>
> OSv v0.24
> eth0: 10.0.2.15
> [2016-06-04 11:56:59,667][WARN ][bootstrap ] running as ROOT user. this is
> a bad idea!
> syscall(): unimplemented system call 999. Aborting.
>

This is interesting. 999 is not a valid Linux system call, but it's not a
reason to crash OSv: OSv should just return the same error as Linux does -
see https://bugzilla.kernel.org/show_bug.cgi?id=79661.

**Comment by nyh** [comment]
On Sat, Jun 4, 2016 at 7:08 PM, wkozaczuk <notifications@github.com> wrote:

> Caused by: java.security.AccessControlException: access denied
> ("java.lang.RuntimePermission" "shutdownHooks")
>
> at
> java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
> at
> java.security.AccessController.checkPermission(AccessController.java:884)
> at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
> at
> java.util.logging.LogManager.checkSubclassPermissions(LogManager.java:272)
> at java.util.logging.LogManager.(LogManager.java:251)
> at io.osv.jul.DefaultLogManager.(DefaultLogManager.java:11)
> at io.osv.jul.LogManagerWrapper$1.call(LogManagerWrapper.java:34)
> at io.osv.jul.LogManagerWrapper$1.call(LogManagerWrapper.java:29)
> at io.osv.util.LazilyInitialized.get(LazilyInitialized.java:59)
> ... 24 more
>
> I believe it is caused by code in elasticsearch bootstrap that sets up
> shutdown hooks Runtime.getRuntime().addShutdownHook() which maybe is
> disallowed by OSv RunJava code.
>

@tgrabriec, any idea how/why we broke addShutownHook?

**Comment by wkozaczuk** [comment]
I actually got passed the addShutdownHook() issue. It turns out that by default elasticsearch enables java security manager and effectively prevents OSv RunJava to setup its own shutdown hook handler. So I disabled security manager in elasticsearch. 

It looks like OSv RunJava enables shutdown hook handler to execute onVMStop() which is native on_vm_stop which maybe needs to be run to do proper cleanup on shutdown.

**Comment by wkozaczuk** [comment]
Regarding __realpath_chk I wonder why I do not see this problem when I used cloudius/osv-openjdk8 image which uses full open JDK8 JRE but I do see when I use the custom profile JRE that I build myself. Could it be that the custom profile JRE that I built is slightly newer that the one in cloudius/osv-openjdk8.

**Comment by wkozaczuk** [comment]
Regarding __realpath_chk it seems this issue is related - https://github.com/cloudius-systems/osv/issues/701 - and indeed I need to build OSv myself from master.

Regarding new build 0.25 and build process I think there is a value in having "official builds".

**Comment by wkozaczuk** [comment]
Indeed I was able to run the same elasticsearch instance on the build from master so I think this issue can be closed.

**Comment by nyh** [comment]
Hi Nadav,

On Sun, Jun 5, 2016 at 9:59 AM, Nadav Har'El <nyh@scylladb.com> wrote:
>
> On Sat, Jun 4, 2016 at 7:42 AM, wkozaczuk <notifications@github.com> wrote:
>>
>> I get this every time I try to start OSv image created to run
>> elasticsearch. I wonder if it is because I built openjdk8 compact profiles
>> against wrong libnio library? Or maybe realpath_chk is not implemented in
>> OSv?
>>
>> Created instance: elasticsearch
>> OSv v0.24
>> eth0: 10.0.2.15
>> /usr/lib/jvm/j2re-compact3-image-with-java-beans/jre/lib/amd64/libnio.so:
>> failed looking up symbol __realpath_chk
>
>
> We do have __realpath_chk in OSv, in libc/misc/realpath.c, but it was
> implemented in December while the v0.24 release you are using was built
> almost a year ago, and misses this feature.
>
> Can you please build the latest OSv from source and try that?
> @penberg, should we make a new OSv release, or alternatively, stop providing
> "releases" completely and ask users to compile on their own?

We can make a new release but currently "make image=mgmt" fails with
the following error, which causes "scripts/build-capstan-images" to
also fail:

Traceback (most recent call last):
  File "/home/penberg/osv/scripts/upload_manifest.py", line 207, in <module>
    main()
  File "/home/penberg/osv/scripts/upload_manifest.py", line 199, in main
    upload(osv, manifest, depends)
  File "/home/penberg/osv/scripts/upload_manifest.py", line 151, in upload
    perm = os.stat(hostname).st_mode & 0o777
OSError: [Errno 2] No such file or directory:
'./tools/ifconfig/ifconfig-stripped.so'
qemu: terminating on signal 2
Traceback (most recent call last):
  File "scripts/run.py", line 491, in <module>
    main(cmdargs)
  File "scripts/run.py", line 400, in main
    start_osv(options)
  File "scripts/run.py", line 384, in start_osv
    launchers[options.hypervisor](options)
  File "scripts/run.py", line 200, in start_osv_qemu
    subprocess.call(cmdline, env=qemu_env)
  File "/usr/lib64/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 1384, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib64/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt


- Pekka

**Comment by nyh** [comment]
On Sun, Jun 12, 2016 at 10:53 AM, Pekka Enberg <penberg@scylladb.com> wrote:

> Hi Nadav,
>
> On Sun, Jun 5, 2016 at 9:59 AM, Nadav Har'El <nyh@scylladb.com> wrote:
> >
> > On Sat, Jun 4, 2016 at 7:42 AM, wkozaczuk <notifications@github.com>
> wrote:
> >>
> >> I get this every time I try to start OSv image created to run
> >> elasticsearch. I wonder if it is because I built openjdk8 compact
> profiles
> >> against wrong libnio library? Or maybe realpath_chk is not implemented
> in
> >> OSv?
> >>
> >> Created instance: elasticsearch
> >> OSv v0.24
> >> eth0: 10.0.2.15
> >>
> /usr/lib/jvm/j2re-compact3-image-with-java-beans/jre/lib/amd64/libnio.so:
> >> failed looking up symbol __realpath_chk
> >
> >
> > We do have __realpath_chk in OSv, in libc/misc/realpath.c, but it was
> > implemented in December while the v0.24 release you are using was built
> > almost a year ago, and misses this feature.
> >
> > Can you please build the latest OSv from source and try that?
> > @penberg, should we make a new OSv release, or alternatively, stop
> providing
> > "releases" completely and ask users to compile on their own?
>
> We can make a new release but currently "make image=mgmt" fails with
> the following error, which causes "scripts/build-capstan-images" to
> also fail:
>

Sorry about that. It broke after recent changes to move the build of
ifconfig.so out of
the main OSv Makefile, and I didn't notice because I wasn't using the
"mgmt" module.
I'm actually surprised it still works - I (wrongly) assumed it stopped
working long ago.

I just sent a patch for this now.

So maybe with that patch we can have a new release.



>
> Traceback (most recent call last):
>   File "/home/penberg/osv/scripts/upload_manifest.py", line 207, in
> <module>
>     main()
>   File "/home/penberg/osv/scripts/upload_manifest.py", line 199, in main
>     upload(osv, manifest, depends)
>   File "/home/penberg/osv/scripts/upload_manifest.py", line 151, in upload
>     perm = os.stat(hostname).st_mode & 0o777
> OSError: [Errno 2] No such file or directory:
> './tools/ifconfig/ifconfig-stripped.so'
> qemu: terminating on signal 2
> Traceback (most recent call last):
>   File "scripts/run.py", line 491, in <module>
>     main(cmdargs)
>   File "scripts/run.py", line 400, in main
>     start_osv(options)
>   File "scripts/run.py", line 384, in start_osv
>     launchers[options.hypervisor](options)
>   File "scripts/run.py", line 200, in start_osv_qemu
>     subprocess.call(cmdline, env=qemu_env)
>   File "/usr/lib64/python2.7/subprocess.py", line 522, in call
>     return Popen(*popenargs, **kwargs).wait()
>   File "/usr/lib64/python2.7/subprocess.py", line 1384, in wait
>     pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
>   File "/usr/lib64/python2.7/subprocess.py", line 476, in _eintr_retry_call
>     return func(*args)
> KeyboardInterrupt
>
>
> - Pekka
>
