### ISSUE TITLE
syscall set_mempolicy missing

### ISSUE THREAD

**Issue by justinc1** [cloudius-systems/osv#760]
During Open MPI execution:

```
syscall(): unimplemented system call 238
```

That should be set_mempolicy. Asking for addition.

**Comment by nyh** [comment]
We could easily add a stub implementation (like we did with get_mempolicy), but to provide a real implementation we would need to change OSv to actually support several NUMA nodes, and allow explicitly allocating memory from different parts of the memory. This will likely involve mmap() and malloc() needing to inspect the current thread's NUMA policy when allocating memory, and both of them having separate pools of memory per NUMA node.

**Comment by wkozaczuk** [comment]
We actually have a simple `set_mempolicy` implemented in linux.cc that returns 0 - it looks like I implemented it (see your review of the patch - https://groups.google.com/g/osv-dev/c/Cx4bJ2WX3og/m/OsbtFb4lBAAJ). Shall we close it or did @justinc1 need full-blown real implementation? Should we maybe instead have a separate issue of supporting multi-node NUMA? It could be that my implementation was not quite correct. It was enough to support libnuma.so used by ffmpeg library though.

I myself added basic sysfs implementation (https://github.com/cloudius-systems/osv/commit/d14a5dca10c167c03bcc355c8d78e70701cc1930) to support libnuma.so.

**Comment by nyh** [comment]
I'll close this issue. If one day anybody will want real, full, support for NUMA nodes this will require work and a new issue involving changes to multiple functions - not just set_mempolicy.
