### ISSUE TITLE
gcc compiler

### ISSUE THREAD

**Issue by ufo19890607** [cloudius-systems/osv#762]
I want to know how to build gcc 4.8.3 , when I run ./contrib/download_prerequisites command. the terminal says time out....

**Comment by nyh** [comment]
Hi, I think you have the wrong project... OSv is a kernel for virtual machines; You can compile it *with* gcc 4.8.3 (anything above 4.8 should be ok), but it is unrelated to how you built gcc 4.8.3 itself, of course.... Try looking for the gcc project and asking them.
