### ISSUE TITLE
About netperf benchmark

### ISSUE THREAD

**Issue by ufo19890607** [cloudius-systems/osv#767]
Hi everone,
I follow the netperf Benchmark, I run a netperf on osv. 
sudo ./scripts/run.py -n -v -e "/tools/netperf.so -H 10.117.7.170 -l 30 -- -P 12866 -m 1400" -c 4

But it says ""Cannot set up guest memory 'pc.ram': Cannot allocate memory"

Can you tell me how to sovle this problem?

**Comment by nyh** [comment]
This command line will try to allocate 2 gigabytes of memory on your host for this guest (run.py's default, which you can override with the "-m" option, is two gigabytes). It looks like qemu is failing to allocate this memory, and OSv hasn't even run yet.

Is it possible you genuinely don't have enough memory?

**Comment by nyh** [comment]
@ufo19890607 can you please add some clarifications, or close this issue? Thanks.

**Comment by benoit-canet** [comment]
ah no sorry your -m 1400 is for netperf.

**Comment by benoit-canet** [comment]
You are using -m 1400 here. It does not look like a power of two. Please
try with a power of two.

**Comment by wkozaczuk** [comment]
Is this reallly still an issue? Or can it be closed?
