### ISSUE TITLE
Compilation failure on gcc 6: constructor priorities

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#769]
According to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=59281 we are no longer allowed to use enum class as constructor priorities in include/osv/prio.hh. The actual compilation error we get with gcc 6.1.1:

```
In file included from loader.cc:21:0:
arch/common/smp.hh:14:62: error: constructor priorities must be integers from 0 
to 65535 inclusive
 void smp_init() __attribute__((constructor(init_prio::sched)));
```

**Comment by nyh** [comment]
By the way, we have an even bigger mess in arch/x64/apic.hh, where we use enum class for the same purpose one would use #define in old-style C, and then expect we can use them as integers. We no longer can. 

Probably the solution to both could be to have instead of

enum class name {
   VAL = 7
}

something like:

namespace  name {
   static const VAL=7;
}

(hoping the "static" does something so the compiler doesn't need to put these constant in the executable...).

**Comment by pdziepak** [comment]
Alternatively:
```c++
namespace name {
enum {
    VAL = 7,
};
}
```
This has the advantage (over `static constexpr` solution) of making linker not complain when VAL is bound to const reference in debug mode.
