### ISSUE TITLE
pthread_t should be an unsigned long.

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#770]
There turns out to be quite a few problems in compiling OSv on gcc 6, and I have a few patches already lined up. One of the surprising bugs is that Linux has (see `/usr/include/bits/pthreadtypes.h`):
```c++
typedef unsigned long int pthread_t;
```
While we have: (`include/api/x64/bits/alltypes.h`)
```c++
typedef struct __pthread * pthread_t;
```

Ideally this difference should not cause any problems, because applications should never make any assumption on what pthread_t. But sadly, in gcc 6.1.1's libstdc++, we find this gem in <thread>:
```c++
#ifdef __GLIBC__
      // For the GNU C library pthread_self() is usable without linking to
      // libpthread.so but returns 0, so we cannot use it in single-threaded
      // programs, because this_thread::get_id() != thread::id{} must be true.
      // We know that pthread_t is an integral type in the GNU C library.
      if (!__gthread_active_p())
	return thread::id(1);
#endif
``` 

This thread::id(1) tries to construct a pthread_t from the integer 1, which fails with:
```
In file included from java/jvm/jvm_balloon.cc:18:0:
/usr/include/c++/6.1.1/thread: In function ‘std::thread::id std::this_thread::get_id()’:
/usr/include/c++/6.1.1/thread:290:21: error: invalid conversion from ‘int’ to ‘std::thread::native_handle_type {aka __pthread*}’ [-fpermissive]
  return thread::id(1);
```

While libstdc++ did something really bad here, we should just give up and use unsigned long for our pthread_t. It's also important for binary compatibility (although we didn't have problems with that because the length of a pointer and unsigned long is the same on x64).
```
```

**Comment by rofl0r** [comment]
this shouldn't affect you as long as you don't ```#define __GLIBC__``` in your musl-based libc (upstream musl doesn't - for good reasons).

**Comment by nyh** [comment]
We do define __GLIBC__ in include/glibc-compat/features.h.
The reason why we added this macro is explained in commit 66008d835949a700e64a67fd235512815964b608 - Boost tries to use this macro to differentiate between Linux and BSD using this macro.

Anyway, is there a reason not to use exactly the same type (unsigned long) as glibc does?

As I noted in a patch I already sent, all it takes to fix this is to change the typedef - no changes in the code are necessary.

**Comment by rofl0r** [comment]
> Boost tries to use this macro to differentiate between Linux and BSD using this macro

would've been smarter then to ```s/__GLIBC__/__linux__/``` in boost and leave libc untouched...

> Anyway, is there a reason not to use exactly the same type (unsigned long) as glibc does?

it's UB, since it's supposed to be an opaque type (in musl's case a pointer to struct).
it may work out of luck in this specific case (but probably building your libc with that definition will not succeed).

btw, gcc >= 6 recognizes musl triplets, so there shouldn't be a problem getting the toolchain built when properly configured.
