### ISSUE TITLE
pthread_setaffinity_np and friends should not ignore cpusetsize

### ISSUE THREAD

**Issue by justinc1** [cloudius-systems/osv#771]
See
https://github.com/open-mpi/ompi-release/blob/d722cc452adaa7a5ac524f0d261a5073a6073b09/opal/mca/hwloc/hwloc1112/hwloc/src/topology-linux.c#L829-L843

The cpusetsize is minimized to be just-large-enough. Current OSv code ignores cpusetsize, counts bits beyond end of allocated cpu-set memory and fails as it thinks that pinning to more than one cpu was requested.

**Comment by nyh** [comment]
@justinc1 thanks, I sent a patch to the mailing list to fix this issue. Can you please verify the fix?

**Comment by justinc1** [comment]
Patch is OK, except that CPU_COUNT_S should be used. My trivial 
follow-up patch attached. But, you might decide that all _S macro family 
should be implementd.

Thank you, Justin.

**Comment by nyh** [comment]
@justinc1 I committed my patch, I didn't see your follow-up patch, can you please send it to the mailing list?

**Comment by justinc1** [comment]
OK, I just resent it. I thought it only got removed from github - since 
attachment didn't end with .png/jpg/txt.
