### ISSUE TITLE
netperf benchmark

### ISSUE THREAD

**Issue by ufo19890607** [cloudius-systems/osv#774]
Hi,nyh
I want to compare the network performance of OSV and Linux.  I really want to know how to do the performance test. I don't know if I get your meaning. Test 1: To  run an osv which acts as a server, and run a Linux or osv which acts as a client.  Test 2: Using the qemu/kvm to run a Linux which acts as a server,and run a Linux or osv which acts as a client. Then ,just compare the result of Test1 and Test2. Am I right? If I were right, the result is really amazing, the result of test 1 is 10 times than that of test2.

**Comment by nyh** [comment]
Hi, this bug tracker is for bugs and feature requests, not for general discussions - let's hold those on the OSv mailing list (osv-dev@googlegroups.com). Regarding your actual test, seeing that OSv is 10 times faster than Linux on some workload is indeed amazing - unexpected and frankly, too good to be true. Let's continue discussing on the mailing list.
