### ISSUE TITLE
Fix more cpu-affinity functions

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#776]
Commit c468fb98a831ed64fb5feadb9ab71f30e2ae3295 added a way for one thread to pin() a different thread, and used that to implement pthread_setaffinity_np() for an arbitrary thread.
But we need to complete this work and also fix the following (should be easy):

1. sched_setaffinity() should also be able to work on arbitrary threads, not just this one.
2. pthread_getaffinity_np() should use the new _pinned flag (see 558b963c3f5321cf1c80d03808ed464460fa0647), not the possibly-temporary migration disable counter.
3. sched_getaffinity() should also be able to work on arbitrary threads, not just this one.

**Comment by justinc1** [comment]
The setaffinity() from 705f9cf96cd47a5e0916e2d8641a0ab1d2743c8c use CPU_COUNT instead of CPU_COUNT_S, which doesn't work with dynamically allocated cpu_set. A followup patch send to mail list.
