### ISSUE TITLE
getifaddrs not working

### ISSUE THREAD

**Issue by justinc1** [cloudius-systems/osv#783]
NodeJS os.networkInterfaces uses getifaddrs(), and this one always fails with errno 105/No buffer space available. Minimal test program to show that is C example from 'man getifaddrs'.

**Comment by miha-plesko** [comment]
The problem arises when NodeJS tries to obtain a list of all network adapters using it's core library named "os", error looks like this:

```
Printing my local IPs
/app.js:20
        var interfaces = os.networkInterfaces();
                            ^

Error: ENOBUFS: no buffer space available, uv_interface_addresses
    at Error (native)
    at printMyIP (/app.js:20:22)
    at Object.<anonymous> (/app.js:111:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```


We've managed to narrow the problem down to OSv function [getifaddrs](https://github.com/cloudius-systems/osv/blob/3544629e5fb7935af8149b36395b72a9ae588350/libc/network/getifaddrs.c#L115) that crashes with error code 
```
105 ENOBUFS, No buffer space available
```

**Comment by nyh** [comment]
Turns out that the musl implementation of getifaddrs() starts by calling if_nameindex(), also implemented by musl, and that function is what misleadingly returns ENOBUFS. 

Actually if_nameindex()'s problem isn't lacking memory. Rather it runs

	int s = socket(AF_UNIX, SOCK_DGRAM|SOCK_CLOEXEC, 0);

hoping to run ioctl with SIOCGIFCONF and SIOCGIFINDEX on this socket, but this socket() call fails with "Protocol not supported".  Indeed we don't yet support datagram Unix-domain sockets (this is issue #351). Perhaps this code could work if using AF_INET instead of AF_UNIX? (modules/libtools/network_interface.cc seems to suggest that this is the way to go).

**Comment by miha-plesko** [comment]
Awesome @nyh , could you prepare a patch for this?

**Comment by nyh** [comment]
I'm trying :-) I really hope I can get something simple to work (and not massive changes to the TCP/IP stack or anything like that).

**Comment by nyh** [comment]
With AF_INET we can open the socket, but the SIOCGIFCONF ioctl is failing. It seems we have an implementation for it (see bsd/sys/compat/linux/linux_ioctl.cc) so I don't know why it's failing :-( Need to continue investigating.

**Comment by miha-plesko** [comment]
I wonder why replacing only three characters can never solve the problem... :D
<pre>
AF_<b>U</b>N<b>IX</b> -> AF_<b>I</b>N<b>ET</b>
</pre>

**Comment by nyh** [comment]
@miha-plesko I just sent a series of 4 patches to the OSv mailing list for fixing this getifaddrs() issue. I tested getifaddrs() with my own code (I didn't yet send the test as a patch) but would be grateful if you could test it in your code before I commit these patches. Thanks.

**Comment by miha-plesko** [comment]
@nyh I confirm that it works after applying all the four patches. Thumbs up from my side to commit.
