### ISSUE TITLE
Add Mono (MITized) or CoreRT to OSV

### ISSUE THREAD

**Issue by cia48621793** [cloudius-systems/osv#786]
Mono has re-licensed to MIT few months ago. I think it is a good time to demonopolize Java.

CoreRT is also licensed under MIT, but under the control of Microsoft I think it is possible for CoreRT to be private-source it again (Just like what happened to OpenAL) so it could be risky.

The market margin could be bigger if there were .NET support, for example we can run ASP.NET Core with OSV.
#289

**Comment by radu-matei** [comment]
Hi!

Is there any perspective on this? .NET Core is open source and will remain so.
Can you provide some initial guidance on how to get started on this?

Thanks!

**Comment by avikivity** [comment]
Try to build CoreRT as a shared library using the module system, and fix any fallout.

Since CoreRT is optimized for AOT, it would be interesting to run the AOT compilation as part of the build step.  But first we can get it working as a plain osv module.

**Comment by radu-matei** [comment]
Ok @avikivity, I will try and have a look at this over the weekend. Is there a discussion channel we can get in touch?

Thanks!

**Comment by avikivity** [comment]
https://groups.google.com/forum/#!forum/osv-dev

**Comment by wkozaczuk** [comment]
Closing it in favor of #1161. On top of this, the CoreRT seems to be reaching its end of life (https://github.com/dotnet/corert/issues/7200) in favor of .NET which has support for Linux now. We also have support for simple mono apps - see this example - https://github.com/cloudius-systems/osv-apps/tree/master/mono-example.
