### ISSUE TITLE
JVM ballooning is disabled

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#796]
I'm just adding this as an issue so we don't forget it (I couldn't find an existing issue on this).

In commit e69fa2b6364da0c38068216eee4aeabeef82a3fa, the JVM ballooning feature was disabled because commit 4bd87202ef862c7ac6039775ad2721387cca0ad2 broke it. Eventually we should figure out how to fix it and return this feature...

**Comment by wkozaczuk** [comment]
It would be nice to make JVM ballooning not to depend on JMX as it requires compact profile 3 and jmx module in java 9.

It might be possibly to JVMTI (http://docs.oracle.com/javase/8/docs/platform/jvmti/jvmti.html#GarbageCollectionFinish) to setup some kind of event callbacks that would be called by JVM when GC collection completes. Currently it is handled by https://github.com/cloudius-systems/osv/blob/master/java/runjava/src/main/java/io/osv/OSvGCMonitor.java I believe.

**Comment by wkozaczuk** [comment]
Closing this one, as the newer issue #1038 seems to have some promising ideas from @nozohono on how to solve it.
