### ISSUE TITLE
SYSCALL does not save FPU state or rflags register

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#798]
This is what remains of issue #791:
1. Our SYSCALL implementation (syscall_entry() in arch/x64/entry.S) does not save/restore the FPU. This will be needed if the function which calls SYSCALL uses the FPU. While it is certainly possible that such functions exist, we're not aware of any such example, and unfortunately doing this save/restore will dramatically slow down these system calls :-(
2. We do not restore rflags at the end of syscall_entry(). We also do not modify it much (FMASK MSR is set to 0), so I wonder how important this restoration is, but we might overwrite some arithmetic flags (zero/carry/etc.) and possibly some calling function might care?

**Comment by wkozaczuk** [comment]
I just realized that these 2 lines in syscall function related to this issue implicate that the fix effectively serializes execution of SYSCALL instructions from Golang. As I understand fpu lock is a global lock so essentially call to read SYSCALL will block all other SYSCALL instructions from other threads. 

Am I correct?

`long syscall(long number, ...)
{
    // Save FPU state and restore it at the end of this function
    sched::fpu_lock fpu;
    SCOPE_LOCK(fpu);
`

**Comment by wkozaczuk** [comment]
I meant that fpu_lock is EFFECTIVELY a global lock.

**Comment by nyh** [comment]
No, this is fine, despite the name, this sched::fpu_lock is not a real lock :-) It just holds a saved FPU state, and SCOPE_LOCK(fpu) saves the current FPU state to this variable, and when the cope ends - the state stored in this (on-stack) variable is automatically restored to the FPU. No mutex or any other sort of locking is involved. Note, by the way, that the variable "fpu" is a local variable, so even if it was a real mutex or something similar, it would not have been a "global lock" because each call would have a different lock...

To explain why it's called an "fpu_lock" and not something clearer (e.g., fpu_state_saver), I need to tell you a bit of context: Locks (e.g., a mutex) have a lock() and unlock() method. Using these directly is dangerous in the sense that you may forget to call unlock() at the end - especially when C++ exceptions are possible - so C++ encourages the so-called RAII approach, i.e., you create an object like std::lock_guard (see http://en.cppreference.com/w/cpp/thread/lock_guard) and when this object goes out of scope for any reason, the lock is released. OSv supplies a couple of even more convenient idoms - WITH_LOCK and SCOPE_LOCK - to take a lock and hold it for the duration of a block or until a scope ends.

But once we had those idioms why use them just for "locks"? Any type which has the equivalent of a lock() and unlock() - e.g., taking something and releasing it, can be used. For example, sched::fpu_lock simply holds a saved FPU state, "locking" it will save the current FPU state, and "unlocking" will restore the saved FPU state. Just like real locks, you must not forget to "unlock" (restore) if you "locked" (saved). So the SCOPE_LOCK idiom is just as useful.

**Comment by wkozaczuk** [comment]
I see. I must admit that the word "LOCK" use of SCOPE_LOCK confused. In
most places I would see SCOPE_LOCK macro used with a mutex variable and it
is then used to implement a critical section.

In this case however we *happen* to use the same macro against a resource
(fpu_lock which by the way is NOT a mutex but has methods lock() and
unlock() which simply acquire (save the state in this case) and release
(restore the state)) in similar way mutexes would be used. Wow I think it
is pretty easy to get an impression I got :-)

So essentially SCOPE_LOCK does not necessarily lock anything. It is
equivalent to this try/finally block:

auto resource = aqcuire(..);
try {
  ... do something with resource
}
finally {
  if( resource )
    resource->release();
}

or something like this.

**Comment by wkozaczuk** [comment]
And also to your point the fpu variable is local but then my thinking was
"why are we locking on local mutex? It must be global or something".

**Comment by wkozaczuk** [comment]
Finally I saw the expression “dramatically slow” somewhere. Is it because saving and restoring FPU (floating processing unit, part of CPU) is super expensive?

**Comment by nyh** [comment]
SCOPE_LOCK is not equivalent to a try/finally, because the latter only catches exceptions, not "return" for example. You can consider it syntactic sugar over the standard C++11 class std::lock_guard. You can see its implementation in include/osv/mutex.h.

The FPU "not lock" is slow in the sense it needs to save a lot of floating-point registers, which is slow compared to something small like gettimeofday() (which shouldn't be a syscall anyway, that's why vdso is there). It is *not* as slow as a contended mutex which causes a context switch. You are welcome to measure its actual cost in nanoseconds, I don't remember measuring this myself.
