### ISSUE TITLE
Running ./scripts/run.py -n -v in Ubuntu 14.04 reports "bridge virbr0 does not exist!"

### ISSUE THREAD

**Issue by hsluoyz** [cloudius-systems/osv#807]
Hi, I'm using Ubuntu 14.04 x64 to install OSv.

When comes to the run step, I'm stuck here:
```
root@ubuntu:/osv# ./scripts/run.py -n -v
set stp status failed: No such device
bridge virbr0 does not exist!
OSv v0.24-201-ge9f12c3
```

I tried to install ``virbr0`` by running ``brctl addbr virbr0``, then got stuck here:
```
root@ubuntu:/osv# ./scripts/run.py -n -v
OSv v0.24-201-ge9f12c3
```

After some debugging, I found ``subprocess.call(cmdline, env=qemu_env)`` call to run ``qemu-system-x86_64`` in ``start_osv_qemu()`` of ``/scripts/run.py`` halts.

How to solve it?

**Comment by nyh** [comment]
"virbr0" is normally provided by the "libvirt" package - you'll get it by just installing libvirt.
You can also set up your own bridge in whatever way you like, and use the "-b" option to pass this bridge's name to libvirt.
If your setting up your own bridge which is completely virtual (no physical nic on it) you'll need to run a DHCP server on it, if you don't want to tell OSv its IP address manually (you can do that too). If your bridge includes a physical network, than that would have the DHCP server.
Try adding the "-V" option to run.py to add some debugging printouts to OSv's boot, maybe you'll see that it's stuck trying to get an IP address, or somewhere else.
Finally, if you are just testing OSv, and do not specifically need to use bridged networking, then don't - drop the "-n" option, and you'll get Qemu's emulated network mode. If you are running a server inside OSv and need to connect to one of its ports from the outside (from the host), run.py also has a "--forward" option to forward connections from the host to the guest. For example, "run.py --forward tcp::1234::80" will run OSv in a way that when you connect to port 1234 in the host, the connection will be forwarded to the guest's port 80.
