### ISSUE TITLE
Support --env in scripts

### ISSUE THREAD

**Issue by miha-plesko** [cloudius-systems/osv#819]
There is a nice feature in OSv introduced with [this](https://github.com/cloudius-systems/osv/commit/ac7bf9ff1db0fc27526f45d6d2ae2a3dd2f4d8b4) commit that allows to run simple scripts.
Would it be possible to also support --env there?

For example if I run OSv like this:
```
run.py -e "runscript /run/server123"
```
and the content of /run/server123 is
```bash
# content of file /run/server123
--env=PORT=123 node server.js
```
Then the NodeJS server would be started with environment given. At the moment, it results in error
```bash
Failed to load object: --env=PORT=123. Powering off.
```
But if I remove `--env=PORT=123` part from the script, it works.

**Comment by nyh** [comment]
Currently, "runscript" uses  parse_command_line_min() to parse the file's content (actually, it runs it on each line in that file). If it somehow used parse_options() (from loader.cc) instead, it would gain the capability to parse "--env".

Alternatively, you could achieve the "env" feature without any modifications to OSv, with an external program , say call "setenv", and then use the runscript file:

```
setenv PORT 123
node server.js
```

**Comment by miha-plesko** [comment]
@justinc1 what do you think would make more sense?

**Comment by justinc1** [comment]
Maybe split parse_options() into two parts - parsing part and apply-options part. Then, parsing part could be reused for runscript.
