### ISSUE TITLE
Add ability to build read-only version of httpserver-api module for monitoring purposes

### ISSUE THREAD

**Issue by wkozaczuk** [cloudius-systems/osv#820]
Currently OSv REST apis provided by httpserver module can be used in all or nothing mode only. 

It would be nice for security reasons to limit API to read-only subset (GETs) so that no state modification is possible. In general it should be possible to somehow customize set of available API. Also it would be nice to restrict what part of filesystem file API could access.

One way (static option) to accomplish this could done by enriching httpserver API code with preprocessor #if defined(OS_REBOOT_API_ENABLED) type of expressions. Another way (dynamic option) would be to use some kind of API configuration file specifying what APIs are enabled.

**Comment by nyh** [comment]
So, after commit 92c1d8254c00dd2f5aaa9ef9bd12ee0fdce5fb79 and commit c2a67b89c5a69d23050e0248020eeeeefa67fb7e the size of the image created by "scripts/build image=httpserver" went down from 25 MB to 16 MB. The libhttpserver.so itself is just 1 MB of this size.

So if you still want to modularize the REST apis for security or something, you can keep this issue open. But if it's only the size which bothered you, I think we can close this issue.

**Comment by wkozaczuk** [comment]
Very glad to hear about the size. But my main motivation here is security. And I and am leaning toward the preprocessor-#if-type-of-solution as it seems simpler to implement and more in spirit of unikernels (only what you need). But I am interested in opinion of others. 
Please keep it open.
