### ISSUE TITLE
Modularize httpserver

### ISSUE THREAD

**Issue by wkozaczuk** [cloudius-systems/osv#822]
Currently httpserver module adds 15MB to an image and libhttpserver.so is 17M big. It would be nice to break down this module into some smaller ones:
- base module
- API that simply server OSv REST API
- generic simple webserver serving static content with ability to configure document roots; existing one it is based on boost webserver example (http://www.boost.org/doc/libs/1_62_0/doc/html/boost_asio/examples/cpp11_examples.html) and it might not be difficult to refine existing logic to make it perform decently especially especially with ramfs or other in-memory filesystem; that would be a great use case for a typical HTML5 webapp

**Comment by nyh** [comment]
While I don't disagree that httpserver could be modularized, the 17M size is not a good reason to do it: this size is almost entirely debugging symbols, and when this object is "stripped", it shrinks to only 1MB!
Yuri Volchkov @yvolchkov already noticed this in May, and sent a patch titled "upload_manifest.py: strip binaries from modules dir". I'll look into reviving this patch now.

**Comment by wkozaczuk** [comment]
I am glad to hear about the size of libhttpserver.so (indeed remarkable difference!!!). 

I think my main motivation here is to have a simple generic httpserver that can be used to serve static content possibly from read-only filesystem (maybe ramfs) with decent performance. I noticed there were some efforts to make nginx work on OSv but I wonder if might be less effort to get httpserver or its part to become a basis for some sort of httpserver app that maybe could take advantage of OSv specific APIs like memcached did - https://github.com/cloudius-systems/osv/wiki/OSv-Case-Study:-Memcached).

Some uses cases:
1. Serve HTLML5 app artifacts (html,js, css and other static content) from memory. It would require some document root configuration and mime type handling needed I think. 
2. Serve video files for video streaming. For example to stream HLS ordinary httpserver is enough - https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StreamingMediaGuide/DeployingHTTPLiveStreaming/DeployingHTTPLiveStreaming.html.
