### ISSUE TITLE
fedisableexcept, eenableexcept not implemented

### ISSUE THREAD

**Issue by justinc1** [cloudius-systems/osv#827]
@gberginc tried to include decoposePar from OpenFOAM into OSv image. At runtime, fedisableexcept was missing.
```
/usr/lib/libscotchDecomp.so: failed looking up symbol fedisableexcept
```

For first try, I just added a do-nothing implementation (should be at least WARN_ONCE stub). decomposePar then runs and is able to finish (@gberginc, can you confirm that?)

```
[xlab@mike-c7 fenv]$ pwd
/home/justin_cinkelj/devel/mikelangelo/osv/musl/src/fenv
[xlab@mike-c7 fenv]$ git diff fegetexceptflag.c
diff --git a/src/fenv/fegetexceptflag.c b/src/fenv/fegetexceptflag.c
index bab0b44..d0eadff 100644
--- a/src/fenv/fegetexceptflag.c
+++ b/src/fenv/fegetexceptflag.c
@@ -5,3 +5,13 @@ int fegetexceptflag(fexcept_t *fp, int mask)
        *fp = fetestexcept(mask);
        return 0;
 }
+
+int feenableexcept(int excepts) {
+ return 0;
+}
+int fedisableexcept(int excepts) {
+ return 0;
+}
+int fegetexcept(void) {
+ return 0;
+}
[xlab@mike-c7 fenv]$ 
```

I'm not sure how bad idea is to include stub implementation. Could that cause some ugly/subtle bugs? I mean, if floating exception occurs, app might not execute the correct code path - as fedisableexcept/feenableexcept were ignored.

And maybe a new files should be added for that functions. Likely not to musl/src/fenv (it is submodule), but to the actual OSv code.

```
nm ./platforms/linux64GccDPOpt/lib/libscotchDecomp.so | grep except
                 U __cxa_get_exception_ptr@@CXXABI_1.3.1
                 U fedisableexcept@@GLIBC_2.2.5
                 U feenableexcept@@GLIBC_2.2.5
```
So fegetexcept is not really needed, but it is from the same family.

**Comment by gberginc** [comment]
@justinc1 the app runs flawlessly with the patch, yes.

**Comment by nyh** [comment]
@justinc1 thanks for investigating this. My small comments are that:
1. Please put these functions in a new file, perhaps in arch/x64 (if it will contain x86_64-specific code), not inside an existing musl file (and note the "musl/" directory is a submodule, it's not part of the OSv tree proper).
2. As you said, please use WARN_STUBBED from <osv/stubbing.hh>

However, I think we can actually do a proper implementation of this without too much effort:

In init_fpu() (in arch/x64/processor.hh) we do:
```c++
inline void init_fpu()
{
    asm volatile ("fninit" ::: "memory");
    unsigned int csr = 0x1f80;
    asm volatile ("ldmxcsr %0" : : "m" (csr));
}
```

Sadly this is not explained there, but this magic number "0x1f80" is actually (0x3f << 7) or using the macro in include/api/x64/bits/fenv.h, FE_ALL_EXCEPT << 7 (see the same header file for the meaning of the bit). So feenableexcept() and friends can be implemented exactly the same way, just set the appropriate bits (but not touching the rest of the bits, which are used for other things - the status bits and the "rounding" flags). And also need to set the x87 control word (which strangely, init_fpu() never sets, I don't know why).

I'll prepare a simple implementation and ask you to test it.

**Comment by nyh** [comment]
Hmm, interestingly, the setting in init_fpu() means to *mask* all the FPU exceptions, not to enable all of them. And only effects SSE, not x87. Weird. I don't know why it was ever done this way....

**Comment by nyh** [comment]
I just sent a full implementation (I think) as a patch. @justinc1 can you please test it?

**Comment by justinc1** [comment]
The patch is ok, meaning that decomposePar.so can be run now.

I just have to add that decomposePar.so doesn't really call any of those three function, so they were not tested by me (even if I add abort() into them, decompesePar.so will run just fine)

**Comment by nyh** [comment]
Done by commit d5cf37af8be57beed4c78c7fa95ac135d96640e8 (I forgot to add a "Fixes ..." to the commit message, so doing it manually).
