### ISSUE TITLE
mount-nfs.so with more that one option

### ISSUE THREAD

**Issue by justinc1** [cloudius-systems/osv#829]
Right now, I can (or know how to) mount NFS share with specific UID or with specific GID
```
/tools/mount-nfs.so nfs://192.168.122.1/home/justin_cinkelj/devel-hd/mikelangelo/openfoam-cases/?uid=1000 /openfoam
/tools/mount-nfs.so nfs://192.168.122.1/home/justin_cinkelj/devel-hd/mikelangelo/openfoam-cases/?gid=1000 /openfoam
```

But how to specify both? & should be used as separator. Url encoded or not?
```
/tools/mount-nfs.so nfs://192.168.122.1/home/justin_cinkelj/devel-hd/mikelangelo/openfoam-cases/?uid=1000&gid=1000 /openfoam
/tools/mount-nfs.so nfs://192.168.122.1/home/justin_cinkelj/devel-hd/mikelangelo/openfoam-cases/?uid=1000%26gid=1000 /openfoam
```

In first case, OSv command-line parser intercepts & and tell that "object gid=1000 not found".
In second case, mount-nfs.so doesn't know what to do with "uid=1000%26gid=1000".

I would expect that in second case, %26 will be passed to mount-nfs.so as &, e.g. unescaped. Or is expected that mount-nfs.so is supposed to perform unescaping?

**Comment by justinc1** [comment]
@benoit-canet do you know how to handle the & in this context?

**Comment by nyh** [comment]
We need to tell the command line parser that this "&" is not a separator. Perhaps we can somehow allow to escape it, but you can try using the "quoted string" feature we already have, i.e., put the entire command or just one of the space-separated words in it in quotes ("..."), and the & should be protected. Can you please try?

**Comment by justinc1** [comment]
Yes, that works*
```
sudo ./scripts/run.py -dnvV -c4 -e '/tools/mount-nfs.so "nfs://192.168.122.1/ggg/?uid=1000&gid=1000" /ggg; /cli/cli.so' -V
```

*again; Nadav, maybe you need a bot for my issues - first reply would be always "try quotes".
