### ISSUE TITLE
"osv syms" might load symbols from incorrect target

### ISSUE THREAD

**Issue by myechuri** [cloudius-systems/osv#848]
``osv syms`` attempts to load symbols from the [first matching file](https://github.com/cloudius-systems/osv/blob/master/scripts/loader.py#L120) on local host OS. This match might not necessarily correspond to the right source of symbols for the application.

Example:
i have two applications, both named ``hello`` under ``osv/apps``: one under ``native-example`` and another under ``golang-example``:
```
# pwd
/root/osv/apps
root@ubuntu:~/osv/apps# find . -name hello
./native-example/hello
./golang-example/hello
root@ubuntu:~/osv/apps# 
```

While attempting to debug ``loader.elf`` containing ``golang-example``'s ``hello`` using gdb, ``osv syms`` ends up loading symbols from ``osv/apps/native-example/hello`` instead of ``osv/apps/golang-example/hello``:

```
(gdb) 
myechuri: obj_path, path /hello /root/osv/apps/native-example/hello
/root/osv/apps/native-example/hello 0x100000c00000
add symbol table from file "/root/osv/apps/native-example/hello" at
	.text_addr = 0x100000c51a90
	.gnu.hash_addr = 0x100000c00260
	.dynsym_addr = 0x100000c00340
	.dynstr_addr = 0x100000c008c8
	.gnu.version_addr = 0x100000c00c40
	.gnu.version_r_addr = 0x100000c00cb8
	.rela.dyn_addr = 0x100000c00d28
	.rela.plt_addr = 0x100000c516b0
	.init_addr = 0x100000c518d8
	.plt_addr = 0x100000c51900
	.plt.got_addr = 0x100000c51a80
	.fini_addr = 0x100000cce490
	.rodata_addr = 0x100000cce4a0
	.eh_frame_hdr_addr = 0x100000cd9e08
	.eh_frame_addr = 0x100000cd9ea0
	.note.go.buildid_addr = 0x100000cda140
	.tbss_addr = 0x100000eda740
	.init_array_addr = 0x100000eda740
	.fini_array_addr = 0x100000eda750
	.jcr_addr = 0x100000eda758
	.data.rel.ro_addr = 0x100000eda760
	.dynamic_addr = 0x100000f52dc8
	.got_addr = 0x100000f52fc8
	.got.plt_addr = 0x100000f53000
	.data_addr = 0x100000f530e0
	.noptrdata_addr = 0x100000f54f00
	.bss_addr = 0x100000f57000
	.noptrbss_addr = 0x100000f719e0
	.comment_addr = 0x100000c00000
	.debug_aranges_addr = 0x100000c00000
	.debug_pubnames_addr = 0x100000c00000
	.debug_info_addr = 0x100000c00000
	.debug_abbrev_addr = 0x100000c00000
	.debug_line_addr = 0x100000c00000
	.debug_frame_addr = 0x100000c00000
	.debug_str_addr = 0x100000c00000
	.debug_loc_addr = 0x100000c00000
	.debug_pubtypes_addr = 0x100000c00000
	.debug_ranges_addr = 0x100000c00000
	.debug_gdb_scripts_addr = 0x100000c00000
	.symtab_addr = 0x100000c00000
	.strtab_addr = 0x100000c00000
warning: section .comment not found in /root/osv/apps/native-example/hello
warning: section .debug_aranges not found in /root/osv/apps/native-example/hello
warning: section .debug_pubnames not found in /root/osv/apps/native-example/hello
warning: section .debug_info not found in /root/osv/apps/native-example/hello
warning: section .debug_abbrev not found in /root/osv/apps/native-example/hello
warning: section .debug_line not found in /root/osv/apps/native-example/hello
warning: section .debug_frame not found in /root/osv/apps/native-example/hello
warning: section .debug_str not found in /root/osv/apps/native-example/hello
warning: section .debug_loc not found in /root/osv/apps/native-example/hello
warning: section .debug_pubtypes not found in /root/osv/apps/native-example/hello
warning: section .debug_ranges not found in /root/osv/apps/native-example/hello
warning: section .debug_gdb_scripts not found in /root/osv/apps/native-example/hello
warning: section .symtab not found in /root/osv/apps/native-example/hello
warning: section .strtab not found in /root/osv/apps/native-example/hello
(gdb) 
```

Instead of assuming the first file that matches application name as the source of its symbols, it might be better to extract fully qualified path of the app from ``build/last/usr.manifest``?

```
# tail -1 build/last/usr.manifest 
/hello: /root/osv/apps/golang-example/hello
# 
```

**Comment by justinc1** [comment]
I also frequently use wrong file to get debug info. For example, I build open-mpi, and I have different out directories - debug or release, build host distro name, and distro version. Example directory structure:
```
drwxrwxr-x.  9 justin_cinkelj justin_cinkelj     4096 Jan 17 10:20 build-osv-debug-centos-linux-7.2.1511/
drwxrwxr-x.  9 justin_cinkelj justin_cinkelj     4096 Jan  9 05:40 build-osv-release-centos-linux-7.2.1511/
drwxrwxr-x.  9 justin_cinkelj justin_cinkelj     4096 Jan 27 18:48 build-osv-release-ubuntu-14.04/
lrwxrwxrwx.  1 justin_cinkelj justin_cinkelj       37 Jan 11 09:15 build-osv-symbols -> build-osv-debug-centos-linux-7.2.1511/
```
The symlink helps, but it's pita.

Finding out full path from usr.manifest might not be most reliable method, usr.manifest and usr.img can be totally different (say I started scripts/build, usr.manifest is updated, but then build fails, and I run an  old image).

I was thinking about using ELF file BuildID (or maybe checksum over whole file) to check if file on host and file in OSv are the same. https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Developer_Guide/compiling-build-id.html.

Then, all directories with some binary would be added to search path, and still only the correct one would be used.

**Comment by nyh** [comment]
@justinc1, indeed if you start a new build the usr.manifest might get out of sync, but in general, if you do start a new build while OSv, you might no longer have the application executable - or even the unstripped OSv kernel image (build/*/loader.elf), so I think it's not a situation we need to worry about.

I think that trying to look up the path in the current usr.manifest (note - the one in the same directory of the kernel image being debugged - build_dir in loader.py) as the first attempt makes sense - it can't be worse than what we're doing today in loader.py's translate(path) (which is to pick up any shared object which happens to have the same basename).

I would welcome a patch :-)

**Comment by justinc1** [comment]
@myechuri patch is at https://groups.google.com/forum/#!topic/osv-dev/4t9GKUtfOgM - the [v2] mail. Works for you?

**Comment by myechuri** [comment]
> @myechuri patch is at https://groups.google.com/forum/#!topic/osv-dev/4t9GKUtfOgM - the [v2] mail. Works for you?

@justinc1 @nyh : thanks a lot for the quick fix! Verified that @justinc1 's patch (grabbed from osv master) worked for me. Apologies for the delay in confirmation.
