### ISSUE TITLE
tst-kill FAIL: with SA_RESETHAND, signal handler is reset

### ISSUE THREAD

**Issue by justinc1** [cloudius-systems/osv#861]
```
./scripts/run.py -nv --novnc -e '/tests/tst-kill.so' -Vd

PASS: kill SIGUSR1 succeeds
PASS: 'global' is now 1
FAIL: with SA_RESETHAND, signal handler is reset
SUMMARY: 31 tests, 1 failures
handler1 called, sig=10
```

Interesting, I didn't notice problem, when compiling image on centos7 VM and running it on VM. But same image failed when run on host (fedora 25). Now I compiled current master on host, and it also fails when run on host (and works on c7 VM).

Of about 5-10 tries, one even worked on the host.

**Comment by nyh** [comment]
On my Fedora 25, I can't reproduce a failure.
I'll try to think what can cause the failure you saw...

**Comment by nyh** [comment]
Can you please try this patch?
```patch
diff --git a/tests/tst-kill.cc b/tests/tst-kill.cc
index 249ff53..a049d84 100644
--- a/tests/tst-kill.cc
+++ b/tests/tst-kill.cc
@@ -139,6 +139,7 @@ int main(int ac, char** av)
         usleep(10000);
     }
     report(global == 1, "'global' is now 1");
+    sleep(1);
     r = sigaction(SIGUSR1, nullptr, &oldact);
     report(r == 0 && oldact.sa_handler == SIG_DFL, "with SA_RESETHAND, signal handler is reset");
```

What I suspect is happening is that we sleep waiting for global==1 set by the signal handler - but when we recognize it, it's possible the signal handler hasn't yet finished, and therefore also not yet reset. This is why we had the sleep(1) below, to avoid rare crashes. I wonder how this issue became common on your test machine.

**Comment by nyh** [comment]
My explanation above was wrong: kill() (see libc/signal.c) first resets the signal handler, and only then runs it. So it can't be a race like I suggested. Back to the drawing board.

**Comment by justinc1** [comment]
I just wanted to say that a "global=0" after first kill() is missing.

```
diff --git a/tests/tst-kill.cc b/tests/tst-kill.cc
index 249ff53..23197f0 100644
--- a/tests/tst-kill.cc
+++ b/tests/tst-kill.cc
@@ -126,10 +126,12 @@ int main(int ac, char** av)
         usleep(10000);
     }
     report(global == 1, "'global' is now 1");
+
     struct sigaction oldact;
     r = sigaction(SIGUSR1, nullptr, &oldact);
     report(r == 0 && oldact.sa_handler == handler1, "without SA_RESETHAND, signal handler is not reset");
     act.sa_flags = SA_RESETHAND;
+    global = 0;
     r = sigaction(SIGUSR1, &act, nullptr);
     report(r == 0, "set SIGUSR1 handler with SA_RESETHAND");
     r = kill(0, SIGUSR1);
```

**Comment by nyh** [comment]
Good catch. I assume this patch fixes the bug you saw, right? since global was already 1, we would think the signal handler already ran (and was reset), while it wasn't yet run and we just need to sleep a bit more?

**Comment by justinc1** [comment]
Yes, test looks ok now. Patch sent.
