### ISSUE TITLE
DHCP client sets wrong hostname in some circumstances

### ISSUE THREAD

**Issue by wkozaczuk** [cloudius-systems/osv#866]
With some DHCP servers during init OSv ends up setting incorrect hostname osv.local.<domain_name>. This becomes a problem when many OSv instances are running on the same network.

Here is an example of the interaction when it goes wrong:

```
[I/27 dhcp]: Broadcasting DHCPDISCOVER message with xid: [1536021685]
[I/27 dhcp]: Waiting for IP...
[I/195 dhcp]: DHCP received hostname: dhcp-10-191-57-239

[I/195 dhcp]: Received DHCPOFFER message from DHCP server: 10.x.y.z regarding offerred IP address: 10.i.j.k
[I/195 dhcp]: Broadcasting DHCPREQUEST message with xid: [1536021685] to SELECT offered IP: 10.i.j.k
[I/195 dhcp]: DHCP received hostname: osv.local

[I/195 dhcp]: Received DHCPACK message from DHCP server: 10.x.y.z regarding offered IP address: 10.i.j.k
[I/195 dhcp]: Server acknowledged IP 10.i.j.k for interface eth0 with time to lease in seconds: 3600
[I/195 dhcp]: Configuring eth0: ip 10.i.j.k subnet mask 255.255.255.0 gateway 10.g.x.z MTU 1500
```

As part of DHCPDISCOVER message [OSv requests number of properties from the server](https://github.com/cloudius-systems/osv/blob/master/core/dhcp.cc#L212) including host name. In DHCPOFFER reply server sends back (suggested?) HOST NAME option [3.14](https://tools.ietf.org/html/rfc2132) which is ignored by OSv at this point. As part of DHCPREQUEST message [OSv adds HOST NAME option](https://github.com/cloudius-systems/osv/blob/master/core/dhcp.cc#L260) set to the value returned by gethostname which typically would be **osv.local.** In DHCPACK message server returns host name option with the same value that was part of DHCPREQUEST. 

In some setups for example in AWS (probably depends on DHCP type and configuration) DHCP server ignores HOST NAME option in DHCPREQUEST message and returns the same value as in DHCPOFFER. The same interaction looks a little bit different:

```
[I/28 dhcp]: Broadcasting DHCPDISCOVER message with xid: [1454881774]
[I/28 dhcp]: Waiting for IP...
[I/195 dhcp]: DHCP received hostname: ip-172-31-12-238

[I/195 dhcp]: Received DHCPOFFER message from DHCP server: 172.31.0.1 regarding offerred IP address: 172.31.12.238
[I/195 dhcp]: Broadcasting DHCPREQUEST message with xid: [1454881774] to SELECT offered IP: 172.31.12.238
[I/195 dhcp]: DHCP received hostname: ip-172-31-12-238

[I/195 dhcp]: Received DHCPACK message from DHCP server: 172.31.0.1 regarding offerred IP address: 172.31.12.238
[I/195 dhcp]: Server acknowledged IP 172.31.12.238 for interface eth0 with time to lease in seconds: 3600
[I/195 dhcp]: Configuring eth0: ip 172.31.12.238 subnet mask 255.255.240.0 gateway 172.31.0.1 MTU 9001
```

It is not 100% clear to me what the correct behavior should be. In my opinion OSv should be sending back host name that was suggested by DHCP server as part of DHCPOFFER unless it was different from the default **osv.local**. 

[This article](http://www.ingmarverheij.com/configure-hostname-via-dhcp/) seems to describe very well how requesting/setting hostname through DHCP works on LInux. 

Also not sure if #617 is related.

**Comment by wkozaczuk** [comment]
I did a little more research and talked to some DHCP/DNS SMEs and it turns out there are many ways a client may resolve its hostname. In general there are two approaches (there are obviously various flavors and edge cases that apply to both):

1. The hostname is pre-configured on client side and is then propagated to the DHCP/DNS infrastructure and bound with specific IP/MAC address. 
2. The hostname (based on MAC address mapping, etc) is pre-configured on DHCP/DNS infrastructure side and client receives on init.

I think that OSv should (is?) follow the 2nd approach at least as far as DHCP init goes. On other hand there is also [some logic in cloud-init](https://github.com/cloudius-systems/osv/blob/master/modules/cloud-init/cloud-init.cc#L25) that may set/rename the hostname based on what is pre-configured in the cloud provider which maybe be conflicting with it.

Also OSv supports REST API setHostName that can be used to change hostname. It is not clear if in this case what should happen as far as DHCP/DNS infrastructure is related. Possibly the IP should be released and reacquired with new hostname?

Adding @justinc1 as he has touched many relevant parts.

**Comment by justinc1** [comment]
I agree that OSv does (or at least that it makes sense to) follow the 2nd approach. Then, on say openstack, the cloud provided/proposed dns-name/hostname can be pushed to VM either via metadata service or via metadata contextualization image (which is ISO image for normal linux guest). 

In metadata disk case, there is line like "hostname: new-name" - see also https://github.com/cloudius-systems/osv/blob/master/modules/cloud-init/cloud-init.yaml#L10. So we first set hostname, and later use hostname to request corresponding DNS name from DNS server (which is done by renewing DHCP lease, and DHCP server is supposed to do dynamic DNS update). This was implemented to support non-cloudish DHCP/DNS server setup.

If it is legal per RFC to request hostname, without suggesting some value in DHCPDISCOVER/DHCPREQUEST, than we might just not include suggested value into DHCPDISCOVER/DHCPREQUEST packets if our current hostname is "osv" (or is it "osv.local"?).

The whole DNS name register procedure is fragile. After i kill -9 my test VM (started via run.py, without metedata disk), its DHCP lease is still valid for about 1 hour (dnsmasq from libvirt network default). So until that 1 hour expires, no new VM can get the "osv" name. And if I remember correctly, when I restart the same VM (e.g. VM with has same MAC) and request a different DNS name (I added metadata disk), the new VM get same IP as old VM, but does not get a new DNS name.

(sorry for late reply. I started looking into this, got sidetracked, and original reply is still somewhere waiting on me to hit submit button :)

**Comment by justinc1** [comment]
> With some DHCP servers during init OSv ends up setting incorrect hostname osv.local.<domain_name>. This becomes a problem when many OSv instances are running on the same network.

I guess the problem could be services, running on multiple VMs, and using hostname as uniq identifier? Or is it something else?

> In my opinion OSv should be sending back host name that was suggested by DHCP server as part of DHCPOFFER unless it was different from the default osv.local.

I might misunderstand the sentence. The "unless it was different from the default osv.local" - I don't get that part. Maybe you set host name in DHCPREQUEST to the value from DHCPOFFER always, and maybe use hostname only if there is no host name in DHCPOFFER?

**Comment by wkozaczuk** [comment]
By "unless it was different from the default osv.local" I meant that if OSv had a way to specify its hostname in some sort of dhcpclient.conf file and it was different than osv.local then this hostname should be sent as part of DHCPREQUEST instead of what dhcp server suggests if any. But it looks like it is a mute point/case as OSv does not support it.

In any case I have a simple patch ready that sends hostname value suggested in DHCPOFFER (if any) or osv.local as part of DHCPREQUEST.

**Comment by justinc1** [comment]
When cloud-init metadata _disk_ is used the DHCPOFFER-ed hostname could be wrong. I\m preparing patch to cover that case too (I think that the metadata disk hostname option was the only reason I ever looked into dhcp code at all).
