### ISSUE TITLE
Alow environment of `runscript` to override environment hardcoded in script itself

### ISSUE THREAD

**Issue by miha-plesko** [cloudius-systems/osv#870]
Having following content in `/run/startserver` on OSv's disk:
```
# /run/startserver
--env=PORT=8000 myserver.so
```
When I run such unikernel with `capstan run --execute "runscript /run/startserver"` it starts server on port `8000`. Well but sometimes I want to be able to run server on different port without rebuilding the whole unikernel - so by just modifying the bootcmd. If I do for example:
```bash
$ capstan run --execute "--env=PORT=9999 runscript /run/startserver"
```
then I would like to have server started on port `9999`, but current implementation of OSv bootloader starts it on port `8000`. To be honest, `PORT=9999` gets set properly, but as fast as the `runscript` program loads the bootcmd from script, it overrides it to `PORT=8000`...

Q: Could we adjust `runscript` program so that it would invert the priority?

/cc @justinc1  @gberginc

**Comment by justinc1** [comment]
Inverting priority logic seems very illogical to me. As alternative, I would prefer to implement the syntax from bash default parameter value ```FOO=${VARIABLE:-default}``` (this is what @miha-plesko suggested among first things anyway :)

**Comment by miha-plesko** [comment]
@justinc1 just to be clear, is this the usage that would be supported then:
```
# /run/startserver
--env=PORT=${PORT:-8000} myserver.so
```
```bash
$ capstan run --execute "--env=PORT=9999 runscript /run/startserver"
```
?

**Comment by nyh** [comment]
@justinc1 suggestion seems good to me and easy to implement. Even easier if you implement ${PORT-8000} without the ":" - one less byte to parse and one less byte to type :-)

But if you're looking for still more ideas, here another one: right now "--env" supports the assignment operator "=". We can add to it a "make"-like (see http://stackoverflow.com/questions/448910/makefile-variable-assignment) "?=" operator, which sets a value only if not yet set. So the /run/startserver would be:

```
# /run/startserver
--env=PORT?=8000 myserver.so
```

**Comment by justinc1** [comment]
Nice ideas, thank you @nyh. @miha-plesko, that's exactly what you need, right?

**Comment by miha-plesko** [comment]
That is correct, introducing `?=` would be just perfect!

**Comment by justinc1** [comment]
@miha-plesko patch is sent, https://groups.google.com/forum/#!topic/osv-dev/_Nb14wKid3Q in case you want to try it

**Comment by miha-plesko** [comment]
Thank you @justinc1, this seems to be working - the server now starts on the port that I want 🍾 🎆 😄
