### ISSUE TITLE
fs=ramfs build fails with std::bad_alloc during LZ loader-stripped.elf

### ISSUE THREAD

**Issue by justinc1** [cloudius-systems/osv#881]
After fixing #879, I can compile "./scripts/build -j4 mode=release image=openjdk8-zulu-compact3-with-java-beans fs=ramfs". The image=openjdk8-fedora case however still fails, but with entirely different error:

```
  LZ loader-stripped.elf
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
/bin/sh: line 1: 13586 Aborted                 (core dumped) build/release.x64/fastlz/lz build/release.x64/loader-stripped.elf
make: *** [build/release.x64/loader-stripped.elf.lz.o] Error 134
Makefile:457: recipe for target 'build/release.x64/loader-stripped.elf.lz.o' failed
make failed. Exiting from build script
```

**Comment by justinc1** [comment]
```
./scripts/build -j4 mode=release image=openjdk8-fedora fs=ramfs V=1
...
build/release.x64/fastlz/lz build/release.x64/loader-stripped.elf
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Makefile:457: recipe for target 'build/release.x64/loader-stripped.elf.lz.o' failed
make: *** [build/release.x64/loader-stripped.elf.lz.o] Aborted (core dumped)
make failed. Exiting from build script
```

Runnig problematic line under gdb, it fail at
https://github.com/cloudius-systems/osv/blob/master/fastlz/lz.cc#L40
```
output = new char[(int)(input_length*2)];
```
And
```
ll build/release.x64/loader-stripped.elf
-rwxrwxr-x. 1 justin_cinkelj justin_cinkelj 1760707760 Jun  8 22:00 build/release.x64/loader-stripped.elf*
``` 
malloc(3.5 GB) fails :/, I'm so surprised.

I set lzkernel_base := 0x20000000 == 512 MB in Makefile, I really didn't expect 1.7 GB loader size (but more something near 512 MB).

**Comment by wkozaczuk** [comment]
I believe this can be closed as we implemented "almost-in-place" decompression of kernel (https://github.com/cloudius-systems/osv/commit/baf5c301f74a45072cdc551eaf1cd53618958bd6) where we chunk it in 1MB segments and decompress it one by one.
