### ISSUE TITLE
NFS Makefile cleanups

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#895]
Cleanups for "make nfs=true":

Issue 1:
In the Makefile rule for $(out)/libnfs.a, we have a command which looks like
```
        cd $(libnfs-path) && \
        $(call quiet, ./bootstrap) && \
       ...
```
This does not work - $(call quiet) is just a shortcut for "@" and can't be used in the middle of a command, just on the whole command line (note that because of the "\" these few lines are all one command).
What we should do instead is:
```
       @cd $(libnfs-path) && \
       ./bootstrap && \
       ...
```
Note how it's easier to use `@` directly instead of the "call quiet" shortcut - the latter is only useful when you have a second parameter which says what to print instead of the long command.

Issue 2:
This runs libnfs autoconf which has tons of output mixed with the normal slow "make" progress. I think autoconf's output should probably be redirected to /dev/null or to a log file. If we really want to go out of our way (and we probably shouldn't), It's even possible to "cat" this logfile in case autoconf fails.

**Comment by wkozaczuk** [comment]
@nyh,

Given this commit - https://github.com/cloudius-systems/osv/commit/4ffb0fa9329849cd587d62f91b6979bc0e0ce6d1 - is this issue still applicable?

**Comment by nyh** [comment]
No, it's no longer relevant. Thanks. Closing.
