### ISSUE TITLE
Build failed in 'aligned_new.hh' file 

### ISSUE THREAD

**Issue by acsdkquery** [cloudius-systems/osv#898]
Osv build fails, following is the trace. The same issue occurred at line 46 of the same file and it seems fixed by 26/07.

I think, the same fix applicable for this.  

Building into build/release.x64
  GEN gen/include/osv/version.h
  CXX bsd/sys/netinet/tcp_input.cc
In file included from bsd/sys/netinet/tcp_input.cc:93:0:
include/osv/aligned_new.hh: In function ‘void aligned_array_delete(T*)’:
include/osv/aligned_new.hh:60:45: error: expected ‘,’ before ‘)’ token
     static_assert(sizeof(T) > sizeof(size_t));
                                             ^
include/osv/aligned_new.hh:60:45: error: expected string-literal before ‘)’ token
Makefile:363: recipe for target 'build/release.x64/bsd/sys/netinet/tcp_input.o' failed
make: *** [build/release.x64/bsd/sys/netinet/tcp_input.o] Error 1
Build step 'Execute shell' marked build as failure
Finished: FAILUR

**Comment by nyh** [comment]
We fixed this issue in commit 9aba80aa777eeb1e92e8f6a47fcffe909673ef67, this morning. Can you please try to update and check again? Thanks.
