### ISSUE TITLE
Support per-thread standard input/output

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#90]
This issue was raised by @lightpriest.

Unix allows each process to have a different meaning for file descriptors such as 0,1 and 2, and this is how different processes can input/output on different terminals.

We want to allow something similar for _threads_ - i.e., allow two threads to each send output to a different terminal. Right now, all threads which send output to fd 1 will send it the console (even a thread which was started on an ssh session).

Here is one possible solution:

Say we have a struct thread field fdout (and fdin, fderr) whose value is a file descriptor. We create a new type of file descriptor with the function
   perthreadfd(&(thread->fdout))
whose fileops simply call the fileop of the current thread's fd.

When creating a new thread, the new thread will copy its fdout,fdin,fderr values from the creating thread. We also need a function to set the current thread's fds to something else.

In fs/vfs/main.cc, instead of setting fd 0,1,2 to point to the console, we set them to perthreadfd(&(thread->fdin)), perthreadfd(&(thread->fdout)), perthreadfd(&(thread->fderr)). We set the initial thread's thread->fdin, thread->fdout, thread->fderr to all point to the console.

**Comment by wkozaczuk** [comment]
@nyh given you originally created this issue, can you assess if it is still relevant given we are focused on supporting running a single app? Would this be even posix compliant? How would one enable this functionality? In code using some OSv-specific api?

**Comment by nyh** [comment]
I'll close it. It's an idea for a new feature that interested us 8 years ago, but nobody actually wants it today.

**Comment by lightpriest** [comment]
Ohh, wow :D
