### ISSUE TITLE
incorrect upload order when building ramfs image

### ISSUE THREAD

**Issue by justinc1** [cloudius-systems/osv#905]
In apps/nginx/usr.manifest I have:
```
...
/nginx/conf/**: ${MODULE_DIR}/upstream/nginx/conf/**
/nginx/conf/nginx.conf: ${MODULE_DIR}/patches/nginx.conf
```

The ${MODULE_DIR}/upstream/nginx/conf/nginx.conf is from downloaded nginx.tar.gz, and patches/nginx.conf is my modified version. When building zfs version, the patches/nginx.conf overwrites the original one. But when building with fs=ramfs, patches/nginx.conf is in final image.

**Comment by nyh** [comment]
upload_manifest.py (used for normal image building) and mkbootfs.py (used for fs=ramfs) have different implementations of the read_manifest() function: In the former (actually, manifest_common.py now), the manifest file is read into a list, and therefore in order. But in the latter it is read into a hash table and uses some sort of library which also can apparently reorder stuff.

I think the proper solution is to drop mkbootfs.py's implementation of read_manifest and use the one from manifest_common.py.

Note that this still means that *both* versions of the file get uploaded into the image, which is kind of silly (and wasteful if the file is not very small). I think the real solution in your case isn't to to fix the read_manifest() inconsistency, but to delete upstream/nginx/conf/nginx.conf in the Makefile, so it won't get uploaded at all and only the one from patches/ will.

**Comment by justinc1** [comment]
That is what I did then (removed upstream/nginx/conf/nginx.conf).

**Comment by geraldo-netto** [comment]
Dear Friends,

I don't know if it's still relevant but  have sent some patches regarding this:
https://groups.google.com/forum/#!topic/osv-dev/yLpeBPj3lIU
https://groups.google.com/forum/#!topic/osv-dev/U8wKnLKvfmY

Kind Regards,
Geraldo Netto
