### ISSUE TITLE
lzloader miscompiles on gcc 6.2.0

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#913]
Rick Payne @rickpayne reported on the mailing list in December 15, 2016 that:
```
I’ve been setting up a small testbed with some intel nuc computers. I just stuffed the latest Ubuntu (16.10) on them as thats what I had to hand. Images that I build on another machine (Ubuntu 16.04) run fine. Downgrading is hard (we’re fairly remote with poor connectivity, but do have a mirror of 16.10 hence why we used that).
However, I can’t build an OSv image on the nuc. The build gets to the point where its about to cpio the files into an image, but the image never starts properly. It stops here:
...
  LZ loader-stripped.elf
  OBJCOPY loader-stripped.elf.lz -> loader-stripped.elf.lz.o
  LINK lzloader.elf
  ALIGN lzloader.elf
  DD loader.img boot.bin
  DD loader.img lzloader.elf
  IMGEDIT build/release.x64/loader.img
  IMGEDIT build/release.x64/loader.img
qemu-system-x86_64: -redir tcp:10000::10000: The -redir option is deprecated. Please use '-netdev user,hostfwd=...' instead.

Is there any known issue building with gcc/g++ version 6.2.0 20161005? Thats the main difference between the machines (other than one is a VM on my laptop and the other is a proper intel machine).

Any suggestions as to where to start looking to debug this? The process ends up taking a lot of CPU but if I connect to it using the usual ‘gdb build/debug/loader.elf’ and ‘connect’, it doesn’t look like the process has started…

Reading symbols from build/debug/loader.elf...done.
(gdb) connect
warning: remote target does not support file transfer, attempting to access files from local filesystem.
warning: Unable to find dynamic linker breakpoint function.
GDB will be unable to debug shared library initializers
and track explicitly loaded dynamic code.
0x0000000000000000 in ?? ()
```

5 days later he came up with a workaround:

In case anyone else runs into this, its a problem with optimisation of lzloader which causes it to fail to decompress properly. If I compile lzloader without optimisation, then the build proceeds fine. I’m using this patch:

```patch
diff --git a/Makefile b/Makefile
index 3ef3b54..d7e6121 100644
--- a/Makefile
+++ b/Makefile
@@ -462,7 +462,8 @@ $(out)/loader-stripped.elf.lz.o: $(out)/loader-stripped.elf $(out)/fastlz/lz

 $(out)/fastlz/lzloader.o: fastlz/lzloader.cc | generated-headers
        $(makedir)
-       $(call quiet, $(CXX) $(CXXFLAGS) -O2 -m32 -fno-instrument-functions -o $@ -c fastlz/lzloader.cc, CXX $<)
+       # $(call quiet, $(CXX) $(CXXFLAGS) -O2 -m32 -fno-instrument-functions -o $@ -c fastlz/lzloader.cc, CXX $<)
+       $(call quiet, $(CXX) $(CXXFLAGS) -g -m32 -fno-instrument-functions -o $@ -c fastlz/lzloader.cc, CXX $<)

 $(out)/lzloader.elf: $(out)/loader-stripped.elf.lz.o $(out)/fastlz/lzloader.o arch/x64/lzloader.ld \
        $(out)/fastlz/fastlz.o
```

Today he sent a reminder and said he was using this patch:
```patch
diff --git a/Makefile b/Makefile
index 8372cd8..50fb396 100644
--- a/Makefile
+++ b/Makefile
@@ -446,11 +446,11 @@ $(out)/arch/x64/boot32.o: $(out)/loader.elf

$(out)/fastlz/fastlz.o:
       $(makedir)
-       $(call quiet, $(CXX) $(CXXFLAGS) -O2 -m32 -fno-instrument-functions -o $@ -c fastlz/fastlz.cc, CXX fastlz/fastlz
.cc)
+       $(call quiet, $(CXX) $(CXXFLAGS) -O0 -g -m32 -fno-instrument-functions -o $@ -c fastlz/fastlz.cc, CXX fastlz/fas
tlz.cc)

$(out)/fastlz/lz: fastlz/fastlz.cc fastlz/lz.cc | generated-headers
       $(makedir)
-       $(call quiet, $(CXX) $(CXXFLAGS) -O2 -o $@ $(filter %.cc, $^), CXX $@)
+       $(call quiet, $(CXX) $(CXXFLAGS) -O0 -g -o $@ $(filter %.cc, $^), CXX $@)

$(out)/loader-stripped.elf.lz.o: $(out)/loader-stripped.elf $(out)/fastlz/lz
       $(call quiet, $(out)/fastlz/lz $(out)/loader-stripped.elf, LZ loader-stripped.elf)
@@ -459,7 +459,7 @@ $(out)/loader-stripped.elf.lz.o: $(out)/loader-stripped.elf $(out)/fastlz/lz
$(out)/fastlz/lzloader.o: fastlz/lzloader.cc | generated-headers
       $(makedir)
       #$(call quiet, $(CXX) $(CXXFLAGS) -O2 -m32 -fno-instrument-functions -o $@ -c fastlz/lzloader.cc, CXX $<)
-       $(call quiet, $(CXX) $(CXXFLAGS) -g -m32 -fno-instrument-functions -o $@ -c fastlz/lzloader.cc, CXX $<)
+       $(call quiet, $(CXX) $(CXXFLAGS) -O0 -g -m32 -fno-instrument-functions -o $@ -c fastlz/lzloader.cc, CXX $<)

$(out)/lzloader.elf: $(out)/loader-stripped.elf.lz.o $(out)/fastlz/lzloader.o arch/x64/lzloader.ld \
       $(out)/fastlz/fastlz.o
```

**Comment by nyh** [comment]
I asked @rickpayne on the mailing list whether it's enough to change the compilation of just one file (as in the first patch) or all files (as in the second patch). He responde: "It does indeed seem that the original patch is sufficient. It wasn’t at one time, I’m sure - but for now I can use the single change for both debug and release images."

```
    $(call quiet, $(CXX) $(CXXFLAGS) -O0 -m32 -fno-instrument-functions -o $@ -c fastlz/lzloader.cc, CXX $<)
```

He then said: "Its such a small file, but my assembler foo is very rusty. Attached are objdumps of the two resulting compiles of lzloader.o, one with -O0 which results in a working image, and one with -O1 with results in a hang as the VM starts."

O0 (working):
```
build/release.x64/fastlz/lzloader.o:     file format elf32-i386
Disassembly of section .text:

00000000 <memset>:
extern char _binary_loader_stripped_elf_lz_end;
extern char _binary_loader_stripped_elf_lz_size;

// std libraries used by fastlz.
extern "C" void *memset(void *s, int c, size_t n)
{
   0:	55                   	push   %ebp
   1:	89 e5                	mov    %esp,%ebp
   3:	53                   	push   %ebx
   4:	83 ec 04             	sub    $0x4,%esp
   7:	e8 fc ff ff ff       	call   8 <memset+0x8>
   c:	05 01 00 00 00       	add    $0x1,%eax
    return __builtin_memset(s, c, n);
  11:	83 ec 04             	sub    $0x4,%esp
  14:	ff 75 10             	pushl  0x10(%ebp)
  17:	ff 75 0c             	pushl  0xc(%ebp)
  1a:	ff 75 08             	pushl  0x8(%ebp)
  1d:	89 c3                	mov    %eax,%ebx
  1f:	e8 fc ff ff ff       	call   20 <memset+0x20>
  24:	83 c4 10             	add    $0x10,%esp
}
  27:	8b 5d fc             	mov    -0x4(%ebp),%ebx
  2a:	c9                   	leave  
  2b:	c3                   	ret    

0000002c <uncompress_loader>:

extern "C" void uncompress_loader()
{
  2c:	55                   	push   %ebp
  2d:	89 e5                	mov    %esp,%ebp
  2f:	53                   	push   %ebx
  30:	83 ec 04             	sub    $0x4,%esp
  33:	e8 fc ff ff ff       	call   34 <uncompress_loader+0x8>
  38:	05 01 00 00 00       	add    $0x1,%eax
    // pass a the last (maxout) parameter of fastlz_decompress. Let it
    // uncompress as much as it has input. The Makefile already verifies
    // that the uncompressed kernel doesn't overwrite this uncompression code.
    // Sadly, "INT_MAX" is the largest number we can pass. If we ever need
    // more than 2GB here, it won't work.
    fastlz_decompress(&_binary_loader_stripped_elf_lz_start,
  3d:	8b 90 00 00 00 00    	mov    0x0(%eax),%edx
            (size_t) &_binary_loader_stripped_elf_lz_size,
            BUFFER_OUT, INT_MAX);
  43:	68 ff ff ff 7f       	push   $0x7fffffff
  48:	68 00 00 20 00       	push   $0x200000
  4d:	52                   	push   %edx
  4e:	8b 90 00 00 00 00    	mov    0x0(%eax),%edx
  54:	52                   	push   %edx
  55:	89 c3                	mov    %eax,%ebx
  57:	e8 fc ff ff ff       	call   58 <uncompress_loader+0x2c>
  5c:	83 c4 10             	add    $0x10,%esp
}
  5f:	90                   	nop
  60:	8b 5d fc             	mov    -0x4(%ebp),%ebx
  63:	c9                   	leave  
  64:	c3                   	ret    

Disassembly of section .text.__x86.get_pc_thunk.ax:

00000000 <__x86.get_pc_thunk.ax>:
{
   0:	8b 04 24             	mov    (%esp),%eax
   3:	c3                   	ret    
```

O1 (not working):
```
build/release.x64/fastlz/lzloader.o:     file format elf32-i386
Disassembly of section .text:

00000000 <memset>:
extern char _binary_loader_stripped_elf_lz_end;
extern char _binary_loader_stripped_elf_lz_size;

// std libraries used by fastlz.
extern "C" void *memset(void *s, int c, size_t n)
{
   0:	55                   	push   %ebp
   1:	89 e5                	mov    %esp,%ebp
   3:	53                   	push   %ebx
   4:	83 ec 08             	sub    $0x8,%esp
   7:	e8 fc ff ff ff       	call   8 <memset+0x8>
   c:	81 c3 02 00 00 00    	add    $0x2,%ebx
    return __builtin_memset(s, c, n);
  12:	ff 75 10             	pushl  0x10(%ebp)
  15:	ff 75 0c             	pushl  0xc(%ebp)
  18:	ff 75 08             	pushl  0x8(%ebp)
  1b:	e8 fc ff ff ff       	call   1c <memset+0x1c>
}
  20:	8b 5d fc             	mov    -0x4(%ebp),%ebx
  23:	c9                   	leave  
  24:	c3                   	ret    

00000025 <uncompress_loader>:

extern "C" void uncompress_loader()
{
  25:	55                   	push   %ebp
  26:	89 e5                	mov    %esp,%ebp
  28:	53                   	push   %ebx
  29:	83 ec 04             	sub    $0x4,%esp
  2c:	e8 fc ff ff ff       	call   2d <uncompress_loader+0x8>
  31:	81 c3 02 00 00 00    	add    $0x2,%ebx
    // that the uncompressed kernel doesn't overwrite this uncompression code.
    // Sadly, "INT_MAX" is the largest number we can pass. If we ever need
    // more than 2GB here, it won't work.
    fastlz_decompress(&_binary_loader_stripped_elf_lz_start,
            (size_t) &_binary_loader_stripped_elf_lz_size,
            BUFFER_OUT, INT_MAX);
  37:	68 ff ff ff 7f       	push   $0x7fffffff
  3c:	68 00 00 20 00       	push   $0x200000
  41:	ff b3 00 00 00 00    	pushl  0x0(%ebx)
  47:	ff b3 00 00 00 00    	pushl  0x0(%ebx)
  4d:	e8 fc ff ff ff       	call   4e <uncompress_loader+0x29>
}
  52:	83 c4 10             	add    $0x10,%esp
  55:	8b 5d fc             	mov    -0x4(%ebp),%ebx
  58:	c9                   	leave  
  59:	c3                   	ret    

Disassembly of section .text.__x86.get_pc_thunk.bx:

00000000 <__x86.get_pc_thunk.bx>:
{
   0:	8b 1c 24             	mov    (%esp),%ebx
   3:	c3                   	ret    
```

**Comment by nyh** [comment]
Hi @rickpayne. It's easier to understand the compilation results if we disassemble the final executable, not disassemble the object file (which contains quite a bit of pre-linking complications) with something like `objdump -D build/release/lzloader.elf`.`

In this object dump I see - on my own machine (with a different compiler) - something really suspicious:
```
01801000 <memset>:
 1801000:       55                      push   %ebp
 1801001:       89 e5                   mov    %esp,%ebp
 1801003:       5d                      pop    %ebp
 1801004:       eb fa                   jmp    1801000 <memset>
 1801006:       8d 76 00                lea    0x0(%esi),%esi
 1801009:       8d bc 27 00 00 00 00    lea    0x0(%edi,%eiz,1),%edi
```

See, memset() calling itself! It should call some builtin code, not itself, but obviously this trick did not actually work.
In my machine, this broken memset() function is never actually called - in neither debug or release build. Is it possible on your compiler, with optimizations enabled, it does get called?

Can you please try commenting out the entire memset() definition in lzloader.c and see what breaks? On my machine nothing breaks - it's not used at all. I am guessing on your machine it does get used somehow, and you'll get an error building without it, but which error?

**Comment by nyh** [comment]
@rickpayne I just sent two patches to the OSv mailing list to fix lzloader by implementing memset() correctly instead of infinite recursion. Can you please test them? Thanks.

**Comment by rickpayne** [comment]
> On 11 Oct 2017, at 00:50, nyh <notifications@github.com> wrote:
> 
> @rickpayne I just sent two patches to the OSv mailing list to fix lzloader by implementing memset() correctly instead of infinite recursion. Can you please test them? Thanks.

They didn’t solve the problem - compelling with -O1 still results in an image which fails to boot.

Commenting out the memset() function made no difference - it didn’t provoke a compile failure.

This is the broken uncompress_loader (-O1 with your 2 patches applied):

01801085 <uncompress_loader>:
 1801085:       55                      push   %ebp
 1801086:       89 e5                   mov    %esp,%ebp
 1801088:       53                      push   %ebx
 1801089:       83 ec 04                sub    $0x4,%esp
 180108c:       e8 16 11 00 00          call   18021a7 <__x86.get_pc_thunk.bx>
 1801091:       81 c3 c7 2d 65 00       add    $0x652dc7,%ebx
 1801097:       68 ff ff ff 7f          push   $0x7fffffff
 180109c:       68 00 00 20 00          push   $0x200000
 18010a1:       ff b3 fc ff ff ff       pushl  -0x4(%ebx)
 18010a7:       ff b3 f8 ff ff ff       pushl  -0x8(%ebx)
 18010ad:       e8 ae 0b 00 00          call   1801c60 <_Z17fastlz_decompressPKviPvi>
 18010b2:       83 c4 10                add    $0x10,%esp
 18010b5:       8b 5d fc                mov    -0x4(%ebp),%ebx
 18010b8:       c9                      leave
 18010b9:       c3                      ret
 18010ba:       66 90                   xchg   %ax,%ax
 18010bc:       66 90                   xchg   %ax,%ax
 18010be:       66 90                   xchg   %ax,%ax

And this is the working one (-O0 with your 2 patches applied):

01801098 <uncompress_loader>:
 1801098:       55                      push   %ebp
 1801099:       89 e5                   mov    %esp,%ebp
 180109b:       53                      push   %ebx
 180109c:       83 ec 04                sub    $0x4,%esp
 180109f:       e8 23 11 00 00          call   18021c7 <__x86.get_pc_thunk.ax>
 18010a4:       05 94 2d 65 00          add    $0x652d94,%eax
 18010a9:       c7 c2 95 18 65 00       mov    $0x651895,%edx
 18010af:       68 ff ff ff 7f          push   $0x7fffffff
 18010b4:       68 00 00 20 00          push   $0x200000
 18010b9:       52                      push   %edx
 18010ba:       c7 c2 40 25 80 01       mov    $0x1802540,%edx
 18010c0:       52                      push   %edx
 18010c1:       89 c3                   mov    %eax,%ebx
 18010c3:       e8 b8 0b 00 00          call   1801c80 <_Z17fastlz_decompressPKviPvi>
 18010c8:       83 c4 10                add    $0x10,%esp
 18010cb:       90                      nop
 18010cc:       8b 5d fc                mov    -0x4(%ebp),%ebx
 18010cf:       c9                      leave
 18010d0:       c3                      ret
 18010d1:       66 90                   xchg   %ax,%ax
 18010d3:       66 90                   xchg   %ax,%ax
 18010d5:       66 90                   xchg   %ax,%ax
 18010d7:       66 90                   xchg   %ax,%ax
 18010d9:       66 90                   xchg   %ax,%ax
 18010db:       66 90                   xchg   %ax,%ax
 18010dd:       66 90                   xchg   %ax,%ax
 18010df:       90                      nop

Cheers,
Rick

**Comment by nyh** [comment]
Interesting, so the memset() was just a red herring - it's buggy, but completely unrelated because it's never called...

My next guess is that the hang you see is not caused by an endless loop (which I can't find), but rather some sort of unhandled exception. Maybe there's a way to debug even this early code in gdb. But looking at the two snippets, I am not sure what's really different. It really looks very similar, with some difference on the before-last pushes, which seems to be different (in the working code it pushes what seems to be a relative address, in the broken code it pushes an absolute address). I'm not familiar enough with this stuff to say if one of them is actually wrong.

I'm starting to think we should just to compile this file without optimization, and stop trying to understand what went wrong :-) Can you please send a minimal patch which does this to the mailing list, and I'll apply? Thanks.
