### ISSUE TITLE
scripts/loader.py is not python3 compatible

### ISSUE THREAD

**Issue by lynus** [cloudius-systems/osv#916]
Some osv commands don't work within a python3-supported gdb.
For example osv heap gives the following output:

> Python Exception <class 'TypeError'> %x format: an integer is required, not gdb.Value:
> Error occurred in Python command: %x format: an integer is required, not gdb.Value

A minor fix is needed to make the print statements of the script python3 compatible.

**Comment by nyh** [comment]
Thanks. Something like wrapping the value with the int() function?
Can you please send a patch for this? Thanks.

**Comment by geraldo-netto** [comment]
Hello @lynus ,

Could you point out which files are affected?
Apparently, all we need to do is cast the gdb.value to int which means "int(gdb_variable)"


Kind Regards,
Geraldo Netto

**Comment by wkozaczuk** [comment]
@nyh, @lynus 

Did this commit - https://github.com/cloudius-systems/osv/commit/228190adf949164ec83acea791dad72f5c8f0f75 - resolve this issue?

**Comment by nyh** [comment]
I think we can close this issue. I don't know if we solved *all* the issues - I didn't test each and every "osv ..." feature implemented in loader.py. But you test that the "osv heap" mentioned above works, I think we can close this issue. If we ever find more problems with loader.py, we'll open a new issue - we don't need to keep around a generic issue saying that "it doesn't work".

**Comment by wkozaczuk** [comment]
I do not remember if I have tested 100% of osv commands with gdb when I was working on converting to Python 3 but at least `osv heap` should work as expected:

```
(gdb) py
>import sys
>print(sys.version)
>end
3.7.5 (default, Apr 19 2020, 20:18:17) 
[GCC 9.2.1 20191008]
(gdb) osv heap
0xffff800002afc000 0x000000007cf04000
0xffff800002add000 0x0000000000001000
0xffff800002af4000 0x0000000000003000
(gdb) 
```
