### ISSUE TITLE
OSv hangs on VirtualBox/OSX when booting

### ISSUE THREAD

**Issue by wkozaczuk** [cloudius-systems/osv#917]
4 out of 5 times when running under VirtualBox on OSX OSv hangs right after initializing networking but before mounting file system. At the some time same image behaves just fine under QEMU on OSx. 

I am suspecting this issue is caused by some kind of race condition during AHCI initialization stage that possibly leads to a deadlock. I have been experiencing this issue under VirtualBox on OSX ever since I started playing with OSv over year ago so I do not think it is caused by new changes but rather confined to drivers/ahci.cc code. 

Here is the verbose console output when OSv hangs (please note I added extra debug statements in ahci.cc):
`OSv v0.24-450-g44f2050`
`4 CPUs detected`
`Firmware vendor: innotek GmbH`
`bsd: initializing - done`
`VFS: mounting ramfs at /`
`VFS: mounting devfs at /dev`
`net: initializing - done`
`eth0: ethernet address: 08:00:27:f3:67:91` 
`virtio-net: Attached ethernet interface`
`hba::probe`
`hba::probe`
`hba::probe`
`AHCI: before reset`
`AHCI: before setup`
`AHCI: before enable_irq`
`AHCI: before scan`

On other hand when it succeeds the output is as follows:
`OSv v0.24-450-g44f2050`
`4 CPUs detected`
`Firmware vendor: innotek GmbH`
`bsd: initializing - done`
`VFS: mounting ramfs at /`
`VFS: mounting devfs at /dev`
`net: initializing - done`
`eth0: ethernet address: 08:00:27:1f:cf:76`
`virtio-net: Attached ethernet interface`
`virtio-net: Finished initializing`
`hba::probe`
`hba::probe`
`hba::probe`
`AHCI: before reset`
`AHCI: before setup`
`AHCI: before enable_irq`
`AHCI: before scan`
`AHCI:scan:checking port 0!`
`AHCI:scan:About to create device for port 0!`
`AHCI:scan:Created device for port 0!`
`AHCI:scan:Before adding port 0!`
`AHCI:scan:Before read_partition_table for port 0!`
`AHCI: Add sata device port 0 as vblk0, devsize=268435456`
`AHCI:scan:checking port 1!`
`AHCI:scan:checking port 2!`
`AHCI:scan:checking port 3!`
`....`
`AHCI:scan:checking port 29!`
`AHCI:scan:Finished!`
`AHCI: after scan`
`hba::probe`
`hba::probe`
`vga: Add VGA device instance`
`hba::probe`
`random: intel drng, rdrand registered as a source.`
`random: <Software, Yarrow> initialized`
`VFS: unmounting /dev`
`VFS: mounting zfs at /zfs`
`zfs: mounting osv/zfs from device /dev/vblk0.1`
`random: device unblocked.`
`VFS: mounting devfs at /dev`
`VFS: mounting procfs at /proc`

Also once OSv boots successfully it continues to behave properly with no other issues at least in all tested cases.

I am not sure if there is any better (less primitive way) way of debugging this problem apart from printing to the console. Can somehow OSv be run under gdb control in VirtualBox on OSX so that one can attach remotely and get better diagnostics? Or is it simply too early in the boot process to do so? 

I have added even **more debug statements to [ahci.cc](https://github.com/wkozaczuk/osv/blob/0330550068587cf69969d176dbd347ff6195fa15/drivers/ahci.cc)** that show which thread is executing what by using following macro:

`#define AHCI_DEBUG1(message,arg) debug("AHCI :%d:" message "\n", gettid(), arg);`

With that I could narrow down where roughly OSv hangs:
`OSv v0.24-455-ga387aaa`
`4 CPUs detected`
`Firmware vendor: innotek GmbH`
`bsd: initializing - done`
`VFS: mounting ramfs at /`
`VFS: mounting devfs at /dev`
`net: initializing - done`
`eth0: ethernet address: 08:00:27:92:14:3f`
`virtio-net: Attached ethernet interface`
`virtio-net: Finished initializing`
`AHCI :42:hba::probe`
`AHCI :42:hba::probe`
`AHCI :42:hba::probe`
`AHCI :42:before reset`
`AHCI :42:before setup`
`AHCI :42:before enable_irq`
`AHCI :42:before scan`
`AHCI :42:scan:checking port 0!`
`AHCI :42:port_readl: [0018]`
`AHCI :42:port_writel: [0014]`
`AHCI :42:port_readl: [0010]`
`AHCI :42:port_writel: [0010]`
`AHCI :42:port(): after reset`
`AHCI :42:port_writel: [0000]`
`AHCI :42:port_writel: [0004]`
`AHCI :42:port_writel: [0008]`
`AHCI :42:port_writel: [000C]`
`AHCI :42:port_readl: [0018]`
`AHCI :42:port_writel: [0018]`
`AHCI :42:port_writel: [0018]`
`AHCI :42:port_readl: [0028]`
`AHCI :42:port_readl: [0030]`
`AHCI :42:port_writel: [0030]`
`AHCI :42:port_readl: [0020]`
`AHCI :42:port_writel: [0018]`
**`AHCI :48:port::req_done:Interrupt handler thread started !!!`
`AHCI :48:port::done_mask:In`
`AHCI :48:port::done_mask:_cmd_active = 0`**
`AHCI :42:port(): after setup`
`AHCI :42:port_writel: [0038]`
`AHCI :42:port::send_cmd-> after lock`
`AHCI :42:port_readl: [0010]`
`AHCI :42:port_writel: [0010]`
`AHCI :42:port_readl: [0020]`
`AHCI :42:port_readl: [0038]`
`AHCI :42:port(): after disk_identify`
`AHCI :42:port_readl: [0014]`
`AHCI :42:port_writel: [0014]`
`AHCI :42:port(): after enable_irq`
`AHCI :42:scan:After creating port for port 0!`
`AHCI :42:scan:About to create device for port 0!`
`AHCI :42:scan:Created device for port 0!`
`AHCI :42:scan:Before adding port 0!`
`AHCI :42:scan:Before read_partition_table for port 0!`
`device:42:read_partition_table:Before bread() for vblk0!`
`AHCI :42:port_writel: [0038]`
`AHCI :42:port::send_cmd-> after lock`
`AHCI :42:port::disk_rw:Before poll_mode_done`
`AHCI :42:port::disk_rw:After poll_mode_done`
`vfs_bio:42:BEFORE bio_wait`

Based on my analysis it seems that the interrupt handler thread 48 successfully starts and loops only once and never gets to handle possible interrupt raised when rw_buf() in vfs_bio.cc is called -
 last statement `vfs_bio:42:BEFORE bio_wait` is from this file. I wonder if there is some kind of deadlock around _cmd_lock that prevents this code in port::req_done() to execute again (or maybe I am misreading it):

`        WITH_LOCK(_cmd_lock) {
            sched::thread::A(_cmd_lock, [&] { mask = this->done_mask(); return mask != 0x0; });
        }
`

I have also noticed that with more logging when OSv succeeds mounting the filesystem it ends up crashing later like so (which maybe different issue):

`AHCI:42:scan:Created device for port 0!`
`AHCI:42:scan:Before adding port 0!`
`AHCI:42:scan:Before read_partition_table for port 0!`
`device:42:read_partition_table:Before bread() for vblk0!`
`AHCI:42:port_writel: [0038]`
`AHCI:42:port::send_cmd-> after lock`
`AHCI:11:port_readl: [0010]`
`AHCI:42:port::disk_rw:Before poll_mode_done`
`AHCI:11:port_writel: [0010]`
`AHCI:48:port::done_mask:In`
`AHCI:42:port::disk_rw:After poll_mode_done`
`AHCI:48:port::done_mask:_cmd_active = 1`
`vfs_bio:42:BEFORE bio_wait`
`AHCI:48:port::done_mask:Before port_readl`
`AHCI:48:port_readl: [0038]`
`AHCI:48:port::done_mask:port_readl read 0`
`AHCI:48:port::req_done:After lock`
`AHCI:48:port::req_done:After load`
`AHCI:48:port::req_done:Before biodone`
`vfs_bio:42:AFTER bio_wait`
`AHCI:48:port::req_done:After biodone`
`device:42:read_partition_table:Before acquiring lock() for vblk0!`
`AHCI:48:port::done_mask:In`
`device:42:read_partition_table:After acquiring lock() for vblk0!`
`device:42:read_partition_table:Before creating device for vblk0!`
`device:42:read_partition_table:After creating device for vblk0!`
`device:42:read_partition_table:Before device_set_softc for vblk0!`
`device:42:read_partition_table:Before releasing lock() for vblk0!`
`device:42:read_partition_table:Before brelse for vblk0!`
`AHCI:42:Add sata device port 0 as vblk0, devsize=268435456`
`AHCI:42:scan:checking port 1!`
`AHCI:42:port_readl: [0018]`
`AHCI:42:port_writel: [0014]`
`AHCI:42:port_readl: [0010]`
`AHCI:42:port_writel: [0010]`
`AHCI:42:port(): after reset`
`AHCI:42:port_writel: [0000]`
`AHCI:42:port_writel: [0004]`
`AHCI:42:port_writel: [0008]`
`AHCI:42:port_writel: [000C]`
`AHCI:42:port_readl: [0018]`
`AHCI:42:port_writel: [0018]`
`AHCI:42:port_writel: [0018]`
`AHCI:42:port_readl: [0028]`
`AHCI:42:port_readl: [0028]`
`AHCI:42:port_readl: [0028]`
`AHCI:42:port_readl: [0028]`
`AHCI:42:port_readl: [0028]`
`AHCI:42:port_readl: [0028]`
`AHCI:42:port_readl: [0028]`
`AHCI:42:port_readl: [0028]`
`AHCI:42:port_readl: [0028]`
`AHCI:42:port_readl: [0028]`
`AHCI:42:port_readl: [0028]`
`AHCI:42:port_readl: [0028]`
`AHCI:42:port_readl: [0028]`
`AHCI:42:port_readl: [0028]`
`AHCI:42:port_readl: [0028]`
`AHCI:42:port_readl: [0028]`
`AHCI:42:port_readl: [0028]`
`AHCI:42:port(): after setup`
`AHCI:42:scan:After creating port for port 1!`
`AHCI:42:scan:checking port 2!`
`AHCI:42:port_readl: [0018]`
`AHCI:42:port_writel: [0014]`
`AHCI:42:port_readl: [0010]`
`AHCI:42:port_writel: [0010]`
`AHCI:42:port(): after reset`
`AHCI:42:port_writel: [0000]`
`AHCI:42:port_writel: [0004]`
`AHCI:42:port_writel: [0008]`
`AHCI:42:port_writel: [000C]`
`AHCI:42:port_readl: [0018]`
`AHCI:42:port_writel: [0018]`
`AHCI:42:port_writel: [0018]`
`AHCI:42:port_readl: [0028]`
`AHCI:42:port_readl: [0028]`
`AHCI:42:port_readl: [0028]`
`AHCI:42:port_readl: [0028]`
`AHCI:42:port_readl: [0028]`
`AHCI:42:port_readl: [0028]`
`AHCI:42:port_readl: [0028]`
`AHCI:42:port_readl: [0028]`
`AHCI:42:port_readl: [0028]`
``
`VFS: mounting zfs at /zfs`
`AHCI:42:port_writel: [0038]`
`AHCI:42:port_readl: [0010]`
`AHCI:42:port_writel: [0010]`
`AsserAtHiCoI:n4 2fa:ipolerdt::: spreendem_pcmtab-e(>)  af(itenrc luldoec/ko`
`sv/sched.hh: do_wait_until: 1047)`
``
**`[backtrace]`
`0x0000000000225868 <__assert_fail+24>`
`0x00000000003c395e <lockfree::mutex::lock()+510>`
`0x0000000000339013 <console::console_multiplexer::write(char const*, unsigned long)+83>`
`0x0000000000374d80 <void debug<long>(char const*, long)+32>`
`0x000000000037311b <ahci::port::done_mask()+27>`
`0x0000000000373264 <ahci::port::req_done()+164>`
`0x00000000003733cb <???+3617739>`
`0x00000000003e4c06 <thread_main_c+38>`**

I am at loss what could be the exact root cause or how to make progress diagnosing it. So any help would be appreciated.

I think it would be very nice to identify and fix this issue as VirtualBox is way more popular emulator than QEMU on OSx. It also runs way faster (if starts successfully) than under QEMU. Also I have not tested running OSv under VirtualBox on Linux so I wonder if this issue is VirtualBox/OSX or simply VirtualBox specific.

**Comment by nyh** [comment]
Hi, I'm unfortunately not familiar with this code (@asias is), so I'll try to help as much as I can as a first-time reader.
First of all, there is no _cmdlock deadlock as far as I can see. The code which does:
```c++
        WITH_LOCK(_cmd_lock) {
            sched::thread::wait_until(_cmd_lock, [&] { mask = this->done_mask(); return mask != 0x0; });
        }
```
Takes the _cmd_lock lock, but then releases it while waiting, and takes it back when waking up - and then when the _cmd_lock is released when the WITH_LOCK block ends. While waiting, the lock is released so send_cmd can take it.

However, I have a bad feeling about the _cmd_lock code - maybe I just don't understand it, but it looks wrong to because when the wait_until predicate (the done_mask() check) is done, the mutex is NOT taken, and I think it needs to be for the check to be correct (there's even a comment in the code explaining why this lock is needed). I wonder if the above quoted code (including the WITH_LOCK) should not be replaced by something like this instead:

```c__
        sched::thread::wait_until([&] { WITH_LOCK(_cmd_lock) { mask = this->done_mask(); return mask != 0x0; } });
```

So that we hold the lock while testing done_mask() - not before and after we do it...

Can you please try that if it helps?

The last error you saw is just because of the printout: The sched::thread::wait_until() predicate - the function it tests - req_done() - is run in preemption disabled context. So it must not do memory allocations, and printing to the console sometimes (rarely) does. Sadly even debug_ll() no longer 100% works in preemption disabled contexts (see issue #533 and #731), so unless we fix that, you should just ignore these rare crashes while you add debugging printouts.

**Comment by nyh** [comment]
Sorry, my comment above is wrong... wait_until does keep _cmd_lock taken while testing the predicate - it only releases it when actually going to sleep when the predicate is false. So I think the existing code should be fine... And yet it doesn't work....

**Comment by nyh** [comment]
Hmm, two things I don't understand in the current code:

1. port::send_cmd() does `port_writel(PORT_CI, 1U << slot);`. Shouldn't this also include the previously set bits? I.e., `port_writel(PORT_CI, _cmd_active)`?

2. Shouldn't the WITH_LOCK in req_done include the **entire** functions, not just the small part it currently includes? I'm worried that the code below that sets _cmd_active does it without locking. I think this probably can't explain the bug you're seeing, though...

**Comment by wkozaczuk** [comment]
Do you have any suggestions where to put next debug statements to get more clarity what exactly the problem is?

Is it also valid to say that irq_thread never gets awaken (port::wakeup())?

**Comment by nyh** [comment]
I don't know, you added some pretty good printouts. I would first try my two last guesses (changing the port_writel(PORT_CI) line and making the WITH_LOCK bigger) and see if it helps.

Yes, from your printout it does seem like the irq_thread never got woken. You can perhaps add (if you didn't already) printouts in hba::ack_irq() to see if gets called, and if not why it doesn't call power->wakeup(). My guess was that it doesn't get called at all, which may mean we didn't set PORT_CI to **ask** to be woken for this slot, which is why I guessed the PORT_CI setting was wrong. But it's just a guess...

**Comment by wkozaczuk** [comment]
I think I have found the culprit which is also pretty trivial to fix.

I have added more logging to enable_irq() method like so:

```
void hba::enable_irq()
{
    AHCI_DEBUG0("hba::enable_irq(): in")
      if (poll_mode()) {
        return;
    }

    // Enable Interrupts
    auto ghc = hba_readl(HOST_GHC);
    ghc |= HOST_GHC_IE;
    hba_writel(HOST_GHC, ghc);

    if (_pci_dev.is_msix() || _pci_dev.is_msi() ) {
        AHCI_DEBUG0("hba::enable_irq(): msi enabled")
        _msi.easy_register({ { 0, [=] { ack_irq(); }, nullptr} });
    } else {
        AHCI_DEBUG0("hba::enable_irq(): gsi enabled")
        _gsi.reset(new gsi_level_interrupt(_pci_dev.get_interrupt_line(),
                                           [=] { return ack_irq(); }, [] {}));
    }
}
```

I have noticed that randomly I could see "msi enabled" or "gsi enabled" which seemed weird. I looked at the function definition which has is_msi() and is_msix() methods. To my surprise it looked like the _have_msi and _msi_enabled variables did not seem to be initialized in the function constructor. Best to my understanding of C++ primitive member variables in this case are left set to some random values.

Long story short it looks like this simple patch solves the problem:

```
diff --git a/drivers/pci-function.cc b/drivers/pci-function.cc
index 4d53d66..74d3c96 100644
--- a/drivers/pci-function.cc
+++ b/drivers/pci-function.cc
@@ -178,7 +178,7 @@ namespace pci {
     }

     function::function(u8 bus, u8 device, u8 func)
-        : _bus(bus), _device(device), _func(func), _have_msix(false), _msix_enabled(false)
+        : _bus(bus), _device(device), _func(func), _have_msix(false), _msix_enabled(false), _have_msi(false), _msi_enabled(false)
     {

     }
```

I am not 100% sure this is iit but I have not seen "hanging issue" in 10-15 runs of the same app since this correction.

Now I have noticed that is_msi() and is_msix() are used all over the place in other drivers so this change might be affecting many platforms.

**Comment by nyh** [comment]
Good catch! This is definitely a bug - I see the initialization code there setting have_msi to true when relevant, but never to false, so it should be set to false in the constructor, like you did.
If you send a proper patch, I'll apply it. Thanks.
