### ISSUE TITLE
Being stuck when running Osv image

### ISSUE THREAD

**Issue by Answerhua** [cloudius-systems/osv#923]
Hello, I've got some problems in running Osv image.

After compiling OSv source code with make, running its own compiled (scripts / build) image, such as user.img, always stuck in the startup interface, but it is ok if running qcow2 image which was published
by Osv official website.

**Comment by nyh** [comment]
Can you please give a bit more information? How do you build? How do you run?
For example, try this:
```
scripts/build
scripts/run.py
```
This should run a shell (with a prompt "/# ") where you can type commands, e.g., "ls".
This this work? If it does, what doesn't work? If it doesn't work, what exactly happens?

**Comment by dingtarly** [comment]
Hi, guys, I also encountered the similar problem.
I followed the tutorials step by step at [HERE](https://github.com/cloudius-systems/osv/blob/master/README.md).
The "make" processing is fine. 
When I used "scripts/build" in the terminal, the process was also OK, but stuck in the end with the information as follows:
`qemu-system-x86_64: -redir tcp:10000::10000: The -redir option is deprecated. Please use '-netdev user,hostfwd=...' instead.`
Then, i existed QEMU, tried to use "scripts/run.py" to boost "build/last/usr.img", but also stuck with information as follows: 
`booting from hard disk`

I have tried the published image in the [OSv](www.osv.io) website, such as the Redis one. 
It can be booted normally. 
So, i have no idea that whats wrong with the self-build images.

**Comment by Answerhua** [comment]
Hello!!!
Yes, I have tried:
`scripts/build`
`scripts/run.py`
This problem seems to occur only in a special image, such as user.img and memcached.so. And Redis worked well. Maybe I made some mistake, misusing it, I really don't know what can I do to fix the problem.

**Comment by nyh** [comment]
Can you please give a complete example of building the specific image and running it and the output? I still don't understand what the problem is.

**Comment by Answerhua** [comment]
I am really sorry for making you confused.Here is the problem.
I want to start usr.img by using:
`sudo scripts/run.py -nv -e "build/last/usr.img"`

But it shows me:
OSv v0.24-455-g13b8acb
eth0: 192.168.122.89
Failed to load object: build/last/usr.img. Powering off.


Using `scripts/run.py` just start osv without any images is fine.

**Comment by nyh** [comment]
This is not a bug, the "-e" option for run.py doesn't give the image name... What you were looking for is the "-i" option:
```
scripts/run.py -i build/last/usr.img
```
What the "-e" option does is to modify the "command line" stored in the image, so when OSv boots, it will try to run the executable you told it, in this case "build/last/usr.img"; But this string is not the name of an executable object inside the image, which is why you get the "Failed to load object" error message and OSv powers off.

If you have more questions on how to use run.py or how to build images, let's take them on the mailing list, not in the bug tracker.

**Comment by Answerhua** [comment]
It's my bad. Thank for your patience. Hope you have a nice day.
