### ISSUE TITLE
Question: there is some NAS specific deployment of OSV?

### ISSUE THREAD

**Issue by stevexyz** [cloudius-systems/osv#932]
Since the ZFS filesystem should be good to have a NAS VM based on OSV, but I didn't see them around: there are?

**Comment by wkozaczuk** [comment]
Do you mind posting your question the group
https://groups.google.com/forum/#!forum/osv-dev and closing this issue?

Thanks,
Waldek

**Comment by wkozaczuk** [comment]
Do you mind posting your question the group
https://groups.google.com/forum/#!forum/osv-dev and closing this issue?

Thanks,
Waldek
