### ISSUE TITLE
How much does OSV need from a shared library?

### ISSUE THREAD

**Issue by dakami** [cloudius-systems/osv#942]
Given that osV implements its own loader, I'm wondering how much it could potentially take advantage of platforms' recent change to PIE compilation.  (GCC7 is PIE by default, a thing that's been some headache for kernel compilation.)  PIE binaries are almost entirely identical to shared libraries, relocatable top to bottom.

Build systems are actually hilariously fragile so "just" adding a compilation flag is a bigger problem than you'd think.

**Comment by wkozaczuk** [comment]
Could you please send this question to the mailing list and close this issue?

Thanks,
Waldek

**Comment by dakami** [comment]
A totally reasonable request.  My apologies.
