### ISSUE TITLE
Inconsistent inclusion of libcrypt in OSv

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#945]
Currently, OSv includes - from Musl - a crypt() implementation - we have in Makefile
```
musl += crypt/crypt_blowfish.o
musl += crypt/crypt.o
musl += crypt/crypt_des.o
musl += crypt/crypt_md5.o
musl += crypt/crypt_r.o
musl += crypt/crypt_sha256.o
musl += crypt/crypt_sha512.o
```
However, in `core/elf.cc`, we don't say in `supplied_modules` that `libcrypt.so.1` is included in OSv, so applications will either load their own version of libcrypt (overriding OSv's definitions) or if they forget to include this library in the image, will report that this library is missing though crypt() will still work.

Moreover while we implement the crypt(3) functions in OSv, we do not implement the encrypt(3) functions, which are also supposed to be part of libcrypt.

**Comment by geraldo-netto** [comment]
Hello @nyh,

I have copied the new musl version of crypt functions/files including the encrypt (musl has it now)
and I also applied the change on elf.cc
But I don't understand how to test the functions
I was checking the directory tests and saw many testing cases
I have tried to tune the Makefile like this:
#tools += tests/tst-crypt.c.so
#cmdline = --nomount tests/tst-crypt.c.so

But it didn't work

Do you happen to have any suggestion?

Kind Regards,
Geraldo Netto

**Comment by wkozaczuk** [comment]
The regular way to build a test image with all unit tests and run is this:

./scripts/build check

**Comment by geraldo-netto** [comment]
Hello Waldek/All,

Thanks Waldek, I'll try and report :)


Kind Regards,

Geraldo Netto
Sapere Aude => Non dvcor, dvco
http://exdev.sf.net/
