### ISSUE TITLE
Add and use "java8" alias module

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#947]
Currently, if we "scripts/build image=apache-derby" and then "scripts/run.py", the run fails with:
```
java.lang.UnsupportedClassVersionError: org/apache/derby/drda/NetworkServerControl : Unsupported major.minor version 52.0
```
The problem is that the apache-derby project requires (see apps/apache-derby/module.py) the 'java' module, and that is an alias (see modules/java/module.py) for 'openjdk7', which is JVM version 7, but the Apache Derby we download requires version 8.

We should have a "java8" alias which will default to one of the Java 8 implementations (maybe openjdk8-zulu-full?) and **all** the Java 8 implementation will `provides = ['java8']`, so by default apache-derby will cause openjdk8-zulu-full (for example) to be included, but the user can easily overrride it by specifying a different Java implementation on the build line.

**Comment by wkozaczuk** [comment]
I am closing this issue manually as the changes to address this issue are part of the commit https://github.com/cloudius-systems/osv-apps/commit/0005c2416c2e1bc99d3b39d99cd32177420f66e2 made to the apps project.
