### ISSUE TITLE
tst-feexcept.cc failing: division by zero with isinf() and isnan()

### ISSUE THREAD

**Issue by geraldo-netto** [cloudius-systems/osv#949]
Dear Friends,

I noticed an issue on tst-feexcept.cc and because i thought it might be related to my changes
I decided to re-clone osv repo from scratch and test it with make check in a clean osv repo

It turns out that we have a division by zero issue in the test:
...
cpiod finished
+ cd /home/netto/Downloads/osv-clean
+ exec ./scripts/test.py
  TEST java-perms                         
 OK  (13.232 s)
  TEST java_isolated                      
 OK  (15.652 s)
  TEST java_non_isolated                  
 OK  (10.292 s)
  TEST tcp_close_without_reading          qemu-system-x86_64: -redir tcp:7777::7777: The -redir option is deprecated. Please use '-netdev user,hostfwd=...' instead.
 OK  (3.536 s)
  TEST tracing_smoke_test                 
 OK  (16.458 s)
  TEST tst-af-local.so                    
 OK  (6.210 s)
  TEST tst-align.so                       
 OK  (3.922 s)
  TEST tst-app.so                         
 OK  (3.664 s)
  TEST tst-async.so                       
 OK  (4.381 s)
  TEST tst-bitset-iter.so                 
 OK  (3.928 s)
  TEST tst-bsd-evh.so                     
 OK  (3.910 s)
  TEST tst-bsd-kthread.so                 
 OK  (3.735 s)
  TEST tst-bsd-taskqueue.so               
 OK  (3.743 s)
  TEST tst-bsd-tcp1-zrcv.so               
 OK  (6.001 s)
  TEST tst-bsd-tcp1-zsnd.so               
 OK  (5.884 s)
  TEST tst-bsd-tcp1-zsndrcv.so            
 OK  (6.093 s)
  TEST tst-bsd-tcp1.so                    
 OK  (6.090 s)
  TEST tst-calloc.so                      
 OK  (3.793 s)
  TEST tst-chdir.so                       
 OK  (3.577 s)
  TEST tst-chmod.so                       
 OK  (3.864 s)
  TEST tst-clock.so                       
 OK  (18.610 s)
  TEST tst-commands.so                    
 OK  (4.010 s)
  TEST tst-concurrent-init.so             
 OK  (4.384 s)
  TEST tst-condvar.so                     
 OK  (25.521 s)
  TEST tst-console.so                     
 OK  (9.631 s)
  TEST tst-cxxlocale.so                   
 OK  (3.490 s)
  TEST tst-dlfcn.so                       
 OK  (3.927 s)
  TEST tst-dns-resolver.so                 SKIPPED
  TEST tst-elf-permissions.so             
 OK  (4.214 s)
  TEST tst-epoll.so                       
 OK  (4.982 s)
  TEST tst-eventfd.so                     
 OK  (35.626 s)
  TEST tst-except.so                      
 OK  (4.806 s)
  TEST tst-faccessat.so                   
 OK  (3.733 s)
  TEST tst-fallocate.so                   
 OK  (4.146 s)
  TEST tst-fcntl.so                       
 OK  (3.116 s)
  TEST tst-feexcept.so                    
OSv v0.24-499-g58c358d
eth0: 192.168.122.15
FAIL: /home/netto/Downloads/osv-clean/tests/tst-feexcept.cc:95: For sig_check([] { expect(isinf(1 / zero_d()), true); }, SIGFPE), expected true, saw 0.
FAIL: /home/netto/Downloads/osv-clean/tests/tst-feexcept.cc:101: For sig_check([] { expect(isnan(0.0 / zero_d()), true); }, SIGFPE), expected true, saw 0.
FAIL: /home/netto/Downloads/osv-clean/tests/tst-feexcept.cc:104: For sig_check([] { expect(isinf(1 / zero_d()), true); }, SIGFPE), expected true, saw 0.
SUMMARY: 17 tests, 3 failures
Test tst-feexcept.so FAILED
Traceback (most recent call last):
  File "/home/netto/Downloads/osv-clean/scripts/test.py", line 186, in <module>
    main()
  File "/home/netto/Downloads/osv-clean/scripts/test.py", line 173, in main
    run_tests()
  File "/home/netto/Downloads/osv-clean/scripts/test.py", line 164, in run_tests
    run(tests_to_run)
  File "/home/netto/Downloads/osv-clean/scripts/test.py", line 84, in run
    run_test(test)
  File "/home/netto/Downloads/osv-clean/scripts/test.py", line 59, in run_test
    test.run()
  File "/home/netto/Downloads/osv-clean/scripts/tests/testing.py", line 29, in run
    run_command_in_guest(self.command).join()
  File "/home/netto/Downloads/osv-clean/scripts/tests/testing.py", line 163, in join
    raise Exception('Guest failed')
Exception: Guest failed
Makefile:143: recipe for target 'check' failed
make: *** [check] Error 1

Checking the code, we have this below where zero_i() is an integer zero (0), zero_d() is a decimal zero (0.0):

int main(int argc, char **argv)
{
    // Test that fegetexcept() does not return a negative number
    expect(fegetexcept() >= 0, true);

    // Test that *integer* division by zero generates, ironically, a SIGFPE
    expect(sig_check([] { printf("%d\n", 1 / zero_i()); }, SIGFPE), true);

    // While, continuing the irony, by default a floating-point division by
    // zero does NOT generate a SIGFPE signal, but rather inf or nan:
    expect(sig_check([] { expect(isinf(1 / zero_d()), true); }, SIGFPE), false);
    expect(sig_check([] { expect(isnan(0.0 / zero_d()), true); }, SIGFPE), false);

    // Using feenableexcept, we can cause a division by zero to cause a
    // SIGFPE even for floating point.
    // First, let's test the FE_DIVBYZERO flag, which applies to division
    // of a non-zero by zero (which would generate an inf without this flag)
    int old = feenableexcept(FE_DIVBYZERO);
    expect(old & FE_DIVBYZERO, 0);
    expect(fegetexcept() & FE_DIVBYZERO, FE_DIVBYZERO);
    expect(sig_check([] { expect(isinf(1 / zero_d()), true); }, SIGFPE), true);
    // 0/0 isn't considered a "divide by zero" (inf) but rather an
    // "invalid operation" (nan) so FE_DIVBYZERO won't catch it. but
    // FE_INVALID would.
    expect(sig_check([] { expect(isnan(0.0 / zero_d()), true); }, SIGFPE), false);
    feenableexcept(FE_INVALID);
    expect(sig_check([] { expect(isnan(0.0 / zero_d()), true); }, SIGFPE), true);
    // enabling a bit doesn't clear the previous bit we've set
    expect(fegetexcept() & (FE_DIVBYZERO | FE_INVALID), (FE_DIVBYZERO | FE_INVALID));
    expect(sig_check([] { expect(isinf(1 / zero_d()), true); }, SIGFPE), true);

    std::cout << "SUMMARY: " << tests << " tests, " << fails << " failures\n";
    return fails == 0 ? 0 : 1;
}

I may be mistaken here but using python as a reference, we have a different situation:
netto@vmx01 ~/Downloads/osv-clean/tests $ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import math
>>> math.isinf(1 / 0.0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: float division by zero

>>> math.isinf(1 / 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: integer division or modulo by zero

>>> 1 / 0.0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: float division by zero

>>> 1 / 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: integer division or modulo by zero

Because, I don't know if I'm missing some detail,
I would like to ask if it makes sense to remove the call to isinf() and the call to isnan()

Also, it seems we have more tests that are been skipped

Kind Regards,
Geraldo Netto

**Comment by wkozaczuk** [comment]
I think it might be a duplicate of #855

**Comment by geraldo-netto** [comment]
Hello @wkozaczuk! :)

Indeed, I'll close this ticket
Once we already have the discussion in the other ticket

Kind Regards,
Geraldo Netto
