### ISSUE TITLE
Missing dlvsym() function

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#961]
Java fails in new Jenkins machine. See failed test run, http://jenkins.cloudius-systems.com:8080/job/osv-build/1360/console
The error:
```
java.so: Starting JVM app using: io/osv/isolated/RunIsolatedJvmApp
/usr/lib/jvm/java/jre/lib/amd64/server/libjvm.so: failed looking up symbol dlvsym
```

The dlvsym() function is a Linux-specific variant of the POSIX dlsym() described in dlsym(3), and apparently the JRE now started to use...

**Comment by wkozaczuk** [comment]
I wonder why we do not see these issues with Zulu java?

**Comment by nyh** [comment]
I don't know what is running on this new Jenkins machine... I guess some new build of Java, I don't even know which version. Luckily it's not using gcc 8 as the C++ compiler - I'm seeing dozens of compilation errors with gcc 8, and now still trying to sort them out :-(

**Comment by nyh** [comment]
Can be reproduced with
```
scripts/build -j4 image=openjdk8-fedora,java-tests
scripts/test.py
```
