### ISSUE TITLE
Fix annoying warnings while building tests

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#976]
We've been careful to clear any compilation warnings during the main OSv build, either by fixing the code or adding a compilation parameter to ignore specific false alarms. However, we've been less diligent in the tests ("scripts/build image=tests", or "make check") and those produce quite a number of silly warning messages during the build. With gcc 8.1.1, I see warnings while building the following tests:

```
tst-pthread
tst-mmap
misc-fsx
tst-truncate
misc-free-perf
tst-zfs-mount
tst-run
tst-calloc
tst-crypt
tst-vfs
misc-fs-stress
tst-stat
tst-rename
tst-fallocate
tst-fslink
```

Most of these warnings are silly and can be easily fixed

**Comment by geraldo-netto** [comment]
Hi @nyh / @wkozaczuk ,

I still need to fix test-crypt :(
Hope to do it as soon as I can
(still busy with other things)

Kind Regards,
Geraldo Netto

**Comment by nyh** [comment]
The list of warnings during test compilation continues to grow in gcc 8.2 :-(

**Comment by geraldo-netto** [comment]
Hi @nyh / @wkozaczuk ,

How are you doing?

My Friends, doing a quick run, I've got this:
/home/netto/Desktop/osv/osv-tomcat9/tests/tst-pthread.c: In function ‘main’:
/home/netto/Desktop/osv/osv-tomcat9/tests/tst-pthread.c:171:5: warning: implicit declaration of function ‘usleep’; did you mean ‘fseek’? [-Wimplicit-function-declaration]
     usleep(1000);
     ^~~~~~
     fseek

In file included from /home/netto/Desktop/osv/osv-tomcat9/tests/tst-elf-permissions.cc:8:0:
/home/netto/Desktop/osv/osv-tomcat9/tests/tst-mmap.hh: In function ‘bool try_write(int (*)())’:
/home/netto/Desktop/osv/osv-tomcat9/tests/tst-mmap.hh:76:37: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     char byte = **(volatile char**)&func;
                                     ^~~~
/home/netto/Desktop/osv/osv-tomcat9/tests/tst-mmap.hh:77:25: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     **(volatile char**)&func = byte;
                         ^~~~
In file included from /home/netto/Desktop/osv/osv-tomcat9/tests/tst-mmap.cc:11:0:
/home/netto/Desktop/osv/osv-tomcat9/tests/tst-mmap.hh: In function ‘bool try_write(int (*)())’:
/home/netto/Desktop/osv/osv-tomcat9/tests/tst-mmap.hh:76:37: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     char byte = **(volatile char**)&func;
                                     ^~~~
/home/netto/Desktop/osv/osv-tomcat9/tests/tst-mmap.hh:77:25: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     **(volatile char**)&func = byte;
                         ^~~~
/home/netto/Desktop/osv/osv-tomcat9/tests/misc-free-perf.cc: In function ‘void test_across_core_alloc_and_free(Alloc, Dealloc)’:
/home/netto/Desktop/osv/osv-tomcat9/tests/misc-free-perf.cc:69:35: warning: ‘new’ of type ‘queue_t {aka ring_spsc<void*, 67108864>}’ with extended alignment 64 [-Waligned-new=]
     queue_t* queue1 = new queue_t();
                                   ^
/home/netto/Desktop/osv/osv-tomcat9/tests/misc-free-perf.cc:69:35: note: uses ‘void* operator new(std::size_t)’, which does not have an alignment parameter
/home/netto/Desktop/osv/osv-tomcat9/tests/misc-free-perf.cc:69:35: note: use ‘-faligned-new’ to enable C++17 over-aligned new support
/home/netto/Desktop/osv/osv-tomcat9/tests/misc-free-perf.cc:70:35: warning: ‘new’ of type ‘queue_t {aka ring_spsc<void*, 67108864>}’ with extended alignment 64 [-Waligned-new=]
     queue_t* queue2 = new queue_t();
                                   ^
/home/netto/Desktop/osv/osv-tomcat9/tests/misc-free-perf.cc:70:35: note: uses ‘void* operator new(std::size_t)’, which does not have an alignment parameter
/home/netto/Desktop/osv/osv-tomcat9/tests/misc-free-perf.cc:70:35: note: use ‘-faligned-new’ to enable C++17 over-aligned new support
/home/netto/Desktop/osv/osv-tomcat9/tests/misc-free-perf.cc: In instantiation of ‘void test_across_core_alloc_and_free(Alloc, Dealloc) [with Alloc = std::_Bind<void* (*(int))(long unsigned int)>; Dealloc = void (*)(void*)]’:
/home/netto/Desktop/osv/osv-tomcat9/tests/misc-free-perf.cc:146:66:   required from here
/home/netto/Desktop/osv/osv-tomcat9/tests/misc-free-perf.cc:69:23: warning: ‘new’ of type ‘queue_t {aka ring_spsc<void*, 67108864>}’ with extended alignment 64 [-Waligned-new=]
     queue_t* queue1 = new queue_t();
                       ^~~~~~~~~~~~~
/home/netto/Desktop/osv/osv-tomcat9/tests/misc-free-perf.cc:69:23: note: uses ‘void* operator new(std::size_t)’, which does not have an alignment parameter
/home/netto/Desktop/osv/osv-tomcat9/tests/misc-free-perf.cc:69:23: note: use ‘-faligned-new’ to enable C++17 over-aligned new support
/home/netto/Desktop/osv/osv-tomcat9/tests/misc-free-perf.cc:70:23: warning: ‘new’ of type ‘queue_t {aka ring_spsc<void*, 67108864>}’ with extended alignment 64 [-Waligned-new=]
     queue_t* queue2 = new queue_t();
                       ^~~~~~~~~~~~~
/home/netto/Desktop/osv/osv-tomcat9/tests/misc-free-perf.cc:70:23: note: uses ‘void* operator new(std::size_t)’, which does not have an alignment parameter
/home/netto/Desktop/osv/osv-tomcat9/tests/misc-free-perf.cc:70:23: note: use ‘-faligned-new’ to enable C++17 over-aligned new support
/home/netto/Desktop/osv/osv-tomcat9/tests/tst-crypt.c: In function ‘concat_str’:
/home/netto/Desktop/osv/osv-tomcat9/tests/tst-crypt.c:9:34: warning: argument to ‘sizeof’ in ‘strncat’ call is the same expression as the source; did you mean to provide an explicit length? [-Wsizeof-pointer-memaccess]
  strncat(tmp, first_block, sizeof(first_block));
                                  ^
/home/netto/Desktop/osv/osv-tomcat9/tests/tst-crypt.c:10:35: warning: argument to ‘sizeof’ in ‘strncat’ call is the same expression as the source; did you mean to provide an explicit length? [-Wsizeof-pointer-memaccess]
  strncat(tmp, second_block, sizeof(second_block));
                                   ^
/home/netto/Desktop/osv/osv-tomcat9/tests/tst-crypt.c: In function ‘main’:
/home/netto/Desktop/osv/osv-tomcat9/tests/tst-crypt.c:47:3: warning: implicit declaration of function ‘setkey’; did you mean ‘setbuf’? [-Wimplicit-function-declaration]
   setkey(key);
   ^~~~~~
   setbuf
/home/netto/Desktop/osv/osv-tomcat9/tests/tst-crypt.c:50:2: warning: implicit declaration of function ‘encrypt’; did you mean ‘crypt’? [-Wimplicit-function-declaration]
  encrypt(buf, 0);
  ^~~~~~~
  crypt
/home/netto/Desktop/osv/osv-tomcat9/tests/tst-crypt.c:44:29: warning: iteration 6 invokes undefined behavior [-Waggressive-loop-optimizations]
    buf[i * 8 + j] = password[i] >> j & 1;
                     ~~~~~~~~^~~
/home/netto/Desktop/osv/osv-tomcat9/tests/tst-crypt.c:42:2: note: within this loop
  for (i = 0; i < 8; i++) {
  ^~~
/home/netto/Desktop/osv/osv-tomcat9/tests/tst-calloc.cc: In function ‘int main()’:
/home/netto/Desktop/osv/osv-tomcat9/tests/tst-calloc.cc:34:16: warning: unused variable ‘refX’ [-Wunused-variable]
     const char refX[11] = "XXXXXXXXXX";
                ^~~~

/home/netto/Desktop/osv/osv-tomcat9/build/release.x64/tests/tst-truncate.o: In function `main':
/home/netto/Desktop/osv/osv-tomcat9/tests/tst-truncate.c:10: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
/home/netto/Desktop/osv/osv-tomcat9/build/release.x64/tests/tst-zfs-mount.o: In function `check_zfs_refcnt_behavior()':
/home/netto/Desktop/osv/osv-tomcat9/tests/tst-zfs-mount.cc:54: warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'
/home/netto/Desktop/osv/osv-tomcat9/build/release.x64/tests/tst-stat.o: In function `test_mkdir_fails_if_file_exists::test_method()':
/home/netto/Desktop/osv/osv-tomcat9/tests/tst-fs.hh:25: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
/home/netto/Desktop/osv/osv-tomcat9/build/release.x64/tests/misc-fs-stress.o: In function `main':
/home/netto/Desktop/osv/osv-tomcat9/tests/misc-fs-stress.cc:54: warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'
/home/netto/Desktop/osv/osv-tomcat9/build/release.x64/tests/tst-vfs.o: In function `test_path_lookup::test_method()':
/home/netto/Desktop/osv/osv-tomcat9/tests/tst-fs.hh:25: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
/home/netto/Desktop/osv/osv-tomcat9/build/release.x64/tests/tst-fallocate.o: In function `main':
/home/netto/Desktop/osv/osv-tomcat9/tests/tst-fallocate.cc:52: warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'
/home/netto/Desktop/osv/osv-tomcat9/build/release.x64/tests/tst-fs-link.o: In function `check_vnode_duplicity':
/home/netto/Desktop/osv/osv-tomcat9/tests/tst-fs-link.cc:39: warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'
/home/netto/Desktop/osv/osv-tomcat9/build/release.x64/tests/tst-rename.o: In function `TempDir::TempDir()':
/home/netto/Desktop/osv/osv-tomcat9/tests/tst-fs.hh:25: warning: the use of `tmpnam' is dangerous, better use `mkstemp'

I hope to find some time to help with those small things, let's keep in touch! :)


Kind Regards,
Geraldo Netto

**Comment by geraldo-netto** [comment]
Guys,

How can I run a specific test?
eg: tst-pthread

Kind Regards,
Geraldo Netto

**Comment by wkozaczuk** [comment]
./scripts/test.py —name tst-pthread.so

First you have to build image with all tests.

**Comment by geraldo-netto** [comment]
Thanks Waldek :)

I think I fixed the first pthread issue I have found, hope to commit in a few minutes
I'm also creating a page on wiki to document it
It's a bare simple page but at least, it's a start :)

See You! :)

**Comment by geraldo-netto** [comment]
Guys,

I have created this page to document how to test
As I said, I still need to polish it, but it's a start
https://github.com/cloudius-systems/osv/wiki/Testing-POSIX-APIs-on-OSv

**Comment by wkozaczuk** [comment]
Geraldo,

Thanks for taking on it.

Could you please prepare series of fairly small patches targeting specific
test or type of warning issue across all affected tests? So it is easier to
review.

Waldek

**Comment by nyh** [comment]
The last of these compilation warnings on test build were fixed by several patches by @wkozaczuk so finally closing this issue.
