### ISSUE TITLE
cpiod.so is much too big

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#980]
The stripped cpiod.so is around 300KB. Currently, it appears twice in every image (inside the kernel as bootfs, and in the zfs disk image).
But cpiod is a fairly trivial program and should not be anywhere this large...

I suspect the problem is in the Boost libraries that we use... `nm -D build/release.x64/tools/cpiod/cpiod.so` shows almost a thousand ridiculously long symbol names for boost asio and program_options, date manipulation, streams and other stuff we don't really need because... well... cpiod is such a trivial program. We could have done it easily with standard C++ code without the Boost stuff.

**Comment by geraldo-netto** [comment]
Hello @nyh ,

Doing a quick check, we use the following headers from boost:
osv/tools/cpiod/cpiod.cc:
#include <boost/asio.hpp>
#include <boost/program_options.hpp>

osv/tools/cpiod/cpio.cc:
#include <boost/lexical_cast.hpp>
#include <boost/iostreams/concepts.hpp>
#include <boost/iostreams/stream.hpp>
#include <boost/iostreams/restrict.hpp>


Kind Regards,
Geraldo Netto
