### ISSUE TITLE
aarch64 system call numbers are probably wrong

### ISSUE THREAD

**Issue by nyh** [cloudius-systems/osv#991]
I believe many of the system call numbers in `include/api/aarch64/bits/syscall.h` are wrong. I found people on the Web saying that, for example:

>The getrandom() system call number is indeed 384 on ARM, but it is not the same on ARM64. ARM64 uses the asm-generic headers, including for, system call numbers, so the getrandom() system call number on ARM64 is 278.

So I think we need to copy the system call numbers from `/usr/include/asm-generic/unistd.h`, not the x64 numbers we currently seem to copy.

**Comment by wkozaczuk** [comment]
Fixed by https://github.com/cloudius-systems/osv/commit/21440360f41803fc54460ae78b3d928837621e5d
