### ISSUE TITLE
CPU Scheduler

### ISSUE THREAD

**Issue by foreverpersist** [cloudius-systems/osv#998]
Why not use CFS(Complete Fair Schedule) for CPU scheduling?

Just compare CFS and current scheduler (named GFS - Global Fair Schedule)

## Overhead

CFS has lower overhead than GFS
```
CFS - integer
GFS - float-point number, `exp` 
```

## Fair

CFS has better fairness than GFS

## Scalable

Both CFS and GFS have O(lgN) complexity

## Tick

GFS is tick-less. We can adjust traditional CFS without tick as follows:

When selecting a new thread, just keep it running for `dt` rather than a `tick`
```
dv = v_next - v

       /-> T * w / sum(wi) , if dv = 0
dt = |
       \-> dv * w / NICE0 , if dv > 0

Limits: 
    dt >= min_dt  --- avoid excessive context (done by CFS)
    dt <= max_dt  --- avoid starvation caused by long running thread

    where,
                T - schedule period in CFS
                v - virtual runtime in CFS
                v_next - next alternative virtual runtime
                w - weight of current thread
                sum(wi) - total weights
                NICE0 - weight of threads whose nice values are 0 
```
  
### New Thread

Set `v` for new thread as traditional CFS:
```
v = min_v + sched_vslice(T)
```

### Long Sleep Thread

Set `v` for long sleep thread as traditional CFS:
```
v = min_v - k * T

where,
            k - a constant
```

**Comment by nyh** [comment]
We meant to write a paper about OSv's scheduler, but unfortunately never got around to it :-(
I agree with most of what you wrote above except the "CFS has better fairness than GFS".
My two cents:

When we started with OSv, the "tickless" thing seemed like a big deal. Linux couldn't do it, and we could. But the more time that passed, the more it became apparent that OSv wasn't *really* tickless (we had various background threads which had their own periodic ticks anyway), while Linux's CFS got its own tickless approximation. It's still really cool that we don't need tics, but had we started from scratch, I'm no longer sure it would have been an important design criterion.

About fairness, I don't understand your comment that CFS has better fairness. The main feature of OSv's scheduler is its mathematical fairness - we calculate exactly how much time each thread ran, and let two competing threads run the same time. So if we have one thread that runs continuously, and a second thread which runs for 0.01 second, then sleeps for 0.01 seconds, and so forth periodically - both will get exactly the same runtime (the continous thread will run while the intermittent thread sleeps). OSv has a "decay" formula which defines, in mathematical terms, how this runtime accounting decays (so a thread which sleeps for a minute, doesn't get a full minute of uninterrupted runtime!), but it's not arbitrary heuristics like in CFS. OSv can also exactly account threads which run intermittently for very short durations, never completing a full tick, and more fairly pit them against the other threads.

**Comment by wkozaczuk** [comment]
I appreciate it is very interesting discussion but can we close it and move its continuation to the mailing list - https://groups.google.com/forum/#!forum/osv-dev ?

**Comment by nyh** [comment]
I'm closing this issue as it is indeed an interesting discussion but not really an issue. If you know of specific problems with the current scheduler - something it doesn't do fairly, or a workload it handles badly, please open a new issue. We should probably also discuss this over the mailing list before you come up with a proposal to change the scheduler, which is a delicate part of the system which will need a lot of testing and verification if we decide to change it.
